### ISSUE TITLE
【自定义开发数据导出和导入】

### ISSUE THREAD

**Issue by sunnyvinson** [apolloconfig/apollo#1681]
您好！
目前有个想法：
在portal界面上实现一些自定义的界面和按钮，实现数据的导出和导入。

对于这个想法，您觉得实现要付出的代价有多大呢？因为要去缕清源码的逻辑，难易度如何？

**Comment by sunnyvinson** [comment]
可否分享下，数据库各个表之间的关系，让开发者更好的缕清数据逻辑

**Comment by nobodyiam** [comment]
可以参考[E-R Diagram](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#14-e-r-diagram)

**Comment by JaredTan95** [comment]
我们这边最近刚好实现了这个需求，看后面需要的话可以分享出来。

**Comment by nobodyiam** [comment]
@JaredTan95 具体是满足了什么样的场景？

**Comment by sunnyvinson** [comment]
@JaredTan95 你好，可以分享一波吗

**Comment by JaredTan95** [comment]
@nobodyiam 主要是解决环境之间的配置同步吧，这边的环境是网络隔离的，也就是说部署了两套apollo，在服务从开发到测试的时候会把namespace中的配置导出来导入到另外一个环境，再对配置稍微更改。

**Comment by nobodyiam** [comment]
恩，这个应该有些公司需要的，可以看看能不能合并进来~

**Comment by sunnyvinson** [comment]
好的谢谢

**Comment by JaredTan95** [comment]
> 恩，这个应该有些公司需要的，可以看看能不能合并进来~

ok

**Comment by litttlefisher** [comment]
导入导出的功能，哪次迭代会发布呢？

**Comment by nobodyiam** [comment]
#1767 已经merge了，增加了import和export的接口，还没有界面支持，1.3.0版本会发布，预计2月份

**Comment by litttlefisher** [comment]
import和export的界面支持，有支持了嘛？

**Comment by nobodyiam** [comment]
@litttlefisher 界面暂时还没

**Comment by litttlefisher** [comment]
@nobodyiam 大概什么时候能在界面进行支持呢？我司启用Apollo，经常需要多个Apollo间进行同步的

**Comment by nobodyiam** [comment]
如果经常需要多个apollo间同步的话，其实通过open api就可以了吧？

**Comment by neal-zhu** [comment]
请问这个 api 可以给一下吗？

**Comment by kezhenxu94** [comment]
> 请问这个 api 可以给一下吗？

/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import
/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export

**Comment by nobodyiam** [comment]
楼上这两个是portal的api，程序访问的话可能比较麻烦，因为要通过等登录授权

open api里面是有创建、更新配置接口的，这样通过程序是能比较方便的同步不同环境的配置的

**Comment by nobodyiam** [comment]
#3947 provides the UI to export/import configs and is now merged.
