### ISSUE TITLE
关于多种私有文件格式namespace支持

### ISSUE THREAD

**Issue by yzh1798** [apolloconfig/apollo#1795]
由于业务需要，想把多种后缀的文件创建为私有文件格式的namespace，例如 .conf, .toml, .cfg...请问一下应该如何支持这种操作呢，是否可以创建一个通用的文件格式（后缀名自己定）？

**Comment by java-longmiao** [comment]
目前支持properties、xml、json、yml、yaml这几种文件格式

**Comment by yzh1798** [comment]
> 目前支持properties、xml、json、yml、yaml这几种文件格式

现在是想增加多种文件格式，因为很多配置文件都想使用apollo，但是文件后缀不尽相同，现有的5种可能不满足，所以想是否可以开发一种通用格式以满足所有类型的文件

**Comment by nobodyiam** [comment]
这个是在`com.ctrip.framework.apollo.core.enums.ConfigFileFormat`中定义的

**Comment by yzh1798** [comment]
> 这个是在`com.ctrip.framework.apollo.core.enums.ConfigFileFormat`中定义的

您好，我现在已经成功创建了一个后缀名.conf的文件格式,在创建过程中我发现在client中有如下代码:case XML: return new XmlConfigFile(namespace, configRepository); 实际上XmlConfigFile,YamlConfigFile这几个类内容无太大区别,那为什么要分为这几个类,仅仅是为了区分文件格式么?另外,文件格式namespace使用除了监听配置变化、开放平台接入还有需要注意配置获取的地方么?还望告知，谢谢

**Comment by nobodyiam** [comment]
目前实现上仅仅只是名称而已，之前是觉得这块可能会做扩展，比如返回对象之类的。

**Comment by wangda** [comment]
> 目前支持properties、xml、json、yml、yaml这几种文件格式

我搭的一个apollo，只能使用properties格式的文件，请问在哪里可以配置使用其它格式的配置文件呢？

**Comment by yzh1798** [comment]
> > 目前支持properties、xml、json、yml、yaml这几种文件格式
> 
> 我搭的一个apollo，只能使用properties格式的文件，请问在哪里可以配置使用其它格式的配置文件呢？

创建namespace ，类型选择私有 ， 下拉框里面选择需要创建的namespace类型即可

**Comment by MrtKing** [comment]
我创建了一个peoperties的和一个yml，只会去读properties里面的，这是为什么呢？

**Comment by hemkvo** [comment]
你好 我想知道apollo 1.4.1升级到1.9.1版本  apollo的portal面板  namespace添加pulic的侧边栏json文件消失是怎么回事呢

**Comment by nobodyiam** [comment]
@hemkvo would you please provide more details?

**Comment by Anilople** [comment]
Can we make an plugin extension here?

Left a basic .txt namespace, user write an plugin extension to decide how to use it.

.conf, .toml, .cfg have their own plugin.

For example, 

`user.toml`'s content

```toml
name = "Mwanji Ezana"

[address]
  street = "123 A Street"
  city = "AnyVille"
  
[contacts]
  "email address" = "me@example.com"
```

user can write it to `.txt` namespace in apollo portal, then write a plugin extension in apollo-client to read it, parse it

reference:
* [How to parse TOML document with Java](https://stackoverflow.com/questions/70033062/how-to-parse-toml-document-with-java)

**Comment by nobodyiam** [comment]
@Anilople This sounds a good idea.
