### ISSUE TITLE
Apllo-Portal能不能提供一个页面管理公共命名空间？

### ISSUE THREAD

**Issue by ldcsaa** [apolloconfig/apollo#1992]
公共命名空间要在具体项目中引入才能看见，查看和管理起来不是很方便。
能不能提供一个管理公共命名空间的页面？

**Comment by xiaoxing598** [comment]
我现在是通过创建一个common项目来管理的，你说的这个确实可以优化。

**Comment by nobodyiam** [comment]
是的，这个是一个很好的优化点

**Comment by nobodyiam** [comment]
#3850 provides the public namespaces list in front page
