### ISSUE TITLE
为Apollo各组件添加认证功能

### ISSUE THREAD

**Issue by Zhang21** [apolloconfig/apollo#2200]
出于安全考虑，个人认为可为Apollo各组件portal, admin, config之间添加认证。

**Comment by nobodyiam** [comment]
有啥好的方案建议吗？

**Comment by Zhang21** [comment]
@nobodyiam ，宋工，您好。

我的想法是在poratl, config, admin的配置文件中添加一个key变量进行比对认证，如果两者的key相同则允许通信，否则拒绝并返回Authentic Error。

我个人觉得各组件之间没有认证机制实在是很不安全，虽然是在内网环境下，虽然可以添加ACL，但再加把锁更好。

**Comment by nobodyiam** [comment]
portal <-> admin之间可以采用这个方式，config由于需要服务客户端，可能不太适用

**Comment by nobodyiam** [comment]
Apollo now has several access control mechanisms, see [Apollo Security Guide](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_71-%e5%ae%89%e5%85%a8%e7%9b%b8%e5%85%b3) for more information.
