### ISSUE TITLE
怎么让不同配置文件中的相同配置项同时生效而不是覆盖

### ISSUE THREAD

**Issue by xycpand** [apolloconfig/apollo#2454]
目前如果多个配置文件中有相同配置项的话，只会以第一个配置文件中的为准，例如下面的config1.yml 。这个就像是spring的active 包含的profile被优先级高的定义覆盖。
那Apollo有没有提供和spring  include 属性一样的功能，让包含的profile的相同配置项都生效而不是覆盖？
app:
    id: test
    bootstrap: config1.yml,config2.yml,config3.yml

**Comment by nobodyiam** [comment]
这个覆盖是Spring的配置模型决定的，如果不希望覆盖的话，可以通过[注入Config对象](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#323-spring-annotation%E6%94%AF%E6%8C%81)来获取配置

**Comment by xycpand** [comment]
因为是spring启动的时候从配置文件中获取配置项，而不是我们自己定义的业务中去获取配置项，所以“通过注入Config对象来获取配置”就不可行了（除非修改sping源码）。所以如果Apollo能够提供像spring的 include配置项功能就更好了。

**Comment by nobodyiam** [comment]
apollo的配置是通过注入到spring中实现的，所以本质上还是spring在管理配置。

spring的include配置项功能能展开说明一下吗？

**Comment by xycpand** [comment]
spring.profiles.include属性可以用来无条件的添加生效的配置。
例如spring.profiles.include：config1.yml,config2.yml 
最终config1.yml和config2.yml中的相同配置项不会覆盖，而是全部都生效。但是用Apollo的时候没有达到预期效果。


config1.yml内容如下
spring:
    cloud:
        gateway:
          routes:
           - id: test1
             uri: https://test1
             predicates:
              - Path=/test1

config2.yml内容如下
spring:
    cloud:
        gateway:
          routes:
          - id: test2
            uri: https://test2
            predicates:
               - Path=/test2

最终合并的内容如下
spring:
    cloud:
        gateway:
          routes:
           - id: test1
             uri: https://test1
             predicates:
              - Path=/test1
          - id: test2
            uri: https://test2
            predicates:
               - Path=/test2

**Comment by duwey** [comment]
include不是用来导入不同配置项的类似于公用配置嘛？
https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-profiles.html#boot-features-adding-active-profiles

**Comment by nobodyiam** [comment]
我在项目中测试了一下，spring.profiles.include 能导入不同 profile 的配置，不过相同配置还是会相互覆盖的

![image](https://user-images.githubusercontent.com/837658/86526146-9d499700-bec2-11ea-879f-f0289ce537a4.png)

![image](https://user-images.githubusercontent.com/837658/86526151-b8b4a200-bec2-11ea-8318-59e5748dffec.png)
