### ISSUE TITLE
考虑支持私有app对用户只赋予只读权限吗？

### ISSUE THREAD

**Issue by jianguod** [apolloconfig/apollo#2491]
有些场景下，同一app有多个人负责，但只有负责人有管理员权限，且app权限必须私有，权限的赋予想要达到尽可能的颗粒度。

**Comment by nobodyiam** [comment]
只读权限是啥用户场景？

**Comment by yocaning** [comment]
> 只读权限是啥用户场景？

+1 ，ex:生产apollo配置如今是由运维维护，平时开发想看下配置，都只能寻找运维，所以期待有一个读写分离的权限，允许线上数据只读。

**Comment by nobodyiam** [comment]
This is now supported, see [configView.memberOnly.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_319-configviewmemberonlyenvs)
