### ISSUE TITLE
比较配置功能希望只列出有差异的配置项

### ISSUE THREAD

**Issue by th891285** [apolloconfig/apollo#2663]
对于管理员而言，有时需要比较两个或多个环境下的配置差异。

Apollo提供了比较参数的功能。

目前该比较参数功能，把全部参数都列出来了，不论相同还是不同。这样的话，如果要找出不同的配置项，非常不方便。也失去了比较的意义。

而且只能比较某个项目的配置。如果项目比较多，逐个去比较也是很繁琐的事情。

建议：
1. 增加 只比较指定配置。
2. 增加 只列出不同的项。
3. 增加 可以一次比较多个项目的参数。

![image](https://user-images.githubusercontent.com/56578500/66809321-b76fcd80-ef5f-11e9-9fd2-38db2765fe5f.png)

**Comment by nobodyiam** [comment]
很好的建议，这块也比较适合大家一起来贡献，欢迎提交PR！
