### ISSUE TITLE
建议“比较配置”功能把配置不一致的标红，一眼就能看出来

### ISSUE THREAD

**Issue by ITG001** [apolloconfig/apollo#2664]
1.目前公司项目用的阿波罗配置中心，项目发布的时候用了比较配置功能，对比各环境配置的差异，但是肉眼真的很难看出来细微差距，比如开发环境数据库URL加了allowMultiQueries=true，线上只修改了对应的IP和用户名密码，没注意到这个批量处理的参数，导致上线报错，排查了很久的问题，所以强烈建议，比较配置页的页面把配置有差异的标红，方便核对。

2.比较出差异文件后，能否直接增加同步差异文件功能，不用再返回去来一次同步配置。

**Comment by lutianqi-java** [comment]
可以使用网上一些插件文本对比

**Comment by nobodyiam** [comment]
duplicated with #2663
