### ISSUE TITLE
check the Josn format of configuration items

### ISSUE THREAD

**Issue by ppj19891020** [apolloconfig/apollo#2707]
JSON configuration items are prone to errors. It is recommended to check the Josn format of configuration items.

**Comment by JaredTan95** [comment]
I don't think it's a necessary feature for config-center, and it will take time to support this. And contributions are welcome.

**Comment by nobodyiam** [comment]
Maybe we could add a syntax check button, just like the yaml format

![image](https://user-images.githubusercontent.com/837658/67910657-8d084c00-fbbe-11e9-8c1d-9f5364cca065.png)

**Comment by ppj19891020** [comment]
This feature was developed yesterday.
![checkjson](https://user-images.githubusercontent.com/4514718/67913168-1a4f9e80-fbc7-11e9-9bbd-034f982a7bbc.png)

**Comment by nobodyiam** [comment]
It might not be a good idea to add this json syntax check no matter what the actual value is, e.g. a plain text doesn't need it?

**Comment by ppj19891020** [comment]
The routing information configuration of the api gateway is  json format string.

**Comment by nobodyiam** [comment]
What I mean is if the actual value is just some plain text, not a json format string, will the json syntax check tip display in the dialog?

**Comment by nobodyiam** [comment]
duplicated with #590
