### ISSUE TITLE
apollo目前不支持全文搜素功能这极大的限制了apollo的发展及成为行业第一的配置平台

### ISSUE THREAD

**Issue by freelogic** [apolloconfig/apollo#2720]
apollo用过的人都知道，因为没有全文搜索，数百个配置被分配到十几个分类当中，然后不少配置的名称是接近的，搜索起来特别麻烦。 能否在全局所有的配置当中做全文搜索，这将极大的提升apollo的易用性。测试组的同事使用了小半年apollo，都认可其在微服务架构当中的作用，都挺好，就是搜索关键字很繁琐，需要每个namespace打开后，用IE/FIREFOX等浏览器的自己的搜索字符串才能搜索，非常不方便，都想放弃使用了。作为apollo的owner，期望贵司能优化提升apollo，做到全球第一不是没有可能。谢谢！

**Comment by wkcaeser** [comment]
确实是个需求，不过这个很大原因是配置管理不规范吧。如果配置名称有规范的话，看到一个配置名称应该可以很明确的确定它属于那个namespace的。

**Comment by nobodyiam** [comment]
@freelogic 

是个很好的建议，可以尝试先在贵司的实际场景中实现该功能，后续欢迎提交PR~

**Comment by lepdou** [comment]
@freelogic 
#2724 中已实现，下个版本发布

**Comment by fanglijun** [comment]
最好再加个全局value搜索，场景是：redis服务器ip变了，需要修改所有用到这个IP的配置项

**Comment by cciechao** [comment]
@freelogic 可以使用Apollo开放Api，自己实现一个配置搜索平台，目前我这边就是这样做的

**Comment by nobodyiam** [comment]
This feature was implemented by ##3977
