### ISSUE TITLE
有些属性配置无法生效

### ISSUE THREAD

**Issue by 1725636955** [apolloconfig/apollo#2769]
例如spring.cloud.inetutils.preferred-networks = 192.168.0.186 配置在bootstrap.properties可以生效生效,但是将spring.cloud.inetutils.preferred-networks配置在Apollo上无法生效,Apollo的配置是配置到bootstrap.properties上面的并且apollo.bootstrap.enabled = true
apollo.bootstrap.eagerLoad.enabled=true
apollo.bootstrap.namespaces = elasticsearch.properties,application.properties配置了这些属性

**Comment by nobodyiam** [comment]
可以看下该配置是哪个类具体使用的吗？可能要看下它具体的配置读取方式

**Comment by 1725636955** [comment]
我尽量找下
