### ISSUE TITLE
logback日志级别

### ISSUE THREAD

**Issue by songwenh** [apolloconfig/apollo#2798]
目前apollo是不是不支持logback-spring.xml里面配置的日志级别动态刷新，参考https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-logger 没问题，但是使用logback动态刷新不成功
![image](https://user-images.githubusercontent.com/31386856/69787332-43c80e00-11f7-11ea-92bc-af53e70aa524.png)

**Comment by g5niusx** [comment]
可以貼一下`logback-spring.xml`的完整配置嗎？我最近正在搞這塊。

**Comment by g5niusx** [comment]
@nobodyiam spring 初始化日志是通过监听了`ApplicationEnvironmentPreparedEvent`来实现的，在这个阶段是拿不到`namespace`的，自然也拿不到对应的`apollo`配置。😢

**Comment by nobodyiam** [comment]
There are several sample projects showing how to adjust logging levels in [apollo-use-cases](https://github.com/apolloconfig/apollo-use-cases)
