### ISSUE TITLE
apollo 参数复用

### ISSUE THREAD

**Issue by lizhichao999** [apolloconfig/apollo#2833]
apollo能参数复用吗？如：
"spring.datasource.url":"jdbc:postgresql://ip:port/db_schema",
这边参数就ip：port 这个参数能复用吗？
xxxxx=jdbc:postgresql://ip:port
跟spring里面的"spring.datasource.url":"${xxxxxxxx}/db_schema",

**Comment by nobodyiam** [comment]
如果是和spring集成的话，是支持的。如果是api使用的话，目前不支持。
