### ISSUE TITLE
.properties namespace能否也支持通过"content"来获取原始的全部文本（可以是一个map？）

### ISSUE THREAD

**Issue by Colstuwjx** [apolloconfig/apollo#2847]
**Is your feature request related to a problem? Please describe.**
由于我这边是通过"content"这个magic key来获取一个namespace的全部内容，然后dump成文件的形式来管理配置文件和加载配置，而现在如果获取.properties namespace下的"content"内容的话，默认应该是拿不到值的。

为了一致性考虑，是否可以加一下这块支持？把"content"作为namespace级别的magic key，所有类型的namespace都支持这样操作？

**Describe the solution you'd like**
如题，添加对.properties获取content key时以kv形式返回全部的文本内容。

**Describe alternatives you've considered**
或者，如果能拿到.properties下面的全部key（是否apollo已经有这样的API？），然后遍历一次，变通生成全部文本内容也可以，但是如果从外界调用API来实现的话，可能性能方面比较糟糕。

**Additional context**
None

谢谢！

**Comment by nobodyiam** [comment]
`ConfigService.getConfigFile("application", ConfigFileFormat.Properties).getContent()`

**Comment by Colstuwjx** [comment]
感谢回复！请问一下，HTTP API 层面是否还没支持？见 [agollo相关issue](https://github.com/philchia/agollo/issues/60#issuecomment-567317275).

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/ConfigFileController.java

**Comment by philchia** [comment]
这个接口是从缓存读取的吧？能否支持不带缓存的接口

**Comment by nobodyiam** [comment]
@philchia 可以参考[1.3 通过不带缓存的Http接口从Apollo读取配置](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#13-%E9%80%9A%E8%BF%87%E4%B8%8D%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE)
