### ISSUE TITLE
RefreshScope 自动刷新影响范围

### ISSUE THREAD

**Issue by zuesgooogle** [apolloconfig/apollo#2851]
使用 RefreshScope.refresh(name) 刷新配置，会同时触发监听该事件的程序。比如：
spring-cloud-netflix-eureka-client:1.4.0
`
EurekaDiscoveryClientConfiguration

                @EventListener(RefreshScopeRefreshedEvent.class)
		public void onApplicationEvent(RefreshScopeRefreshedEvent event) {
			//This will force the creation of the EurkaClient bean if not already created
			//to make sure the client will be reregistered after a refresh event
			if(eurekaClient != null) {
				eurekaClient.getApplications();
			}
			if (autoRegistration != null) {
				// register in case meta data changed
				this.autoRegistration.stop();
				this.autoRegistration.start();
			}
		}

`

显然这不是Apollo的问题，而是EurekaClient 监听事件时，没有处理事件类型。
处理方式一：RefreshScopeRefreshedEvent.getName() == “eureka-client-event” 然后执行刷新
处理方式二：Apollo实现只对属性进行刷新
`
 @ApolloConfigChangeListener
    public void onChange(ConfigChangeEvent event) {
        Set<String> changeKeys = event.changedKeys();
        for (String key : changeKeys) {
            ConfigChange configChange = event.getChange(key);

            for (Map.Entry<String, RefreshConfig> configEntry : autoConfigs.entrySet()) {
                String component = configEntry.getKey();
                RefreshConfig config = configEntry.getValue();
                String prefix = config.getPrefix();

                if (key.startsWith(config.getPrefix())) {
                    try {
                        // 属性规则：属性名称 = prefix + "." + realName
                        String propertyName = key.substring(prefix.length() + 1);
                        BeanUtils.setProperty(config.getConfig(), propertyName, configChange.getNewValue());

                        logger.info("config changed. component: {}, data: {}", component, config.getConfig());
                    } catch (Exception e) {
                        logger.error("parser property failed. change key: {}, config component: {}", key, config.getComponent(), e);
                    }
                    break;
                }
            }
        }
    }
`

**Comment by nobodyiam** [comment]
这个倒是可以结合 #2825 一起来看
