### ISSUE TITLE
doker环境下如何使用灰度功能？

### ISSUE THREAD

**Issue by maxiaolong** [apolloconfig/apollo#2880]
docker环境下pod重启 ip会变化， 灰度功能如何适配呢？

**Comment by nobodyiam** [comment]
你是指k8s的场景吧？

对于k8s的场景确实需要解一下灰度配置的规则问题，之前有想法是借助于label来实现，使用百分比来实现的话，还没想清楚一些细节

**Comment by shown1985** [comment]
对我们也是个问题，需要帮忙解决下这个问题。

**Comment by christinkaka** [comment]
我们生产中也有这样的问题，但是貌似没有特别好的方式，如果是固定的label，那就和单独定义一个集群一样了，需要client上送多一个标志上来，这样等于是在现有的集群管理维度上多加了一层（并且这一层可能会因为管理体系不一样而不一样，比如有些可能是ip、有些可能是容器id、有些可能是园区节点），会增加管理复杂度以及实例的状态信息。我们想的方式是label依然送，但是能和cmdb这类资源管理系统联合起来（容器状态下沉至cmdb），apollo通过label其获取状态信息对其进行灰度下发，但这样又会把灰度功能做复杂了。

**Comment by nobodyiam** [comment]
duplicated with #2932

**Comment by trust-freedom** [comment]
> 我们生产中也有这样的问题，但是貌似没有特别好的方式，如果是固定的label，那就和单独定义一个集群一样了，需要client上送多一个标志上来，这样等于是在现有的集群管理维度上多加了一层（并且这一层可能会因为管理体系不一样而不一样，比如有些可能是ip、有些可能是容器id、有些可能是园区节点），会增加管理复杂度以及实例的状态信息。我们想的方式是label依然送，但是能和cmdb这类资源管理系统联合起来（容器状态下沉至cmdb），apollo通过label其获取状态信息对其进行灰度下发，但这样又会把灰度功能做复杂了。

请问这个容器化后的灰度配置问题，新特性开发的如何，或者有什么方案了吗？@nobodyiam
你们的问题解决了吗？  @christinkaka

**Comment by nobodyiam** [comment]
@trust-freedom 

可以尝试的思路：
1. 灰度规则增加自定义标签配置能力，IP 和 AppId 抽象为系统默认标签
2. 一条规则中的多个标签之间是 AND 的关系，比如同时配置了 ip 和 自定义标签，那么需要同时满足所有条件才能匹配上
3. 之前私有 namespace 只有一条规则，需要扩展为支持多条规则，和公共 namespace 一样，多条规则之间是 OR 的关系
4. 客户端定义自定义标签规范，可以从文件、system properties、system env 等多种途径获取标签的值
5. config service 基于客户端的标签信息计算灰度匹配结果

**Comment by nobodyiam** [comment]
This feature is implemented via #4013
