### ISSUE TITLE
1.6.0版本启用秘钥后，其它语言客户端调用api时如何传参

### ISSUE THREAD

**Issue by joyexpr** [apolloconfig/apollo#2986]
请问1.6.0版本启用秘钥后，其它语言客户端调用api时如何传参？

其它语言客户端接入指南文档中目前尚未更新相关说明，能否抽空更新下

**Comment by nobodyiam** [comment]
其它语言暂时还没支持，可以先参考下`com.ctrip.framework.apollo.core.signature.Signature#buildHttpHeaders`的实现

**Comment by joyexpr** [comment]
恩，后面看源码试出来了，http请求的Header里要增加2个字段，供大家参考（nodejs）：
Timestamp: '当前毫秒时间戳字符串timestamp'
Authorization: ':' + crypto.createHmac('sha1', '秘钥')
      .update('上面的timestamp' + '\n' + '请求url的path及query，如/configs/zk1/default/application？ip=10.0.0.1')
      .digest('base64')

注意：Authorization的值开头要有一个冒号，这个让我踩坑了挺久，因为之前没使用过，不清楚为什么这么设计

**Comment by nobodyiam** [comment]
格式是`Apollo ${appId}:${signature}`，最终发出去的内容应该是如下的格式：

```properties
Authorization: Apollo SampleApp:87BB3Pb70N6NaKNXfVmw5UdIzHg=
Timestamp: 1585451170575
```

**Comment by joyexpr** [comment]
收到，谢谢

**Comment by bruse-peng** [comment]
我是运维的同学不是开发，对于启用了秘钥后，怎么去访问，能不能说明下，直接请求报401：
![image](https://user-images.githubusercontent.com/47881861/80566535-ca427f00-8a25-11ea-87ce-83232b8311c8.png)

**Comment by nobodyiam** [comment]
已经增加说明[1.5 配置访问秘钥](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#15-%E9%85%8D%E7%BD%AE%E8%AE%BF%E9%97%AE%E7%A7%98%E9%92%A5)

**Comment by nisiyong** [comment]
辛苦顺哥写文档了，之前想帮忙写的。但是由于apollo文档都放到Github wiki里，这块是否不支持大家提PR @nobodyiam

**Comment by nobodyiam** [comment]
@nisiyong github的wiki貌似确实不支持PR

**Comment by eddycjy** [comment]
> 其它语言暂时还没支持，可以先参考下`com.ctrip.framework.apollo.core.signature.Signature#buildHttpHeaders`的实现

Go 客户端的话，@philchia 的 [philchia/agollo](https://github.com/philchia/agollo/releases/tag/v3.1.0) 在 v3.1.0 已经支持，有需要的小伙伴可以了解一下。
