### ISSUE TITLE
pubilc类型的namespace选择其他属性(json,yaml...)

### ISSUE THREAD

**Issue by ImLeoChan** [apolloconfig/apollo#2990]
在创建namespace的时候发现private类型的有属性下拉窗，可以选择属性，
而public类型的没有，是public类型只支持properties属性吗？

**Comment by zhaokejin** [comment]
同问，支持yml格式怎么拉取

**Comment by nobodyiam** [comment]
public类型目前只支持properties属性

**Comment by quzhixue-Kimi** [comment]
Hi @nobodyiam 
请问有计划加这个功能么？

BR
Kimi

**Comment by nobodyiam** [comment]
This feature was implemented by #3836
