### ISSUE TITLE
get namespaces by regular expression match

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#3063]
## Problem

Usually, use namespace like follow
通常，这样使用namespace

```properties
apollo.bootstrap.namespaces = application,TEST1.password
```
But sometimes, the namespaces require a new one, like `TEST1.management`, 
但是有时，会需要添加一个新的namespace，例如`TEST1.management`

So we need to change `apollo.bootstrap.namespaces`
所以我们需要改变`apollo.bootstrap.namespaces`
```properties
apollo.bootstrap.namespaces = application,TEST1.password,TEST1.management
```
then restart the application.
然后重启应用

Is there a way to use namespaces like follow?
是否存在一种如下使用namespace的方法？
```properties
apollo.bootstrap.namespaces = application,TEST1.*
```
The `TEST1.management` will work after associate it to the application without change `apollo.bootstrap.namespaces`
不用修改`apollo.bootstrap.namespaces`，`TEST1.management`就可以在关联到应用后生效

Through we can change the start script of application, like use vm options in java
虽然我们可以修改应用的启动脚本，就像java的vm参数
```shell
-Dapollo.bootstrap.namespaces = application,TEST1.password,TEST1.management
```
there are still some workload
但是仍旧存在一些工作量

## solution 

There are 2 alternative ways to enable the namespaces
有2种可选的方法使得配置生效

One is in runtime, application doesn't need to restart;
一种是运行时，应用不需要重启

another is in bootstrap time, like code in method `com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)`, application need to restart.
另一种是在加载阶段，就像在方法`com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)`中的代码。应用需要重启

## alternatives I've considered

Get new namespace in runtime is better then bootstrap time, but may hard to implement.
运行时获取新的namespace比在加载时更好，但是可能难以实现.

There is a way to implement it in bootstrap time. When application run method `com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)`, query all namespaces from config service which AppId associated, then use regular expression to match them, the match one will add to `ConfigurableEnvironment`.
这里有一个在加载阶段实现这个功能的方法。当应用运行方法`com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)`时，从config service中查询AppId关联了哪些namespace，然后使用正则去匹配他们，符合的会被加入`ConfigurableEnvironment`。

## Additional context

The order of namespace will affect the priority of config, but when use regular expression match, user cannot decided which one namespace has higher priority.
namespace的顺序会影响优先级，但是当使用正则匹配后，用户无法决定哪个namespace的优先级更高。

**Comment by nobodyiam** [comment]
I'm curious what the actual use case would be? To load new namespaces without changing code?

**Comment by Anilople** [comment]
> I'm curious what the actual use case would be? To load new namespaces without changing code?

level 1: Load new namespaces without changing code. But the application need to restart.
level 2: Load new namespaces without changing code and the application doest not neet to restart

**Comment by nobodyiam** [comment]
I mean what kind of situations would use this feature?

In my mind, if a new namespace is added, it would mean there would be some code changes to use the configurations in this new namespace.

**Comment by Anilople** [comment]
> I mean what kind of situations would use this feature?
> 
> In my mind, if a new namespace is added, it would mean there would be some code changes to use the configurations in this new namespace.

It about application's management, multiple application use namespaces like follow:
```properties
apollo.bootstrap.namespaces = TEST1.*,application
```
give application's config management to organization **TEST1**.

One day, **TEST1** want to management application's password, so add namespace *TEST1.password*,

Another day, **TEST1** want to management application's database's parameters, so add namespace *TEST1.database.parameters*,

The demand is on **TEST1**'s side, because sometimes need to management applications, but also need to group the config to differect namespace(Through just one namespace **TEST1.management** can do that)

**Comment by Anilople** [comment]
The use of namespace is a precise design,
Which namespaceId is used in runtime should be resolve before appliction startup.

If there is dynamic namespaceId in application, user can read them by apollo-client manually.
