### ISSUE TITLE
apollo配置缓存在容器中怎么处理比较好

### ISSUE THREAD

**Issue by coonne** [apolloconfig/apollo#3081]
虚拟和实体中，APOLLO的配置缓存有办公永久的存于磁盘上，APOLLO不可用的时候还能读取缓存文件。

容器环境中，缓存文件是随着容器生成的，在APOLLO不可用的情况下，容器重启就无法读取在线配置或者缓存了。

在当前 还没有多活，与灾备的情况 下，有没有好的解决方案。

**Comment by YoungRainyDay** [comment]
容器设置一下文件夹挂载啊

**Comment by nisiyong** [comment]
@YoungRainyDay 不太可能直接挂载一个`/opt/data`大目录，因为这样所有应有都能访问，会导致其他应用配置泄漏问题。

**Comment by wcp1231** [comment]
我们最近也遇到这个问题

> @YoungRainyDay 不太可能直接挂载一个`/opt/data`大目录，因为这样所有应有都能访问，会导致其他应用配置泄漏问题。

大目录的问题可以通过 `subPathExpr` 分配不同的目录给 Pod，在 Pod 内看到的都是 `/opt/data`。这样只有登录 Nodes 机器才能看到所有的配置，在 Pod 只能看到自己的配置。

不知道还有没有更好的解决方式。

**Comment by nobodyiam** [comment]
Duplicate of #3506
