### ISSUE TITLE
对于密码一类配置，除了加密存储外，能否在Portal展示时进行掩码展示（即使是密文）

### ISSUE THREAD

**Issue by JefferyCat** [apolloconfig/apollo#3133]
对于密码或类似的敏感数据的配置，在Portal上展示时，能否进行掩码展示。
即，在Portal上添加一个配置时，可以指定该配置是安全敏感的，那么在存储时可以进行加密存储（加密存储社区内已有实现），在展示时进行掩码展示（如全部显示成*）

**Comment by nobodyiam** [comment]
see #3187

**Comment by nobodyiam** [comment]
Duplicate of #3187
