### ISSUE TITLE
portal管理员工具的系统信息中怎么显示1个env的所有cluster的信息

### ISSUE THREAD

**Issue by zzzhcc** [apolloconfig/apollo#3204]
我有2个idc，1个a，1个b
在a中部署了config server, admin server ,portal, mysql
在b中只部署了config server,直接连a的mysql
现在我有一个env叫pro，通过设置/opt/settings/server.properties中的idc属性，a和b各自连注册自己的eurake，连自己的config server。但在portal管理员工具的系统信息中只能看到a机房的env信息，看不到b的。
请问我需要怎么配置，才能看到全部的。

**Comment by nobodyiam** [comment]
duplicated with #3638
