### ISSUE TITLE
Release表清理策略

### ISSUE THREAD

**Issue by MilkSDF** [apolloconfig/apollo#3208]
apollo数据库里Release表非常大，咨询下是否有清理数据的策略。之前删除某个时间点前的数据，好像需要应用重新发布。

**Comment by nobodyiam** [comment]
release表存放的是应用配置的历史版本，涉及到回滚、审计等因素，所以目前还无法做自动清理，可以根据自己公司的需求（比如对某个应用保留多久的配置版本）实现一下清理策略？

**Comment by MilkSDF** [comment]
3Q

**Comment by jadedrip** [comment]
不回滚的话，Release 表可以清空吗？

**Comment by nobodyiam** [comment]
@jadedrip 如果不回滚的话，可以针对每个app+cluster+namespace的组合保留最近一条记录

**Comment by nobodyiam** [comment]
assigned to student `吴铭侃`, see https://summer-ospp.ac.cn/#/org/orgdetail/c4cc2271-6627-4965-a5ec-37d5ac3c0ad8/

**Comment by youngzil** [comment]
> assigned to student `吴铭侃`, see https://summer-ospp.ac.cn/#/org/orgdetail/c4cc2271-6627-4965-a5ec-37d5ac3c0ad8/

麻烦问下，目前这个清理有方案吗 或者 具体计划吗？目前是一个什么状况？

**Comment by nobodyiam** [comment]
Unfortunately, the student didn't complete this task so this feature is still open.

**Comment by chunlaiqingke** [comment]
我们自己实现的方案是使用mysql的表分区，做2个分区，然后做一个页面手动腾数据和清理数据，用分区表是为了truncate，分区之间腾数据的时候不用停机，把最新的一条release腾到新分区，结束之后把老的分区truncat掉，下次需要清的时候，再往回倒腾就行，就像2个servivor一样
