### ISSUE TITLE
超简单的Rancher安装Apollo集群

### ISSUE THREAD

**Issue by Yif-Liu-Github** [apolloconfig/apollo#3260]
### 0.准备工作--数据库
mysql版本5.6.5+
导入2个数据库
[apolloportaldb.sql](https://github.com/nobodyiam/apollo-build-scripts/blob/master/sql/apolloportaldb.sql)
[apolloconfigdb.sql](https://github.com/nobodyiam/apollo-build-scripts/blob/master/sql/apolloconfigdb.sql)
### 1.添加应用商店。
-   1.1进入某个集群的某个项目下（我现在在909192集群的default项目下）
-   1.2点击应用商店，点击管理，点击添加应用商店
-   1.3随便起个名，填上Apollo的固定地址http://ctripcorp.github.io/apollo/charts ，Helm版本选择 Helm V3，保存
![image](https://user-images.githubusercontent.com/54025962/91144319-718aa680-e6e6-11ea-9f4e-4067fd6b5ffb.png)

### 2.找到刚添加的应用商店。
-   2.1回到集群项目下，点击应用商店，点击启动。
![image](https://user-images.githubusercontent.com/54025962/91145145-992e3e80-e6e7-11ea-99f6-1d4c05c2ba84.png)
-   2.2找到刚添加的应用商店
![image](https://user-images.githubusercontent.com/54025962/91145477-18bc0d80-e6e8-11ea-85b6-b60834654c2d.png)
### 3.安装apollo-service（一定要先装apollo-service）
- 3.1点击刚才应用商店的Apollo-Service，进入到安装前的配置界面
- 3.2参照图片 配置数据库信息 ，点击启动，等待安装完成。
configdb.host=127.0.0.1
configdb.port=3306
configdb.dbName=ApolloConfigDB
configdb.userName=root
configdb.password=123456
configdb.connectionStringProperties=characterEncoding=utf8&useSSL=false
![image](https://user-images.githubusercontent.com/54025962/91145929-c92a1180-e6e8-11ea-9deb-1513494dd99c.png)
- 3.3回到集群项目下，从工作负载界面中确定apollo-service-apollo-adminservice 、apollo-service-apollo-configservice两个组件状态正常。
![image](https://user-images.githubusercontent.com/54025962/91149847-2b394580-e6ee-11ea-8490-e3a48ee29275.png)
- 3.4 对外暴露apollo-service-apollo-configservice 的访问端口
集群项目下，从服务发现界面中，找到apollo-service-apollo-configservice，在高级选项中，选择类型为NodePort（所有主机端口均可访问），保存后会发现被分配了一个随机的端口，IP:端口即可访问此组件，第4步安装apollo-portal会用到。
![image](https://user-images.githubusercontent.com/54025962/91147191-80735800-e6ea-11ea-809e-6158a93c0cf5.png)
### 4安装apollo-portal
- 4.1点击刚才应用商店的apollo-portal，进入到安装前的配置界面
- 4.2参照图片 配置数据库信息apollo-service访问地址（步骤3.4得到的地址），和 点击启动，等待安装完成。
portaldb.host=127.0.0.1
portaldb.port=3306
portaldb.dbName=ApolloPortalDB
portaldb.userName=root
portaldb.password=123456
portaldb.connectionStringProperties: characterEncoding=utf8&useSSL=false
config.envs=dev
config.metaServers.dev=http://127.0.0.1:26591/
![image](https://user-images.githubusercontent.com/54025962/91148666-95e98180-e6ec-11ea-9da0-b186226959cb.png)
- 4.3回到集群项目下，从工作负载界面中确定apollo-portal组件状态正常。
![image](https://user-images.githubusercontent.com/54025962/91150538-19a46d80-e6ef-11ea-85d7-7ce3d7fb1d0a.png)
- 4.4 对外暴露apollo-portal的访问端口
集群项目下，从服务发现界面中，找到apollo-portal，在高级选项中，选择类型为NodePort（所有主机端口均可访问），保存后会发现被分配了一个随机的端口，IP:端口即可访问此组件。
![image](https://user-images.githubusercontent.com/54025962/91150741-5e300900-e6ef-11ea-91a2-62fcf2d98f69.png)

**Comment by nobodyiam** [comment]
@Yif-Liu-Github 

多谢贡献，有一点想确认下，在 3.4 步骤中如果 apollo-portal 和 apollo-configservice/adminservice 在同一个 k8s 集群的话，可以不用暴露 nodeport 的，直接通过 service 访问即可。
如果 apollo-portal 和 apollo-configservice/adminservice 不在同一个 k8s 集群的话，那么可以通过 nodeport 来暴露，不过同时还得配置下 configService.config.adminServiceUrlOverride，详见[指定Meta Server返回的apollo-adminservice地址](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#241345-%E6%8C%87%E5%AE%9Ameta-server%E8%BF%94%E5%9B%9E%E7%9A%84apollo-adminservice%E5%9C%B0%E5%9D%80)
