### ISSUE TITLE
注册中心eureka改造成nacos，有好的改造方案吗？

### ISSUE THREAD

**Issue by wuhwAndGod** [apolloconfig/apollo#3444]

**Comment by chenzy2017** [comment]
哎, 换成zk都没啥commit可参考的, 更别提nacos了~

**Comment by nisiyong** [comment]
这块确实可以支持下，剥离eureka后configservice就是无状态的

**Comment by nobodyiam** [comment]
可以参考下 kubernetes 服务发现的实现：
1. https://github.com/ctripcorp/apollo/blob/master/apollo-adminservice/src/main/resources/application-kubernetes.properties
2. https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/resources/application-kubernetes.properties
3. https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/KubernetesDiscoveryService.java

**Comment by chenzy2017** [comment]
谢谢宋总, 我试试~
