### ISSUE TITLE
openapi getNamespace prompt user when namespace not exists

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#3580]
**Is your feature request related to a problem? Please describe.**

I want to predicate that a namespace exists or not.

When Java method
`com.ctrip.framework.apollo.openapi.client.ApolloOpenApiClient#getNamespace`
throw an exception, user may doesn't know that this exception is caused by namespace not exists or other `RuntimeException`.

**Describe the solution you'd like**

Define a new NamespaceNotExistsException extends RuntimeException, when namespace is not exists, throw that exception.

And add javadoc to describe it.

**Describe alternatives you've considered**

return null when namespace not exists

**Comment by nobodyiam** [comment]
The ApolloOpenApiException already has a getStatus method, if this returns 404, then it means it doesn't exist.

https://github.com/ctripcorp/apollo/blob/a06813f147e7a20ef74d974e58f941175854522b/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/exception/ApolloOpenApiException.java#L13-L15
