### ISSUE TITLE
Apollo Java客户端初始化过程日志打印问题

### ISSUE THREAD

**Issue by laywin** [apolloconfig/apollo#3640]
**Describe the bug**
当apollo.bootstrap.eagerLoad.enabled=true时，Apollo初始化过程中的日志均无法输出

**To Reproduce**
当apollo.bootstrap.eagerLoad.enabled=true时，spring boot日志系统并未初始化好，这个过程中产生的日志均无法输出

**Expected behavior**
建议可以根据类似spring boot中DeferredLog的处理方式来进行这个阶段的日志打印

**Comment by nobodyiam** [comment]
implemented by #3677
