### ISSUE TITLE
使用JDK16启动报错

### ISSUE THREAD

**Issue by zhangdc007** [apolloconfig/apollo#3642]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

版本 Apollo client 1.8.0，spring boot 2.4.4
在JDK8，JDK11，JDK15都可以运行启动，在JDK16 启动报错

**期望**
期望在JDK16能启动，当然 最终是想今年9月升到17

![image](https://user-images.githubusercontent.com/7760477/115651229-5a778380-a35d-11eb-9444-495751244357.png)

- 版本：1.8.0
- 错误日志
([jdk16_error.txt](https://github.com/ctripcorp/apollo/files/6355310/jdk16_error.txt))
- 平台和操作系统：spring boot 2.4.4 JDK 16 mac OS

**Comment by nobodyiam** [comment]
#3646 was reverted based on the discussion #3896
