### ISSUE TITLE
[Event] Summer 2021 of Open Source Promotion Plan

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#3681]
[Open Source Promotion Plan](https://summer.iscas.ac.cn/) is committed to cultivating and discovering more outstanding developers, promoting the development of open source software and the construction of excellent open source software communities.

As a member of the open source force, the Apollo community actively responded and [signed up to participate](https://summer.iscas.ac.cn/#/org/orgdetail/apollo), hoping to attract student groups to participate in the construction of the Apollo open source community through this activity, cultivate new forces for the sustainable development of the community, and promote the development of the open source ecology together.

Apollo community has submitted [3 tasks](https://summer.iscas.ac.cn/#/org/orgdetail/apollo) as of now and if you have any idea or want to participate as a [mentor](https://summer.iscas.ac.cn/help/mentor/), feel free to comment in this thread.

Students are encouraged to participate in this open source event, please refer [student guide](https://summer.iscas.ac.cn/help/student/) for more information.

**Comment by klboke** [comment]
mentor +1
