### ISSUE TITLE
有没有 API 可以支持批量创建 AppId 与 Namespace 并上传配置

### ISSUE THREAD

**Issue by lymslive** [apolloconfig/apollo#3688]
**你的特性请求和某个问题有关吗？请描述**

假设已有一堆微服务，原来有自己的本地配置文本，想迁移到 Apollo 配置中心。那么必须在 Web Portal 端的管理界面手动一个个创建相应的 AppId 与 Namespace 并填充配置吗？有没有暴露 API 支持脚本批量创建 AppId/Namespace 并上传配置呢？
在开发测试阶段，我们手动创建一些 AppId 填上配置没问题，但是到发布阶段，如果有支持批量操作的 API 接口，会对运维操作更友好，沟通也更方便。

**清晰简洁地描述一下你希望的解决方案**

希望有 API 支持创建 AppId/Namespace 及上传配置。

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by 1123183721** [comment]
https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform

**Comment by lymslive** [comment]
我看了一下那个 open api 文档，感觉不能满足我之前提出的需求。open api 好像只能对已创建的 appId 与 Namespace 授权 token.
而我提出的场景是迁移配置初始阶段，希望有 api 创建 appId 与 namespace 以避免手动逐个创建。

**Comment by lymslive** [comment]
我看了一下那个 open api 文档，感觉不能满足我之前提出的需求。open api 好像只能对已创建的 appId 与 Namespace 授权 token.
而我提出的场景是迁移配置初始阶段，希望有 api 创建 appId 与 namespace 以避免手动逐个创建。

**Comment by nobodyiam** [comment]
目前不支持通过 open api 创建 app

**Comment by Accelerater** [comment]
@nobodyiam 是不是可以添加一个 创建appId的openapi接口呢 这块我正好也有需求 。可以贡献出来

**Comment by nobodyiam** [comment]
@Accelerater 可以发起一个[discussion](https://github.com/ctripcorp/apollo/discussions)大家讨论下，open api 创建 app 目前主要的阻碍是权限如何管理的问题，因为目前的权限都是绑在 app 上的
