### ISSUE TITLE
Refactor the soft delete design to support unique constraint index

### ISSUE THREAD

**Issue by nisiyong** [apolloconfig/apollo#3700]
**Is your feature request related to a problem? Please describe.**

Due to the Apollo design that any important data should not be deleted physically, we use soft delete in most scenarios.
But the current soft delete design is too simple, and cause we cannot add a unique constraint index. There are some issues talking about duplicate data:
- #3635 
- #3203 
- #1991
- #1317

**Describe the solution you'd like**

### Step 1. Add column `DeletedAt` for all tables which contains the  column `IsDeleted`

```
ALTER TABLE `xxx` 
ADD COLUMN `DeletedAt` BIGINT(20) NOT NULL DEFAULT 0 AFTER `IsDeleted`;
```

### Step 2. Refactor the persistent layer logic
 
- **Delete Logic**：replace `set IsDeleted=1`  with `set  DeletedAt=${currentTimeMillis}, IsDeleted=1`

> NOTE：We can use `System.currentTimeMillis()` generate the ${currentTimeMillis}

### Step 3. Wash data and add the unique constraint index 

Initial the deleted data `DeletedAt` value as **Negative number of primary key Id**

```
UPDATE `xxx` SET `DeletedAt`=-Id WHERE `IsDeleted`= 1 and `DeletedAt`= 0;
```

### Step 4. Remove Column`IsDeleted` in future（Optional）

- Refactor the persistent layer logic, remove the stuff code about the column `IsDeleted`
  - **Delete Logic**：replace `set  DeletedAt=${currentTimeMillis}, IsDeleted=1` with `set  DeletedAt=${currentTimeMillis}。
  - **Query Logic**：use `where DeletedAt=0`

- Execute the DDL, drop the column `IsDeleted`
  ```
  ALTER TABLE `xxx` 
  DROP COLUMN `IsDeleted`;
  ```

### Add Column `DeletedAt`

1. Execute the DDL, add the column `DeletedAt`
2. Deploy `ConfigService`, `AdminService`, `Portal` in order
3. Execute the DML, wash the historical data
4. Execute the DDL,  add the unique constraint index

### Drop Column `IsDeleted` (Optional)

1. Deploy `ConfigService`, `AdminService`, `Portal` in order
2. Execute the DDL, drop the column `IsDeleted`

@nobodyiam Please take a look.

**Comment by nobodyiam** [comment]
@nisiyong 

Thanks for raising this! This is an issue that the community wants to solve for a very long time!
Here are some comments:

> Query Logic：replace `where IsDeleted=0` with `where (DeleteAt=0 and IsDeleted=0)`

I think this is not necessary since if `IsDeleted=0` then `DeleteAt=0` is always true?

> UPDATE `xxx` SET `DeleteAt`=-Id, `IsDeleted`=0 WHERE `IsDeleted`=1;

Why would we set the `IsDeleted` to 0? Is it a typo?

> ### Add Column `DeleteAt`
> 1 Execute the DDL, add the column DeleteAt
> 2 Deploy ConfigService, AdminService, Portal in order
> 3 Execute the DML, wash the historical data
> 4 Execute the DDL, add the unique constraint index

The upgrade steps look fine to me.
However, introducing these manual steps indicate this is a major change. And it's better to bump apollo version from 1.x to 2.0.

**Comment by nisiyong** [comment]
## First Question

> > Query Logic：replace `where IsDeleted=0` with `where (DeleteAt=0 and IsDeleted=0)`
> 
> I think this is not necessary since if `IsDeleted=0` then `DeleteAt=0` is always true?


Yes, If you want to keep both columns long time, we can still use `where IsDeleted=0`.
And If we want to remove `IsDeleted` in future, we should use `where DeleteAt=0`, but consider this situation:
- After we execute step-1, all rows will be set `DeleteAt=0`, if this time we deploy apollo, the application we read the dirty data because we haven's wash the data.
- Simply speaking, if we keep both columns, we do nothing for the query logic; If only keep the `DeleteAt` column in the future, we should use `where (DeleteAt=0 and IsDeleted=0)` for the capability.

## Second Question

> > UPDATE `xxx` SET `DeleteAt`=-Id, `IsDeleted`=0 WHERE `IsDeleted`=1;
> 
> Why would we set the `IsDeleted` to 0? Is it a typo?

Yes, I have correct it. Please check again.

**Comment by nobodyiam** [comment]
Regarding the first question, I think we can keep the original condition `where IsDeleted=0` since no matter the washing/conversion is done or not, this condition is always right. In the future, we may remove the `IsDeleted` column and only use the `where DeleteAt=0` condition, however I assume it will take a long time since it's a breaking change and I can't think of a smooth way for this upgrade.

Regarding the second question, I think the statement should add the `DeleteAt=0` condition since according to the upgrade steps, this conversion script is run after the new code is deployed, which means there might exist records with `IsDeleted`=1 and `DeleteAt`= ${currentTimeMillis} already.
```
UPDATE `xxx` SET `DeleteAt`=-Id WHERE `IsDeleted`=1 and `DeleteAt`=0;
```

**Comment by nisiyong** [comment]
Okay. Regarding the first question, we keep the original query condition.

> UPDATE `xxx` SET `DeleteAt`=-Id WHERE `IsDeleted`=1 and `DeleteAt`=0;

The above DML is correct, I will update the issue description.

**Comment by nisiyong** [comment]
@nobodyiam By the way, the new column name which is better, `DeleteAt` or `DeletedAt`?

**Comment by nobodyiam** [comment]
@nisiyong personally I would prefer `DeletedAt` 😀

**Comment by nisiyong** [comment]
Okay, `DeletedAt` is fine. I have updated the description.

**Comment by nobodyiam** [comment]
@nisiyong are you still working on this?

**Comment by nisiyong** [comment]
> @nisiyong are you still working on this?

Yes, I have done some work on the local but didn't finish. I am busy these days, I will create a PR ASAP.

**Comment by nisiyong** [comment]
> ### Step 2. Refactor the persistent layer logic
> * **Delete Logic**：replace `set IsDeleted=1`  with `set  DeletedAt=${currentTimeMillis}, IsDeleted=1`
> 
> > NOTE：We can use `System.currentTimeMillis()` generate the ${currentTimeMillis}

According to Step 2, I try to refactor the code. But there has a little trouble.
How to pass the `currentTimeMillis` to the annotation `@SQLDelete`? 

```java
@SQLDelete(sql = "Update Item set isDeleted = 1 where id = ?")
```

@nobodyiam 
Are you familiar with the usage of the annotation`@SQLDelete`? I don't figure it out after searching solution from Google.

But there has another way, not graceful, we need to write the soft delete method with `@Modifying @Query` for every table, like this as follow:
```java
@Modifying
@Query("delete from InstanceConfig  where ConfigAppId=?1 and ConfigClusterName=?2 and ConfigNamespaceName = ?3")
int batchDelete(String appId, String clusterName, String namespaceName);
```

**Comment by nobodyiam** [comment]
You may take look at `com.ctrip.framework.apollo.common.entity.BaseEntity`, there are several methods like prePersist, preUpdate and preRemove

**Comment by nisiyong** [comment]
There are 3 delete ways in the current codes:

### 1. Use Repository#delete

```java
favoriteRepository.delete(favorite);
```

### 2. Use Repository#save

```java
item.setDeleted(true);
item.setDataChangeLastModifiedBy(operator);
Item deletedItem = itemRepository.save(item);
```

### 3. Use custom SQL

```java
@Modifying
@Query("delete from InstanceConfig  where ConfigAppId=?1 and ConfigClusterName=?2 and ConfigNamespaceName = ?3")
int batchDelete(String appId, String clusterName, String namespaceName);
```

---
The @preRemove annotation seems to only works in a 1st way.
I think I should consider all situations.

**Comment by nobodyiam** [comment]
I think we need to only consider the first 2 cases, the third case is `hard` delete instead of `soft` delete.
For case 2, it looks like we could modify the logic of `com.ctrip.framework.apollo.common.entity.BaseEntity#setDeleted`?

**Comment by nisiyong** [comment]
> For case 2, it looks like we could modify the logic of `com.ctrip.framework.apollo.common.entity.BaseEntity#setDeleted`?

That's a good idea, it just only needs to modify BaseEntity. For case 2, I have tested it, and it works!

But with the first case, @PreRemove didn't work, it cannot update the `deletedAt` column in the database because the `@SQLDelete()` needs to add the `deletedAt` column. Like this:
```
@SQLDelete(sql = "Update Favorite set isDeleted = 1, deletedAt = currentMillis where id = ?")
```

But it is hard to pass the `currentMillis` to this SQL even I have tried a lot of ways. I quit.

---

And I found another way, we could replace  `deletedAt bigint` with `DataChange_DeletedTime timestamp`. It is easy to redefine the @SQLDelete with the MySQL function`CURRENT_TIMESTAMP()`, like this:
```
@SQLDelete(sql = "Update Favorite set isDeleted = 1, DataChange_DeletedTime = CURRENT_TIMESTAMP() where id = ?")
```

Although the`UNIX_TIMESTAMP()` works for `deletedAt`, it is only for seconds. So I decide to use `DataChange_DeletedTime timestamp` like `DataChange_CreatedTime` and `DataChange_LastTime`.

How do you think? @nobodyiam

**Comment by nobodyiam** [comment]
I think option2 is the better way, is it possible we get the milliseconds?

**Comment by nisiyong** [comment]
> I think option2 is the better way, is it possible we get the milliseconds? e.g.
> 
> ```sql
> select ROUND(UNIX_TIMESTAMP(NOW(4))*1000);
> ```

It is Okay. But do you wanner make the @SQLDelete like that: 
```
@SQLDelete(sql = "Update Favorite set isDeleted = 1, deletedAt = ROUND(UNIX_TIMESTAMP(NOW(4))*1000) where id = ?")
```

I had created the PR, you can review the code. And it still has some works to do, like add the unique constraint.
