### ISSUE TITLE
SpringValueRegistry#scanAndClean  方法判断疑似不生效导致内存溢出

### ISSUE THREAD

**Issue by xmzDesign** [apolloconfig/apollo#3787]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
我在spring中声明一个bean的scope为prototype，并在这个bean中注入一个apollo 配置属性，类似下图（举个例子，真实的不是这样）
![image](https://user-images.githubusercontent.com/26053310/123283054-97b6e800-d53d-11eb-8adf-a5fdaa1a5026.png)

上线后过了段时间发现应用内存溢出了，dump下来内存发现全部都是SpringValue这个对象
![image](https://user-images.githubusercontent.com/26053310/123283626-27f52d00-d53e-11eb-83ad-d1d5f3c9c32e.png)
事实上，承载这个属性的bean早就被销毁了，证据如下
![image](https://user-images.githubusercontent.com/26053310/123284032-83271f80-d53e-11eb-8e3d-528d8b9d80d3.png)

我看到SpringValueRegistry#scanAndClean 方法是会清理这些不再被使用的属性，所以我判断 isTargetBeanValid 这个方法判断的不够严谨

`private void scanAndClean() {
    Iterator<Multimap<String, SpringValue>> iterator = registry.values().iterator();
    while (!Thread.currentThread().isInterrupted() && iterator.hasNext()) {
      Multimap<String, SpringValue> springValues = iterator.next();
      Iterator<Entry<String, SpringValue>> springValueIterator = springValues.entries().iterator();
      while (springValueIterator.hasNext()) {
        Entry<String, SpringValue> springValue = springValueIterator.next();
        if (!springValue.getValue().isTargetBeanValid()) {
          // clear unused spring values
          springValueIterator.remove();
        }
      }
    }
  }`

 

**期望**

希望我在spring中声明一个bean的scope为prototype，并在这个bean中注入一个apollo 配置属性后，当这个bean销毁，属性也能被垃圾回收掉

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
 version=1.4.0
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
WeakReference 在 fgc 后会被清理掉，isTargetBeanValid 判断就会为 false，进而 SpringValue 也会被 gc 掉。我在本地测试了这个场景也是会被清理掉的。

看了你的截图，初步猜测是在 dump 内存时候发生了 gc，所以 WeakReference 被清理掉了，但是 SpringValue 还没来得及被清理（5 秒一次），可以尝试手动触发下 gc 然后再 dump 下内存看看。
