### ISSUE TITLE
apollo-quick-start1.8.0，访问有报错。failed! Exception: Could not extract response: no suitable HttpMessageConverter found for response type

### ISSUE THREAD

**Issue by 799983050** [apolloconfig/apollo#3839]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
liunx系统上，安装了这个网盘里的1.8.0版本，启动成功。但是访问界面有异常，显示不了环境信息
https://pan.baidu.com/s/1Ieelw6y3adECgktO0ea0Gg?_at_=1627036169807#list/path=%2F

简介明了地描述你希望正常情况下应该发生什么
![图片](https://user-images.githubusercontent.com/45658355/126769950-1629415a-0691-4bd7-b0b1-355d755ff6b3.png)
![图片](https://user-images.githubusercontent.com/45658355/126769843-e974059d-d4df-4a19-b822-09f277d1dae9.png)

**Comment by nobodyiam** [comment]
看报错信息应该是 meta server 地址填错了，你访问下 http://192.168.0.184:8080/services/config 看下返回什么

**Comment by 799983050** [comment]
@nobodyiam 返回的这个，你帮看下
![图片](https://user-images.githubusercontent.com/45658355/126925327-27f4304b-6fed-4c2f-8e6b-5e8e4922fd76.png)

**Comment by 799983050** [comment]
@nobodyiam 查看apollo-server.log 有这个报错，改怎么解决呢

**Comment by nobodyiam** [comment]
> @nobodyiam 返回的这个，你帮看下
> ![图片](https://user-images.githubusercontent.com/45658355/126925327-27f4304b-6fed-4c2f-8e6b-5e8e4922fd76.png)

这个说明 meta server 地址不对啊，为什么是 spark 的页面呢？
