### ISSUE TITLE
关于配置的灰度发布

### ISSUE THREAD

**Issue by akaxb** [apolloconfig/apollo#3852]
目前Apollo是否仅仅支持基于客户端IP的灰度发布？并且灰度的配置是否只支持一个？
我们遇到的问题是：
当我们的应用部署到K8s后，我们没有能力去固定IP，所以没办法使用Apollo的灰度。这个，有没有一些办法解决
另外：Apollo未来会支持其他方式的灰度吗？比如根据请求的参数中版本号参数去获取不同的配置

**Comment by nobodyiam** [comment]
这个需求目前在[开源之夏活动](https://summer.iscas.ac.cn/#/org/orgdetail/apollo)跟进中

**Comment by akaxb** [comment]
看到啦，方便问下，这个活动有没有大概的交付时间。谢谢
