### ISSUE TITLE
apollo服务器日志较大，是否可删除

### ISSUE THREAD

**Issue by zzw122333** [apolloconfig/apollo#3873]
发现服务器apollo这两个日志很大，是否可删除？

![lALPD2eDQio19nLNAW7NA9o_986_366](https://user-images.githubusercontent.com/15028767/128446581-ff6a158f-0974-4525-a150-adb4bf575da8.png)
![lALPD4d8tfUvC7jNAVXNBSw_1324_341](https://user-images.githubusercontent.com/15028767/128446603-691220a2-7bd9-4346-8df4-7d6c04eb7f2f.png)

**Comment by nobodyiam** [comment]
可以删除，另外可以考虑升级到 1.8.2 版本，#3488 解决了该日志文件过大的问题
