### ISSUE TITLE
test: improve coverage

### ISSUE THREAD

**Issue by mghio** [apolloconfig/apollo#3874]
The code coverage https://codecov.io/github/ctripcorp/apollo seems to be less than 60%.

It would be great if it can be brought up around 80-90%.

**Comment by nobodyiam** [comment]
Yes, 80-90% is truly a better status. Do you have some time to work on this?

**Comment by mghio** [comment]
OK, I'm free on weekends, but I need to take the time to familiarize myself with the code logic first.

**Comment by nobodyiam** [comment]
Sure, feel free to let the community know if you need any assistance.

**Comment by Anilople** [comment]
#4113 add test for https://github.com/apolloconfig/apollo/blob/4a202065964a2daf4ebe1316b0f6ea5c0ce73105/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/PropertiesUtil.java

Thanks @youyulan 

----

The test of xxxUtil is a good first pull request for new contributors.

**Comment by Anilople** [comment]
These xxxUtil are lacking test too.

* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/utils/EntityManagerUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/util/BeanRegistrationUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/http/HttpUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/exception/BeanUtilsException.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/BeanUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/ExceptionUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/DeprecatedPropertyNotifyUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/DNSUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/MachineUtil.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/ResourceUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/io/IOUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/Utils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/util/OpenApiBeanUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/util/ConfigToFileUtils.java
* [ ] https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/util/NamespaceBOUtils.java

**Comment by nobodyiam** [comment]
@ayush0407 Thanks for your kind support, I believe what @Anilople proposed is still valid.

> These xxxUtil are lacking test too.
> 
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/utils/EntityManagerUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/util/BeanRegistrationUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/http/HttpUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/exception/BeanUtilsException.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/BeanUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/ExceptionUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/DeprecatedPropertyNotifyUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/DNSUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/MachineUtil.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/ResourceUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/io/IOUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/Utils.java [Add unit tests for Utils #4193](https://github.com/apolloconfig/apollo/pull/4193) Thanks @joshknopp
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/util/OpenApiBeanUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/util/ConfigToFileUtils.java
> * [ ]  https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/util/NamespaceBOUtils.java

**Comment by ayush0407** [comment]
Ok cool, I'll try to cover as many of these as I can over this weekend. Thanks guys!

**Comment by ayush0407** [comment]
Which branch should I pull from and commit to?

**Comment by Anilople** [comment]
> Which branch should I pull from and commit to?

see https://www.apolloconfig.com/#/en/contributing

**Comment by ayush0407** [comment]
Yeah, I forked the project created a new branch but when I am trying to commit from my eclipse IDE it's not allowing me.
Am I missing something?
Please help me out.

**Comment by Anilople** [comment]
> Yeah, I forked the project created a new branch but when I am trying to commit from my eclipse IDE it's not allowing me. Am I missing something? Please help me out.

Try another git tool?

* https://desktop.github.com/
* https://tortoisegit.org/
* Git bash

**Comment by ayush0407** [comment]
I tried from terminal using auth code but it's giving access denied 403 for my id?
remote: Permission to ayush0407/apollo.git denied to ayush0407.
fatal: unable to access 'https://github.com/ayush0407/apollo.git/': The requested URL returned error: 403
ayushjha@Ayushs-MacBook-Pro apollo7 %
