### ISSUE TITLE
configService模块中的controller/ConfigFileController文件冗余代码是否可以去掉呢

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#3886]
看了下代码，发现configService模块中的controller/ConfigFileController.java这个文件，没有请求会触发到这个控制器，请问下这个控制器的主要作用是什么呢，如果不需要的话，程序中是否可以删除该文件呢

**Comment by nobodyiam** [comment]
see https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide
