### ISSUE TITLE
当我有多个Apollo站点时，要把某个命名空间的配置导入到另一个站点时只能手动一个个添加。能不能添加个导入的功能？

### ISSUE THREAD

**Issue by Cyril-hcj** [apolloconfig/apollo#3900]
![image](https://user-images.githubusercontent.com/31679398/129657130-c9360df8-c08a-414a-8cb4-3c7341bffec2.png)
在这虽然能直接修改，但是我的备注丢失了
![image](https://user-images.githubusercontent.com/31679398/129657187-17288e3d-0e78-4c3c-aa04-a4c2cfd3c5e1.png)

**Comment by nobodyiam** [comment]
see #1681

**Comment by nobodyiam** [comment]
#3947 provides the UI to export/import configs and is now merged.
