### ISSUE TITLE
使用helm部署，log没有异常，但ready总是处于0/1的状态

### ISSUE THREAD

**Issue by uania** [apolloconfig/apollo#3901]
使用helm部署在aks的k8s上。
![image](https://user-images.githubusercontent.com/31028677/129694226-7c1538ce-62c1-48a1-90c8-919f2c957e0c.png)
请问我还可以参考哪些信息找到原因那？

**Comment by nobodyiam** [comment]
访问下 readinessProbe 的接口看看，比如 http://localhost:8090/health
