### ISSUE TITLE
安装完成后用apollo账号登录权限不是超级管理员

### ISSUE THREAD

**Issue by Novemberinp** [apolloconfig/apollo#3904]
![image](https://user-images.githubusercontent.com/25147840/130031378-438f4f40-b4ed-4e82-ba71-8f19701fa188.png)
接口：hasPermission: false
数据库没有改动过，superadmin 有apollo这个用户

**Comment by nisiyong** [comment]
你依据什么判断不是管理员？

**Comment by Novemberinp** [comment]
![image](https://user-images.githubusercontent.com/25147840/130192248-a14f6fb7-4a3d-4f13-9a49-e9fc46f7d5be.png)
当前登录用户：apollo
