### ISSUE TITLE
请问可以保证兼容性的使用 Apollo 吗？也就是用户可以选择使用 Apollo 或者 仅使用本地文件

### ISSUE THREAD

**Issue by LeBW** [apolloconfig/apollo#3906]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

我们想要在项目新版本中引入 Apollo，但同时也想照顾不想引入 Apollo 的用户，让他们可以继续使用本地文件作为配置。请问有没有比较好的方式来实现这种兼容性呢？

**Comment by nisiyong** [comment]
可以考虑不用Apollo Client API获取配置，直接使用Spring的`@Value`注解，这样基本上是对Apollo弱依赖。

另外如果只是为了本地开发方便，可以看下[本地开发模式](https://www.apolloconfig.com/#/zh/usage/dotnet-sdk-user-guide?id=%e4%ba%94%e3%80%81%e6%9c%ac%e5%9c%b0%e5%bc%80%e5%8f%91%e6%a8%a1%e5%bc%8f)

**Comment by Anilople** [comment]
如果是spring boot的项目，这是可以实现的，可以添加apollo-client的依赖，通过配置来决定是否开启

参考 [3.2.1.3 Spring Boot集成方式（推荐）](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89)

通过调整
```properties
# will inject 'application' namespace in bootstrap phase
apollo.bootstrap.enabled = true
```
为`true`来打开

如果要关闭，可以注释掉
```properties
# apollo.bootstrap.enabled = true
```

**Comment by LeBW** [comment]
> 可以考虑不用Apollo Client API获取配置，直接使用Spring的`@Value`注解，这样基本上是对Apollo弱依赖。
> 
> 
> 
> 另外如果只是为了本地开发方便，可以看下[本地开发模式](https://www.apolloconfig.com/#/zh/usage/dotnet-sdk-user-guide?id=%e4%ba%94%e3%80%81%e6%9c%ac%e5%9c%b0%e5%bc%80%e5%8f%91%e6%a8%a1%e5%bc%8f)

感谢您的回答，我会进一步尝试和了解

**Comment by LeBW** [comment]
> 如果是spring boot的项目，这是可以实现的，可以添加apollo-client的依赖，通过配置来决定是否开启
> 
> 
> 
> 参考 [3.2.1.3 Spring Boot集成方式（推荐）](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89)
> 
> 
> 
> 通过调整
> 
> ```properties
> 
> # will inject 'application' namespace in bootstrap phase
> 
> apollo.bootstrap.enabled = true
> 
> ```
> 
> 为`true`来打开
> 
> 
> 
> 如果要关闭，可以注释掉
> 
> ```properties
> 
> # apollo.bootstrap.enabled = true
> 
> ```
> 
> 
> 
> 这样可以通过本地配置的方式，来决定应用是否使用Apollo

非常感谢您的建议，我所在的项目由几个服务组成，其中有Spring服务，也有非Spring的Java服务。请问对于非Spring的Java服务，有没有相关建议呢？

**Comment by nobodyiam** [comment]
非Spring的Java服务可以自己封装一下，比如通过某个配置决定是读取apollo还是本地文件

**Comment by LeBW** [comment]
> 非Spring的Java服务可以自己封装一下，比如通过某个配置决定是读取apollo还是本地文件

好的，谢谢您的建议！
