### ISSUE TITLE
[Announment] Welcome new committer: Zhuohao Li

### ISSUE THREAD

**Issue by JaredTan95** [apolloconfig/apollo#3923]
Hi Community,

On behalf of the Apollo PMC, I am pleased to announce that [Zhuohao Li](https://github.com/Accelerater), has been voted in as a new Apollo committer.

Please join me to say congratulations to him!

@Accelerater , would you please briefly introduce yourself to the community?

BTW, after you accepted this invitation, you can submit your GithubId and name info in https://www.apolloconfig.com/#/en/community/team through Pull Request.

Best Regards,
Jared Tan

**Comment by klboke** [comment]
Welcome

**Comment by JaredTan95** [comment]
https://github.com/apolloconfig/apollo/pull/3924
