### ISSUE TITLE
普通应用继承公共namespace出现提示这个提示该如何处理呢

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#3926]
普通应用继承公共namespace出现提示，如下：
   当前公共namespace的所有者 ABC 没有关联此namespace,请联系ABC 的所有者在ABC项目里关联此namespace；

portal页面中出现这个提示后，用户需要怎么操作来解决这个提示呢

**Comment by nobodyiam** [comment]
> 请联系ABC 的所有者在ABC项目里关联此namespace

应该是 ABC 的项目中把这个 namespace 该删了，需要让 Owner 加回来
