### ISSUE TITLE
命名空间配置下拉滚动条修改需求评审

### ISSUE THREAD

**Issue by cookiejoo** [apolloconfig/apollo#3928]
**你的特性请求和某个问题有关吗？请描述**
我们在使用apollo配置时，因配置过多，在翻找配置时浏览器没有出现下拉框滚动条，只能通过鼠标滚动轴去不停的上下滚动。
没有滚动条的情况下也不知道目前的位置在哪里，想选择其他的命名空间配置时又要不停的滚动鼠标。
这样极其不方便。

**清晰简洁地描述一下你希望的解决方案**
希望有显示滚动条，并且固定每个命名空间配置的高度，这样极大的方便了选择命名空间配置和当前空间配置的位置。

**清晰简洁地描述一下这个特性的备选方案**
无

**本人解决方案**
我修改了common-style.css 一点样式达到了该效果，是否准许我提个PR？
效果如下
![2](https://user-images.githubusercontent.com/3397316/131278612-35f3ab6d-f38a-4e9f-989a-60d2a0255cff.png)
![1](https://user-images.githubusercontent.com/3397316/131278628-f248db00-7b4b-4b19-94be-c2e06b02a21c.png)

**Comment by cookiejoo** [comment]
主要是::-webkit-scrollbar这个样式阻止了滚动条的产生，在namespace-panel-master-tab.html中223行加了最大搞定限制为600px，这样就达到了效果，使用起来非常方便。

**Comment by nobodyiam** [comment]
看下和 #3925 是否解决的是同一问题？

**Comment by cookiejoo** [comment]
> 看下和 #3925 是否解决的是同一问题？

我看了这位兄弟的提交的代码，应该只是把滚动条显示出来没有更多变更了，因为对方没有详细的意图和截图我无法得知。
我这边是对配置框做了高度限制，在发布很多配置的时候也有这个问题，我也做了高度限制。
我的变更在内部已经发布了，用户反馈体验不错。

不知你这边怎么看这个issue，请评估能否接受这个需求，一切由你们官方决定为准。

如：改图就是多配置发布的时候没有高度的话得滚动很远，也不美观。
![image](https://user-images.githubusercontent.com/3397316/131355781-27e9e5b6-4a8d-46cb-be73-1f3f398e145e.png)

**Comment by nobodyiam** [comment]
社区始终是欢迎大家贡献的，可以提交 PR 大家一起看下~

**Comment by cookiejoo** [comment]
> 社区始终是欢迎大家贡献的，可以提交 PR 大家一起看下~

好的，我一会提交PR。
