### ISSUE TITLE
docker部署时 admin 报错找不到服务

### ISSUE THREAD

**Issue by zzq361267211** [apolloconfig/apollo#3932]
### Discussed in https://github.com/apolloconfig/apollo/discussions/3931

<div type='discussions-op-text'>

<sup>Originally posted by **zzq361267211** August 30, 2021</sup>
docker部署时 admin 报错找不到服务
异常信息：  There was a problem with the instance info replicator
![image](https://user-images.githubusercontent.com/66397159/131323018-4950a818-d908-472b-9cdc-489123b7c386.png)

Eureka 服务信息截图：
![image](https://user-images.githubusercontent.com/66397159/131322800-d223fdc2-8f37-415d-93ac-59cdb6942b6a.png)

eureka的Instance Info写的172.17.0.3 这个地址不知道是什么，本机地址应该是192.168.x.x这种才对

我已经修改过mysql里面的配置，但仍然没有效果
![image](https://user-images.githubusercontent.com/66397159/131322929-680615f7-1c5a-44b3-85eb-faba04de0d19.png)
</div>

**Comment by nobodyiam** [comment]
目测是 eureka.service.url 填写不对，看截图应该是要填 http://172.17.0.3:8080/eureka 吧

**Comment by zzq361267211** [comment]
改成  http://172.17.0.3:8080/eureka，这个地址以后也是一样的问题，而且访问不到信息
![image](https://user-images.githubusercontent.com/66397159/131425589-8a019d79-4a98-4af1-ac00-acada6b19055.png)
这个路径下倒是能返回结果
![image](https://user-images.githubusercontent.com/66397159/131425652-868c17d3-faf4-4629-b0da-78e491a19ca2.png)
感觉问题在于 eureka注册了个 172.17.0.3:8080 这种莫名其妙的ip端口，而真正正确的是192.168.xx.xx 的本机地址，

**Comment by nobodyiam** [comment]
172.17.0.3 是 docker 网络，192.168.xx.xx 是你的本机网络，docker 启动的时候可以配置把容器端口映射到本地端口，不过本质上底下还是两个网络体系，可以先学习一下 docker 相关知识~

**Comment by zzq361267211** [comment]
但是我刚刚重启了mysql数据库以后，不知道为什么就正常了 
eureka的UI：
![image](https://user-images.githubusercontent.com/66397159/131431290-2362f12a-4f6b-491d-b81c-45af27dc6ae9.png)

，eureka.service.url 设置的192.168.xx.xx
