### ISSUE TITLE
如何查看 Apollo 服务端的版本信息

### ISSUE THREAD

**Issue by kong62** [apolloconfig/apollo#3935]
生产环境有一套 Apollo，但是时间久了，维护人员都不在了，现在想确认下线上的版本信息，但是在 portal 上找了半天也没找到，请问如何查看

**Comment by nobodyiam** [comment]
1. 较新的版本可以查看右上角 管理员工具 - 系统信息
2. 较老的版本可以访问 http://{portal-url}:{port}/apollo/version
