### ISSUE TITLE
使用openapi进行版本的一些操作

### ISSUE THREAD

**Issue by PoorTraveler** [apolloconfig/apollo#3938]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述疑问**

1.请问如何通过openapi获取目前已经发布的所有的配置的releaseid？
2.如何通过releaseid切换版本，并且获取对应id的配置信息？

我没有在openapi文档中查看到相关接口。

**期望**

期望获取相关帮助或者解决问题的链接，谢谢

**Comment by nobodyiam** [comment]
目前 openapi 没有提供这些接口，如有需要可以参照 portal 的 ReleaseController 在 openapi 中增加下相关接口

**Comment by PoorTraveler** [comment]
好的，openapi目前不支持，请问有其他的途径去获取这些信息吗，比如sql操作，或者优雅一点的方式？身边没有Java开发，主要是c开发。谢谢

**Comment by nobodyiam** [comment]
portal 是有这些接口的，可以登录后调用相关接口
