### ISSUE TITLE
是否支持java -D的方式加载namespace

### ISSUE THREAD

**Issue by seqwait** [apolloconfig/apollo#3939]
一个webserver 分布在不通的3台机器上面,我在做CI的时候 需要根据机器性能的不通发布不通的参数,比如
A机器配置高:需要调整webserver内某些参数配置
B机器配置低:需要另外一个低配置的namespace
我想问下apollo 是否支持这样的策略.

**Comment by klboke** [comment]
支持，可以使用如下方式设置 namespace
```java
-Dapollo.bootstrap.namespaces=ecs1
```

**Comment by seqwait** [comment]
thk
