### ISSUE TITLE
Implement password policies to avoid weak passwords

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#3948]
**Is your feature request related to a problem? Please describe.**
The default spring security auth method does not have control set in password complexity. It is possible to add a user with a weak password.

**Describe the solution you'd like**
To add a secure password policy so that admin users must set complex passwords for users.

**Comment by WillardHu** [comment]
Hi @nobodyiam, is this feature completed? I'll add password validation to the user manage form and the backend api server. Verification specification: The password must contain uppercase and lowercase characters and digits, and the length is greater then or equals 8 characters.

**Comment by nobodyiam** [comment]
@WillardHu This feature is not yet assigned, it'll be great if you could work on this! Shall I assign this issue to you?

**Comment by WillardHu** [comment]
> @WillardHu This feature is not yet assigned, it'll be great if you could work on this! Shall I assign this issue to you?

Ok, thanks. @nobodyiam

**Comment by nobodyiam** [comment]
@WillardHu This issue is now assigned to you, thanks!
