### ISSUE TITLE
helm repo add apollo http://ctripcorp.github.io/apollo/charts 404

### ISSUE THREAD

**Issue by shaly** [apolloconfig/apollo#3954]
PS C:\Users\admin> helm repo add apollo http://ctripcorp.github.io/apollo/charts
helm : Error: looks like "http://ctripcorp.github.io/apollo/charts" is not a valid chart repository or cannot be rea
ched: failed to fetch http://ctripcorp.github.io/apollo/charts/index.yaml : 404 Not Found
所在位置 行:1 字符: 1
+ helm repo add apollo http://ctripcorp.github.io/apollo/charts
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: looks li...: 404 Not Found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by kezhenxu94** [comment]
@shaly please do not submit duplicate issue... https://github.com/apolloconfig/apollo/discussions/3953#discussioncomment-1285915
