### ISSUE TITLE
helm install apollo-portal -f apollo-portal-values.yaml -n ns-apollo-portal apollo/apollo-portal  unable to build kubernetes objects from release manifest: error validating "":

### ISSUE THREAD

**Issue by shaly** [apolloconfig/apollo#3958]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

PS C:\Users\admin> helm search repo apollo
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                                       
apollo/apollo-portal 	0.3.0        	1.9.0      	A Helm chart for Apollo Portal                    
apollo/apollo-service	0.3.0        	1.9.0      	A Helm chart for Apollo Config Service and Apol...

PS C:\Users\admin> helm install apollo-portal -f apollo-portal-values.yaml -n ns-apollo-portal apollo/apollo-portal
helm : Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersi
on not set
所在位置 行:1 字符: 1
+ helm install apollo-portal -f apollo-portal-values.yaml -n ns-apollo- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: INSTALLA...Version not set:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

**期望**

能正常安装portal

**截图**
configservice和adminservice安装没问题，但是portalservice安装有误
![image](https://user-images.githubusercontent.com/20148706/132316614-675ee152-9c15-4484-8262-d3f04b7021fa.png)
![image](https://user-images.githubusercontent.com/20148706/132316666-759eb1c7-cb87-4bde-bb71-30fb6c22bfd2.png)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Thanks for reporting, it's a known issue #3933
