### ISSUE TITLE
[Proprosoal] Split helm chart into another repo

### ISSUE THREAD

**Issue by JaredTan95** [apolloconfig/apollo#3959]
**Describe the solution you'd like**
After discussed with @nobodyiam PMC member, we decided to split helm chart into another github repo, maybe like `apollo-helm-chart` or others.

Note:
Helm charts in the `apolloconfig/apollo` repo will remain in place for a period of time, and maintenance such as bug fixes and feature additions will be updated in the `apollo-helm-chart` repo.

**Comment by nobodyiam** [comment]
shall we also move the [apollo-on-kubernetes](https://github.com/apolloconfig/apollo/tree/master/scripts/apollo-on-kubernetes) to the separate repo?

**Comment by JaredTan95** [comment]
I found out that If we want slipt `helm-chart` or `apollo-on-kubernetes`, we should release or provide docker image for helm/kubernetes deployment to pull image. 

So, we need to rearrange the dockerfiles.

**Comment by JaredTan95** [comment]
> I found out that If we want slipt `helm-chart` or `apollo-on-kubernetes`, we should release or provide docker image for helm/kubernetes deployment to pull image.

ingore this, 
because I found it in
https://github.com/apolloconfig/apollo/pull/3956/files#diff-58d193a961f6388b58a34096f2a1d5fa3cf8ebf3690ff4f57fccda88779aea14R83

**Comment by JaredTan95** [comment]
Hi, 

We have moved the helm chart into another repo. https://github.com/apolloconfig/apollo-helm-chart

**Comment by JaredTan95** [comment]
> shall we also move the [apollo-on-kubernetes](https://github.com/apolloconfig/apollo/tree/master/scripts/apollo-on-kubernetes) to the separate repo?

Seems other open source projects put native deployment yamls with code, unlike helm chart. For me, I'd like to hold apollo-on-kubernetes in apollo main repo. we can take a look at other committers' suggestions？
