### ISSUE TITLE
如何配置一个带有 ${} 的字符串

### ISSUE THREAD

**Issue by JiZhihan** [apolloconfig/apollo#3961]
**问题**
如何配置一个带有 ${}  的字符串

**现象**
![image](https://user-images.githubusercontent.com/56993966/132440488-782c1757-451d-4dc4-9d1e-22e1be173c84.png)
![image](https://user-images.githubusercontent.com/56993966/132440548-d140fdcb-605e-4b96-a767-6e3f1ec2a947.png)
![image](https://user-images.githubusercontent.com/56993966/132440627-ca054cd0-65af-4540-9572-55b0e57ebc96.png)

**期望**
期望输出   ${abc}  字符串

**Comment by nobodyiam** [comment]
This looks like a spring framework issue?

**Comment by JiZhihan** [comment]
> This looks like a spring framework issue?

但是我直接写在项目里面的yaml就可以得到期望，写在Apollo配置就不行

**Comment by nobodyiam** [comment]
Would you please describe how to reproduce this issue in detail? Or you may submit a sample project to show this issue.

**Comment by JiZhihan** [comment]
> Would you please describe how to reproduce this issue in detail? Or you may submit a sample project to show this issue.

问题很简单啊，我不应该没描述清楚吧
第一步:在apollo的UI上加了一个value的为  **${abc}**  的key
第二步:在程序里面连上apollo获取配置时报错
Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'abc' in value "${abc}"

期望是能正确读取到一个字符串  **${abc}**

**Comment by vgbhfive** [comment]
这是 spring framework 的问题，${abc} 会被解析去配置文件中寻找 abc 的占位符，因为没有找到所以会报错。

**Comment by nobodyiam** [comment]
这个是 spring 的工作机制，可以查阅一下 spring 是否有相关的配置，apollo 只负责给 spring 提供 property source，不会对 placeholder 做解析的。
我在 spring 文件配置，也是报一样的错误。
```java
  @Value("${test}")
  private String test;
```

```yaml
test: "${abc}"
```

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'abc' in value "${abc}"

**Comment by JiZhihan** [comment]
> 这个是 spring 的工作机制，可以查阅一下 spring 是否有相关的配置，apollo 只负责给 spring 提供 property source，不会对 placeholder 做解析的。
> 我在 spring 文件配置，也是报一样的错误。
> 
> ```java
>   @Value("${test}")
>   private String test;
> ```
> 
> ```yaml
> test: "${abc}"
> ```
> 
> Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'abc' in value "${abc}"

但是spring的yaml配置使用单引号可以读取到  test: '{$abc}'

**Comment by Anilople** [comment]
参考 https://stackoverflow.com/questions/13162346/escape-property-reference-in-spring-property-file

想运行时读到`$`
有2种解决方法

1种是配置里写
```
dollar=$
```
然后代码里写
```java
@Value("${dollar}{abc}")
private String a;
```

---

另一种是，直接代码里写
```java
@Value("#{'$'}{abc}")
private String a;
```

**Comment by JiZhihan** [comment]
> 参考 https://stackoverflow.com/questions/13162346/escape-property-reference-in-spring-property-file
> 
> 想运行时读到`$`
> 有2种解决方法
> 
> 1种是配置里写
> 
> ```
> dollar=$
> ```
> 
> 然后代码里写
> 
> ```java
> @Value("${dollar}{abc}")
> private String a;
> ```
> 
> 另一种是，直接代码里写
> 
> ```java
> @Value("#{'$'}{abc}")
> private String a;
> ```

首先感谢回答！但好像不能应用到我的场景，我的场景是某一个Key配置的value里面包含了若干个 
 ```java
 {$abc} 
``` 
按照你这种方式，我好像需要把key拆成很多部分再去拼接

**Comment by nobodyiam** [comment]
@JiZhihan 话说我在 apollo 测试了下，貌似是可以的？是否和 Spring 的版本有关？我本地跑的是 Spring Boot 2.4.2

```java
  @Value("${testplaceholder}")
  private String test;
```

![image](https://user-images.githubusercontent.com/837658/134755279-45819f28-15ad-4121-93a2-b37e536f782e.png)

![image](https://user-images.githubusercontent.com/837658/134755312-d1a9c6bd-c504-4cce-96e2-1152d3bf9185.png)

**Comment by JiZhihan** [comment]
@nobodyiam
和springboot版本应该没关系
尴尬，我上个评论把 ${abc} 写成了 {$abc}

**Comment by nobodyiam** [comment]
😓，难怪了，我测试了 ${abc} 不管是本地文件配置还是 apollo 配置都是不行的，那应该就要参考 @Anilople 的回复了
