### ISSUE TITLE
希望增加按“项目组”分配权限的功能

### ISSUE THREAD

**Issue by xujiansheng** [apolloconfig/apollo#3964]
目前系统是按单个项目赋予权限，很可能部门负责人都没有所有项目的管理员权限。希望增加按“项目组”分配权限的功能，负责人把不同项目分到对应组中，不同的业务组各自使用自己的项目组，新员工入职直接加到项目组中，默认拥有项目组中项目权限。

**Comment by nobodyiam** [comment]
duplicated with #2178
