### ISSUE TITLE
跨k8s健康检查有误，fat和uat环境adminservice与configservice检查Check Health报错，生产没问题

### ISSUE THREAD

**Issue by shaly** [apolloconfig/apollo#3965]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：
![image](https://user-images.githubusercontent.com/20148706/132457532-b0008687-0c60-4fd4-ae68-8ec9c3738e32.png)

1. K8S部署apollo，service服务fat与uat在一个k8s中，service pro和portal在另一个k8s中.每个服务都启动成功了，进入portal管理界面，健康检查中只有pro环境(上图蓝框)的service的Check Health是健康的，fat与uat环境（上图红框）的service进行Check Health报错,比如下图uat:“Code:500 Msg:I/O error on GET request for "http://apollo-service-apollo-configservice.ns-apollo-service-uat:8080/health": apollo-service-apollo-configservice.ns-apollo-service-uat: Name does not resolve; nested exception is java.net.UnknownHostException: apollo-service-apollo-configservice.ns-apollo-service-uat: Name does not resolve”
![image](https://user-images.githubusercontent.com/20148706/132458178-4269d3ef-6dd2-45ab-9caf-8a15ea6f4ce1.png)

2. 初步分析是因为生产与fat&uat环境不在一台服务器，k8s无法调通其它服务器的namespace地址，如果是的话该如何解决？

**期望**

希望fat与uat均可以Check Health通过

**截图**
apollo-service fat、uat、pro的values.yaml如下图
![image](https://user-images.githubusercontent.com/20148706/132458511-f552c877-b53f-4134-b863-e50fa59e7595.png)
apollo-portal的values.yaml如下图
![image](https://user-images.githubusercontent.com/20148706/132458964-12e5c65d-f498-48ac-a9b5-5c5459651e24.png)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by shaly** [comment]
发布环境修改adminservice及configservice为对应ip及端口

**Comment by GridxFuJun** [comment]
@shaly 请问一下老哥你是怎么解决这个问题的？
