### ISSUE TITLE
public ReleaseDTO createGrayRelease model.setClusterName(branchName);

### ISSUE THREAD

**Issue by guangxuewu** [apolloconfig/apollo#3973]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

public ReleaseDTO createGrayRelease model.setClusterName(branchName);
是否应该是 
`model.setClusterName(clusterName);`

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
灰度发布的分支是 branch name 应该没问题
