### ISSUE TITLE
BootstrapApplicationListener无法合并Apollo的PropertySource问题

### ISSUE THREAD

**Issue by wujinqing** [apolloconfig/apollo#3981]
1.我的配置文件名称bootstrap.properties。
2.我的spring-cloud-context-2.1.1.RELEASE。（spring-cloud-context-2.0.8之后的某个版本才出现的这个问题）

org.springframework.cloud.bootstrap.BootstrapApplicationListener部分合并逻辑源代码

只会合并OriginTrackedMapPropertySource类型的PropertySource。
`
private void mergeAdditionalPropertySources(MutablePropertySources environment,
			MutablePropertySources bootstrap) {
		PropertySource<?> defaultProperties = environment.get(DEFAULT_PROPERTIES);
		ExtendedDefaultPropertySource result = defaultProperties instanceof ExtendedDefaultPropertySource
				? (ExtendedDefaultPropertySource) defaultProperties
				: new ExtendedDefaultPropertySource(DEFAULT_PROPERTIES,
						defaultProperties);
		for (PropertySource<?> source : bootstrap) {
			if (!environment.contains(source.getName())) {
                                // 关键看add逻辑，下面有add方法的源码
				result.add(source);
			}
		}
		for (String name : result.getPropertySourceNames()) {
			bootstrap.remove(name);
		}
		addOrReplace(environment, result);
		addOrReplace(bootstrap, result);
	}

// 只会添加OriginTrackedMapPropertySource类型的PropertySource
public void add(PropertySource<?> source) {
			// Only add map property sources added by boot, see gh-476
			if (source instanceof OriginTrackedMapPropertySource
					&& !this.names.contains(source.getName())) {
				this.sources.addPropertySource(source);
				this.names.add(source.getName());
			}
		}
`
但是Apollo的PropertySource并不是OriginTrackedMapPropertySource导致无法合并。

com.ctrip.framework.apollo.spring.config.ConfigPropertySource

**Comment by wujinqing** [comment]
apollo client 版本是1.7.0

**Comment by nobodyiam** [comment]
能描述下实际的影响是啥吗？

**Comment by wujinqing** [comment]
我的项目需要在spring cloud里面要使用Apollo配置，我需要在BootstrapApplicationListener加载bootstrap.properties配置，
由于bootstrap里面的ApolloBootstrapPropertySources无法复制到我自己项目的Environment中（spring-cloud-context-2.0.8版本是可以复制的），导致我不得不一样的配置复制一份命名为application.properties, 这样我自己的项目才会重新加载一遍ApolloBootstrapPropertySources到我自己的环境。

现在我的项目里面就会出现两个内容一样的配置
bootstrap.properties
application.properties

虽然配置很简单，但是对于追求完美的程序员来说 非常难以接受。

`
app.id=xxxxAppId
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces=application,xxxx.public
apollo.bootstrap.eagerLoad.enabled = true
`

**Comment by nobodyiam** [comment]
看上去这个是 spring cloud 的特殊逻辑导致的问题，可以去原始的 issue 看看为啥做了这个改动？https://github.com/spring-cloud/spring-cloud-commons/issues/476

**Comment by wujinqing** [comment]
thanks!
