### ISSUE TITLE
可以在灰度分支新增配置项时，支持批量操作吗

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#3984]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦

**清晰简洁地描述一下你希望的解决方案**

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
灰度的设计理念是对少量的配置进行试验，而且一般是基于已有的配置修改，所以批量新增意义可能不是太大
