### ISSUE TITLE
生产环境配置一直状态异常，测试环境正常

### ISSUE THREAD

**Issue by Greax** [apolloconfig/apollo#3993]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

测试环境和生产环境都是用docker 部署的，拉取的是最新的版本，部署方式都是一样，但是在Portal页面，测试环境正常，生产环境一直异常，请问是什么原因

**截图**

<img width="1420" alt="Snipaste_2021-09-18_17-15-47" src="https://user-images.githubusercontent.com/3661671/133883978-37046631-7a8c-4d11-ac32-23258b545584.png">

![image](https://user-images.githubusercontent.com/3661671/133884053-6f1e066a-032e-4e3c-9998-b1c8eaa4c39c.png)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by lepdou** [comment]
你在 portal 机器上，telnet 172.17.8.3 8090 试一下。大概率是网络的原因
