### ISSUE TITLE
The WebHook feature doesn't include the changed configurations

### ISSUE THREAD

**Issue by nisiyong** [apolloconfig/apollo#3995]
Recently I wanna [enable the webhook notification](https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-webhook-notification) to do something on an external application. 

But this feature can't meet me cause it doesn't include the changes configurations when releasing namespace. Currently, this feature ONLY contains all the newest items in the `configuration` field.

What about adding the changed data in this webhook data likes the [Email notification](https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-email-service?id=_32-emailtemplatereleasemodulediff)? In my opinion,  the difference between the two releases is more meaningful.

```
{
    "appId": "",  // appId
    "clusterName": "",  // 集群
    "namespaceName": "", // namespace
    "operator": "",  // 发布人
    "releaseId": 2,  // releaseId
    "releaseTitle": "",  // releaseTitle 
    "releaseComment": "",  // releaseComment
    "releaseTime": "",  // 发布时间  eg：2020-01-01T00:00:00.000+0800
    "configuration": [ { // 发布后的全部配置，如果为灰度发布，则为灰度发布后的全部配置
        "firstEntity": "",  // 配置的key
        "secondEntity": ""  // 配置的value
    } ],
    "isReleaseAbandoned": false,
    "previousReleaseId": 1,  // 上一次正式发布的releaseId
    "operation":  // 0-正常发布 1-配置回滚 2-灰度发布 4-全量发布
    "operationContext": {  // 操作设置的属性配置
        "isEmergencyPublish": true/false,  // 是否紧急发布
        "rules": [ {  // 灰度规则
            "clientAppId": "",   // appId
            "clientIpList": [ "10.0.0.2", "10.0.0.3" ]  // IP列表
        } ],
        "branchReleaseKeys": [ "", "" ]  // 灰度发布的key
    }
}
```

**Comment by nobodyiam** [comment]
What's the actual use case? There is a previousReleaseId in the webhook request body, which could be used to retrieve the previous configuration.

**Comment by nisiyong** [comment]
Webhook is good for users to do something customize, like notification bot, etc.

Even the email feature, I think if the webhook data support shows the diff between the two releases, users could integrate their message system with RESTful.

**Comment by nobodyiam** [comment]
Your point makes sense to me. The wehook, email feature are all async notifications triggered when the configuration is released. Actually they are implemented in the same program block so I think it's reasonable to add difference between the two releases.

https://github.com/apolloconfig/apollo/blob/2fb347993586c41b925edca37c4c91e3dd054ff0/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/listener/ConfigPublishListener.java#L104-L108

**Comment by nisiyong** [comment]
Yes, that's what I mean. They can reuse the `releaseHistory` object with the changes.
