### ISSUE TITLE
建议部署文档直接给出可以用的示例

### ISSUE THREAD

**Issue by panol** [apolloconfig/apollo#4000]
建议部署文档直接给出可以用的示例,把配置的复杂度降到1,而不是每次都点开一个又一个的超链接,然后再发现超链接后面还有超链接,有些超链接还不能用.
https://www.apolloconfig.com/#/zh/deployment/quick-start

**Comment by nobodyiam** [comment]
感谢建议，是否能具体展开一下？

> 有些超链接还不能用

这个有具体案例吗？也可以协助修复下哈~
