### ISSUE TITLE
私有namespace，授权和删除都报错

### ISSUE THREAD

**Issue by Yonikon** [apolloconfig/apollo#4005]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

私有namespace，授权和删除都报错（报错添加失败405），导致无法处理此配置。
**复现**

通过如下步骤可以复现：

1. 新建一个私有namespace，search.yaml（发现希望使用yml后缀）
2. 删除search.yaml。创建search.yml
3. 生产环境授权给一个用户编辑权限，报错添加失败405
4. 想删除search.yml重新建一个search.yml也报错，无法删除

**期望**

能否让search.yml能编辑并授权？

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
到 [apollo demo 站点](http://106.54.227.205/)重现一下该问题吧，建议把每一步的截图贴一下~
