### ISSUE TITLE
删除namespace之后,客户端感知不到namespace的变化,导致的配置残留

### ISSUE THREAD

**Issue by diwenzheng** [apolloconfig/apollo#4006]
@nobodyiam

**Comment by diwenzheng** [comment]
能否禁用掉file

**Comment by diwenzheng** [comment]
这时候我该如何通知客户端重新读取apollo数据,而不走缓存map了.

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/135240338-7503ac0b-ae13-4593-b4d9-fcf1cabf7324.png)
![image](https://user-images.githubusercontent.com/60613511/135240384-af0e14ca-14d8-44ca-a08e-dba5c76d09b6.png)
实际上apollo已经没有了,这难道只能reset了？

**Comment by nobodyiam** [comment]
删除接口我记得会发出 release message，config service 收到通知后会告诉客户端重新获取配置的

**Comment by diwenzheng** [comment]
这种是删除应用 
![image](https://user-images.githubusercontent.com/60613511/135372745-56caa979-83f2-46f8-8ca3-f080f21cad12.png)
而且ConfigService 你们设计的的安全性太好了- - 无法反射调自行删除cache

**Comment by diwenzheng** [comment]
我们在删除配置后会等待15S左右,这看起来这并不会发起release message,当然你可以告诉我 自行在客户端如何触发这个函数。

**Comment by diwenzheng** [comment]
@nobodyiam

**Comment by diwenzheng** [comment]
我们这里的配置比较特殊需要删除这块的namespace,所以发现缓存的问题,这种在客户端测有办法使用什么方式删除掉cache吗。我觉得 是不是应该对外给开发者去管理缓存 这样 会不会更灵活。

**Comment by nobodyiam** [comment]
看了下代码并做了下测试，删除 app 时会发出 release message 的，所以 config service 的 cache 是会被清空的，不过 apollo-client 在收到通知像 config service 发起请求该 namespace 会拿到 404 的响应，所以在本地不会更新内存中的配置。
这个行为是符合预期的，所以建议确保没有客户端在读取该应用的配置再删除 app。
如果你确实有这个场景需要，可以考虑通过 ApolloInjectorCustomizer( #3602 )，定制一下 RemoteConfigRepository 的逻辑。

https://github.com/apolloconfig/apollo/blob/348bee52dd8440e5aeb304f52e88935ecdd2ad69/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/NamespaceService.java#L340-L342

**Comment by diwenzheng** [comment]
尝试自定义成功删除掉configmanager里的cache 但是 
![image](https://user-images.githubusercontent.com/60613511/136741007-78ab733d-1b00-49aa-8306-b77e71ce7795.png)
又获取到了 我已经删除的数据 是为什么？

**Comment by nobodyiam** [comment]
通过 ApolloInjectorCustomizer 可以自定义 ConfigFactory 的逻辑，从而在创建 DefaultConfig 时可以注入自定义的 config repository。
不过你提到的 cache 这块确实没有特别考虑过统一管理，所以自定义逻辑会稍显凌乱一些。
