### ISSUE TITLE
安装了Apollo，可以正常运行但是后面想添加多个环境，就在数据库里添加fat,uat,pro三个环境，但是启动之后发现还是只有一个dev环境，因为什么问题？

### ISSUE THREAD

**Issue by lmz-json** [apolloconfig/apollo#4010]
![png](https://user-images.githubusercontent.com/91598843/135426926-7117a6da-db01-4fd2-83d1-9ea2fbbbfe80.png)
![未命名1632993935](https://user-images.githubusercontent.com/91598843/135427707-ac807760-98d2-473e-88c8-d63d2791d090.png)
![未命名1632994035](https://user-images.githubusercontent.com/91598843/135427025-6c1214ee-a8d8-4219-b60e-3b90b91dae8d.png)
![未命名1632994156](https://user-images.githubusercontent.com/91598843/135427037-ad996c14-9127-41bc-84be-1332f9ca7aa3.png)

**Comment by Anilople** [comment]
参考 [3.1.2 apollo.portal.meta.servers - 各环境Meta Service列表](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_312-apolloportalmetaservers-%e5%90%84%e7%8e%af%e5%a2%83meta-service%e5%88%97%e8%a1%a8)

你需要把 FAT,UAT,PRO 对应的apollo.meta地址填上

将 `apollo.portal.meta.servers`
![image](https://user-images.githubusercontent.com/15523186/135717248-1f691721-1d17-4469-bcf4-63231468e664.png)
改成
```json
{
    "DEV":"http://1.1.1.1:8080",
    "FAT":"http://apollo.fat.xxx.com",
    "UAT":"http://apollo.uat.xxx.com",
    "PRO":"http://apollo.xxx.com"
}
```
