### ISSUE TITLE
csrf开启之后，报403

### ISSUE THREAD

**Issue by javacheng7** [apolloconfig/apollo#4019]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
csrf 开启的话，前端应该要配合传递 csrf token 的，可以查阅下相关文档，同时也欢迎提交 PR~

**Comment by nobodyiam** [comment]
@javacheng7 是否能提供下相关改动细节，csrf 功能也是 apollo 需要的一个 feature 哈，如果能提交 pull request 那就更好了~
