### ISSUE TITLE
Open Api 是否能支持灰度配置的新增

### ISSUE THREAD

**Issue by yangyangyang121** [apolloconfig/apollo#4021]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦

**清晰简洁地描述一下你希望的解决方案**

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
open api 应该是可以的，clusterName 传灰度的 branch name
