### ISSUE TITLE
apollo-client依赖的guice版本提升到5.0.1

### ISSUE THREAD

**Issue by LittleChengxuYuan** [apolloconfig/apollo#4031]
**你的特性请求和某个问题有关吗？请描述**
在使用 9 及以上 jdk 版本启动依赖项包含有 apollo-client 的项目时，会出现以下警告信息：
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/xxx/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**清晰简洁地描述这个问题是什么。**
此警告是由guice引起的非法访问警告，在 guice 5.0.1版本已被解决，详见 https://github.com/google/guice/issues/1133

**清晰简洁地描述一下你希望的解决方案**
将apollo-clent依赖的guice版本提升至 5.0.1

**Comment by nobodyiam** [comment]
Previously we did not upgrade the guice version because we need to support java 7. Since now we decided to drop java 7 support(#3896), I think we can upgrade guice now. Would you please help to submit a pr to fix this?

**Comment by Anilople** [comment]
Done in pr #4060 

see 
https://github.com/apolloconfig/apollo/pull/4060/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R176
