### ISSUE TITLE
能否增加配置内容业务规则校验

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4034]
目前apollo只能做一些简单的语法格式校验，但很多时候，数据本身是带有一定的格式要求的，特别是一些复杂的json、xml配置等等。目前只是对json、xml本身进行了校验，但是没有对内容进行校验。如果内容不符合要求，只有运行时才能发现，无法确定配置是否生效了（可能内容有问题，直接被抛弃了）。如果不及时回滚，甚至会发生服务无法重启之类的问题。

请教下，这种想对内容进行校验，有什么好的方式或者思路吗

**Comment by hezhaoye** [comment]
那只通过openAPI调用的话，那portal端界面修改后，就绕过了检验了，这个感觉也不太可行。

**Comment by Anilople** [comment]
Duplicate of #1517
