### ISSUE TITLE
如何取消“已修改”并且“未发布”的条目

### ISSUE THREAD

**Issue by hirosiwang** [apolloconfig/apollo#4036]
在某个 namespace 下修改了很多条目，没有发布，但因为某些原因不想发布了，如何取消这些修改（除了改回原始文案）？

**Comment by Anilople** [comment]
revoke （撤销配置）

![image](https://user-images.githubusercontent.com/15523186/137315534-c64c0c63-c1a2-4d12-800f-a1500d249a25.png)

![image](https://user-images.githubusercontent.com/15523186/137315630-0ca374bc-ba41-40e4-90b4-d6b88ae2b939.png)


---

**Comment by hirosiwang** [comment]
![image](https://user-images.githubusercontent.com/19341031/137315977-9cc3c849-ad16-4b7b-a10d-f2930b8fb9af.png)
多谢，另外问下这个是从哪个版本开始支持的，我用的版本目前没有这个功能
因为数量太多，如果我想通过改数据解决，应该如何操作，只删commit表数据可以吗，有没有缓存等问题？或者别的方案？
