### ISSUE TITLE
feature: add a shortcut to scroll to the top in the dashboard

### ISSUE THREAD

**Issue by NICEXAI** [apolloconfig/apollo#4037]
We have many projects in our cluster, and after changing the configuration of the last few projects, we have to manually scroll to the top if we want to continue changing the configuration of other clusters, which is a very troublesome process.

like this:
![image](https://user-images.githubusercontent.com/19580983/137427440-5320a758-9616-4c39-b2a1-ad634a1dd8c6.png)

I would like to ask your opinion.

**Comment by DiegoKrupitza** [comment]
It would be great to only show the "scroll to top" button when you scrolled a bit down, so it does not hide any information. For example if we just loaded the side it would be a bit useless to make the button visible since we are already at the top of the page.

But the idea is really great! 👍
