### ISSUE TITLE
删除多个灰度配置，页面展示错误

### ISSUE THREAD

**Issue by Liwenju** [apolloconfig/apollo#4039]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

删除多个灰度配置项并灰度发布，页面会存留一个刚删除的配置项

**复现**

通过如下步骤可以复现：

1. 新建多个灰度配置项并灰度发布
![image](https://user-images.githubusercontent.com/14797520/137441185-c1fbeb6a-b55e-46b3-8c00-bbf0c1c79005.png)

2. 删除灰度配置项
![image](https://user-images.githubusercontent.com/14797520/137441330-1c6ac5ab-2fd2-4d3c-ad0e-656a77c8960b.png)

3. 灰度发布
![image](https://user-images.githubusercontent.com/14797520/137441386-59646686-4354-4805-a999-f9ed37df20b8.png)

**期望**

灰度发布点击后，界面不应该仍存在一个待发布的删除项；
这是个当前页面数据刷新的问题，重新载入下当前集群，待发布的删除项就会消失
apollo demo 站点 即可复现

**截图**
重新载入
![image](https://user-images.githubusercontent.com/14797520/137442038-06352331-b238-4050-bee9-7ca8b698cb81.png)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Thanks for your report, this seems an issue on the UI side.
