### ISSUE TITLE
客户端应用rest修改阿波罗配置，报302错误

### ISSUE THREAD

**Issue by Level1Accelerator** [apolloconfig/apollo#4057]
rest读取正常，一更新就GG。不知道具体原因是为啥

错误信息：
Caused by: com.ctrip.framework.apollo.openapi.client.exception.ApolloOpenApiException: Request to apollo open api failed, status code: 302, reason: Moved Temporarily,

代码：
   OpenItemDTO openItemDTO=new OpenItemDTO();
        openItemDTO.setKey("key");
        openItemDTO.setValue("111");
        openItemDTO.setDataChangeLastModifiedBy("name");
        apolloClient.updateItem("appid",
                "dev",
                "default",
                "application",
                openItemDTO);

**Comment by yuhangbin** [comment]
I have the same problem. I find the reason which my portalUrl is wrong. The code only check the start of portalUrl.
`      Preconditions.checkArgument(portalUrl.startsWith("http://") || portalUrl.startsWith("https://"), "Portal url should start with http:// or https://" );
`
Check your portalUrl.

**Comment by yuhangbin** [comment]
My case http 302 meaning moves to /signin page.  
Just like: 
`http://172.18.229.61:9212/,http://172.18.229.60:9212/`
