### ISSUE TITLE
apollo-configservice不能注册到自己的内嵌eureka地址上，显示OUT_OF_SERVICE

### ISSUE THREAD

**Issue by hwisecn** [apolloconfig/apollo#4058]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
apollo-configservice不能注册到自己的内嵌eureka地址上，显示OUT_OF_SERVICE

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

正常注册

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 

> 版本：v1.9.1

- 错误日志
- 配置：
- 平台和操作系统

**Comment by programming-pupil** [comment]
解决了吗？我也是这问题，一天啦！

**Comment by caizhijian13** [comment]
> 

你好，请问你找到问题所在了吗？
