### ISSUE TITLE
通过ingress 域名访问apollo portal 地址被错误重定向

### ISSUE THREAD

**Issue by lemanlai** [apolloconfig/apollo#4063]
1. 环境： eks( k8s 1.16)
2. apollo verision: 1.9.1
3. 部署方式helm
4. ingress gateway:  kong 2.0.5
5. 故障：
ingress 域名： xxxx1  -- > svc apollo configservice :  ok
ingress 域名： xxxx2  --> svc apollo portal : 失败。
6. 问题：
访问：  xxxx2/signin  : ok
访问：  xxxx2 :  被重定向为xxxx2:8000/singin :  打不开。 问题定位：与kong无关。
使用 kubectl port-forward svc/xxxx   8070: 8070  ok.

7. curl header:  respond localtion 返回错误地址：
```
curl -i https://xxxxxxx
HTTP/2 302
date: Tue, 26 Oct 2021 03:42:41 GMT
content-length: 0
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: SAMEORIGIN
set-cookie: SESSION=N2MyOWUzZWUtYTA5Mi00ODE5LTg5NDAtOTU5ZTViN2FmZGQ2; Path=/; HttpOnly; SameSite=Lax
location: http://xxxxxx:8000/signin
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: __cf_bm=i1tnyuwaal39vw8IAWBkxccn3TvylZpvVQKWcvdlGB0-1635219761-0-AZZLj7MWZTwW16Wa3XQ49BY0T6h6XcrZThikM4H7ttqwbjOWclZLg44AL888ef4FLsiA9xJjz5UB1Ui2afjwE4U=; path=/; expires=Tue, 26-Oct-21 04:12:41 GMT; domain=.3ona.co; HttpOnly; Secure; SameSite=None
server: yyyyy
cf-ray: 6a40ad13adae3d0c-HKG
```

**Comment by jamesdeng57** [comment]
@nobodyiam 我和 @lemanlai 是同事，一起看这个问题

从 http response header 可以看到 location: http://xxxxxx:8000/signin ，这是一个绝对路径，源代码看到是设置 了 use-relative-redirects: true
``` yaml
server:
  tomcat:
    use-relative-redirects: true
```

这个可以改成 false ?

**Comment by nobodyiam** [comment]
@jamesdeng57 

This change was brought by #1967, it looks like this pr was meant to fix some similar issues as this one. But you may try to change the config to false to see if it solves the issue and we could do some analysis to see how to correctly set this config.

**Comment by jamesdeng57** [comment]
我尝试设置为 false，并没有用，我们需要得到一个相对路径，我在 spring issues 中找到一个类似的问题
https://github.com/spring-projects/spring-boot/issues/27801

我尝试修改源码，我有看到 dockerfile，但是在文档中并没有找到怎么 bulid image ，你可以相关的指导吗？

**Comment by nobodyiam** [comment]
@jamesdeng57 you may refer [this document](https://www.apolloconfig.com/#/zh/development/apollo-release-guide?id=_47-%e5%8f%91%e5%b8%83-docker-%e9%95%9c%e5%83%8f) for how to build docker image.
