### ISSUE TITLE
如何运行时设置long polling的timeout

### ISSUE THREAD

**Issue by reignsr** [apolloconfig/apollo#4077]
@nobodyiam  请问apollo-1.4.0，如何在运行时（configservice启动时）设置long polling的timeout？
看代码DeferredResultWrapper类中，private static final long TIMEOUT = 60 * 1000;//60 seconds，是个常量，除了改写此处代码，能否从外部设置该值？如环境变量或-D参数。

另外确认一下，我们通过调用链监控和命令行测量long polling的执行时长，发现有时会多出60秒一点返回（偶尔达到61秒以上），请问这属于正常现象吗？之所以想要调整long polling timeout也是源于此。

**Comment by nobodyiam** [comment]
the long polling timeout could be customized from apollo 1.5.0 via pr #2532
