### ISSUE TITLE
change ctripcorp to apolloconfig in .yaml files

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4078]
**Is your feature request related to a problem? Please describe.**
The git repository has been move from ctripcorp to apolloconfig, but stil some content need to change.

For example, we need also change ctripcorp to apolloconfig in follow .yaml files

https://github.com/apolloconfig/apollo/blob/729e1fd4598a470f985dedf9e53eb57907f88762/docs/charts/index.yaml

https://github.com/apolloconfig/apollo/blob/729e1fd4598a470f985dedf9e53eb57907f88762/scripts/helm/apollo-portal/Chart.yaml

https://github.com/apolloconfig/apollo/blob/729e1fd4598a470f985dedf9e53eb57907f88762/scripts/helm/apollo-service/Chart.yaml

**Additional context**

A good first issue to let people join community.

**Comment by Anilople** [comment]
File https://github.com/apolloconfig/apollo/blob/master/.github/workflows/cla.yml#L37 also need change too.

Just change `ctripcorp/` to `apolloconfig/` simply.

**Comment by Fool-coder** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Anilople** [comment]
> File https://github.com/apolloconfig/apollo/blob/master/.github/workflows/cla.yml#L37 also need change too.
> 
> Just change `ctripcorp/` to `apolloconfig/` simply.

Done in #4150

Thanks @Fool-coder
