### ISSUE TITLE
客户端可以监听某个namespace的实例个数的变化

### ISSUE THREAD

**Issue by jxctx88** [apolloconfig/apollo#4080]
**你的特性请求和某个问题有关吗？请描述**

通过监听namespace的的实例个数来做一些个性化的需求，
比如：配置一个总的限流值，监听这个实例的个数来平均设置每个节点的限流阀值

**清晰简洁地描述一下你希望的解决方案**
client可以提供接口监听到某个namespace的实例信息的变化

**Comment by nobodyiam** [comment]
That doesn't sound a normal requirement for config center but a common feature of service registry :-)
