### ISSUE TITLE
接入oidc没有跳转到https而是跳转到了http

### ISSUE THREAD

**Issue by lixiangzzz2017** [apolloconfig/apollo#4081]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

登录的时候跳转没有带上https而是http，例如
https://login.partner.microsoftonline.cn/{tenant}/oauth2/v2.0/authorize?response_type=code&client_id={client_id}&scope=openid&state=qAVu-cULMtHpc9aZCZGE-tvQs_6uuxMop_84wK8SUHA%3D&redirect_uri=http://xxx.com/login/oauth2/code/azure&nonce=6sFinXXWxR2WxOPDnI8pPpBI7J0UDOQnf6tk-yxVj-g

**复现**

通过如下步骤可以复现：

1. application-oidc.yml
spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.partner.microsoftonline.cn/${tenant}/v2.0
        registration:
          azure:
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            client-id: ${client_id}
            provider: azure
            scope:
              - openid
            client-secret: ${client_secret}
2.nginx代理到后端
https:xxx.com -> apollo-portal(ip:port)

nginx配置如下
location / {
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_cache off;
            proxy_pass_header server;
            proxy_set_header host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header x-real-ip $remote_addr;
            proxy_set_header x-scheme $scheme;
            proxy_set_header X-Forwarded-Proto "https";
            proxy_pass http://internal.infra.apollo-portal_test;
        }

参考https://github.com/apolloconfig/apollo/discussions/3794之后 也不行

**期望**

https://login.partner.microsoftonline.cn/{tenant}/oauth2/v2.0/authorize?response_type=code&client_id={client_id}&scope=openid&state=qAVu-cULMtHpc9aZCZGE-tvQs_6uuxMop_84wK8SUHA%3D&redirect_uri=https://xxx.com/login/oauth2/code/azure&nonce=6sFinXXWxR2WxOPDnI8pPpBI7J0UDOQnf6tk-yxVj-g

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.9.1
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
@vdisk-group do you have any experience in oidc with https?

**Comment by vdisk-group** [comment]
please try adding `server.forward-headers-strategy = framework` to the application-oidc.yml
```yml
server:
  forward-headers-strategy: framework

```

**Comment by lixiangzzz2017** [comment]
加上了之后是可以了。但是显示的用户名不太友好
![image](https://user-images.githubusercontent.com/30712303/140674925-a260c4a6-3885-48fa-a22e-01246ef8fa3b.png)
数据库里面是这个
![image](https://user-images.githubusercontent.com/30712303/140674977-066ef8e7-c1fe-4cf2-a30d-1cd7930989ea.png)

**Comment by lixiangzzz2017** [comment]
azure返回的信息应该是这个 我看里面并没有包含8l0xxx的
![image](https://user-images.githubusercontent.com/30712303/140677673-4de7dd99-a9dd-43ff-9d72-2d11388cfb65.png)

**Comment by lixiangzzz2017** [comment]
我看了下https://github.com/apolloconfig/apollo/issues/3625 我觉得Users这张表应该再加一列oidc_id用来从oidc vendor确定唯一的用户，Username使用name 这样即使用户改了邮箱和用户名也不会收到影响

**Comment by lixiangzzz2017** [comment]
研究了下数据库 发现里面跟权限相关都是用的Users.Username 只能把权限相关的变成用户id..这样的话 其实是不支持修改用户的Username的

**Comment by nobodyiam** [comment]
> please try adding `server.forward-headers-strategy = framework` to the application-oidc.yml
> 
> ```yaml
> server:
>   forward-headers-strategy: framework
> ```

@vdisk-group Shall we add this config to [application-oidc-sample.yml](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/config/application-oidc-sample.yml)?
