### ISSUE TITLE
ClassLoaderUtil 异常捕获的问题

### ISSUE THREAD

**Issue by swabber-kun** [apolloconfig/apollo#4086]
**描述bug**

![image](https://user-images.githubusercontent.com/4974393/141129936-dbcebeb3-4756-4313-86a4-0b565731bd1d.png)

我们系统在接入CAT的时候，出现了NoClassDefFoundError的报错，ClassLoaderUtil的try-catch没有明确捕获到，导致服务启动失败

![image](https://user-images.githubusercontent.com/4974393/141130181-1a4e1f6a-c260-49bc-907c-5490c0dbc797.png)

**Comment by nobodyiam** [comment]
It looks like the `com.dianping.cat.Cat` class is present while the `ComponentLookupException` class it imports doesn't exist.
I think the ClassLoaderUtil needs to fix this by also catching `LinkageError` and `ExceptionInInitializerError`.
To make your case work, you need to fix the `ComponentLookupException` not found issue.
