### ISSUE TITLE
疑问:configservice kill掉之后，在eureka注册中心仍然存在，如何解决呢？

### ISSUE THREAD

**Issue by hza2022** [apolloconfig/apollo#4092]
新手问题：configservice kill掉之后，在eureka注册中心仍然存在，如何解决呢？

**Comment by hza2022** [comment]
查了下资料，可以调用api进行下线：
// 客户端可以通过如下代码主动通知注册中心下线
DiscoveryManager.getInstance().shutdownComponent();

或者配置eureka参数，等待一定时间后检测到无心跳后自动下线。
各位大佬，有更好的方案吗？

**Comment by hza2022** [comment]
实测以下代码无效，kill掉任务之后注册中心中仍存在：
Runtime.getRuntime().addShutdownHook(new Thread(() -> DiscoveryManager.getInstance().shutdownComponent()));

**Comment by nobodyiam** [comment]
如果是 kill 应该不会执行 shutdown hook 的，这种情况只能等待心跳检测了

**Comment by vdisk-group** [comment]
尝试使用 kill -15 来停止 configservice，kill -9 会导致 shutdownHook 无法执行
