### ISSUE TITLE
对于容器化的服务，灰度发布应该怎么使用

### ISSUE THREAD

**Issue by lixiangzzz2017** [apolloconfig/apollo#4093]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
对于桥接模式的容器应该怎么使用?现在桥接模式的服务注册到apollo里面的ip为172.17开头，可能两台主机注册到apollo里面都是172.17.0.3，这样的话，灰度就没法进行。。

![image](https://user-images.githubusercontent.com/30712303/141303429-5cf308cf-43fd-4253-aaa5-3077086e2e40.png)

**复现**

通过如下步骤可以复现：

1. 服务容器化

**期望**

我觉得应该使用主机名来标识 主机名能够保证不重复

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.9.2
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
The master branch support grayscale by [label](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_1247-apollolabel).

**Comment by lixiangzzz2017** [comment]
从这个文档来看，我的理解是相当于在启动服务的时候就将服务分组打上标签，然后portal那边根据标签来灰度是吧 这个release会在什么时候发布呢？
