### ISSUE TITLE
Macbook pro m1(2020) 芯片启动 apollo-quick-start 模式特别慢

### ISSUE THREAD

**Issue by lantu-group** [apolloconfig/apollo#4099]
**你的特性请求和某个问题有关吗？请描述**

我的电脑是 macbook pro m1 chip(2020), 新启动一个 apollo-quick-start 超级慢， 用 `docker stats ` 命令 看下，只能占用一个 cpu 的性能，不能你们是否有在 macbook pro m1 chip(2020) 下测试过。
我另有一个 macbook intel i7 chip(2017) ，启动就正常.

**清晰简洁地描述一下你希望的解决方案**
正常启动

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
It looks more like a docker issue?
