### ISSUE TITLE
在内网中，如何保证Eureka页面访问的安全性？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4100]
目前发现大家知道了meta域名后，都能够通过手动构造URL来访问eureka页面，可以对实例进行启动或者停止，存在一定的风险性，这个目前可以有什么方式增强安全性吗

**Comment by nobodyiam** [comment]
There was a discussion(#3807) on whether we need to support Eureka authentication or not.

**Comment by hezhaoye** [comment]
这个可以通过Spring security来限制吗

**Comment by nobodyiam** [comment]
I think we could give it a try?
