### ISSUE TITLE
apollo 1.8.1版本支持暴露metrics给prometheus吗

### ISSUE THREAD

**Issue by ingla9988** [apolloconfig/apollo#4105]
当前apollo使用的是1.8.1版本，但是没发现有接口暴露metrics指标，请问是否有这个功能？ 谢谢

**Comment by nobodyiam** [comment]
see #2507, it is available since 1.5.0

**Comment by ingla9988** [comment]
好的，谢谢
另外再咨询下，是否有对应的grafana模板可供参考？
