### ISSUE TITLE
namespace权限管理

### ISSUE THREAD

**Issue by lostmaniac** [apolloconfig/apollo#4106]
想回收研发查看数据库账号密码，这个只能DBA同学查看配置，研发同学不能查看，不能配置，实现这样的功能

**Comment by lostmaniac** [comment]
同一个项目，通过新增namespace，
数据库账号密码通过私密namespace配置。
其他配置使用项目内谁都可以看的namespace配置

**Comment by nobodyiam** [comment]
The config [configView.memberOnly.envs](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90) should work for this scenario.

**Comment by lostmaniac** [comment]
非常感谢，我尝试一下

**Comment by lostmaniac** [comment]
已有项目成员就可以查看
可能不能够满足
更希望的是开发工程师来配置项目的一个namespace
DBA配置数据库连接的namespace
DBA配置的namespace只允许DBA查看和编辑

**Comment by nobodyiam** [comment]
I believe the config `configView.memberOnly.envs` should work based on your description. You may have a try and get back to this issue if it does not work.

**Comment by WilliamShoww** [comment]
> 已有项目成员就可以查看 可能不能够满足 更希望的是开发工程师来配置项目的一个namespace DBA配置数据库连接的namespace DBA配置的namespace只允许DBA查看和编辑
用作者的这个配置开启，新建一个项目全部是公共空间配置，项目直接使用就可以了。
