### ISSUE TITLE
Does Apollo. Label support multiple labels configured for a project

### ISSUE THREAD

**Issue by vision-qiu** [apolloconfig/apollo#4120]
I checked the source code (version 2.0.0), the label I saw was only input in the form of string, there was no special processing of label, but my colleague said that it supports multiple labels.

**Comment by nobodyiam** [comment]
I believe `apollo.label` now is treated as a single label, however, it would be interesting to discuss whether it should support multiple labels, i.e. separated by commas.

**Comment by vision-qiu** [comment]
Thank you. I got it.
