### ISSUE TITLE
SQL Error: 1062, SQLState: 23000

### ISSUE THREAD

**Issue by billy98** [apolloconfig/apollo#4122]
通过helm3安装apollo，
K8s版本v1.19.15
apollo版本1.9.1
我因为系统迁移，然后把Apollo也一起迁移了，但是迁移后报唯一索引错误，也就是有重复的数据写进数据库
![image](https://user-images.githubusercontent.com/13307862/143975351-8c68cd93-c646-4059-a657-d71a239d23f3.png)

**Comment by nobodyiam** [comment]
The related code is as follows:

https://github.com/apolloconfig/apollo/blob/75f9950d5e1675dbb0617555c4502685ef4d4618/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java#L145-L165
