### ISSUE TITLE
show-text-modal 特殊json值显示错误

### ISSUE THREAD

**Issue by Liwenju** [apolloconfig/apollo#4131]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

配置值为json类型，其值包含大于或等于16位数字时，会在原值后加入该数字

**复现**

通过如下步骤可以复现：
配置：
json：
{
    "id": 4,
    "partnerShopLabelList": "MDBQ201911040002000001",
    "partnerOrderUnitChangeCount": 10000
}
![image](https://user-images.githubusercontent.com/14797520/144836799-1b615268-14d1-4753-a4f5-ac5ab35c74cd.png)

现象：
![image](https://user-images.githubusercontent.com/14797520/144836921-3d6a0be4-10b1-488a-aa30-83e694182a2a.png)

**期望**
不追加后缀

_**此问题应为 https://github.com/apolloconfig/apollo/pull/3851 _引入**_
![image](https://user-images.githubusercontent.com/14797520/144837786-69f42a1a-9959-4bc5-ab71-b4b03cacf43e.png)

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Thanks for the report.
@CalebZYC Would you please help to take a look at this issue?

**Comment by nobodyiam** [comment]
@Liwenju #4183 is merged to master branch, would you please help to verify this change?

**Comment by Liwenju** [comment]
> @Liwenju #4183 is merged to master branch, would you please help to verify this change?

ok，text modal with json display correctly, thx
