### ISSUE TITLE
支持关闭Apollo配置功能

### ISSUE THREAD

**Issue by wangwenyao** [apolloconfig/apollo#4135]
**支持通过参数配置关闭Apollo配置功能**

由于Apollo的功能丰富特性和优秀，我们的配置中心选择了使用Apollo，但在某些交付场景下，配置中心是不同的，因此需要做区分来打包，并进行不同配置调整，或者使用Local机制，但仍然是强依赖。

**希望支持通过参数配置开启关闭Apollo配置功能**

**Comment by nobodyiam** [comment]
Duplicate of #3045

**Comment by roneywei** [comment]
这个apollo.bootstrap.enabled = false并不会生效，还是会去连接apollo
