### ISSUE TITLE
建立spring_session_attributes表遇到1071 - Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by sxcooler** [apolloconfig/apollo#4140]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我从1.7.1升级到1.9.1的过程中，创建表SPRING_SESSION_ATTRIBUTES 的时候遇到了1071 - Specified key was too long; max key length is 767 bytes，经检查是该表主键过长，sql如下（从你们git库里复制的）：
```
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
```
因为我MySQL的字符集是utf8mb4，这个时候id+name = 236个字，236 * 4 = 944 超过了767，我将attribute_name改为150字勉强解决，希望官方能给出标准的解决办法。
utf8mb4应该已经是目前主流了，特别是emoji大行其道的情况下，希望apollo能够考虑。

**复现**

通过如下步骤可以复现：

1. 在MySQL 5.7 数据库设置CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
2. 建立上述spring_session_attributes表

**期望**

希望避免该问题

**截图**

![image](https://user-images.githubusercontent.com/3192045/145305315-43f23cde-bbc4-453d-99f3-f728c601918b.png)

### 额外的细节和日志

- 版本：1.9.1
- 错误日志
- 配置：
- 平台和操作系统：阿里云ack，k8s 1.8.1，MySQL 5.7

**Comment by nobodyiam** [comment]
Thanks for reporting this issue. Looks like we need to limit the index key length as we did for other tables like `App`.
@vdisk-group would you please help to take a look?
BTW, the default charset of apollo database is utf8mb4, and strangely I didn't meet the issue you described in my local environment.

![image](https://user-images.githubusercontent.com/837658/145316622-f66bda7d-d55e-4729-aef6-8806ee7e81e2.png)

**Comment by vdisk-group** [comment]
please check

**Comment by vdisk-group** [comment]
please check the mysql system variables and make sure `innodb_large_prefix` is `ON` and `innodb_file_format` is `BARRACUDA`
```sql
show variables like 'innodb_large_prefix';
show variables like 'innodb_file_format';

```

if not, please execute the following SQL using root 
```sql
set global innodb_large_prefix=ON;
set global innodb_file_format=BARRACUDA;

```

**Comment by sxcooler** [comment]
> please check the mysql system variables and make sure `innodb_large_prefix` is `ON` and `innodb_file_format` is `BARRACUDA`
> 
> ```sql
> show variables like 'innodb_large_prefix';
> show variables like 'innodb_file_format';
> ```
> 
> if not, please execute the following SQL using root
> 
> ```sql
> set global innodb_large_prefix=ON;
> set global innodb_file_format=BARRACUDA;
> ```

Thanks for that, closing.
