### ISSUE TITLE
springboot获取配置失败

### ISSUE THREAD

**Issue by xianhuadezhuren** [apolloconfig/apollo#4146]
k8s部署apollo1.8 ，部署了dev test release pro四个环境
![image](https://user-images.githubusercontent.com/52482325/145524092-43b2e299-834e-44c3-af58-c2845b736ec3.png)
这个是我配置引用apollo的配置
![image](https://user-images.githubusercontent.com/52482325/145524411-79455cbb-e242-45ac-9ebe-3f25d5c472b3.png)

我已经将这个域名换成config-server-dev的ip:8080，也是报错
![image](https://user-images.githubusercontent.com/52482325/145524338-6e21e14a-2e21-41b5-960a-db30552e1315.png)
这个ip获取的好像有问题

还请老师指导下

**Comment by nobodyiam** [comment]
It looks like the meta service address is wrong. You may run `curl` to see what it returns.
