### ISSUE TITLE
apollo 没有用到 log4j2 (log4j2 is not used in apollo)

### ISSUE THREAD

**Issue by blue110** [apolloconfig/apollo#4147]
请问log4j2漏洞的修复，会安排发紧急的版本吗，怎么安排

**Comment by zouyx** [comment]
正在讨论如何解决，请稍等一下

**Comment by JaredTan95** [comment]
建议添加 JVM 参数解决：log4j2.formatMsgNoLookups=true
社区需要等待 log4j2 正式发布再升级。

**Comment by nobodyiam** [comment]
@blue110 

log4j2 is only used in the apollo-demo project which won't have any impact.
apollo-configservice, apollo-adminservice and apollo-portal use logback for the logging purpose.

**Comment by LittleJZ** [comment]
所以此次log4j2的漏洞对apoll没有影响嘛

**Comment by nobodyiam** [comment]
@LittleJZ right, there is no impact on apollo.

**Comment by byronjxb** [comment]
请教下，通过docker方案部署的apollo， JVM 参数解决：log4j2.formatMsgNoLookups=true 需要在什么位置添加？

**Comment by nobodyiam** [comment]
@byronjxb 

log4j2 is not used in apollo.
apollo 没有用到 log4j2。
