### ISSUE TITLE
如何通过 client 监听一个 app  namespace 的不同 cluster 配置

### ISSUE THREAD

**Issue by xingcici** [apolloconfig/apollo#4148]
举个例子，我们分库分表配置存储在一个 app id 下面，一个逻辑库一个 namespace。
由于存在多机房，我们配置了多个 cluster。
现在有个数据双向同步服务，需要做一个逻辑库 default 与其他 cluster 之间 db 的双向同步，这也就要求在一个同步进程中获取监听一个逻辑库的多集群配置（源和目标），而目前客户端因为 cluster 参数是初始化的时候直接设置的，无法获取监听多集群配置。
同时我们需要在配置变化的时候获得通知，而open api 无法实现监听功能，不太符合我们的需求。
请问目前客户端有办法实现吗，或者在使用上能通过某种方式来实现我们的需求吗。

**Comment by nobodyiam** [comment]
you may consider creating multiple apollo clients based on the [http API](https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide).

**Comment by xingcici** [comment]
客户端 Config 对象加了 cluster 参数和修改服务端 拉取 订阅 接口实现了
