### ISSUE TITLE
demo环境gson解析错误，能否修复下，无法创建项目

### ISSUE THREAD

**Issue by yeexy** [apolloconfig/apollo#4151]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

demo环境创建项目获取部门接口报错，导致无法创建项目进行测试

**复现**

通过如下步骤可以复现：

1. 进入demo环境，点击创建项目即可

**期望**

创建项目流程正常

**截图**

![image](https://user-images.githubusercontent.com/51102488/145920560-0fe6dbc3-e27c-46b7-96ed-5c750e6eff3c.png)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Thanks for reporting this issue, it seems someone made a mistake when changing `organizations` config which makes it an invalid json string. It should be alright now.

**Comment by yeexy** [comment]
是的，已经恢复了，感谢你们的及时修复，祝Apollo越来越好!
