### ISSUE TITLE
一个应用可以添加到多次到一个集群中，导致删除集群出错

### ISSUE THREAD

**Issue by WilliamShoww** [apolloconfig/apollo#4155]
**Version**
server：1.9.1，client: 1.9.0

**Describe the bug**
在Apollo管理后台，可以将一个应用添加多次到同一个集群，导致应用归属同个集群多次，从而导致删除集群出错。希望添加的时候校验一下吧，或者删除放开吧。

**Comment by WilliamShoww** [comment]
![image](https://user-images.githubusercontent.com/19343209/146298076-5703cbde-df5b-40a9-beaf-2937f4a66d9d.png)

> **Version** server：1.9.1，client: 1.9.0
> 
> **Describe the bug** 在Apollo管理后台，可以将一个应用添加多次到同一个集群，导致应用归属同个集群多次，从而导致删除集群出错。希望添加的时候校验一下吧，或者删除放开吧。

![image](https://user-images.githubusercontent.com/19343209/146298076-5703cbde-df5b-40a9-beaf-2937f4a66d9d.png)

**Comment by nobodyiam** [comment]
Please check your system info page, it looks like several environments share the same config services/databases.

![image](https://user-images.githubusercontent.com/837658/146627142-65c21d3c-7954-4f7c-9920-db2d091917ae.png)

**Comment by WilliamShoww** [comment]
> config services/databas

是的，是同一个数据库，难道必须多个环境用多个数据库吗？

**Comment by Anilople** [comment]
> > config services/databas
> 
> 是的，是同一个数据库，难道必须多个环境用多个数据库吗？

In #4160

> 创建自定义环境test1,test2

Of course, test1 has own configdb, test2 has own configdb too.

**Comment by WilliamShoww** [comment]
> 

也就是说一个环境得一个数据库，不然public namespace的配置也会共享，以及出现秘钥和集群问题？

**Comment by WilliamShoww** [comment]
> > 
> 
> 也就是说一个环境得一个数据库，不然public namespace的配置也会共享，以及出现秘钥和集群问题？

因为我发现我的public namespace的配置不仅独立于应用之外，还是独立于环境之外

**Comment by WilliamShoww** [comment]
![image](https://user-images.githubusercontent.com/19343209/146633359-823b77fc-3ad4-4886-a357-598fe642d8e8.png)

**Comment by nisiyong** [comment]
@WilliamShoww The secrets only work for private namespaces, not public namespaces.
