### ISSUE TITLE
item.value.length.limit 配置有时不会动态生效

### ISSUE THREAD

**Issue by CandleFlower** [apolloconfig/apollo#4157]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 改变serverconfig表的item.value.length.limit为40000
2. adminservice日志中提示已经刷新新值，此时新增value>40000的值，后台日志仍然提示value too long,limit:20000
3. 这种境况只是偶尔出现，重启adminservice可以生效

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
It takes up to 1 min to be effective.

![image](https://user-images.githubusercontent.com/837658/146627211-a4698ad6-962f-4758-bc56-52d3ad1026b3.png)

**Comment by CandleFlower** [comment]
等待了超过30分钟时间，仍然不生效，检查admin日志，已经打印了配置更新的信息，但下发配置仍然提示value too long,limit:20000

**Comment by nobodyiam** [comment]
According to the refresh logic below, the property source should be updated after the log is printed, which I can't see what could go wrong...

https://github.com/apolloconfig/apollo/blob/586cc3b632875e5cc097d7bbfdb5ef0ba9aa53a1/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/BizDBPropertySource.java#L94-L101
