### ISSUE TITLE
初次使用，一些心得

### ISSUE THREAD

**Issue by WilliamShoww** [apolloconfig/apollo#4158]
**你的特性请求和某个问题有关吗？请描述**
1. 关联配置，覆盖过配置后，没法复原使用公共空间的配置；出现的场景是：关联了另外的项目的公共空间配置，覆盖过该配置，清空覆盖的配置，没法引用公共默认的配置。
2. 删除已使用过的配置空间，想要立马删除配置，必须手动去数据删除InstanceConfig表对应的记录，才能做到。希望管理界面能做到。
3. 系统参数，希望能像表格一样列出来，让用户自己选择更改配置，目前的交互每次都要看文档，变更非常不便利。
4. 应用集群和命名空间，也希望是表格搜索显示的方式，变更信息方便快捷。
5. 创建私有Namespace的交互界面希望优化一下，应该先有操作，再界面响应。
6. 仔细一看，表结构同一含义的字段长度限制能统一一下吗? 命名空间名字有些varchar(500) 有些varchar(32)。

**Comment by nobodyiam** [comment]
> 1. 关联配置，覆盖过配置后，没法复原使用公共空间的配置；出现的场景是：关联了另外的项目的公共空间配置，覆盖过该配置，清空覆盖的配置，没法引用公共默认的配置。

Would you please help to describe this issue with more information? e.g. provide a detailed steps to reproduce this issue in the [demo site](http://106.54.227.205/)

> 2. 删除已使用过的配置空间，想要立马删除配置，必须手动去数据删除InstanceConfig表对应的记录，才能做到。希望管理界面能做到。

Do you mean to delete the whole namespace?

> 3. 系统参数，希望能像表格一样列出来，让用户自己选择更改配置，目前的交互每次都要看文档，变更非常不便利。

This is a good suggestion.

> 4. 应用集群和命名空间，也希望是表格搜索显示的方式，变更信息方便快捷。

public namespaces could now be searched via #3850

> 5. 创建私有Namespace的交互界面希望优化一下，应该先有操作，再界面响应。

Would you please help to describe this issue with more information?

> 6. 仔细一看，表结构同一含义的字段长度限制能统一一下吗? 命名空间名字有些varchar(500) 有些varchar(32)。

The length limit is controlled in the program as 32. I agree it's better to also unify the field length in database.

**Comment by WilliamShoww** [comment]
> 
> public namespaces could now be searched via #3850
> 
> > 5. 创建私有Namespace的交互界面希望优化一下，应该先有操作，再界面响应。
> 
> Would you please help to describe this issue with more information?
> 
> > 6. 仔细一看，表结构同一含义的字段长度限制能统一一下吗? 命名空间名字有些varchar(500) 有些varchar(32)。
> 
> The length limit is controlled in the program as 32. I agree it's better to also unify the field length in database.

**Comment by WilliamShoww** [comment]
> 2\. 删除



> > 1. 关联配置，覆盖过配置后，没法复原使用公共空间的配置；出现的场景是：关联了另外的项目的公共空间配置，覆盖过该配置，清空覆盖的配置，没法引用公共默认的配置。
> 
> Would you please help to describe this issue with more information? e.g. provide a detailed steps to reproduce this issue in the [demo site](http://106.54.227.205/)
> 
> > 2. 删除已使用过的配置空间，想要立马删除配置，必须手动去数据删除InstanceConfig表对应的记录，才能做到。希望管理界面能做到。
> 
> Do you mean to delete the whole namespace?
> 
> > 3. 系统参数，希望能像表格一样列出来，让用户自己选择更改配置，目前的交互每次都要看文档，变更非常不便利。
> 
> This is a good suggestion.
> 
> > 4. 应用集群和命名空间，也希望是表格搜索显示的方式，变更信息方便快捷。
> 
> public namespaces could now be searched via #3850
> 
> > 5. 创建私有Namespace的交互界面希望优化一下，应该先有操作，再界面响应。
> 
> Would you please help to describe this issue with more information?
> 
> > 6. 仔细一看，表结构同一含义的字段长度限制能统一一下吗? 命名空间名字有些varchar(500) 有些varchar(32)。
> 
> The length limit is controlled in the program as 32. I agree it's better to also unify the field length in database.

2. 就是应用中的配置namespace
5. 就是在创建的应用namespace页面中，创建私有namespace，如下图：
![image](https://user-images.githubusercontent.com/19343209/146633164-1c22466e-9a84-4850-9634-d1f3d41fb600.png)
这里在顺带提一点，希望默认文件格式可以在系统中变更，因为目前配置的格式主流有两种，一种properties和yaml；不然就很容易初始化错一个namespace

**Comment by WilliamShoww** [comment]
关于第二点是指下图里面的功能；能够像管理后台一样列表出来管理。
![image](https://user-images.githubusercontent.com/19343209/146633396-377fef45-0bc4-434b-8d88-8a4603c232f3.png)
