### ISSUE TITLE
应用秘钥管理BUG

### ISSUE THREAD

**Issue by WilliamShoww** [apolloconfig/apollo#4160]
**描述bug**
应用秘钥管理，没法根据环境添加秘钥和启用秘钥；添加都添加秘钥，启用和禁用都同时多环境生效。

**复现**

通过如下步骤可以复现：

1. 创建自定义环境test1,test2
2. 创建应用，点击管理秘钥
3. 选择test1环境，添加秘钥，该秘钥同时在test1和test2环境出现
4. 启用某个秘钥，两个环境秘钥同时启用

- 版本：client 1.9.0，server 1.9.1

**Comment by nobodyiam** [comment]
Sounds like the same issue as #4155 that you share the same config services/databases to different environments.

**Comment by WilliamShoww** [comment]
> Sounds like the same issue as #4155 that you share the same config services/databases to different environments.

不是同一个问题，这个是应用中的秘钥管理里面；那个是应用添加集群的问题
