### ISSUE TITLE
希望发布后可以配置webhooks主动请求用户更新配置

### ISSUE THREAD

**Issue by qq2161811** [apolloconfig/apollo#4174]
希望可以有个类似webhooks的功能用来主动触发，通知用户拉取配置并更新。因为平时更新的配置不多，偶尔可能会用到，如果主动拉取会让维护更加复杂，无法推广，如果创建守护进程又担心浪费资源和守护进程挂掉等等问题。如果能有webhooks这样的功能，应该是一个不错选择，可以满足大多数人的需求。希望开发

**Comment by nobodyiam** [comment]
see [portal webhook notification](https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-webhook-notification)
