### ISSUE TITLE
Long polling failed

### ISSUE THREAD

**Issue by BryanChanCQ** [apolloconfig/apollo#4176]
按照官方文档quik start配置项目启动一直报警告
![截屏2021-12-24 19 18 11](https://user-images.githubusercontent.com/49968907/147348476-3936d0aa-29f0-4495-8636-75ebe50a9ef4.png)

**Comment by BryanChanCQ** [comment]
不影响读取数据

**Comment by nobodyiam** [comment]
Is 192.168.0.3 a gateway instead of apollo-configservice? You may first check the server logs.

**Comment by BryanChanCQ** [comment]
> Is 192.168.0.3 a gateway instead of apollo-configservice? You may first check the server logs.

在自己的电脑上按照quick start部署，中间自己没有任何中间层访问或者转发。192.168.0.3为本机IP，8080为configService端口

**Comment by BryanChanCQ** [comment]
> Is 192.168.0.3 a gateway instead of apollo-configservice? You may first check the server logs.
Eureka注册上去了
![截屏2021-12-25 12 53 57](https://user-images.githubusercontent.com/49968907/147377748-986c8b50-f00a-44c5-93d7-8b87259e06c7.png)
日志还会有这些警告

**Comment by nobodyiam** [comment]
You may access the long polling URL to see what the server responds.
