### ISSUE TITLE
[security] Allow user disable apollo-client‘s local file cache

### ISSUE THREAD

**Issue by Shoothzj** [apolloconfig/apollo#4181]
**Describe the solution you'd like**
add a `boolean localFileConfig` in apollo client, default value is true for compat.

**Additional context**
I am happy to work with this feature :)

**Comment by Shoothzj** [comment]
@nobodyiam PTAL, thanks

**Comment by Anilople** [comment]
Lose high avaibility to gain more security, i.e no one can view config through local file under folder `config-cache`.

When config service is unavaible, application cannot startup, restart.

**Comment by Shoothzj** [comment]
> 

@Anilople Yes, that's why design as a configuration. Allow uesrs to config.

**Comment by nisiyong** [comment]
By the way, I want to say that cache-config also has a function that can check whether the application is successfully connected to the server, or whether the latest configuration is loaded. It is very convenient to find the problem in some cases.

**Comment by nobodyiam** [comment]
I think it's reasonable to allow the users to decide whether to enable local cache or not. You may refer ConfigUtil. isPropertyNamesCacheEnabled for a sample config.

**Comment by Shoothzj** [comment]
@nobodyiam @Anilople Thanks, I will start work on this issue :)

**Comment by zouyx** [comment]
I think there is a good idea for more cases.
