### ISSUE TITLE
Reuse the utils class in `com.ctrip.framework.apollo.core` and `com.ctrip.framework.apollo.foundation`

### ISSUE THREAD

**Issue by Shoothzj** [apolloconfig/apollo#4197]
Hi, guys. I found that there are some classes that can be reused in `com.ctrip.framework.apollo.core` and `com.ctrip.framework.apollo.foundation`. Like `StringUtil#isBlank`.

Sorry about that I am not familiar with `apollo-core`, but I am willing and happy to contribute :)

If `com.ctrip.framework.apollo.core` and `com.ctrip.framework.apollo.foundation` has no dependency relationship. Maybe we can use `com.ctrip.framework.apollo.util`?

@Anilople @nobodyiam Please take a look, thanks for your help

**Comment by Anilople** [comment]
For the compability, we can't delete it simply.

Mark one method as `@Deprecated`, use other one instead of it?

But consider that the version is upgrade to 2.x, maybe we can delete one of them.

**Comment by Shoothzj** [comment]
> For the compability, we can't delete it simply.
> 
> 
> 
> Mark one method as `@Deprecated`, use other one instead of it?
> 
> 
> 
> But consider that the version is upgrade to 2.x, maybe we can delete one of them.
> 
> 
I suggest use com.ctrip.framework.apollo.util.
Are we need to be compat of these utils? There are kore like internal impl.

**Comment by Anilople** [comment]
> > For the compability, we can't delete it simply.
> > Mark one method as `@Deprecated`, use other one instead of it?
> > But consider that the version is upgrade to 2.x, maybe we can delete one of them.
> 
> I suggest use com.ctrip.framework.apollo.util. Are we need to be compat of these utils? There are kore like internal impl.

I think mark method as `@Deprecated` is better than delete.

```java
/**
 * @Deprecated please use {@link xxx} instead
*/
@Deprecated
public static isBlank(String s) {
  // ..
}
```

**Comment by nobodyiam** [comment]
I think we could do something like this:

```java
  /**
   * @deprecated use {@link StringUtils#isBlank(String)} instead
   */
  @Deprecated
  public static boolean isBlank(String str) {
    return StringUtils.isBlank(str);
  }
```

**Comment by Shoothzj** [comment]
@nobodyiam 
1. we should also add remove at x.x.x, when can I remove them
2. `com.ctrip.framework.apollo.core` and `com.ctrip.framework.apollo.foundation`, If this is no relationship between them, I suggest add `com.ctrip.framework.apollo.util`, WDYT? Thanks

**Comment by nobodyiam** [comment]
> we should also add remove at x.x.x, when can I remove them

We can add that, e.g. in 2 releases, but personally I think it's all right to leave it as is.

> com.ctrip.framework.apollo.core and com.ctrip.framework.apollo.foundation, If this is no relationship between them, I suggest add com.ctrip.framework.apollo.util, WDYT? Thanks

Since they are in one module, I think it's ok to have dependency on each other. It's okay to add `com.ctrip.framework.apollo.util` but that would mean we would have 2 deprecated classes, which I think it not quite necessary.

**Comment by Shoothzj** [comment]
> 

If we use `com.ctrip.framework.apollo.util`, not only this module, but `admin service` `portal service` can reuse the ability.

**Comment by nobodyiam** [comment]
I think the package name is ok, e.g. `com.ctrip.framework.apollo.core.utils.StringUtils` is already used in `com.ctrip.framework.apollo.portal.controller.UserInfoController`.

**Comment by Shoothzj** [comment]
@nobodyiam Can we noted as remove at `2.0.0`?

**Comment by nobodyiam** [comment]
@Shoothzj To be honest, I don't think it's a good idea to remove some public method, especially when it's not that necessary.
