### ISSUE TITLE
自定义端口返回80

### ISSUE THREAD

**Issue by jingslunt** [apolloconfig/apollo#4201]
$ curl -IL 127.0.0.1:3030
HTTP/1.1 302
Server: nginx
Date: Mon, 10 Jan 2022 06:17:04 GMT
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: SESSION=OGVhMjYxNjAtNTY1MC00MjQ5LWJmMjItZTRjODMzMDk5ODA2; Path=/; HttpOnly; SameSite=Lax
Location: http://127.0.0.1/signin
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404 Not Found
Server: nginx
Date: Mon, 10 Jan 2022 06:17:04 GMT
Content-Type: text/html;charset=iso-8859-1
Content-Length: 238
Connection: keep-alive
Cache-Control: must-revalidate,no-cache,no-store

**Comment by nobodyiam** [comment]
Looks like an ngnix configuration issue, you may refer the [faq](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_16-portal%e6%8c%82%e8%bd%bd%e5%88%b0nginxslb%e5%90%8e%e5%a6%82%e4%bd%95%e8%ae%be%e7%bd%ae%e7%9b%b8%e5%af%b9%e8%b7%af%e5%be%84%ef%bc%9f) for more information.

**Comment by jingslunt** [comment]
x forward port 没配置端口问题，已解决
