### ISSUE TITLE
apollo 未授权访问

### ISSUE THREAD

**Issue by fxkjnj** [apolloconfig/apollo#4204]
- [✔] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ✔] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [✔ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

在未授权的情况下，可以直接访问 apollo-adminservice/apps 下面的内容 ，我的版本是1.7.2
![image](http://jpg.fxkjnj.com/picgo/202201112024477.png)

**复现**

通过如下步骤可以复现：

1. 访问apollo-adminservice:port/apps 可已看到暴露的一些配置信息

**期望**
有没有版本可以解决这个问题，看不到apollo-adminservice/apps 下面的内容 

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题
![image](http://jpg.fxkjnj.com/picgo/202201112024477.png)

### 额外的细节和日志

- 版本：1.7.2
- 错误日志
- 配置：
- 平台和操作系统 centos7.9

**Comment by nobodyiam** [comment]
see [user guide](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_713-%e7%b3%bb%e7%bb%9f%e8%ae%bf%e9%97%ae)

**Comment by fxkjnj** [comment]
如果对应环境的apollo-adminservice开启了访问控制，那么需要在此配置apollo-portal访问该环境apollo-adminservice所需的access token

我看文档里的这个参数，在potral 哪配置？ 麻烦问下

**Comment by Anilople** [comment]
> 

![image](https://user-images.githubusercontent.com/15523186/149141489-3625d1fd-f70a-4a8b-8099-797fa4d1bc1b.png)

![image](https://user-images.githubusercontent.com/15523186/149141519-cd647144-e8fc-4bed-8ba5-9a2bd622be64.png)

3.1.12 admin-service.access.tokens

in portal's ApolloPortalDB.ServerConfig

**Comment by fxkjnj** [comment]
好的，感谢各位朋友的帮助
问题已解决
![apollo-admin](http://jpg.fxkjnj.com/picgo/202201131135242.png)
