### ISSUE TITLE
@ApolloConfigChangeListener同一个key同时触发多个动作监听不生效

### ISSUE THREAD

**Issue by lintingjie** [apolloconfig/apollo#4208]
**描述bug**

对于某个key,在同一个线程中先删除然后马上添加相同的key/value, 但是@ApolloConfigChangeListener没有收到对应的事件；
打断点debug能正常收到变更事件，使用Thread.sleep(500)也能收到事件。
概率性的，多试几次其中某次会收到事件。

**复现**

通过如下步骤可以复现：

1. 同一个key先删除再添加相同的key/value
2. @ApolloConfigChangeListener没有收到对应的事件

- 版本：1.7.0

**Comment by nobodyiam** [comment]
Do you mean to use the openapi to delete some key and add the same key/value back?
In that case, I think it's possible the client won't trigger @ApolloConfigChangeListener as apollo is designed to be a configuration management system that manages the configuration items instead of an event system.

**Comment by lintingjie** [comment]
Yes. Do you mean @ApolloConfigChangeListener can not  receive every event of item change? In this case, it can not promise to synchronize item value using @ApolloConfigChangeListener.
Any other ways to synchronize item value in local cache?

**Comment by nobodyiam** [comment]
apollo is designed to be an eventually consistent system, suppose there is an item called `timeout` with an initial value 1000.
1. timeout is changed to 2000
2. timeout is changed to 3000
3. timeout is changed back to 1000

apollo server will notify the apollo client that `timeout` is changed 3 times. apollo client will also call apollo server to fetch the value of `timeout` 3 times. However, depends on the interval between the changes, the apollo server might return different values each time - (2000, 3000, 1000), (2000, 1000, 1000), (3000,1000,1000), (1000,1000,1000), etc.
But apollo client will always get the latest value 1000 eventually. So it should be ok to use this listener to handle the local cache.

**Comment by lintingjie** [comment]
Got it, thanks!

**Comment by lintingjie** [comment]
Got it, thanks!
