### ISSUE TITLE
the official website cannot be opened

### ISSUE THREAD

**Issue by zollty** [apolloconfig/apollo#4210]
The CDN site jsDelivr is unavailable！
Since December 20, 2021 jsDelivr encountered a large-scale access error in mainland China, and its SSL certificate was replaced with a default certificate, which caused user verification errors. The reason for this is that jsDelivr’s filing license is cancelled, so access to the relevant domain name is directly blocked after the filing problem is detected.
![image](https://user-images.githubusercontent.com/5770256/150099695-394da270-c983-4304-9312-aad0b1870804.png)
see also: 
[https://zhuanlan.zhihu.com/p/447713250](https://zhuanlan.zhihu.com/p/447713250)
[jsDelivr 事故后的公共CDN故障自动切换思考](https://www.ihewro.com/archives/1211/comment-page-1)

**Comment by nobodyiam** [comment]
According to #18366, you may clean your DNS cache and try again.
Meanwhile, I think we may need to look for an alternative cdn to avoid future issue. cc @Anilople
