### ISSUE TITLE
请问json文件怎么添加注释？

### ISSUE THREAD

**Issue by helloxubo** [apolloconfig/apollo#4215]
如题，不能使用“//”、“#”吗？

**Comment by Anilople** [comment]
> 如题，不能使用“//”、“#”吗？

According https://www.json.org/json-zh.html

json doesn't support comment “//”、“#” 

i.e user cannot write content like follow
```json
// a person
{
    "name": "xiaoming"
}
```

**Comment by helloxubo** [comment]
OK, Thinks!
