### ISSUE TITLE
测试DeferredLogCache发现超过日志数量986即会报空指针异常.

### ISSUE THREAD

**Issue by johnxiaohe** [apolloconfig/apollo#4222]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
![image](https://user-images.githubusercontent.com/37014780/151651145-e09fa84a-ecc8-4984-84ea-515871687a76.png)
![image](https://user-images.githubusercontent.com/37014780/151651152-9b68447d-dcef-4315-bec6-f711a2cccb00.png)

**To Reproduce**
```java
public static void main(String[] args) {
        for (int i = 0; i < 999; i++) {
            DeferredLogCache.info(logger, "DeferredLogUtilTest");
        }
        DeferredLogCache.replayTo();
    }
```

**Expected behavior**
正常情况下超过日志阈值(1000)应有很好的丢弃策略

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by johnxiaohe** [comment]
Cache组件好像在指定数量内会发生覆盖的错误(当我指定循环次数为1000或者999时, 缓存数量都稳定在986)
当我指定循环次数为2W时, 缓存数量会到1000. 
没有查询需求的情况下这里是否可以使用队列.  数量满时自动抛弃队首的日志. 或者使用print打印出来.

**Comment by johnxiaohe** [comment]
![image](https://user-images.githubusercontent.com/37014780/151651869-832a8ac0-2b0d-46d9-bf9c-b29df43adbf0.png)
cache组件的丢弃策略应该是不适合这种GET方式

**Comment by johnxiaohe** [comment]
不过一般不会到达上限这个阈值. 但是从写单元测试角度出发这里又需要测试.

**Comment by johnxiaohe** [comment]
更新了. 发现是忽略空日志对象. 感觉cache因为缓存更新策略导致部分打印的日志丢失

**Comment by nobodyiam** [comment]
It seems there are no instructions to reproduce the null pointer exception?
The eviction strategy is related to the guava cache implementation cc @klboke

**Comment by johnxiaohe** [comment]
> 

Yes, The latest version has changed the judgment logic.
```java
assert logLine != null
```
change to
```java
if (logLine == null) {
         continue;
}
```
But I feel that when the log exceeds the upper limit, the log will be randomly discarded. It only approximates to keep the most recent log

**Comment by nobodyiam** [comment]
> But I feel that when the log exceeds the upper limit, the log will be randomly discarded. It only approximates to keep the most recent log

Yes, I believe this is the current behavior.
