### ISSUE TITLE
在portal可以全部导出配置，但是没看到导入功能

### ISSUE THREAD

**Issue by ingla9988** [apolloconfig/apollo#4226]
系统版本: java-1.8.1

想从一个apollo集群批量把配置导入到另一个集群，两个集群的环境是隔离的

在web控制台的portal界面，在管理员工具里有配置导出按钮，可以把全部环境的配置导出到本地，但是怎么从本地导入到另一个apollo集群呢？没找到导入的按钮

感谢！

**Comment by lepdou** [comment]
Latest version had supported importing configs, but not released.

http://106.54.227.205/config_export.html (user:apollo, password:admin).

Would you want export/import data not only config ?  like user's data, openapi's data ..

**Comment by ingla9988** [comment]
好的，谢谢
