### ISSUE TITLE
helm部署在集群后用nginx代理后无法登入

### ISSUE THREAD

**Issue by zifyloo** [apolloconfig/apollo#4229]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

helm部署在k8s集群后用nginx代理portal的服务，通过集群外能访问登录界面，但无法跳转成功。

**截图**
登录界面
![image](https://user-images.githubusercontent.com/44738882/154182599-2d582b44-e2e1-4446-918f-79d57ae28105.png)
输入密码后跳转失败界面
![image](https://user-images.githubusercontent.com/44738882/154182625-4ddc1264-efd8-4ec4-8848-8f72686ee73f.png)

**Comment by nobodyiam** [comment]
You may check the network tab to see the actual path to access.
Also please take a loot at the [ingress](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241447-%e4%bb%a5ingress%e9%85%8d%e7%bd%ae%e8%87%aa%e5%ae%9a%e4%b9%89%e8%b7%af%e5%be%84apollo%e5%bd%a2%e5%bc%8f%e6%9a%b4%e9%9c%b2%e6%9c%8d%e5%8a%a1) configuration instructions.

**Comment by zifyloo** [comment]
感谢您的回复！但是ingress代理后依然出现503 Service Temporarily Unavailable的错误，然后数据库出现这些warning
![img](https://raw.githubusercontent.com/zifyloo/typora/main/imgs/202202171106203.jpg)
portal日志也报warning
![img](https://raw.githubusercontent.com/zifyloo/typora/main/imgs/202202171108040.jpg)
请问这个会有影响吗？

**Comment by zifyloo** [comment]
用ingress代理成功了！
