### ISSUE TITLE
python如何调用Apollo的OpenAPI？

### ISSUE THREAD

**Issue by lishanlu136** [apolloconfig/apollo#4232]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

以按照文档操作注册第三方应用，并得到token和授权应用，但文档中调用OpenAPI是通过java，想问下，如何通过python调用？

**Comment by nobodyiam** [comment]
Python could use the [http api](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_231-%e8%b0%83%e7%94%a8http-rest%e6%8e%a5%e5%8f%a3).

**Comment by lishanlu136** [comment]
> Python could use the [http api](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_231-%e8%b0%83%e7%94%a8http-rest%e6%8e%a5%e5%8f%a3).

感谢，已成功调用
