### ISSUE TITLE
如何通过api调用的方式调用portal service的接口，实现登录，创建app呢？

### ISSUE THREAD

**Issue by ccccaoxin** [apolloconfig/apollo#4234]
我尝试接入ldap后，能否可以通过api调用portal的接口实现登录，创建app等呢？

**Comment by nobodyiam** [comment]
I suppose it is possible as the login is simply a post request.

![image](https://user-images.githubusercontent.com/837658/154784228-d462855a-0307-4832-8ae9-f90f6a0b8707.png)

**Comment by huayaoyue6** [comment]
在openapi的地方开一个创建应用的api也是可以的，微调一下权限和client即可。

**Comment by nobodyiam** [comment]
@huayaoyue6 

Currently, there is no `create app` permission for open API, do you have any suggestion on that?

**Comment by huayaoyue6** [comment]
看错了，场景不一样。我的场景是需要在另外一个项目中初始化的项目的相关信息。所以需要在apollo里创建应用。内容属于openapi的范畴。

**Comment by ccccaoxin** [comment]
> 看错了，场景不一样。我的场景是需要在另外一个项目中初始化的项目的相关信息。所以需要在apollo里创建应用。内容属于openapi的范畴。

目前openapi并不会提供创建app的接口，要么是在openapi使用一个系统超级管理员的账号二次开发出几个接口可以支持app的自动化创建流程

**Comment by ccccaoxin** [comment]
@nobodyiam 目前我会使用账号密码请求portal service 的登录接口，使用登录成功的cookie去请求创建app，授权等一系列接口来实现devops流程，可以探讨下这样的方式在你们看来会有什么疏忽吗？

**Comment by nobodyiam** [comment]
> @nobodyiam 目前我会使用账号密码请求portal service 的登录接口，使用登录成功的cookie去请求创建app，授权等一系列接口来实现devops流程，可以探讨下这样的方式在你们看来会有什么疏忽吗？

This looks okay to me.

**Comment by huayaoyue6** [comment]
使用openapi的方式我是这样处理的：

1.在 [AppController ](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/AppController.java)中添加一个方法，内容基本与下面的方法保持一致： https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AppController.java#L124 
2. 在系统配置中添加一个配置，用于标明哪些consumerid可以有创建应用的权限。
3. 在 [ConsumerPermissionValidator](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/auth/ConsumerPermissionValidator.java) 添加检测consumer是否有创建应用的权限的方法。
4. 调整client，添加创建应用的方法。

**Comment by nobodyiam** [comment]
> 在系统配置中添加一个配置，用于标明哪些consumerid可以有创建应用的权限

这个目前是一个白名单配置吧，我的建议是最好能复用目前的 role-permission 模型。
看上去我们可以复用类似『系统权限管理』页面的思路来为 consumer 赋予创建应用的权限？

![image](https://user-images.githubusercontent.com/837658/157779486-05e83440-1011-421d-b4e1-8852ab7f5d45.png)

**Comment by huayaoyue6** [comment]
我们是有的项目是自动创建的，有的项目手工创建的，没办法统一。所以不能启用这个配置。

**Comment by huayaoyue6** [comment]
我们是有的项目是自动创建的，有的项目手工创建的，没办法统一。所以不能复用这个配置。

**Comment by nobodyiam** [comment]
我是指我们可以用类似的思路在开放平台授权管理页面里面对 consumer 赋予创建 app 的权限，这样就可以复用权限校验模型了

**Comment by huayaoyue6** [comment]
👍

**Comment by Anilople** [comment]
> 我是指我们可以用类似的思路在开放平台授权管理页面里面对 consumer 赋予创建 app 的权限，这样就可以复用权限校验模型了


### 方案1

面向用户的UI，设计成

![image](https://github.com/apolloconfig/apollo/assets/15523186/92c2e023-dc20-414c-813e-f18e52ce4e8e)

后端的实现复用已有的openapi体系

这个改造量感觉比较小一些

### 方案2

portal新增1个管理端口，与原先的openapi体系隔离，专门供公司内部的系统使用

改造量比较大，但是隔离性会高一些

### 方案3

是否为了满足各大公司定制化portal的需求，模仿 eureka server 的使用方式

用户引入`@EnableApolloPortal`即可让自己的spring boot变成1个apollo portal，再定制化开发自己需要的功能？

改造量巨大，从长远来看既可以满足用户定制化的需求，也可以解决用户定制化portal后，由于改造过多，难以同步升级社区新版本的烦恼。可以降低用户个性化定制后的维护成本

---

针对这个issue，方案1更适合一些？

**Comment by nobodyiam** [comment]
1. 方案 1 可行
2. 方案 2 成本比较高，适用场景比较少
3. 方案 3 很有意思，如果能实现将大大扩展 apollo 的适用场景
