### ISSUE TITLE
apollo级联物理删除

### ISSUE THREAD

**Issue by kongqq** [apolloconfig/apollo#4237]
apollo 已经使用了很多年，库变得非常大，现在需要将历史数据，废弃的数据清理掉，【物理删除】，好像无法实现？ 这个需要怎么做？ 按照appId 级联物理删除，能做吗？

**Comment by nisiyong** [comment]
Cause Apollo uses the soft delete design, maybe you could run the SQL first like this: 
```sql
delete from table_name where IsDeleted = 0;
```

**Comment by nobodyiam** [comment]
I think what @nisiyong mentioned is one possible way, but I suggest backup the data first and starting from dev/test environments.
