### ISSUE TITLE
希望 docker image 支持 arm64

### ISSUE THREAD

**Issue by zchazc** [apolloconfig/apollo#4238]
**你的特性请求和某个问题有关吗？请描述**
用 raspberry pi 使用 `docker-quick-starter`时提示架构不匹配。

**清晰简洁地描述一下你希望的解决方案**
希望构建的镜像支持 arm 架构，毕竟是个 java 项目。

**清晰简洁地描述一下这个特性的备选方案**
貌似没法在现有 image 上重新构建 image。我找到了从 image 提取 dockerfile 的方法，还在尝试中。

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
The docker file for docker-quick-start is [here](https://github.com/apolloconfig/apollo-build-scripts/blob/master/Dockerfile).
Does that mean we have to build multiple docker images?

**Comment by zchazc** [comment]
- 谢谢~🤗
[反向工程的工具](https://github.com/P3GLEG/Whaler)也不支持`arm64`，我打算抽空重新`build`下这个工具。之前`nacos`遇到这这种情况，还好有`Dockerfile`，我就`build`了一个`arm64`版本的...
- 关于
>Does that mean we have to build multiple docker images?

这个看你们的安排，我只是希望能尽快解决这个问题，所以在一边自己解决一边寻求帮助。不过多架构`image`构建的[文档](https://docs.docker.com/desktop/multi-arch/)我也找到了，貌似不用构建多个`image`，有空我再细读。

**Comment by zchazc** [comment]
我已经按[文档](https://docs.docker.com/desktop/multi-arch/)构建了支持多平台的版本并测试成功，有需要的可以[试用下](https://hub.docker.com/r/zchazc/apollo-quick-starter)，因为构建很耗时，所以只构建了`amd64`、`arm64`的。
