### ISSUE TITLE
使用publishEvent  + @ConfigurationProperties 无法更新map

### ISSUE THREAD

**Issue by yangxinbo** [apolloconfig/apollo#4241]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

Properties 对象中喊有map,修改map后内存老的还存在，新的又增加了

**复现**

通过如下步骤可以复现：

Properties 对象
![image](https://user-images.githubusercontent.com/19682139/155938789-a2e31ca8-9c23-4ddf-8cf2-1ce5b23ea4eb.png)
初始化Bean
![image](https://user-images.githubusercontent.com/19682139/155938933-90206250-019b-494e-922f-3821bd3d36f2.png)
apollo 配置
![image](https://user-images.githubusercontent.com/19682139/155938986-f96784b9-244b-47ae-80d9-65fd98ddfbf1.png)

1.初始化启动-正常
![image](https://user-images.githubusercontent.com/19682139/155939483-c7deeecd-8c93-4802-8201-af7ff0fc33f6.png)
2. 修改apollo map
![image](https://user-images.githubusercontent.com/19682139/155939785-7dd8ffcb-6904-43ac-862f-b0914c3465c8.png)
3. 再此查看对象，变两条记录了
![image](https://user-images.githubusercontent.com/19682139/155939893-3d35dbee-00ac-4d1c-8c63-acb940fcec6f.png)

**期望**

正常的修改map

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：java-1.7.0-SNAPSHOT
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
`RefreshScope` might help.

**Comment by yangxinbo** [comment]
ok, i try
