### ISSUE TITLE
通过域名访问 Portal 服务，重定向signin页面自动追加 :0 端口

### ISSUE THREAD

**Issue by why444216978** [apolloconfig/apollo#4242]
通过 xxx.com  域名访问，302重定向时，Header Location 字段为 xxx.com:0/signin，预期应该是 xxx.com/signin（手动访问没问题）

**Comment by nobodyiam** [comment]
You may refer #4201 to see if it helps.

**Comment by why444216978** [comment]
上面那个问题我看了下，好像跟我的不是一个问题，他的问题应该是 302 后的地址 404， Location 是正常的 host/signin，而我的是被重定向到了 host:0/signin

**Comment by why444216978** [comment]
我们网关使用的不是 Nginx，是 kong
