### ISSUE TITLE
期望在提交卡片上增加一个下滑按钮

### ISSUE THREAD

**Issue by coderpolo** [apolloconfig/apollo#4248]
位置：提交预览页面
在配置value是一个长json 或者XML的场景下，还是蛮需要一个下滑按钮的.
![image](https://user-images.githubusercontent.com/25792424/156557107-781cb272-9ce2-42fe-b022-adc2173ce094.png)

**Comment by klboke** [comment]
It does look a lot better than the previous one, I will mention a pr to add this feature
![image](https://user-images.githubusercontent.com/18591662/156742439-cedb8876-2f66-4513-8d9d-a9c9bdeab3f0.png)
