### ISSUE TITLE
feat: add self define meta server

### ISSUE THREAD

**Issue by gy09535** [apolloconfig/apollo#4259]
**Is your feature request related to a problem? Please describe.**
In some environment，we put the config service and the admin service under the gateway, But for the portal we want to access the config service and admin service with gateway not the host which admin service and config service in, Such as different k8s environment. 
![image](https://user-images.githubusercontent.com/15153469/157582807-eab62c16-56a0-4970-bc67-f3d10197b257.png)

 So we want flexible config the admin service and the config service, and remove the stateful of config service(eureka).

**Comment by klboke** [comment]
Can kubernetes Registration Center really solve your problem?

**Comment by nobodyiam** [comment]
as @klboke mentioned, it looks the self define discovery is very similar to [KubernetesDiscoveryService](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/KubernetesDiscoveryService.java), could we just reuse that instead?
