### ISSUE TITLE
一个namespace中使用占位符引用另一个namespace某一个属性，不生效

### ISSUE THREAD

**Issue by liuyi9608** [apolloconfig/apollo#4264]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/26061239/158014490-e44a6f7f-ec43-4d25-bab8-c56ce5aeeb78.png">

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/26061239/158014502-c749bbf3-d8a2-447a-b1a6-d3a753c0a8b7.png">

![image](https://user-images.githubusercontent.com/26061239/158014508-1ea74253-bfc6-44cd-9f16-bc4ebbde6bcd.png)

![image](https://user-images.githubusercontent.com/26061239/158014512-5286563c-5df7-4141-bf4f-b704ebe88084.png)

**Comment by nobodyiam** [comment]
It looks like an issue of dubbo, as what apollo does is simply populate the properties to Spring and Spring context will resolve the references.

![image](https://user-images.githubusercontent.com/837658/158040684-26fc7a32-18d9-4ed6-b119-82234b39977d.png)

![image](https://user-images.githubusercontent.com/837658/158040710-fe94c8a0-f1d8-44af-bfdd-c7139b631a29.png)

![image](https://user-images.githubusercontent.com/837658/158040734-fdc36772-2d30-48c1-a41b-a3790a4a412e.png)
