### ISSUE TITLE
来自开源社区goodrain的合作请求-简化 K8s 环境下的部署操作

### ISSUE THREAD

**Issue by dazuimao1990** [apolloconfig/apollo#4273]
各位好，我来自开源社区 [goodrain](https://github.com/goodrain) ，主要运营开源产品 [Rainbond](https://www.rainbond.com/?channel=apollo)。
Rainbond 有很多用户的业务已经微服务化，所以这些用户也是 apollo 的用户或者潜在用户。Rainbond 通过自身的应用市场机制为这些用户提供了一种选择，一键部署生产可用的 apollo 集群，这种部署方式很受社区用户的欢迎。所以特此提出一种合作的可能，我们愿意提交一份一键部署 apollo 的文档到官方的安装文档序列中去，帮助更多同时需要云原生应用管理平台和 apollo 的用户了解到这种可能性以及其带来的便利性。

> 预计文档内容包括：
> - 图形化部署 apollo 集群 + Mysql 数据库的操作过程
> - 以环境变量的方式配置 apollo 集群的方式方法

非常期待 apollo 社区运营者的回复 😄

> 可以参考 https://nacos.io/zh-cn/blog/use-nacos-with-rainbond.html

**Comment by nobodyiam** [comment]
一键部署 apollo 对开源用户是有比较大帮助的，非常感谢对 apollo 的支持！
初步考虑下来，考虑到未来还可能有其它工具/平台支持 apollo 一键部署，所以在原有的分布式部署指南下方增加一个专门的栏目（比如第三方工具部署指南）可能会比较合适？

![image](https://user-images.githubusercontent.com/837658/159388386-6b346300-06c4-4006-af12-16273dd65940.png)

文档可以提交到 [docs](https://github.com/apolloconfig/apollo/tree/master/docs)，使用 [docsify](https://docsify.js.org/) 在本地测试效果。

**Comment by dazuimao1990** [comment]
新增第三方工具部署目录看起来很棒～ 
我会尽快完成 Apollo 和 Rainbond 的适配，并提交文档 PR，包括第三方工具部署目录的创建，感谢你的支持😊。
Have a nice day~

**Comment by zouyx** [comment]
> 新增第三方工具部署目录看起来很棒～ 我会尽快完成 Apollo 和 Rainbond 的适配，并提交文档 PR，包括第三方工具部署目录的创建，感谢你的支持😊。 Have a nice day~

如果没问题可以 close 一下。
