### ISSUE TITLE
集群配置和集群显示异常

### ISSUE THREAD

**Issue by justyida** [apolloconfig/apollo#4275]
当我的测试环境需要配置两个机房的时候，是否是使用集群模式来创建？部署文档中没有体现出应该怎么来配置集群。
所以我的apollo-portal的apollo-env.properties为：
cat apollo-env.properties
#local.meta=http://localhost:8080
dev.meta=http://172.31.35.135:8080
test.meta=http://172.31.39.102:8080,http://10.27.51.73:8080

**描述bug**
portal在新加坡机房，172.31.39.102:8080在新加坡机房，10.27.51.73:8080在aws的北美弗吉尼亚机房。两地的延迟为
ping 10.27.51.73
PING 10.27.51.73 (10.27.51.73) 56(84) bytes of data.
64 bytes from 10.27.51.73: icmp_seq=1 ttl=255 time=215 ms
64 bytes from 10.27.51.73: icmp_seq=2 ttl=255 time=215 ms
64 bytes from 10.27.51.73: icmp_seq=3 ttl=255 time=215 ms

正常情况下显示的集群情况：
![image](https://user-images.githubusercontent.com/29476868/159435571-2c7748f6-fed1-4b6e-ac6b-0d0c9bf046db.png)

不正常情况下显示的集群情况：
![image](https://user-images.githubusercontent.com/29476868/159437761-ee5195e8-ebc1-400b-a49a-535bfdd89df5.png)

**Comment by justyida** [comment]
不正常情况下，不管怎么点击“补全namespace”都会报错

**Comment by justyida** [comment]
是不是因为我一个测试环境接入了2个集群，两个集群接入了两个configdb数据库。等于每个集群都自建了数据库，因此数据不同步导致的，请问我该如何配置数据库呢，数据库都是读写的还是只读的？

**Comment by Anilople** [comment]
> 是不是因为我一个测试环境接入了2个集群，两个集群接入了两个configdb数据库。等于每个集群都自建了数据库，因此数据不同步导致的，请问我该如何配置数据库呢，数据库都是读写的还是只读的？

1 env 1 configdb 
1个环境1个configdb

1 configdb multiple cluster
1个configdb多个集群

**Comment by justyida** [comment]
> 

每个环境的config服务都使用的是同一个数据库是吧？

那我们在建环境的时候，多个环境和1个环境多个集群有和使用上的区别？官方如何建议。
例如：我建立一个test环境分为sg和vg集群  与  “建立1个testsg环境和一个testvg环境”

**Comment by nobodyiam** [comment]
1. isolation level is different, logical(cluster) vs physical(env)
2. env could have clusters in it, while cluster could not have child clusters
3. cost is different, env cost is higher
