### ISSUE TITLE
文本模式注释掉一些变量之后，不进行发布，重新点击文本模式进行修改，会重复出现注释掉的数据

### ISSUE THREAD

**Issue by dragontree101** [apolloconfig/apollo#4276]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

当一个参数对象里面是list的时候，在"文本"模式把其中一个list的值注释掉之后，这个时候不发布，但是重新点击"文本"模式，就会多出一行之前已经注释掉的那一行，并且多了一行注释的行

**复现**

通过如下步骤可以复现：

1. 删除list的一个配置
<img width="485" alt="image" src="https://user-images.githubusercontent.com/1763935/159437819-7bfe5b61-1dcc-4a75-b1ee-7c9fe62c8de9.png">

2. 点击提交修改

3. 切回"文本"模式之后，除开被注释的那一行以外，有多了一行没有注释的在最后面

4.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1763935/159438192-7ed388dc-5e76-4492-be9a-6f14c2e8ed81.png">

5.  如果没有注意（因为默认在最后一行又进行了放开），想把之前的要注释掉的数据放开，就会出现错误。

**期望**

期望如果不进行发布，重新点击文本，之前注释掉的那个配置还是继续注释，不会又自动添加一行一摸一样的在最后面

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：apollo的 2.0.0-SNAPSHOT
- 错误日志 无
- 配置： 无
- 平台和操作系统

**Comment by dragontree101** [comment]
我稍微看了下源码， 好像逻辑是从release数据库和item数据库都把数据取出来了，然后进行了合并 
但是因为这次修改并没有进行发布， 所以release里面拿到的还是 全部的内容
然后item数据库里面又有这次修改保存的注释掉的内容了
所以把两部分数据进行了合并， 造成了既有之前已经发布的内容和之后注释掉的内容

不知道我这么理解对不对

**Comment by nobodyiam** [comment]
There is an `isDeleted` property of the item, it seems the table view display takes this property into consideration while the text view doesn't.

![image](https://user-images.githubusercontent.com/837658/159819453-c564ae35-1127-4405-addd-bd1c81d5b773.png)

![image](https://user-images.githubusercontent.com/837658/159819685-3c0a94a7-39c6-4067-9c41-84aa849873f4.png)
