### ISSUE TITLE
非Properties格式的配置(yml)变更，能否做到和properties那样同步到其他集群

### ISSUE THREAD

**Issue by zxy1994** [apolloconfig/apollo#4278]
**你的特性请求和某个问题有关吗？请描述**
团队之前所有的配置都用properties格式，后面改成了yml；
但在使用yml的过程中发现了如下几个问题:

1. yml格式的配置，不能查找；没有properties的配置过滤功能
2. yml中新增部分配置时，不能像properties那样同步到其他集群

**下面是nacos的一些做法**

1. 看了下nacos，配置的查找是由前端实现的
2. nacos提供了一个配置文件对比的功能

**Comment by nobodyiam** [comment]
Duplicate of #2927
