### ISSUE TITLE
www.apolloconfig.com is very slow to load

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#4284]
The home page is very slow to load.

![20220329102635](https://user-images.githubusercontent.com/837658/160540380-3e786515-0f18-4f9b-b13f-ef82e0b088b6.jpg)

It looks like `cdn.jsdelivr.net` is dramatically slower than before, we need to look for another CDN to host the javascript files.
* https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
* https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js

**Comment by Anilople** [comment]
In docsify's official website https://docsify.js.org/#/cdn

There are 4 cdn can be choose
* https://www.bootcdn.cn/docsify/
* https://cdn.jsdelivr.net/npm/docsify/
* https://cdnjs.com/libraries/docsify
* https://unpkg.com/browse/docsify/

@sy-records Any good suggestions?

**Comment by sy-records** [comment]
In comparison, the speed of unpkg.com is not bad
