### ISSUE TITLE
apollo1.4.2 版本升级 apollo1.7.2 版本 SQL 问题

### ISSUE THREAD

**Issue by fxkjnj** [apolloconfig/apollo#4286]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug
你好，apollo1.4.2 在升级 apollo1.7.2 版本的时候，需要执行哪些版本的SQL，我在https://github.com/apolloconfig/apollo/tree/master/scripts/sql/delta  上有看到一些SQL 语句，但不知道具体要执行哪些，如图 我圈起来两个，【v151-v160  和  v170-v180 是吗？】
![](http://jpg.fxkjnj.com/picgo/202203310932864.png)

**Comment by nobodyiam** [comment]
You may reference the release notes from 1.5.0 to 1.7.2, then follow the upgrade steps. 
I just did a fast check and the delta schema is v151-v160.
