### ISSUE TITLE
通过 文本编辑过配置之后，表格中的备注信息被清空

### ISSUE THREAD

**Issue by YahuiWong** [apolloconfig/apollo#4288]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
通过 文本编辑过配置之后，表格中的备注信息被清空
简洁明了地描述一下bug

**复现**
通过 文本编辑过配置之后，表格中的备注信息被清空
通过如下步骤可以复现：

1.  通过 文本编辑过配置之后
2.  表格中的备注信息被清空

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.6.1
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Would you please duplicate this bug in [apollo demo site](http://106.54.227.205/) and describe the detailed steps here?
