### ISSUE TITLE
apollo 是否需要支持自动刷新配置类

### ISSUE THREAD

**Issue by gy09535** [apolloconfig/apollo#4293]
**你的特性请求和某个问题有关吗？请描述**
如 demo 所示：https://github.com/apolloconfig/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java

如果我想刷新这部分的配置，我需要手动写一个监听器去刷新，可不可以不用写监听器，直接就可以刷新配置。不包含额外的注解，比如：从 nacos 配置中心迁移到 apollo 当中，如果修改量较大的话，改起来还是比较麻烦的，怎样的实践比较正确呢？

**Comment by mghio** [comment]
see [客户端用法](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=%e4%b8%89%e3%80%81%e5%ae%a2%e6%88%b7%e7%ab%af%e7%94%a8%e6%b3%95)
