### ISSUE TITLE
不同环境,同一个Namespace,为什么变更一个值,其他环境也都变成一样的了?

### ISSUE THREAD

**Issue by a121984376** [apolloconfig/apollo#4304]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/15758574/162454294-e777e6d9-6d62-4ac6-a0ec-23134b9855ab.png">
比如 这里提示的是 此次发布只会作用于当前环境:DEV
然后发布以后,另一个环境的的timeout也会变成1002
<img width="889" alt="image" src="https://user-images.githubusercontent.com/15758574/162454511-db2cda49-8e57-4300-9a2f-352fd9959eb7.png">
按照提示: 我的理解是  只是DEV环境变成了1002, 而PRO环境还是1000啊~

**Comment by pengweiqhca** [comment]
共享同一个库了？

**Comment by CalebZYC** [comment]
![image](https://user-images.githubusercontent.com/42887532/162600438-9204014a-78bd-4c40-a472-84de4f6cbe28.png)
see [创建数据库](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_21-%e5%88%9b%e5%bb%ba%e6%95%b0%e6%8d%ae%e5%ba%93)

**Comment by a121984376** [comment]
> ![image](https://user-images.githubusercontent.com/42887532/162600438-9204014a-78bd-4c40-a472-84de4f6cbe28.png) see [创建数据库](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_21-%e5%88%9b%e5%bb%ba%e6%95%b0%e6%8d%ae%e5%ba%93)
我这边确实是两个数据呀~ 分别对应了DEV与PRO环境
<img width="543" alt="image" src="https://user-images.githubusercontent.com/15758574/162601365-c1eada48-cff3-41f8-841c-d960cb38ba0f.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/15758574/162601385-a28d1399-bdb6-473e-a6b1-d21b4b63a4e7.png">

**Comment by a121984376** [comment]
我这边仔细检查了
我这边两个环境
dev环境的config和admin 对应的数据库:ApolloConfigDBDEV
pro环境的config和admin 对应的数据库:ApolloConfigDBPRO

没有用同一个呢 
**dev环境:**
<img width="633" alt="image" src="https://user-images.githubusercontent.com/15758574/162601643-d98aeade-2d12-4372-aea7-5558f8c0126b.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/15758574/162601650-3c92b12f-eeed-4d9d-a8a9-e3b75ed0216f.png">
**pro环境:**

<img width="659" alt="image" src="https://user-images.githubusercontent.com/15758574/162601659-aa152304-a58c-4782-9c3a-93818168593b.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/15758574/162601670-c6da32d0-790d-4b85-8bfb-2800ccb30670.png">
