### ISSUE TITLE
deploy by docker run with version 1.9.2 takes error

### ISSUE THREAD

**Issue by gouhan** [apolloconfig/apollo#4306]
1、download the 1.9.2 version docker image, it works fine
2、but build docker image based on openjdk:8-jre-alpine by myself, i get the error like:
"/apollo-configservice/scripts/startup.sh: line 183: syntax error: unexpected end of file".

**dockerfile written like:**
FROM openjdk:8-jre-alpine
ENV VERSION 1.9.2
RUN apt-get install unzip
ADD ./apollo-configservice-${VERSION}-github.zip /apollo-configservice/apollo-configservice-${VERSION}-github.zip
RUN unzip /apollo-configservice/apollo-configservice-${VERSION}-github.zip -d /apollo-configservice \
    && rm -rf /apollo-configservice/apollo-configservice-${VERSION}-github.zip \
    && sed -i '$d' /apollo-configservice/scripts/startup.sh \
    && chmod +x /apollo-configservice/scripts/startup.sh \
    && echo "tail -f /dev/null" >> /apollo-configservice/scripts/startup.sh
EXPOSE 8080
CMD ["/apollo-configservice/scripts/startup.sh"]

thanks very much.

**Comment by nobodyiam** [comment]
You may compare yours with the [Dockerfile](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/docker/Dockerfile) apollo used.
