### ISSUE TITLE
Support grayscale feature for non-properties namespaces

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#4316]
**Is your feature request related to a problem? Please describe.**
Currently, apollo supports the grayscale feature for properties namespaces.

![image](https://user-images.githubusercontent.com/837658/164224874-a6c6d1e1-d8f8-4615-a52e-71ee28726248.png)

However, it's not available for non-properties namespaces, e.g. xml/yml, which is strongly required by many users, see https://github.com/apolloconfig/apollo/issues/2927.

**Describe the solution you'd like**
Support grayscale feature for non-properties namespaces, to make it easier, we may only support grayscale the whole text instead of some keys.

![image](https://user-images.githubusercontent.com/837658/164225288-9d8b6c14-03c0-41a7-a4bd-cece7af4df16.png)

**Comment by derecknowayback** [comment]
I am interested in this issue.

**Comment by nobodyiam** [comment]
Thank you for your interest in this feature. If you are a student, you can apply for the feature on the [summer-ospp website](https://summer-ospp.ac.cn/org/prodetail/23c4c0041?list=org&navpage=org).

**Comment by ywy-github** [comment]
我通过修改前端页面使得非properties格式的命名空间具有了灰度和同步的按钮，测试发现目前是可以支持非properties格式的命名空间整体进行灰度和同步的，那么目前的项目需求是支持key级别的灰度和同步吗？

**Comment by nobodyiam** [comment]
> 那么目前的项目需求是支持key级别的灰度和同步吗？

从实现成本考虑，可以实现为 namespace 级别的灰度和同步。
如果可能的话，对 yaml/yml 格式可以看看是否能实现 key 级别的灰度和同步。

**Comment by nobodyiam** [comment]
目前开源之夏还在报名阶段，我觉得应该还没有人开始开发 cc @klboke

**Comment by hezhaoye** [comment]
请教下，目前有人进入开发了吗

**Comment by klboke** [comment]
https://github.com/ywy-github 在开发中了

**Comment by hezhaoye** [comment]
你好，预计什么时候能完成开发呢？

**Comment by hezhaoye** [comment]
> 之夏还在报名阶段，我觉得应该还没有人开始开发 cc @k



> 如果能顺利解决该问题，提交PR应该在9月30日之前

老哥，目前开发进度如何了呢

**Comment by ywy-github** [comment]
目前还在开发中，yaml的key级别的灰度遇到一些问题还在思考解决方法

**Comment by hezhaoye** [comment]
> 目前还在开发中，yaml的key级别的灰度遇到一些问题还在思考解决方法

如果实现为 namespace 级别的灰度和同步，感觉只要修改下前端页面就好了，后端不用变动。感觉支持整个文本的灰度就能解决大部分问题了。

**Comment by ywy-github** [comment]
是的，之前在尝试实现yaml格式的配置key级别的灰度，但是对于注释却不能正确保存，实现全文本的灰度只需要更改前端代码基本就可以使用，目前在测试阶段

**Comment by hezhaoye** [comment]
> 是的，之前在尝试实现yaml格式的配置key级别的灰度，但是对于注释却不能正确保存，实现全文本的灰度只需要更改前端代码基本就可以使用，目前在测试阶段

我们这边也在开发该功能，可加+V 15521230776 进行沟通互助。

**Comment by novayoung** [comment]
![screencapture-192-168-11-129-8070-config-html-2024-04-24-18_17_53](https://github.com/apolloconfig/apollo/assets/1515003/ade59b71-8043-4a39-bbe3-88ccbb257f63)

Why didn't I find the Grayscale button of the yaml format namespace? Apollo version is 2.2.0
