### ISSUE TITLE
openapi: items量大 可否提供分页接口呢

### ISSUE THREAD

**Issue by lic0914** [apolloconfig/apollo#4320]
业务配置items 相对量大点 

通过API获得 获得选中某个namespace下的items 
量大的话很卡的，却不支持分页

**清晰简洁地描述一下你希望的解决方案**
期望可以通过API获得简介的namespaces （而不是包含所有的items）然后通过选择特定的ns 再分页请求items 
非常感谢！

**Comment by nobodyiam** [comment]
Good idea, I think a new API could be added to load the items with pagination.
URL: http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items
Method: GET
Request Params:
* page - page number, starting from 0
* size - records in each page

**Comment by lic0914** [comment]
Yeah！I think so expected
Thanks
