### ISSUE TITLE
portal删除appid，再次创建报错

### ISSUE THREAD

**Issue by ccccaoxin** [apolloconfig/apollo#4328]
portal上删除appid，数据库idDeleted变为1，但DeleteAt不会变，数据库唯一索引  UNIQUE KEY `UK_AppId_DeletedAt` (`AppId`,`DeletedAt`),是这个，所以再次创建相同的appid会报错；

之前发现删除了application的namespace，后面添加也会报错

**Comment by ccccaoxin** [comment]
的确会报错，但不能重现场景

**Comment by nisiyong** [comment]
Could you provide the apollo version information?

**Comment by ccccaoxin** [comment]
apollo version 1.9.1

**Comment by nisiyong** [comment]
The [Unique Constraint Index](https://github.com/apolloconfig/apollo/pull/3866) was introduced in 2.0.0-RC1, you should check the [changelog](https://github.com/apolloconfig/apollo/releases/tag/v2.0.0-RC1). I think it is because you apply the new DDL but did NOT upgrade the apollo.
