### ISSUE TITLE
用第三方应用接入Apollo开放平台，获取 key value 不全

### ISSUE THREAD

**Issue by fananchong** [apolloconfig/apollo#4330]
用第三方应用接入Apollo开放平台，获取 Backend.cserver2 。只获取了，自己修改的。被关联的配置没获取到
![image](https://user-images.githubusercontent.com/20277955/165907846-77beb051-8d0c-416e-bf5e-fc3d4267922f.png)
![image](https://user-images.githubusercontent.com/20277955/165907727-6fa064a9-9bd3-4cee-82ce-a724277c3324.png)

**Comment by nobodyiam** [comment]
That's by design. If you want to fetch the configs effective to the client, you could reference the [client api](https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide).

**Comment by fananchong** [comment]
有问题：
1. [client api](https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide) 可以完整读，但是没有写接口
2. [open api](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform) 有写接口，但是不能完整读

上面 2 组 api 用的参数又不一样。导致配置复杂
