### ISSUE TITLE
单机版的quick-start,怎么修改默认的端口号(8070,8090,8080)

### ISSUE THREAD

**Issue by robben009** [apolloconfig/apollo#4331]
单机版的quick-start,怎么修改默认的端口号(8070,8090,8080)? 修改了demo.sh中端口号不生效，又down了源码，全局替换端口号重新打包，也不行。请教怎么修改呢？

**Comment by fananchong** [comment]
可以参考下： https://github.com/fananchong/apollo_helm_script
