### ISSUE TITLE
namespace 长度太短，希望能支持 128 个字符，或可配置

### ISSUE THREAD

**Issue by fananchong** [apolloconfig/apollo#4335]
![企业微信截图_16516580473675](https://user-images.githubusercontent.com/20277955/166664314-96d64073-2955-4ec5-a294-9ee0b99abc24.png)

**Comment by Zacson-Lee** [comment]
namespace 名称的 MySQL 字段类型为 varchar(32)，不方便扩展，可考虑使用缩写？
