### ISSUE TITLE
集群下配置修改doLongPollingRefresh检测不到

### ISSUE THREAD

**Issue by onlinever-demon** [apolloconfig/apollo#4336]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
同环境多集群的模式下，其他集群中有配置改动返回304，只有default集群中配置改动才会得到200，导致配置不能动态刷新。

**复现**

通过如下步骤可以复现：

1. 同环境下建立多个集群
2. 服务使用非default的集群
3. 修改非default集群中的配置
4. 服务中doLongPollingRefresh返回304

**Comment by nobodyiam** [comment]
would you please duplicate the issue in apollo [demo site](http://106.54.227.205/)?
