### ISSUE TITLE
namespace创建总是会覆盖所有的环境和集群，是否可以做到独立创建 ？

### ISSUE THREAD

**Issue by SperChung-11** [apolloconfig/apollo#4341]
**你的特性请求和某个问题有关吗？请描述**
在apollo的某个appid下面的某环境某集群下新增一个namespace时候，总是会在这个appid下面的所有环境&所有集群下面创建对应的namespace

**清晰简洁地描述一下你希望的解决方案**
能否做到在x环境y集群下创建，就只有x环境和y集群有这个namespace

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
That would make the namespace management complex. And if a namespace is created but not released, then it is invisible to the client, which can achieve the same effect of not creating it at all.

**Comment by SperChung-11** [comment]
@nobodyiam thanks for your reply. is it possibly to make the namespace created independent ? We have found that only independent namespace created could solve the probolem we met. Maybe if it is planned to makie it independent or it would violate the apollo design ? Thanks

**Comment by nobodyiam** [comment]
Would you please help to describe the actual problem you met?
