### ISSUE TITLE
界面删除配置时，偶现删除成功，部分信息回填失败，页面不刷新不会继续回填；页面刷新数据都存在

### ISSUE THREAD

**Issue by SperChung-11** [apolloconfig/apollo#4344]
**Describe the bug**
界面删除配置时，偶现删除成功，部分信息回填失败，页面不刷新不会继续回填；页面刷新数据都存在

**To Reproduce**
【操作步骤】
1.登录Apollo，进入项目，选择namespace，点击新增配置；
2.填写key、value和comment并提交；
3.提交成功后点击发布；
4.配置发布成功后，页面手动删除刚才发布的配置（不发布）

**Expected behavior**
删除成功，删除后页面回填备注、修改人及修改时间等信息
![image1](https://user-images.githubusercontent.com/74529952/167332529-2ff9f09c-687e-4daa-91a0-e53f9768627e.png)

**Actual behavior**
删除成功，但信息未回填，手动刷新后回填正常
![image2](https://user-images.githubusercontent.com/74529952/167332618-da32c3a7-28c3-45b3-ad6c-73ec1320d6fd.png)

- Version：1.7.1
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
Would you please help to reproduce this issue in the [demo site](http://106.54.227.205/)?
