### ISSUE TITLE
能否设置某个namespace只有超级管理员才能查看，即使是项目管理员也不能查看？

### ISSUE THREAD

**Issue by dengdalue** [apolloconfig/apollo#4345]
**描述bug**
在给开发授予权限时，如果有很多namespace，需要一个一个授权，比较麻烦；如果给开发授予项目管理员权限，就方便很多，但是开发就能看到该项目的所有信息，包括敏感信息，这不符合安全要求。

**期望**
能否设置某个namespace只有超级管理员才能查看，即使是项目管理员也不能查看？

- 版本：1.8.2
- 平台和操作系统：centos 7.9

**Comment by nobodyiam** [comment]
目前是不行的，因为项目管理员拥有对项目中 namespace 授权的能力，所以就算他一开始不能查看，但是他可以给自己授予对该 namespace 的编辑/发布权限。

**Comment by dengdalue** [comment]
好的，谢谢！
那请问这个问题有什么解决方案吗？

**Comment by nobodyiam** [comment]
可以参考下 #3187
