### ISSUE TITLE
使用EnvironmentChangeEvent在特定场景下无法刷新ConfigurationProperties注解

### ISSUE THREAD

**Issue by whitefeather2018** [apolloconfig/apollo#4346]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
EnvironmentChangeEvent刷新方式对于配置项删除场景无法实现ConfigurationProperties注解热刷新。

**To Reproduce**
代码示例：
@Component
@ConfigurationProperties(prefix = "user")
public class User {
     private String name;
     ...
}
1. ConfigurationProperties注解对应的属性：user.name；通过监听配置集+发布EnvironmentChangeEvent实现ConfigurationProperties热刷新；
2. 在配置中心配置user.name属性的值，应用启动后可以拿到。
3. 运行过程中修改user.name，刷新成功，可以拿到最新值；但是运行过程中删除user.name，刷新失败，拿到的还是旧值。

**Expected behavior**
使用RefreshScope对于以上的场景可以正常刷新，但是因为一些原因，不想用RefreshScope。希望可以使用EnvironmentChangeEvent或者别的方式解决这个问题。
**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
This is a known issue of Spring Cloud, see #2916

**Comment by whitefeather2018** [comment]
> This is a known issue of Spring Cloud, see #2916

@nobodyiam 如果不使用refreshScope，能解决吗？
