### ISSUE TITLE
apollo配置中的key、value默认最大条目支持多少行？是否可以修改？

### ISSUE THREAD

**Issue by Coldsmokers** [apolloconfig/apollo#4349]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by Coldsmokers** [comment]
指的就是某个cluster集群的配置项条目数，yaml文件的最大行数这样子

**Comment by nobodyiam** [comment]
For properties namespaces, there is no limit on the number of items.
For other type of namespaces like yaml, the default length is 20000, see the [config](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_325-itemvaluelengthlimit-%e9%85%8d%e7%bd%ae%e9%a1%b9-value-%e6%9c%80%e5%a4%a7%e9%95%bf%e5%ba%a6%e9%99%90%e5%88%b6).
