### ISSUE TITLE
OPEN API, 查询配置后返回的结果中没有发布状态字段, 要怎么做才能获取发布状态？

### ISSUE THREAD

**Issue by mingyou-xiong** [apolloconfig/apollo#4351]
URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key}
Method ： GET
Request Params ：无
返回值Sample ：
  {
    "key": "timeout",
    "value": "3000",
    "comment": "超时时间",
    "dataChangeCreatedBy": "zhanglea",
    "dataChangeLastModifiedBy": "zhanglea",
    "dataChangeCreatedTime": "2016-08-11T12:06:41.818+0800",
    "dataChangeLastModifiedTime": "2016-08-11T12:06:41.818+0800"
}
我们公司用OPENAPI读写配置，方便集成，但是发现返回的结果中少了releaseStatus字段，因为配置是否被发布非常重要，这是忘记返回该字段还是要通过其它的方式间接得到？

**Comment by nobodyiam** [comment]
You may use [this api](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3214-%e8%8e%b7%e5%8f%96%e6%9f%90%e4%b8%aanamespace%e5%bd%93%e5%89%8d%e7%94%9f%e6%95%88%e7%9a%84%e5%b7%b2%e5%8f%91%e5%b8%83%e9%85%8d%e7%bd%ae%e6%8e%a5%e5%8f%a3).

**Comment by mingyou-xiong** [comment]
你好,这个接口能解决一部分问题,如果增加配置可以通过求2个接口返回值交集确认配置项是否发布，如果修改配置可以通过对比2个接口返回的key的value是否一致得到，那么如果删除配置项是否发布，是真的没办法了

**Comment by nobodyiam** [comment]
The portal page can display deleted items by fetching commit histories. If it's also needed for open API scenario, I think it's reasonable to add the commit open api.

https://github.com/apolloconfig/apollo/blob/cb308cb7a9b08178046f747c1f02c8385eeca28c/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/NamespaceService.java#L280-L287

**Comment by mingyou-xiong** [comment]
Thankyou , this can sovle my problem , but it is indeed complicated, so I wish  the open api can return the publish status directly in the future...

**Comment by lancelothuxi** [comment]
这个releaseStatus字段加上去了么，我看最新的服务端和客户端代码还是没加
