### ISSUE TITLE
新建私有namespace，使用管理工具删除之后，在新增同名namespace，出现唯一索引冲突

### ISSUE THREAD

**Issue by liuyi9608** [apolloconfig/apollo#4352]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
新建私有namespace，使用管理工具删除之后，在新增同名namespace，出现唯一索引冲突

**复现**

通过如下步骤可以复现：

1. 新增私有namespace
2. 管理者工具删除这个namespace
3. 新增同名public类型的同名namespace

**期望**
新增成功

**截图**
![image](https://user-images.githubusercontent.com/26061239/168269468-32932731-c39a-4537-a553-c3b36d4da6a9.png)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nisiyong** [comment]
Please provide the version information.
