### ISSUE TITLE
以文本方式修改配置时，没有修改的配置项的最后修改人也被更新了

### ISSUE THREAD

**Issue by YuJoe** [apolloconfig/apollo#4357]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

以文本方式修改配置，在中间新增了11个配置项，提交修改后，其他没有动到的配置项的[最后修改人]也变成了我

**复现**

通过如下步骤可以复现：

1. 以文本方式修改配置
2. 新增一些配置
3. 提交修改

**期望**

只有我新增的配置项的[最后修改人]是我，其余我没有动到的配置项的最后修改人不变

**截图**

不方便截图

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
In the text mode scenario, the line number is also considered a change. So if you add a new item in the middle, then it would affect other items' line numbers. If you add the item to the last, then it won't change other items' last modified by.
