### ISSUE TITLE
spring boot的配置优先级顺序

### ISSUE THREAD

**Issue by shenhuaxin** [apolloconfig/apollo#4367]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
apollo配置的优先级高于命令行参数，导致启动脚本中设置的命令行参数失效。

https://github.com/apolloconfig/apollo/issues/1800#issuecomment-465455448

![image](https://user-images.githubusercontent.com/23735480/169645058-266be41e-acaa-4fc2-9cdb-63f334a7c874.png)
这一行代码导致了apollo的优先级是最高的，但是 -D配置的优先级高于apollo的配置，是因为下面的代码。
![image](https://user-images.githubusercontent.com/23735480/169645093-2bb92340-82f8-4acf-9e44-8c0d02d183c4.png)
我尝试将apollo的配置优先级降低，添加到命令行参数后面，这样脚本的命令行参数就优先于apollo配置。 
![image](https://user-images.githubusercontent.com/23735480/169645154-00361c0e-8bf1-491e-aa8c-0970ff8dbdc7.png)

**期望**
命令行参数优先级高于apollo配置

**Comment by nobodyiam** [comment]
The [apollo-client-config-data](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3214-spring-boot-config-data-loader-spring-boot-24-apollo-client-190-%e6%8e%a8%e8%8d%90) uses the Config Data Loader pattern, which should prevent this issue from happening. It uses the [PureApolloConfig](https://github.com/apolloconfig/apollo/blob/master/apollo-client-config-data/src/main/java/com/ctrip/framework/apollo/config/data/internals/PureApolloConfig.java), which won't read from System Property or System Env.

As for this specific issue, maybe we could add a config to let the user config the order of apollo property source?

**Comment by shenhuaxin** [comment]
现在是 -Dserver.port 不会被 apollo 覆盖，--server.port 会被 apollo 覆盖。是否 apollo 不应该覆盖启动脚本中设置的配置？

**Comment by nobodyiam** [comment]
@shenhuaxin 你描述的应该是正确的行为，目前的实现没有兼容 --args 的场景。

**Comment by shenhuaxin** [comment]
我是从 spring-boot 的 org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor#postProcessEnvironment 中看到了下面的写法。 感觉这种方案可行。。 
![image](https://user-images.githubusercontent.com/23735480/169693060-e88ff141-414b-472d-9d46-2f2e04ddb876.png)

**Comment by nobodyiam** [comment]
I suppose we could add some configs to adjust the property source overriden behavior just like what [spring cloud does](https://cloud.spring.io/spring-cloud-static/spring-cloud.html#overriding-bootstrap-properties).

**Comment by shenhuaxin** [comment]
我明白了你的意思了，我会阅读一下这方面的源码，尝试提交一个pr添加这个功能。
