### ISSUE TITLE
MetaServer 直接返回ALB地址, 移除eureka 是否可行?

### ISSUE THREAD

**Issue by majinding** [apolloconfig/apollo#4375]
![image-20220524110459497](https://majingjing.cn/md/mac/image-20220524110459497.png-majj)

公司之前部署的版本为 1.3.0

像上图的公司内部部署的时候, 集群部署config-service , 对外暴露是采用alb的方式(外部服务访问不允许使用ip+port)

> 之前专门搭建了一套eureka服务, 内部注册的ip为 ALB的域名

- 所以我想直接在 Meta-Server的api内部返回对应的 ALB地址

- 移除对eureka的依赖

 对apollo整个系统是否有影响? 想确认下是否可以这么操作?

**Comment by nobodyiam** [comment]
It could work, the kubernetes and custom-defined-discovery mode work that way.
See [KubernetesDiscoveryService](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/KubernetesDiscoveryService.java).

**Comment by majinding** [comment]
Thank you for your information
