### ISSUE TITLE
请问server版本升级到2.0之后，还能使用1.x版本的client（例如1.6.1）访问吗？

### ISSUE THREAD

**Issue by GTaurus** [apolloconfig/apollo#4378]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述**

请问server版本升级到2.0之后，还能使用1.x版本的client（例如1.6.1）访问吗？

**Comment by nobodyiam** [comment]
Apollo server is compatible with old versions of apollo-client, so you could use apollo client 1.x to access apollo server 2.0.0.

**Comment by GTaurus** [comment]
> Apollo server is compatible with old versions of apollo-client, so you could use apollo client 1.x to access apollo server 2.0.0.

Thx.
