### ISSUE TITLE
apollo-portal 一直在启动中，但是没有报错日志

### ISSUE THREAD

**Issue by jun0737** [apolloconfig/apollo#4379]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我不太能确定这是一个bug，我是在学习apollo的使用，想搭建一个本地环境，然后已经成功启动了apollo-configservice和apollo-adminservice，但是在启动apollo-portal的时候，一直处于Waiting for server startup,甚至无法强行终止，只能重启机器，查看日志时没有error日志

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

希望可以有error日志，可以自行发现处理问题。

**截图
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/71121591/170172728-046141f1-b1df-41d6-aa73-9184e9f1bcfe.png">
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/71121591/170172770-c0774e02-c4d1-4001-b629-61b4d4f1a12c.png">
![image](https://user-images.githubusercontent.com/71121591/170187224-af2bf19b-51a7-4b92-b84c-beda47d82a1a.png)

### 额外的细节和日志

- 版本：2.0.0
- 错误日志 无
- 配置：只修改了默认配置中的数据库地
- 平台和操作系统 Alibaba Cloud Linux  3.2104 64位

**Comment by nobodyiam** [comment]
Looks like the server port was changed to 8020, did you do this by changing the SERVER_PORT variable in startup.sh?
The startup script replies on this variable to do the health check.

https://github.com/apolloconfig/apollo/blob/f929541b704348cd72e7d49c9894d6b561700f14/apollo-portal/src/main/scripts/startup.sh#L21
