### ISSUE TITLE
换掉eureka

### ISSUE THREAD

**Issue by githubcheng2978** [apolloconfig/apollo#4381]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦

有没有计划移除掉eureka,毕竟现在的eureka已经不维护了。

**清晰简洁地描述一下你希望的解决方案**

**清晰简洁地描述一下这个特性的备选方案**

高可用可以使用jraft库，来替换掉eureka。

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
apollo now supports `consul`, `kubernetes`, `nacos` and `zookeeper` as its service discovery component, see [distributed-deployment-guide](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide).
