### ISSUE TITLE
官网的E-R图部分不可访问

### ISSUE THREAD

**Issue by trtmu** [apolloconfig/apollo#4390]
![image](https://user-images.githubusercontent.com/26428919/170929120-2a810fd8-a0ae-4b2e-b324-495a6f0b64ad.png)

链接:
https://cdn.jsdelivr.net/gh/apolloconfig/apollo@master/doc/images/apollo-erd.png
https://cdn.jsdelivr.net/gh/apolloconfig/apollo@master/doc/images/apollo-erd-role-permission.png
等
导致无法看到详细的ER图设计 
麻烦处理一下

**Comment by nobodyiam** [comment]
Thanks for reporting this issue, it looks like cdn.jsdelivr.net is not available in China now.
We may need to change the image URLs from `https://cdn.jsdelivr.net/gh/apolloconfig/apollo@master/doc/images` => `https://raw.githubusercontent.com/apolloconfig/apollo/master/doc/images`.

**Comment by nobodyiam** [comment]
Meanwhile, you may read the [wiki page](https://github.com/apolloconfig/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1) instead. It may be a little outdated but are mostly ok.
