### ISSUE TITLE
使用EnvironmentChangeEvent刷新bean失败

### ISSUE THREAD

**Issue by chen1104580703** [apolloconfig/apollo#4391]
import com.ctrip.framework.apollo.model.ConfigChange;
import com.ctrip.framework.apollo.model.ConfigChangeEvent;
import com.ctrip.framework.apollo.spring.annotation.ApolloConfigChangeListener;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.BeansException;
import org.springframework.cloud.context.environment.EnvironmentChangeEvent;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 * 该类可动态监听apollo配置变更，动态加载bean
 */
@Slf4j
@Component
public class ApolloConfigChanged implements ApplicationContextAware {
    private ApplicationContext applicationContext;

    @ApolloConfigChangeListener(value = "application")
    public void onChange(ConfigChangeEvent changeEvent) {

        for (String changedKey : changeEvent.changedKeys()) {
            ConfigChange change = changeEvent.getChange(changedKey);
            log.info("Change-key: {}, oldValue: {}, newValue: {}, changeType: {}",
                    change.getPropertyName(),change.getOldValue(),
                    change.getNewValue(), change.getChangeType());
            refreshProperties(changeEvent);
        }
    }

    private void refreshProperties(ConfigChangeEvent changeEvent){
        long startTime = System.currentTimeMillis();
        // 更新配置
        this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
        long finishTime = System.currentTimeMillis() - startTime;
        log.info("更新数据完成！耗时：" + finishTime + "ms");
    }
    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.autoconfigure.ConfigurationCustomizer;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;

@Configuration
@ConfigurationProperties(prefix = "dburl")
public class MybatisConfig {

    @Value("${dburl}")
    private String dburl;
    @Value("${dbuser}")
    private String username;
    @Value("${dbpsw}")
    private String password;
    /**
     * spring context
     */
    private ApplicationContext context;
    @Bean
    public DataSource dataSource(){
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setUsername(this.username);
        dataSource.setPassword(this.password);
        dataSource.setDriverClassName("com.mysql.jdbc.Driver");
        dataSource.setUrl(this.dburl);
        return dataSource;
    }

    /**
     * 启用分页插件
     * @return PaginationInnerInterceptor
     */
    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor(){
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }

    @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseDeprecatedExecutor(false);
    }
}

spring-cloud-context：3.0.3
spring-boot：2.3.1

**Comment by chen1104580703** [comment]
@nobodyiam 大佬来帮忙看一下吧

**Comment by nobodyiam** [comment]
You may refer the [dynamic-datasource](https://github.com/apolloconfig/apollo-use-cases/tree/master/dynamic-datasource) example.
