### ISSUE TITLE
[问题请教] 边缘节点部署模式有哪些

### ISSUE THREAD

**Issue by rrsunhome** [apolloconfig/apollo#4393]
## 背景
目前有 20-100 服务节点部署在边缘节点，如何更好的设计部署架构、满足业务的接入

## 问题
1. Portal 支持的环境数量有上限吗？
2. Portal 统一管理环境，在每个边缘节点部署一套，这样客户端就可以就近访问、避免网络延迟问题产生，推荐这种模式吗或者有没有更好部署架构

**Comment by nobodyiam** [comment]
Duplicate of #4363
