### ISSUE TITLE
[版本升级] Apollo 跨版本升级注意什么

### ISSUE THREAD

**Issue by rrsunhome** [apolloconfig/apollo#4396]
从 Apollo 1.7.0 升级到 2.0.0 需要注意哪些？

**Comment by Nidhoggur1993** [comment]
> You may refer the [release notes](https://github.com/apolloconfig/apollo/releases/) for more information.
> 
> Basically, here are the things you need to note:
> 
> 1. apollo-client requires java 8
> 2. database changes

Hi, is there any way to check which version I'm current running?
Like any specific file contains version info or maybe in the database?

**Comment by nobodyiam** [comment]
@Nidhoggur1993 

![image](https://user-images.githubusercontent.com/837658/173709642-aa26e8e1-f79d-492d-91c4-c3e4ddd44337.png)

![image](https://user-images.githubusercontent.com/837658/173709660-f1f608ee-09b3-4790-af20-823adbd59445.png)

If your apollo doesn't have the system information menu, you could also retrieve the version via http://${your_portal_url}/apollo/version
