### ISSUE TITLE
Java 中 localIp问题

### ISSUE THREAD

**Issue by lic0914** [apolloconfig/apollo#4400]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述疑问**

在Java 中如何像 .Net 中使用 `localIp` 进行连接呢，以便 long polling notification 接口请求成功呢

**复现**
![image](https://user-images.githubusercontent.com/32569971/172321598-7b4609f2-ca4d-47ff-be3d-6314b321c295.png)

Thanks!

**Comment by nobodyiam** [comment]
do you mean the [apollo.config-service](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_1222-%e8%b7%b3%e8%bf%87apollo-meta-server%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0) option?

**Comment by lic0914** [comment]
No, in this case 

 config-service  : `http://config.apollo.pkulaw.online:30080/test` 

How to update `ip`  in query parameters when the client request configservice ?

In Asp.net core , I can add the `apollo.localIp`  to resolve the issue, However，I could't found the option  in Java, 
I hava no choice!

Thank you your reply!

**Comment by nobodyiam** [comment]
You may use `host.ip`.

https://github.com/apolloconfig/apollo/blob/d15331b25242c5a5d80118b139e7a27bb95076bb/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L107-L118

**Comment by lic0914** [comment]
I will try it , then close the issue

It would be appreciated !

**Comment by lic0914** [comment]
I need to set port ! 
How can I set port?  Because  my app use `NodePort` or `Ingress` to expose other kubernetes cluster

**Comment by nobodyiam** [comment]
Honestly, I don't quite understand what's the relationship between the long polling timeout issue and your app/port setting.
It looks to me the issue is that the server doesn't return before the client timeout, so you may take a look at the server log. Also it looks like you use a slb/nginx as the proxy server, you may also check its log.

**Comment by lic0914** [comment]
I have inspected this photo ,About Read time out ,It may be due to  my nginx about `timeout`  settinggs !
I want to confirm the thing that whether  the config service have to connect the `localIp`(client ip)  ，In other word if the config service must be ping successfully to localIp
If so ,I must be tell config service  what is client ip and port
How should i do about it ?
Thank your very much what you reply to me  in weekend

**Comment by lic0914** [comment]
Why do you say that , I understand the client in local can't  connect to  apollo service in online!

**Comment by nobodyiam** [comment]
According to [apollo-design](https://www.apolloconfig.com/#/en/design/apollo-design?id=_12-architecture-module), apollo server won't connect to the client. As long as the apollo client can connect to apollo servers, it would work well.
