### ISSUE TITLE
Apollo修改配置发布后，SpringBoot监听到了发布动作，但是获取到的新值还是修改之前的(没有更新)

### ISSUE THREAD

**Issue by hongjiahua** [apolloconfig/apollo#4404]
简洁明了地描述一下bug
Apollo修改配置发布后，SpringBoot监听到了发布动作，但是获取到的新值（new value）还是修改之前的(没有更新)
**复现**
1.application.yml 配置 autoUpdateInjectedSpringProperties= true
2.修改配置并发布

**截图**
![image](https://user-images.githubusercontent.com/47426264/172516555-e6314227-9e29-461a-823b-b17143cb9bc3.png)

**Comment by zhaoyanlin** [comment]
所以这个是什么问题呢
