### ISSUE TITLE
build: suppress UnresolvedMavenProperty ${env.GITHUB_OAUTH_TOKEN}

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4407]
**Is your feature request related to a problem? Please describe.**
In IDE idea, a red underline will occur under file pom.xml, because local environment has no property `${env.GITHUB_OAUTH_TOKEN}` 

![image](https://user-images.githubusercontent.com/15523186/173169772-a891537a-51fe-43c1-875d-4cbf125d3608.png)

**Describe the solution you'd like**
A single line to let idea ignore it.
```xml
<!--suppress UnresolvedMavenProperty -->
<github.global.oauth2Token>${env.GITHUB_OAUTH_TOKEN}</github.global.oauth2Token>
```

**Comment by nobodyiam** [comment]
This is for travis ci use, as now we are using github actions, I think we don't need them anymore.

**Comment by HeavenTonight** [comment]
I can solve this issue! I think should delete these codes:
`
<github.global.server>github</github.global.server>
<github.global.oauth2Token>${env.GITHUB_OAUTH_TOKEN}</github.global.oauth2Token>
`
