### ISSUE TITLE
spring boot集成apollo自定义非String类型转换器转换异常

### ISSUE THREAD

**Issue by xiangwww** [apolloconfig/apollo#4411]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

yaml配置中有某项配置的值为数字类型，而Spring加载yaml配置时会将数字类型解析为Integer类型，需要将该配置解析为自定义的枚举类型，因默认转换器不支持此类转换，因此自定义org.springframework.core.convert.converter转换器将Integer转换为自定义枚举类型，在本地环境运行正常。在使用apollo后转换异常，经定位，发现apollo在解析yaml配置时将配置的值解析为String类型，导致转换时使用的是默认的转换器，而非自定义的转换器
异常信息：
Failed to bind properties under 'xx' to xx.xx:
    Property: xx
    Value: 1
    Origin: "xx" from property source "ApolloBootstrapPropertySources"
    Reason: failed to convert java.lang.String to xx.xx

**复现**

通过如下步骤可以复现：

1.  yaml配置key : value，其中value为数字类型
2. 自定义转换器 Converter<Integer, XX>将数字转换为自定义目标类型，并注册此转换器到Spring容器中
3. 关闭apollo启动转换正常
4. 开启apollo启动转换异常

**期望**

apollo能否支持此类转换

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：apollo-client-1.5.1.jar
- 错误日志
- 配置：
- 平台和操作系统

**Comment by xiangwww** [comment]
抱歉， #2896 已提出类似问题，但该问题目前只能自行解决吗？

**Comment by nobodyiam** [comment]
自定义的 Converter 是否可以针对 String 类型处理？

**Comment by xiangwww** [comment]
是的，为了兼容不同环境，yaml中已经将数字改为字符串配置，自定义Converter源类型也改为String类型进行处理，谢谢
