### ISSUE TITLE
SpringCloud Feign加载时,熔断信息未加载,

### ISSUE THREAD

**Issue by Sunywdev** [apolloconfig/apollo#4420]
![image](https://user-images.githubusercontent.com/76762269/174085666-a84462e7-c63f-433c-8681-2f2afd0edbdd.png)
在apollo中配置了熔断配置,但是在启动时,熔断配置未加载进入,下面是区别
通过配置文件配置的:
![1655387768470](https://user-images.githubusercontent.com/76762269/174086076-7ad78307-2728-4bad-95eb-a044713ade97.png)
通过apollo加载的:
![image](https://user-images.githubusercontent.com/76762269/174086126-d0ff43de-eef8-44b4-a9f0-8f173f705263.png)

**Comment by Sunywdev** [comment]
SpringCloud版本为2020.0.3,Apollo版本为1.8.0,熔断组件resilience4j

**Comment by Sunywdev** [comment]
配置文件和apollo上配置是一样的,但是加载进去的数据是不同的

**Comment by Sunywdev** [comment]
配置文件配置
![image](https://user-images.githubusercontent.com/76762269/174086598-5ce98d81-2035-4a4d-8f15-5a650a2a64e6.png)
Apollo配置:
![image](https://user-images.githubusercontent.com/76762269/174086758-ddcf29fc-b5bc-4603-ab7f-1628f5fe9974.png)

**Comment by nobodyiam** [comment]
Have you tried [apollo.bootstrap.eagerLoad.enabled=true](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89)?

**Comment by Sunywdev** [comment]
> 你喜欢[apollo.bootstrap.eagerLoad.enabled=true](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89)吗？


Ok brother, thank you for your detailed answer,  Thanks a million

**Comment by Sunywdev** [comment]
close
