### ISSUE TITLE
求教，v2.0.1 ui中有四个环境 dev,fat,uat,pro,但配置文件改一个地方四个都显示同样的？

### ISSUE THREAD

**Issue by dotlnk-id2** [apolloconfig/apollo#4438]
- 版本：2.0.1
安文档把两个数据库刷完，对应的serverconfig表里数据进行自定义更变
源码启动顺序如下： 
1. config 8081
2. admin 8090
3. portal 8070

进入 http://127.0.0.1:8070 创建一个gateway的app
进入后左边菜单有四个可见环境 DEV,FAT,UAT,PRO
点击DEV环境对application进行添加一条apollo.env=DEV
愿希望进入FAT对application添加一条apollo.env=FAT

发现DEV环境的item也更新成FAT

**Comment by nobodyiam** [comment]
The apollo-configservice and apollo-admin service of each environment should connect to its own apolloconfigdb.
