### ISSUE TITLE
Is this judgment valid?

### ISSUE THREAD

**Issue by zhuxindong** [apolloconfig/apollo#4454]
https://github.com/apolloconfig/apollo/blob/471f59dee1b24664c9d622f6c8e457cb12631dda/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfig.java#L102

like this test case:
```java 
Config config = ConfigService.getConfig("someConfig")
while(true){
    config.addChangeListener(new ConfigChangeListner(){
    @Override
    public void onChange(ConfigChangeEvent event){
      //do something
}
}
}
```
consider override equals() methode in [apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigChangeListener.java](https://github.com/apolloconfig/apollo/blob/471f59dee1b24664c9d622f6c8e457cb12631dda/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigChangeListener.java)

**Comment by nobodyiam** [comment]
That I think is all right as they are different listeners.
