### ISSUE TITLE
初始脚本创建的apollo用户无法登录

### ISSUE THREAD

**Issue by zisongsun** [apolloconfig/apollo#4456]
使用的2.0.1版本，使用初始化的mysql脚本导入的user信息，但是使用apollo/admin无法登录。
页面报错：incorrect username or password
插入user的脚本：
INSERT INTO `Users` (`Username`, `Password`, `UserDisplayName`, `Email`, `Enabled`)
VALUES
    ('apollo', '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS', 'apollo', 'apollo@acme.com', 1);
想问一下，密码的加密方式是什么，可否关闭用户登录功能？

**Comment by nobodyiam** [comment]
The documentation is [here](https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function) and the code is [here](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java#L114).
The default spring security auth should work well with the default user data. You may check the server log to see why it failed.

**Comment by zisongsun** [comment]
> The documentation is [here](https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function) and the code is [here](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java#L114). The default spring security auth should work well with the default user data. You may check the server log to see why it failed.

ApolloPortal服务在启动完成之后，访问Url 尝试登录或者登录失败，ApolloPortal的日志无任何日志输出。。
