### ISSUE TITLE
移除client侧guava库

### ISSUE THREAD

**Issue by cjdxhjj** [apolloconfig/apollo#4457]
**Is your feature request related to a problem? Please describe.**
目前多个组件依赖了不同的版本的guava库，升级时爆出xx类不存在，之前的库无法更新升级，如zk的curator,这个和zk版本强绑定，dubbo又依赖zk,系统中很多dubbo服务，根本不可能升级

**Describe the solution you'd like**
移除guava等高频依赖
**Describe alternatives you've considered**

**Additional context**

**Comment by Shoothzj** [comment]
can you just update guava library version to latest?

**Comment by cjdxhjj** [comment]
can't startup due to the no class def found error

**Comment by Shoothzj** [comment]
@cjdxhjj could please share the detail error msg or your depnendecy tree? :)

**Comment by cjdxhjj** [comment]
[dep tree.txt](https://github.com/apolloconfig/apollo/files/9099447/dep.tree.txt)
yes

**Comment by cjdxhjj** [comment]
[error report.txt](https://github.com/apolloconfig/apollo/files/9099469/error.report.txt)
the startup error is here

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178665339-9644195f-2641-4bad-9a17-7e4a22dc1678.png)

**Comment by cjdxhjj** [comment]
因为此类问题，spring 早就淘汰使用guava,但是其它库还在大量使用，目前我这个项目里就有16，20， 29
apollo 2.0.0依赖 31.0.1这么大的版本跨度下，每次更新依赖都是如履薄冰，一不小心就启动不了

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178666190-3ca3130b-1362-44d8-b9fe-fd21c44056bf.png)

**Comment by Shoothzj** [comment]
Sorry for my late reply, I don't think spring remove guava for this reason, could you prove that? Spring update many dependencies frequently. Like bytebuddy/netty/prometheus-client.
Since you can't update guava dependency now. I suggest you shade `apollo-client` for now[1]. See https://www.jianshu.com/p/8171607ce03f

**Comment by cjdxhjj** [comment]
@Shoothzj  https://stackoverflow.com/questions/47988952/what-meant-by-support-drop-of-guava-in-spring-framework-5

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178711091-53249c18-093f-4e7a-bfb0-a1b8dedd13eb.png)

**Comment by cjdxhjj** [comment]
https://github.com/spring-attic/platform/issues/524
![image](https://user-images.githubusercontent.com/5616997/178711795-70faf3bd-eff7-4643-8af5-88f8bd260f15.png)

**Comment by cjdxhjj** [comment]
那个包的api不兼容变更很常见，发布的也比较频繁

**Comment by cjdxhjj** [comment]
我觉得客户端根本不需要guice,一共没几个类，基本也就一个实现

**Comment by Shoothzj** [comment]
community has been discussed it before. you can share your feature request on https://github.com/apolloconfig/apollo/discussions/4369
If you are in a hurry, you can manually shade apollo package yourself.

cc @nobodyiam

**Comment by cjdxhjj** [comment]
目前我是使用方（有冲突），如果要从我这个地方解决的话，我需要重新打包apollo-client以应用shade插件

**Comment by cjdxhjj** [comment]
实际上我没看到是什么配置让guava降到16
![image](https://user-images.githubusercontent.com/5616997/178891195-2c60b621-f978-44a3-9fee-e9431596d0c1.png)
![image](https://user-images.githubusercontent.com/5616997/178891225-f464c3ed-fbe7-4c47-9347-6c63c57eda22.png)

**Comment by nobodyiam** [comment]
You could declare the guava version in the `dependencyManagement` section of your project's pom.xml, e.g.

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.0.1-jre</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by cjdxhjj** [comment]
好的，我得测试一下，不过不一定能升，启动后也可能随时爆出找不到类找不到方法的问题

**Comment by cjdxhjj** [comment]
我有好几个应用，依赖复杂点的应用用不了2.0。用1.6没问题,不过不兼容jdk 17,没有add opens
