### ISSUE TITLE
原有默认的环境类型和常用的不太一样，建议默认支持test、qa类型

### ISSUE THREAD

**Issue by mashuangwei** [apolloconfig/apollo#4458]
原有默认的环境类型和常用的不太一样，建议默认支持test、qa类型

**Comment by nobodyiam** [comment]
You may specify the envs in [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8) and config the meta server addesses in [apollo.portal.meta.servers](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_312-apolloportalmetaservers-%e5%90%84%e7%8e%af%e5%a2%83meta-service%e5%88%97%e8%a1%a8).
