### ISSUE TITLE
server:   forward-headers-strategy: NATIVE不生效

### ISSUE THREAD

**Issue by cjdxhjj** [apolloconfig/apollo#4460]
使用apollo配置forward-headers-strategy一直为framework
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
如图使用apollo时，我试了在多个配置里添加那个配置，依然不生效
![image](https://user-images.githubusercontent.com/5616997/178897363-57d77858-968a-498d-9c90-4a4a04010232.png)
![image](https://user-images.githubusercontent.com/5616997/178897446-d3b40f86-a516-4373-a6fb-f34d58608463.png)
![image](https://user-images.githubusercontent.com/5616997/178897539-81100008-4718-4e71-997c-383cdaebc2c3.png)
![image](https://user-images.githubusercontent.com/5616997/178897564-9d92ba56-278f-4469-bcec-9d82f844adbe.png)
![image](https://user-images.githubusercontent.com/5616997/178897684-6bd6c204-b145-4f8b-9318-97d5a730e7d0.png)
![image](https://user-images.githubusercontent.com/5616997/178897742-ea17b933-897d-4871-8b49-992704407b98.png)
缓存 的值也是对的
这个在undertow使用时经过调试，必须为native才能将useForwardheader设置为true,从而添加上ProxyPeerAddressHandler
![image](https://user-images.githubusercontent.com/5616997/178898289-4dfa2404-edc0-49c2-a6b9-bb235221e838.png)
![image](https://user-images.githubusercontent.com/5616997/178898417-94851ed3-f3b0-4468-b6fc-b1c240986613.png)
最终能处理nginx转发的forward头部
![image](https://user-images.githubusercontent.com/5616997/178898526-e4b6805f-f227-4d4c-900c-55a799c128f2.png)
目前因为值一直为framework，无法应用相应handler,跳转时从https降级为http

![image](https://user-images.githubusercontent.com/5616997/178898905-598a9f42-ac3b-49e2-8efe-beaf9590807f.png)

![image](https://user-images.githubusercontent.com/5616997/178899478-32f0b541-f6f3-43c7-b17e-8dd535b6acf9.png)
![image](https://user-images.githubusercontent.com/5616997/178899552-f258a5ec-2352-4f11-a311-96aae1e8ac8a.png)

**Expected behavior**
使用我配置的值native,你那个framework真不知道是怎么来的？

![image](https://user-images.githubusercontent.com/5616997/178899681-de264922-5bb6-416d-988b-fff0066b3868.png)

还有个问题就是我没有应用application这个namespace,也不能删除，一直显示有几个在使用，哪怕没有一个行配置。没有application的时候显示warn
**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178900270-bbf8a3f1-0fb3-4808-bdac-23d60db742b1.png)
数量显示和列表不对应，还有就是有时候显示超过了一周了，还是不能删除？？？

**Comment by cjdxhjj** [comment]
没使用apollo时配置正常设置
![image](https://user-images.githubusercontent.com/5616997/178900957-61692954-c49b-41e4-90ef-663d8e2c7142.png)
![image](https://user-images.githubusercontent.com/5616997/178900991-2aa0c0bc-ae9b-4ff0-8ff6-d89d85ff2ed6.png)

**Comment by nobodyiam** [comment]
Have you tried [apollo.bootstrap.eagerLoad.enabled=true](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89)?

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/179127285-f432d9c9-6cc0-45da-8666-d8ecf020ab04.png)
![image](https://user-images.githubusercontent.com/5616997/179127321-1f318433-8893-4191-b0ff-cb3c55b3657b.png)
之前没有加，现在加了也还一样，我觉得这个图很说明问题
![image](https://user-images.githubusercontent.com/5616997/179127380-064b5701-3210-4cff-a234-a7b005176c99.png)

**Comment by cjdxhjj** [comment]
上面那个我仔细追查了下，是我们自己的问题，我们公共配置在public,里面配置了那个值为framework.
![image](https://user-images.githubusercontent.com/5616997/179158420-01cadacd-ca3e-41cb-9b37-cafe1b8d270f.png)
那个类的实现是只要读取到配置就返回，由于那个配置运维维护，没怎么关注，目前通知 移除那个配置后取值正常了
