### ISSUE TITLE
能否支持密钥遮盖与权限控制？

### ISSUE THREAD

**Issue by zhenzh** [apolloconfig/apollo#4469]
当开发需要调整生产配置时，往往希望只将非敏感信息对开发可见，对于密钥等敏感内容仅显示参数名而遮盖具体的参数值。
能否通过用户权限的控制实现对特定用户群展示部分可见参数值的行为？

或者能否通过特定的参数值格式令 apollo 能从外部密钥仓库（如 vault 等）请求具体密钥内容？
通过这种方式使敏感信息在 ui 上不再以明问显示，仅当应用通过接口请求参数时才去密钥仓库获取实际密钥返回给应用。

**Comment by wxlevel** [comment]
查看权限的管控还是有必要的

**Comment by mghio** [comment]
see https://github.com/apolloconfig/apollo/issues/3187

**Comment by nobodyiam** [comment]
对 private namespace，apollo 已经支持[配置查看权限](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90)了。

**Comment by Jxiu** [comment]
> 对 private namespace，apollo 已经支持[配置查看权限](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90)了。

为啥不对共享namespace支持只有key共享，value使用掩码呢？我们目前就是用这个方案对生产环境的共享的vlue掩码

**Comment by nobodyiam** [comment]
公共 namespace 使用掩码只能解决页面查看权限的问题，用户通过 config service 的接口依然能访问到配置的值，所以考虑不做掩码的支持

**Comment by zhenzh** [comment]
> > 对 private namespace，apollo 已经支持[配置查看权限](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90)了。
> 
> 为啥不对共享namespace支持只有key共享，value使用掩码呢？我们目前就是用这个方案对生产环境的共享的vlue掩码

我也比较赞同这种策略。考虑到生产环境的安全控制会相对严格，访问ui的权限和访问config service的权限是可以做到隔离的。
因此实现value层面的掩码是存在实用价值的。
