### ISSUE TITLE
apollo三个应用的数据库密码配置支持加密吗？怎么配置？

### ISSUE THREAD

**Issue by hellotyty** [apolloconfig/apollo#4476]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

apollo三个模块configservice、adminservice和portalservice中都涉及到数据库的连接信息配置，请问数据库密码配置支持加密吗？怎么配置？

**复现**

使用疑问，无需复现

**期望**

生产环境需要支持数据库密码加密

**截图**

无需截图

### 额外的细节和日志

- 版本：1.5.1
- 错误日志
- 配置：官方release包，docker yml中配置数据库连接信息
- 平台和操作系统 linux

**Comment by mghio** [comment]
构造出 DataSource 出来即可，参考 [TitanEntityManager](https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/datasource/TitanEntityManager.java)

**Comment by mghio** [comment]
In the scenario of Apollo's own database connection information encryption, if there is a unified mechanism, it would be better if there is no need to modify the open source code and release package. @nobodyiam

**Comment by nobodyiam** [comment]
@mghio This is a good point! We may embed [Jasypt](https://medium.com/@javatechie/spring-boot-password-encryption-using-jasypt-e92eed7343ab) to achieve this.

**Comment by hellotyty** [comment]
> 构造出 DataSource 出来即可，参考 [TitanEntityManager](https://github.com/apolloconfig/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/datasource/TitanEntityManager.java)

1.5.1版本我在common模块引入jasypt-spring-boot 2.1.2版本，环境变量配置jasypt.encryptor.password即可。
