### ISSUE TITLE
homepageUrl里包含localhost.localdomain，导致客户端侧无法获取配置

### ISSUE THREAD

**Issue by liutao5121** [apolloconfig/apollo#4477]
apollo部署版本：2.0.1
zookeeper服务端版本：3.6.3

当apollo3个模块都部署好之后，访问configservice的接口，http://10.1.62.146:8080   （默认8080是configservice模块的端口）
![image](https://user-images.githubusercontent.com/4645306/180164199-b24483a4-c944-4e2a-a26d-cf2476b64685.png)

结果我在客户端，请求获取配置时日志输出：
![image](https://user-images.githubusercontent.com/4645306/180164535-8e50477e-be84-497e-a705-294f9fc377b4.png)

显然最终我无法获取远程配置信息，我该如何解决呢？

**Comment by nobodyiam** [comment]
You may visit the system information to get more information.
BTW, are you using zookeeper as the service registry? This [doc](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_14-%e7%bd%91%e7%bb%9c%e7%ad%96%e7%95%a5) may be helpful for you.

![image](https://user-images.githubusercontent.com/837658/180627741-eb989cab-626a-462c-926a-b64eb615961e.png)
