### ISSUE TITLE
Wiki FAQ may use ctrip site return 404

### ISSUE THREAD

**Issue by qixiaobo** [apolloconfig/apollo#4481]
**描述bug**

Wiki use ctrip doc that return 404 
https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide
It maybe https://www.apolloconfig.com/#/zh/usage/apollo-user-guide

**复现**

https://github.com/apolloconfig/apollo/wiki/FAQ
![image](https://user-images.githubusercontent.com/2881751/180611157-694ce31b-a329-415c-8134-414475d20a3a.png)

**Comment by nobodyiam** [comment]
Thanks, it's solved now.
