### ISSUE TITLE
文本模式修改如果有key删除，会导致除被删除的key之外的所有key的最后修改时间变化

### ISSUE THREAD

**Issue by coolbreeze2** [apolloconfig/apollo#4482]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

文本模式修改如果有key删除（非底部key），会导致除被删除的key之外的所有key的最后修改时间变化

**复现**

通过如下步骤可以复现：

文本模式随意删除一个key（非底部key），导致除被删除的key之外的所有key的最后修改时间变化

**期望**

文本模式删除key，应该只有被删除的key最后修改时间变化

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by mghio** [comment]
Yes, now the configuration item (key) will be updated if one of the conditions is met (this scenario meets the second condition):

1. Updated the value of the same key (e.g. before  the timeout config value is 100, after update to 200).

2. Updated the line number of the configuration (e.g. removed non-bottom keys).

BTW, can we remove the second condition for update? @nobodyiam

**Comment by nobodyiam** [comment]
This is the current behavior in text mode. However, if it's only the line number that is changed, I think it's reasonable not to update the last modified time.

**Comment by coolbreeze2** [comment]
Not stale
