### ISSUE TITLE
Update item will set DeletedAt timestamp

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#4492]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
After the item is updated, the item's DeletedAt field will be set.

**To Reproduce**
1. Add a new configuration item - `a=1`, the data in `Item` table is:

| Key | Value | IsDeleted | DeletedAt |
|-----|------|-----------|-----------|
| Item | 1       | 0               | 0               |

2. Update the value to 2, the data in `Item` table is:

| Key | Value | IsDeleted | DeletedAt |
|-----|------|-----------|-----------|
| Item | 2       | 0               | 1659181295058 |

**Expected behavior**

The DeletedAt field should be 0 if IsDeleted is 0. 

### Additional Details & Logs

- Version: 2.0.1

**Comment by nisiyong** [comment]
Why updating items will trigger `com.ctrip.framework.apollo.common.entity.BaseEntity#setDeleted` ?

**Comment by nobodyiam** [comment]
It's because of the statement - `BeanUtils.copyEntityProperties(item, managedItem);`.

https://github.com/apolloconfig/apollo/blob/63c16c117a869426f2cbbfdaa099de449789fd18/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/ItemService.java#L186-L197
