### ISSUE TITLE
[oidc] user display names are all `default` when use google openid connect 

### ISSUE THREAD

**Issue by krin-wang** [apolloconfig/apollo#4498]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
oidc PreferredUsername is null when use google openid connect. I'd suggest fallback to FullName, when PreferredUsername is empty.

**To Reproduce**
1. use google openid connect as oidc provider.
2. login and check user display name
3. all display names are `default`

**Expected behavior**
I'd like there is a valid user display name.

**Screenshots**
<img width="1773" alt="Screen Shot 2022-08-03 at 2 24 37 PM" src="https://user-images.githubusercontent.com/65522803/182538708-59252759-3ecb-4086-8905-c352bf0f5ddf.png">

**Comment by krin-wang** [comment]
Based on https://github.com/apolloconfig/apollo/issues/3795, we're using `PreferredUsername` as display name. Could we fallback to `FullName` when `PreferredUsername` is empty?

I did a few changes in local and tested.

apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/oidc/OidcAuthenticationSuccessEventListener.java
```
     newUserInfo.setName(oidcUser.getPreferredUsername());
+    if (!StringUtils.hasText(newUserInfo.getName())) {
+      newUserInfo.setName(oidcUser.getFullName());
+    }
     newUserInfo.setEmail(oidcUser.getEmail());
```

apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/oidc/OidcUserInfoHolder.java
```
       OidcUser oidcUser = (OidcUser) principal;
       userInfo.setUserId(oidcUser.getSubject());
       userInfo.setName(oidcUser.getPreferredUsername());
+      if (!StringUtils.hasText(userInfo.getName())) {
+        userInfo.setName(oidcUser.getFullName());
+      }
       userInfo.setEmail(oidcUser.getEmail());
       return userInfo;
```

**Comment by nobodyiam** [comment]
I think it's reasonable, @vdisk-group what do you think?
