### ISSUE TITLE
portal配置自动还原

### ISSUE THREAD

**Issue by jiangxiaoqiang** [apolloconfig/apollo#4501]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

由于kubernetes证书过期，更新kubernetes证书后重启了主机，发现apollo portal无法访问（之前已经正常使用了一年多），跟踪日志是发现portal无法链接数据库，查看apollo portal configMap数据库的配置如下：

```
spring.datasource.url = jdbc:mysql://apollo-portal-apollo-portaldb:3306/ApolloPortalDB?characterEncoding=utf8
spring.datasource.username = root
spring.datasource.password = uu3E2322VhcU4
apollo.portal.envs = dev,pro
```

我的mysql数据库路径是类似这样的：

`spring.datasource.url = jdbc:mysql://apollo-mysql-0.apollo-mysql.reddwarf-storage.svc.cluster.local:3306/ApolloConfigDB-DEV?characterEncoding=utf8`

问题：

为什么configMap的数据库路径感觉像是回到了初始设置？ 没有调整过portal的configMap的数据库链接。为什么以前的portal使用正常？现在数据库连接异常？哪里会出发portal configMap自动改变？思考了很久，没有想出那种场景下会出现这样的情况。

**复现**

通过如下步骤可以复现：

1. 重启主机
2. 再次访问apollo portal

**期望**

重启主机后，在不做任何配置调整的前提下可以正常访问apollo portal。

### 额外的细节和日志

- 版本：apolloconfig/apollo-portal:1.8.2
- 错误日志
- 配置：
- 平台和操作系统 kubernetes 1.21

**Comment by nobodyiam** [comment]
apollo portal only reads from the properties, so the config map must be updated by other systems or users.
