### ISSUE TITLE
非properties类型的公共namespace，继承覆盖问题

### ISSUE THREAD

**Issue by chenqiweilove** [apolloconfig/apollo#4508]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
k8s 版本 v1.22.5
apollo 版本 2.0.0
继承非properties类型的公共namespace，修改值。如果在想还原回去要怎么做。

比如：
有个json公共类型a, 值为{"a": 1}
B应用继承a，什么都不修改，获取的值是{"a": 1}
如果B修改继a的值为{"a": 2}, 获取的值是{"a": 2}
现在如果想要获取最开始{"a": 1}这个值，我删除{"a": 2}清空后，获取的值是空，只能把{"a": 2}修改为{"a": 1}。
有什么方式可以让我清空继承的namespace的值后，获取是最初的值

**Comment by mghio** [comment]
In Apollo's design, configuration Item are the smallest granularity unit under the namespace. There are five types: `properties` `yml` `yaml` `json` `xml` `txt`.
- properties : each row of configuration corresponds to an Item record.
- the latter five(`yml` `yaml` `json` `xml` `txt`): cannot be split, so a namespace corresponds to **only one Item record**.

Therefore, except for the properties type, the five types do not support single property coverage, only the overall coverage.

see [ItemService](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java#L104-L105).

**Comment by nobodyiam** [comment]
@chenqiweilove mghio explains the design behind this issue. I think you could delete the linked namespace in B to use the configuration from A.

**Comment by chenqiweilove** [comment]
了解了，谢谢。
