### ISSUE TITLE
yaml配置格式错误，导致获取到空配置

### ISSUE THREAD

**Issue by gp0014** [apolloconfig/apollo#4510]
**描述bug**

使用apollo配置yaml，如果yaml格式错误，比如缩进有问题。导致应用程序启动时拉取到空的配置。

**复现**

通过如下步骤可以复现：

1.  配置有格式错误的yaml
2. 拉取配置内容

**期望**

将异常抛出给应用程序，由应用程序自己处理。

**Comment by nobodyiam** [comment]
There is a syntax check button for yaml namespace, and it will show the error if the configuration is invalid.

![image](https://user-images.githubusercontent.com/837658/184469604-02bd6f2b-81dc-473d-a4e2-a23d0de5e012.png)

![image](https://user-images.githubusercontent.com/837658/184469616-0c7fb6f8-c5c4-4226-8e11-28cc6ba8c06c.png)

**Comment by nobodyiam** [comment]
@gp0014 You may use the ConfigFile interface to retrieve and transform the yaml configurations.

```java
  ConfigFile config = ConfigService.getConfigFile("application", ConfigFileFormat.YAML);
  String content = config.getContent();
  // do your own transform logic
```

**Comment by gp0014** [comment]
Thanks for your reply.

That's could obtain original content as expected. The problem is converting yaml to properties when construction YamlConfigFile object, because of parsing error, an empty object will be created without any exception throwing.

**Comment by nobodyiam** [comment]
@gp0014 You may obtain the original content and transform it to properties by yourself, in which case, you could catch the parse exception.
