### ISSUE TITLE
Apollo老版本下线

### ISSUE THREAD

**Issue by wg1993** [apolloconfig/apollo#4512]
公司部署了很多版本的Apollo，目前需要排查下线，有什么比较好的方法能排查出有哪些应用在实际使用呢？ConfigService有记录有哪些正在连接的Client？

**Comment by klboke** [comment]
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/18591662/184327139-48883fb2-3d06-468f-9c1b-6cc1013881b5.png">
这里有 24小时内的实例信息，对应 ConfigDB 里的 `Instance` 、`InstanceConfig` 表

**Comment by wg1993** [comment]
感谢

> <img alt="image" width="1547" src="https://user-images.githubusercontent.com/18591662/184327139-48883fb2-3d06-468f-9c1b-6cc1013881b5.png">
> 
> 这里有 24小时内的实例信息，对应 ConfigDB 里的 `Instance` 、`InstanceConfig` 表
