### ISSUE TITLE
Configuration fetch time error in Apollo UI instance list

### ISSUE THREAD

**Issue by klboke** [apolloconfig/apollo#4513]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

- Configuration fetch time error in Apollo UI instance list, The currently displayed releaseDeliveryTime

**To Reproduce**

1. Create the app, publish the configuration
2. Pull the configuration
3. Observation panel configuration fetch time
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/18591662/184317990-4da7d419-9e1c-4ea7-a536-21a0ad71489d.png">

**Expected behavior**

Should show when the configuration was pulled instead of when it was published, Or here we can keep the release time and the configuration fetch time

### Additional Details & Logs

- Version: 2.0.1

**Comment by nobodyiam** [comment]
I believe this field does show the configuration fetched time...

e.g. You may retrieve the demo configuration via http://106.54.227.205:8080/configs/100004458/default/application and see te instance list in http://106.54.227.205/config.html?#/appid=100004458

![image](https://user-images.githubusercontent.com/837658/184469514-14250e82-187d-465a-9adc-3801d9ef06bb.png)

**Comment by klboke** [comment]
> e.g. You may retrieve the demo configuration via http://106.54.227.205:8080/configs/100004458/default/application and see the instances list in http://106.54.227.205/config.html?#/appid=100004458

- There is a problem with this test, when instance A already exists in the database, instance A fetches the configuration again, and the configuration fetch time will not be updated.
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/18591662/184567612-ed6eace2-1dad-43fa-99a3-720139db542c.png">

**Comment by nobodyiam** [comment]
> There is a problem with this test, when instance A already exists in the database, instance A fetches the configuration again, and the configuration fetch time will not be updated.

This I think is by design, see line 112.

https://github.com/apolloconfig/apollo/blob/b1f78b4cc708b6a1cdd68fb6dccf0d77471a805e/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java#L107-L122

**Comment by klboke** [comment]
```java
 private static final long OFFER_TIME_LAST_MODIFIED_TIME_THRESHOLD_IN_MILLI = TimeUnit.MINUTES.toMillis(10);//10 minutes
 ```

- Configuration fetches within ten minutes do not update the configuration fetch time. This can explain the second record below, but the configuration fetch time of the first record is actually not easy to explain

![image](https://user-images.githubusercontent.com/18591662/184860451-dc637df6-5ef4-4096-a94d-209953d730bc.png)

- Another example

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/18591662/184862061-d22c1b1a-b02a-4fd2-8767-800a10ec4d2b.png">

**Comment by nobodyiam** [comment]
This is because of the following logic, which is to reduce the database burden to write the records.

https://github.com/apolloconfig/apollo/blob/b1f78b4cc708b6a1cdd68fb6dccf0d77471a805e/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java#L72-L73

https://github.com/apolloconfig/apollo/blob/b1f78b4cc708b6a1cdd68fb6dccf0d77471a805e/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java#L91-L99

**Comment by klboke** [comment]
I have a few points

- Can the memory cache expiration time be adjusted to be shorter, say 5 minutes? Because the following logic is not too complicated and will not cause any major load problems, right?
- move `instanceConfig.setReleaseDeliveryTime(auditModel.getOfferTime());` to the following would it be better

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/18591662/185539970-760ed1a5-b0db-46d4-bc04-5d8d3a247260.png">

**Comment by nobodyiam** [comment]
> Can the memory cache expiration time be adjusted to be shorter, say 5 minutes? 

I think we can make this expiration time a configurable item. The original idea is to reduce the database write burden considering there are tens of thousands of instances.

> move instanceConfig.setReleaseDeliveryTime(auditModel.getOfferTime()); to the following would it be better

I believe it's not correct to move this line down, as the release delivery time means the time when this instance first retrieves the config, not the last retrieve time.

**Comment by klboke** [comment]
> I think we can make this expiration time a configurable item. The original idea is to reduce the database write burden considering there are tens of thousands of instances.

yes i think so too

> I believe it's not correct to move this line down, as the release delivery time means the time when this instance first retrieves the config, not the last retrieve time.

So, back to my question at the beginning. Is it incorrect to use releaseDeliveryTime for configuration acquisition time?
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/18591662/185798726-a4a974d3-32ca-44b9-8d81-a2672d9f33e1.png">

**Comment by nobodyiam** [comment]
I still think ReleaseDeliveryTime is better as it's the first time the instance fetches the configuration.
However, I'm interested in why you think it's incorrect. Would you please help to describe the actual scenario?

**Comment by klboke** [comment]
Because of the logic discussed earlier, when a configuration is not re-released. ReleaseDeliveryTime is not updated no matter how many times the configuration has been fetched and when it was fetched, which results in seeing unintuitive configuration fetch times on the UI.

**Comment by nobodyiam** [comment]
ReleaseDeliveryTime is the time when the instance first fetches the configuration. I understand what you want to show is the last fetch time instead of the first fetch time, or show them both?
The first fetch time(ReleaseDeliveryTime) is important as it shows the user when the configuration is effective on the application side.
The last fetch time is also important as it indicates the instance's heartbeat time. However, as I mentioned before, to ease the database write burden, the last modified time will not be updated to the database each time the instance fetches the configuration. It will be updated to the database only when the instanceConfigReleaseKeyCache times out(which may take up to 24 hours). So there is no accurate last fetch time to display, which is why it's not shown in the UI.
I'm not sure how important the last fetch time is, but we need to figure out a solution to display the correct last fetch time if we do want to show it in the UI.

**Comment by klboke** [comment]
> ReleaseDeliveryTime is the time when the instance first fetches the configuration

If so, I understand why it is currently designed this way

- However, most people are still confused by the '配置获取时间', or will we have a more meaningful field description?

**Comment by nobodyiam** [comment]
> However, most people are still confused by the '配置获取时间', or will we have a more meaningful field description?

Yes, I'm open to a more meaningful label.

**Comment by klboke** [comment]
Did not think of a suitable name。Would a '配置生效时间' be more appropriate?

**Comment by nobodyiam** [comment]
> Would a '配置生效时间' be more appropriate?

I think this label is OK.
