### ISSUE TITLE
apolloportaldb 库里面的数据不小心被删除了怎么恢复权限？

### ISSUE THREAD

**Issue by zhuhedong** [apolloconfig/apollo#4516]
apolloportaldb 库里面的数据不小心被删除了怎么恢复权限？

**Comment by mghio** [comment]
I think it's a database data recovery issue. In general, Apollo's permission model is divided into five tables in the ApolloPortalDB database: Users + UserRole + Role + RolePermission + Permission, and the relationship is shown in the following figure:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/43461943/184544502-0b84f942-ca85-4be6-adf8-a61d51557734.png">
