### ISSUE TITLE
apollo支持mysql 8版本吗？ 两套接口，两套数据库做双主，从两边同时写入intance表会报instance.IX_UNIQUE_KEY 冲突

### ISSUE THREAD

**Issue by zhang7410852963** [apolloconfig/apollo#4520]
apollo支持mysql 8版本吗？ 两套接口，两套数据库做双主，从两边同时写入intance表会报instance.IX_UNIQUE_KEY 冲突

**Comment by nobodyiam** [comment]
* apollo 支持 mysql 8
* 从两边同时写入intance表会报instance.IX_UNIQUE_KEY 冲突，这个是两天数据重复了吧
  * UNIQUE KEY `IX_UNIQUE_KEY` (`AppId`,`ClusterName`,`Ip`,`DataCenter`)

**Comment by zhang7410852963** [comment]
是的，是跟eureka.service.url有关吗？ 我是把所有的机器都写进去了。  还是说2套Apollo 用不同的数据库， 并且这两个数据库做双主，数据互相同步不行？

**Comment by nobodyiam** [comment]
一个环境用一套数据库即可，如果是高可用考虑可以是主备
