### ISSUE TITLE
@ApolloJsonValue 无法获取到 LocalDate 类型的值

### ISSUE THREAD

**Issue by doveylovey** [apolloconfig/apollo#4522]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
在实体类中使用 LocalDate 时，无法获取到配置中心的值

**复现**
可以根据官方文档的描述，修改下字段类型即可：
![image](https://user-images.githubusercontent.com/28882195/184780917-6aa05f19-adf5-4a45-97fb-9497913416e9.png)

通过如下步骤可以复现：
1.  在配置中心一个 jsonBeanProperty = [{"userId":1, "username":"沉鱼", "birthday":"2022-08-08", "salary":200}, {"userId":2, "username":"落雁", "birthday":"2022-08-08", "salary":200}, {"userId":3, "username":"闭月", "birthday":"2022-08-08", "salary":200}, {"userId":4, "username":"羞花", "birthday":"2022-08-08", "salary":200}] 的配置
2. 在代码中使用 @ApolloJsonValue("${jsonBeanProperty:[]}") 获取值

**期望**
程序应该能够正常启动，并获取到对应值

**截图**
![image](https://user-images.githubusercontent.com/28882195/184780717-20469f28-90c2-4a99-b076-44cabd80db74.png)

### 额外的细节和日志
- 版本：2.0.1
- 错误日志：
Parsing json '[{"userId":1, "username":"沉鱼", "birthday":"2022-08-08", "salary":200}, {"userId":2, "username":"落雁", "birthday":"2022-08-08", "salary":200}, {"userId":3, "username":"闭月", "birthday":"2022-08-08", "salary":200}, {"userId":4, "username":"羞花", "birthday":"2022-08-08", "salary":200}]' to type java.util.List<com.study.apollo.config.TestApolloAnnotationBean$SysUser> failed!
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 44

- 配置：
- 平台和操作系统

**Comment by mghio** [comment]
The `LocalDate` class contains three fields (`year`, `month` and `day`). You need to change the value of birthday in the configuration to an object containing these three properties.

Change to : `[{"userId":1, "username":"沉鱼", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":2, "username":"落雁", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":3, "username":"闭月", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":4, "username":"羞花", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}]`.

**Comment by Dr-wgy** [comment]
> The `LocalDate` class contains three fields (`year`, `month` and `day`). You need to change the value of birthday in the configuration to an object containing these three properties.
> 
> Change to : `[{"userId":1, "username":"沉鱼", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":2, "username":"落雁", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":3, "username":"闭月", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}, {"userId":4, "username":"羞花", "birthday":{"year":2022,"month":08,"day":08}, "salary":200}]`.

In jdk 17 if we use the following code 
 @ApolloJsonValue (${})
Map<Long.LocalTime>  xxx;
we encounter exception like this `Initialization of bean failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte java.time.LocalTime.hour accessible: module java.base does not "opens java.time" to unnamed module @6b06aa9b`
