### ISSUE TITLE
Apollo SPI扩展机制

### ISSUE THREAD

**Issue by wg1993** [apolloconfig/apollo#4523]
我想使用自己公司的监控方案，通过SPI机制进行扩展。
<img width="946" alt="image" src="https://user-images.githubusercontent.com/20056551/184808567-d0c423be-3cde-4e53-87c2-562f1f98d8cf.png">
其他人引用jar可以替换原先默认的DefaultMessageProducerManager，但是Apollo加载的总是第一个类。这个有什么方法解决吗？因为我也不想使用方自己在项目resources里面添加com.ctrip.framework.apollo.tracer.spi.MessageProducerManager
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/20056551/184808847-06ac60c3-f170-412d-9196-1fe2ebbff101.png">

**Comment by mghio** [comment]
I think you can use `ServiceBootstrap.loadAll(Class<S> clazz)` and then filter your custom implementation class. 

see [ServiceBootstrap#loadAll](https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/ServiceBootstrap.java#L38-L42)

**Comment by wg1993** [comment]
> I think you can use `ServiceBootstrap.loadAll(Class<S> clazz)` and then filter your custom implementation class.
> 
> see [ServiceBootstrap#loadAll](https://github.com/apolloconfig/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/ServiceBootstrap.java#L38-L42)

Thanks,I konw the answer.
