### ISSUE TITLE
平滑支持https

### ISSUE THREAD

**Issue by cl0912** [apolloconfig/apollo#4525]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

服务部署时使用http地址如下，线上已经有业务开始使用，如何配置可以在不影响线上业务的情况下，平滑支持https访问。
portal服务： http://portal.xxx.com:8070
dev环境：http://dev.xxx.com:8080
uat环境：http://uat.xxx.com:8080
pro环境：http://pro.xxx.com:8080

**Comment by mghio** [comment]
I think this is a problem of upgrading https. You can switch DNS resolution to other servers where Apollo is deployed, and then switch back after these services are upgraded to support https.
