### ISSUE TITLE
properties格式的namespace下，如果value是一个存在重名key的map，点击查看数据会不准

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4527]
properties格式的namespace下，如果value是一个存在重名key的map，点击查看数据会不准

![image](https://user-images.githubusercontent.com/9474302/185341931-18d73e40-0820-423b-b3a0-f1658cbf3565.png)

**Comment by mghio** [comment]
When viewing JSON, the same key will use the later value to overwrite the previous value. What is the scenario of using a map with the same key?

**Comment by hezhaoye** [comment]
这个是用户写错了，不过这样自动修改了用户原始的数据，感觉不合理

**Comment by mghio** [comment]
Only the front-end view of the JSON component display is automatically covered, and the final value stored in the database will not be modified. The value obtained by the application of Apollo is still `{"aa":"bb","cc" :"dd" , "aa" : "zz"}`.

**Comment by hezhaoye** [comment]
是的，不过展示内容容易误导人。
