### ISSUE TITLE
目前apollo有办法把CAT的监控数据导入到grafana吗

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4528]
目前apollo有办法把CAT的监控数据导入到grafana吗

**Comment by mghio** [comment]
I don't think it is Apollo's responsibility to `import CAT monitoring data into grafana`. You can go to the [Cat community](https://github.com/dianping/cat/issues) and ask if it supports to integrate with grafana?

In addition, the following links hope to be useful for you:
- [Cat支持接入grafana么？](https://github.com/dianping/cat/issues/1795)
- [CAT可以和Grafana集成吗？](https://github.com/dianping/cat/issues/1066)
- [Export and import](https://grafana.com/docs/grafana/latest/dashboards/export-import/)

**Comment by nobodyiam** [comment]
btw, apollo has [prometheus support](https://www.apolloconfig.com/#/zh/design/apollo-design?id=_52-metrics), hope it helps.
