### ISSUE TITLE
是否支持灰度发布删除已有配置

### ISSUE THREAD

**Issue by whl12345** [apolloconfig/apollo#4539]
目前看起来灰度发布功能，只能进行新配置添加，和原有配置修改，没法把删除配置的过程用灰度发布来实现

**Comment by whl12345** [comment]
<img width="1429" alt="配置中心灰度发布" src="https://user-images.githubusercontent.com/36367435/187160389-5959ddb2-13cc-4a8c-ade3-20bd21463762.png">


我想要将删除主版本某个key的操作实现灰度发布

**Comment by nobodyiam** [comment]
It's not supported officially. However, there is an [Open API](https://github.com/apolloconfig/apollo/blob/150fe19c4a3035e79cae552cb72c701367f2a2db/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ReleaseController.java#L144) for it.
