### ISSUE TITLE
@ConditionalOnProperty( prefix = "yl.dynamic.datasource",name= "name",havingValue = "mysql") 无法读取Apollo配置

### ISSUE THREAD

**Issue by 2lusy** [apolloconfig/apollo#4540]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

@Configuration
@MapperScan({"com.yl.oauth.api.mysqlmapper", "com.yl.mq.mapper"})
@ConditionalOnProperty( prefix = "yl.dynamic.datasource",name= "name",havingValue = "mysql")
public class MysqlMapperScanConfig {
}

@ConditionalOnProperty 加载的时机没有拿到Apollo配置中心的配置。启动参数，和application.yml 里的配置是可以拿到的

**期望**
希望在启动的时候@ConditionalOnProperty配置可以拿到在环境里拿到Apollo的配置

**Comment by nobodyiam** [comment]
Please use [eagerLoad mode](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_3213-spring-boot%e9%9b%86%e6%88%90%e6%96%b9%e5%bc%8f%ef%bc%88%e6%8e%a8%e8%8d%90%ef%bc%89) - `apollo.bootstrap.eagerLoad.enabled=true`

**Comment by 2lusy** [comment]
已解决
