### ISSUE TITLE
ReleaseHistory表发现SQL没走索引，导致全表查询

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4544]
ReleaseHistoryRepository类中的方法
Page<ReleaseHistory> findByPreviousReleaseIdAndOperationOrderByIdDesc(long previousReleaseId, int operation, Pageable pageable);
没有走索引，导致全表查询，产生慢查询

**Comment by mghio** [comment]
This method is only used when rolling back the release on portal, and the frequency of use is not high. I think it is not necessary to add an index.

see [ReleaseController](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ReleaseController.java#L200-L208).

**Comment by hezhaoye** [comment]
目前ReleaseHistory数据量比较大，上线几年了，数据量大概几亿条，这种全表查询可能会引起DB的不稳定，是否可以在这2个字段PreviousReleaseId 和Operation上增加索引会好点呢

**Comment by nobodyiam** [comment]
I think it's ok to add an index for `previousReleaseId`. I suppose it's not necessary to include the `Operation` field as there won't be many records for one `previousReleaseId`.
