### ISSUE TITLE
properties类型文件，在自定义监听器ConfigChangeListener#onChange中调用ConfigFile.getContent获取的内容是上一次修改的旧值

### ISSUE THREAD

**Issue by yanhom1314** [apolloconfig/apollo#4545]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

properties类型文件，在自定义监听器ConfigChangeListener#onChange中调用ConfigFile.getContent获取的内容是上一次修改的旧值。
调试源码发现顺序是先调用监听器ConfigChangeListener#onChange，然后在调用AbstractConfigFile#onRepositoryChange来实现newProperties的赋值，所以会有这个问题，如果顺序调转下就没问题了，不清楚apollo就是这样设计的还是bug

**复现**

通过如下步骤可以复现：

1. 自定义监听器实现ConfigChangeListener接口
2. 配置properties类型配置文件
3. 多次更改配置项值，在onChange方法中通过ConfigFile#getContent获取到的是上一次的值，不是最新的

**期望**

获取到最新的值

**截图**

![image](https://user-images.githubusercontent.com/13051908/187819393-189a45f5-e225-4c89-b62d-73de1a09fbcc.png)

### 额外的细节和日志

- 版本：1.9.1
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
ConfigFile 需要通过 ConfigFileChangeEvent 来获取更新事件。

**Comment by yanhom1314** [comment]
了解了，感谢大佬
