### ISSUE TITLE
apollo portal 可以同时支持多种登录方式吗?

### ISSUE THREAD

**Issue by 4meepo** [apolloconfig/apollo#4548]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

安装方式 : helm
helm 版本: 0.5.1
apollo 版本: 2.0.1

今天把公司的apollo 接入了OIDC 单点登录，然后访问portal的时候**直接就跳转**到 第三方登录页进行授权了, 没有办法再通过原来的用户名和密码登录了。 这样新用户登录之后就没有原来的各种权限了, 有办法可以同时支持 用户名/密码 和 OIDC 单点登录嘛? 

我已知的变通方式就是数据库修改 超级管理员账号，然后重新赋权。

**复现**

**期望**

同时支持原来的用户名/密码登录 和新的 OIDC 单点登录.

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
I think you could export the apollo users from `ApolloPortalDB.Users` and import them into OIDC. The password might be an issue but I suppose the OIDC system should have some mechanism to let the user reset the passwords.

**Comment by Jxiu** [comment]
我们公司曾经使用过LADP和账户/密码同时登录（两个portal），但是会有问题两种用户的权限校验方式互通，每一种只能在自己的范围做事情，比如ldap无法给账户登录用户添加权限
@4meepo
