### ISSUE TITLE
想请问下：com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor#beanName2SpringValueDefinitions有什么用？什么时候会用到？

### ISSUE THREAD

**Issue by DeBruyne2020** [apolloconfig/apollo#4554]
想请问下，源码里面，在com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor#processPropertyValues这个方法里维护了一个叫beanName2SpringValueDefinitions的map,  如下图：
![image](https://user-images.githubusercontent.com/68886035/188593365-769146f8-57c4-407b-bdf4-f18da2cd5e27.png)

想问下大佬，什么时候用到这个map? 主要调试源码调试了半天，发现@Value注解的属性都是存到SpringValueRegistry里registry里，如下图：
![image](https://user-images.githubusercontent.com/68886035/188593137-4c571bd9-9668-413d-827c-ab48402c0c02.png)，

所以实在没明白什么时候用到前面那个beanName2SpringValueDefinitions？

在维护这个beanName2SpringValueDefinitions的入口方法里，看到这么一段注释，如下图
![image](https://user-images.githubusercontent.com/68886035/188593652-4422f68f-bd57-4f6e-be29-932f0a5acb89.png)
，但是，还是没有太get到是为什么， 求大佬指点下~

- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
You may add breakpoints to the lines that reference `beanName2SpringValueDefinitions` and debug `com.ctrip.framework.apollo.spring.XmlConfigPlaceholderTest` and `com.ctrip.framework.apollo.spring.JavaConfigPlaceholderTest`.

**Comment by DeBruyne2020** [comment]
> You may add breakpoints to the lines that reference `beanName2SpringValueDefinitions` and debug `com.ctrip.framework.apollo.spring.XmlConfigPlaceholderTest` and `com.ctrip.framework.apollo.spring.JavaConfigPlaceholderTest`.

@nobodyiam 
大佬您好，请问是触发这两个类里的具体哪个测试方法能复现到这种使用到com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor#beanName2SpringValueDefinitions的情况？


XmlConfigPlaceholderTest里的方法 ：

![image](https://user-images.githubusercontent.com/68886035/188783035-10b77138-5056-48db-b0d5-becde4f0670e.png)

JavaConfigPlaceholderTest里的方法：
![image](https://user-images.githubusercontent.com/68886035/188783115-13387384-8ec4-4cda-ae76-aed028ccc7a0.png)

**Comment by nobodyiam** [comment]
Simply run any of the test should trigger the breakpoints.
