### ISSUE TITLE
Apollo 1.9.1无法修改配置，提示“您的登录信息已过期，请刷新页面后重试”

### ISSUE THREAD

**Issue by ljmict** [apolloconfig/apollo#4555]
我的环境是K8S

![图片](https://user-images.githubusercontent.com/26455502/189024740-be0cf8c1-ede1-4d8e-994b-7cd2d6f3aaed.png)

刷新页面，退出重新登录，清理缓存换浏览器都试过了，还是无法解决。

发现把其中某一行删除可以正常进行修改
```properties
spring.datasource.url = jdbc:mysql://192.168.1.111:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
```
但是这一行也没有特别字符，删除之后，再添加这一行也无法正常添加，于是通过改数据库ApolloConfigDB Item表中IsDeleted字段改回0恢复，然后再添加配置还是会提示“您的登录信息已过期，请刷新页面后重试”

**Comment by ljmict** [comment]
发现新建一个命名空间，也无法添加这一行

**Comment by nobodyiam** [comment]
I think it's related to the user session instead of the config item, please refer https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-session-store to enable session sharing.

**Comment by Moon-giaogiao** [comment]
我也遇到这样的问题，修改了portal的默认session也无法添加

**Comment by wen1949** [comment]
我解决了，挨千刀的，是信息安全部门的拦截了，让安全部门的将自己主机的ip添加白名单解决，他们拦截了部分操作。
