### ISSUE TITLE
WatchKeys相关疑问

### ISSUE THREAD

**Issue by wg1993** [apolloconfig/apollo#4558]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/20056551/189084510-584705ad-6668-4289-8db3-3b6e2f070a6c.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20056551/189084150-6b311eea-066e-4819-9b42-ecb7940d38f8.png">
Client端启动的时候，会像NotificationControllerV2发起长轮询，如图所示，总是会watch自己应用所设置的集群和default集群，也就是default配置变动的时候也会通知对应的Client端，但是Client端发起请求拉取配置的时候却不会拉取default的配置，这么做的原因是什么呢？

**Comment by nobodyiam** [comment]
client 实际生效的配置会按照优先级查找多个集群，在订阅的时候不感知具体哪个集群有配置，所以都会订阅

![image](https://user-images.githubusercontent.com/837658/189252928-9cd8951b-bd0b-4738-9845-6a820e64a09f.png)
