### ISSUE TITLE
查看配置项超大整型数值时，前端展示数值溢出，显示不准

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4559]
namespace是properties格式，key的内容是一个json字符串，里面有key是超大数值类型，点击查看配置，展示出来的数值存在溢出，显示不准，这个要怎么修复下呢
![image](https://user-images.githubusercontent.com/9474302/189258029-d95dcf1a-1eca-4369-904f-e4414805b41e.png)

**Comment by nobodyiam** [comment]
I believe this was fixed by #4183.
