### ISSUE TITLE
why not support all appollo settings in app.properties?such as `cluster` and `env`

### ISSUE THREAD

**Issue by Jxiu** [apolloconfig/apollo#4560]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦

**清晰简洁地描述一下你希望的解决方案**

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
see #3414 #3427

**Comment by Jxiu** [comment]
did you see that there is no full file (in only one file)support config in apollo system.

**Comment by nobodyiam** [comment]
Though not recommended, the spring boot application.properties could config all the configs.
