### ISSUE TITLE
create namespace with single dot 500 error

### ISSUE THREAD

**Issue by AbnerHuang2** [apolloconfig/apollo#4565]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
create namespace with . will crash in query namespace.

**To Reproduce**
1.  create namespace with single dot(.)
2. refresh namespace. 

**Expected behavior**
display normally.

**Screenshots**

https://user-images.githubusercontent.com/50099513/189686696-179451cc-00b9-433b-a2ef-f270baf848c2.mov

### Additional Details & Logs

- Latest Version (All)

**Comment by AbnerHuang2** [comment]
I think the reason is that  quering namepace is in path value, while path contains single dot would return status 200, but response is HTML rather json, which can't be parse in front.

**Comment by nobodyiam** [comment]
This is not a normal case, but I think we could fix it via the new regex.
