### ISSUE TITLE
Apollo checks the yaml format interface Response Code = 500 

### ISSUE THREAD

**Issue by klboke** [apolloconfig/apollo#4566]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
Apollo checks the yaml format interface Response Code = 500 

**To Reproduce**
1. Create a namespace in yaml format
2. Trigger syntax check

**Expected behavior**
Is it better to expect a response of 400 when the check fails? Because a 500 response will always trigger a load balancing alarm by mistake
**Screenshots**
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/18591662/189801710-4f21e513-8236-4fed-982f-dd79bc837271.png">
### Additional Details & Logs

- Version ：2.0.1
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
In this case, I think 4xx codes are more appropriate.
