### ISSUE TITLE
使用一台虚拟机分布式部署Apollo集群，config和admin实例只注册到其中一个eureka

### ISSUE THREAD

**Issue by caoxingsheng** [apolloconfig/apollo#4569]
**描述**

虚拟机IP为192.168.3.50，一共两套环境（local和dev），所有admin、config、portal服务都部署到该虚拟机，admin部署两个实例，config部署两个实例，portal部署一个实例

local环境
    config实例1：192.168.3.50:8080
    config实例2：192.168.3.50:8081
    admin实例1：192.168.3.50:9090
    admin实例2：192.168.3.50:9091
    config db：apolloconfigdblocal
dev环境
    config实例1：192.168.3.50:8082
    config实例2：192.168.3.50:8083
    admin实例1：192.168.3.50:9092
    admin实例2：192.168.3.50:9093
    config db：apolloconfigdbdev
所有环境共用portal
    portal实例1：192.168.3.50:8070
    portal db：apolloportaldb

**复现**

通过如下步骤可以复现：

1. 部署config服务，修改apollo-configservice.conf中日志路径，如8080服务设置为LOG_FOLDER=/opt/logs/1000031718080/，8081设置为LOG_FOLDER=/opt/logs/1000031718081/，以此类推
2. 修改config/application-github.properties数据库配置，local环境配置为apolloconfigdblocal，dev环境配置为apolloconfigdbdev
3. 修改scripts/startup.sh 日志路径和启动端口，如8080服务设置为LOG_DIR=/opt/logs/1000031718080，SERVER_PORT=${SERVER_PORT:=8080}；8081服务设置为LOG_DIR=/opt/logs/1000031718081，SERVER_PORT=${SERVER_PORT:=8081}，以此类推
4. admin服务跟config类似修改，略
5. 修改apolloconfigdblocal数据库serverconfig表中eureka地址为http://192.168.3.50:8080/eureka/,http://192.168.3.50:8081/eureka/
6. 修改apolloconfigdbdev数据库serverconfig表中eureka地址为http://192.168.3.50:8082/eureka/,http://192.168.3.50:8083/eureka/
7. 启动config和admin服务，打开各个eureka地址，观察服务注册信息

**期望**

正常情况下，每一个eureka实例都能看到当前环境下的所有config和admin实例，即http://192.168.3.50:8080/和http://192.168.3.50:8081/均能看到local环境下的所有config和admin实例；http://192.168.3.50:8082/和http://192.168.3.50:8083/均能看到dev环境下的所有config和admin实例。但结果却是eureka只看到部分config或admin。

**截图**

config8080
![image](https://user-images.githubusercontent.com/27294643/190124012-c18193b3-d934-42fd-9ee0-69964569b69f.png)

config8081
![image](https://user-images.githubusercontent.com/27294643/190124048-2adffd3f-89e6-46a7-9cb8-2e09f31f1c1a.png)

config8082
![image](https://user-images.githubusercontent.com/27294643/190124104-f580e986-75bf-44fe-9594-947baf1cdaad.png)

config8083
![image](https://user-images.githubusercontent.com/27294643/190124532-8a3068b8-c397-4400-908f-7b1efc9cb19a.png)

### 额外的细节和日志

- 版本：apollo 2.0.1
- 错误日志
- 配置：
- 平台和操作系统：CentOS 7

**Comment by CalebZYC** [comment]
- EN
This should be a problem with the eureka server side cluster configuration, not apollo.
<hr>

- CN
这应该是eureka服务器端集群配置的问题，不是apollo的；

**Comment by nobodyiam** [comment]
The configurations look all right. You may check the eureka client and server logs for more information.

**Comment by caoxingsheng** [comment]
> The configurations look all right. You may check the eureka client and server logs for more information.

我把serverconfig表中的eureka IP地址全部改成127.0.0.1就好了，为什么不能用192.168.3.50呢？？
