### ISSUE TITLE
1.8.2升级到2.0.1

### ISSUE THREAD

**Issue by dengdalue** [apolloconfig/apollo#4576]
请问从1.8.2升级到2.0.1，是不是需要经过以下步骤？
一.从1.8.2升级到1.9.0
![image](https://user-images.githubusercontent.com/28399052/191189137-71f365c9-d127-45ae-b3dd-ecc4edbca03a.png)

二.从1.9.0升级到2.0.0
![image](https://user-images.githubusercontent.com/28399052/191189304-c5468d2e-fd88-4960-b1ad-0d300ca7051c.png)

**Comment by richieyan** [comment]
没问题，按手册升级即可。

**Comment by dengdalue** [comment]
已按照手册成功升级，谢谢！

**Comment by zhangjundong1992** [comment]
从1.9.0升级到2.0.0这一段版本日志怎么找不到了？

**Comment by nobodyiam** [comment]
@zhangjundong1992 you may reference the upgrade steps in release note page - https://github.com/apolloconfig/apollo/releases/tag/v2.0.0

**Comment by zhangjundong1992** [comment]
> @zhangjundong1992 you may reference the upgrade steps in release note page - https://github.com/apolloconfig/apollo/releases/tag/v2.0.0

谢谢
