### ISSUE TITLE
在点击发布操作时，是否可以获取到此次发布将会影响到的节点实例ip并告知用户？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4577]
在点击发布操作时，是否可以获取到此次发布将会影响到的节点实例ip并告知用户？
![image](https://user-images.githubusercontent.com/9474302/191189977-272ece19-2973-4744-871b-6d4344a7ae83.png)

**Comment by hezhaoye** [comment]
是否可以理解为如果是灰度发布事件，影响到的ip就是灰度规则里面的值，其他都是全量的实例节点呢？

**Comment by nobodyiam** [comment]
看这个页面是自定义的，不过大体原则应该是这样的 - `如果是灰度发布事件，影响到的ip就是灰度规则里面的值，其他都是全量的实例节点`。

**Comment by hezhaoye** [comment]
不过实例是异步上报的，在发布时其实感觉挺难实时获取到影响的节点列表。
