### ISSUE TITLE
openapi 查询 Namespaces，返回的数据是未发布的数据

### ISSUE THREAD

**Issue by MoonBall** [apolloconfig/apollo#4578]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces
使用该 openapi 查询 nanmespace

**To Reproduce**
同上

**Expected behavior**
期望返回的 items[0].value 是发布后的值，但当前是未发布的值。

**Screenshots**
![image](https://user-images.githubusercontent.com/13298548/191478081-b172d246-f755-4fae-af99-178d28b61ca0.png)
![image](https://user-images.githubusercontent.com/13298548/191478108-f223889d-37ea-4cfb-aaa6-775ed7b65e4a.png)

### Additional Details & Logs

- Version
- 系统版本: java-1.9.1

- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
I think this is by design. You may use the API `openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/releases/latest` to retrieve the released item values.

**Comment by MoonBall** [comment]
> I think this is by design. You may use the API `openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/releases/latest` to retrieve the released item values.

get, thanks
