### ISSUE TITLE
not found `getItems` paging openapi

### ISSUE THREAD

**Issue by MoonBall** [apolloconfig/apollo#4581]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

There is a openapi which gets items by paging in [document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3216-%e5%88%86%e9%a1%b5%e8%8e%b7%e5%8f%96%e9%85%8d%e7%bd%ae%e9%a1%b9%e6%8e%a5%e5%8f%a3). But visiting this api will result to an error.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/13298548/191738565-2a05ac2b-3b79-425e-99e1-b3c410ba004f.png">

**To Reproduce**
visit the api `http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items`, reference: [document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3216-%e5%88%86%e9%a1%b5%e8%8e%b7%e5%8f%96%e9%85%8d%e7%bd%ae%e9%a1%b9%e6%8e%a5%e5%8f%a3)

**Expected behavior**
no error

**Screenshots**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/13298548/191738851-82891136-6bba-427b-a05d-abfa74177b1c.png">

### Additional Details & Logs

- Version: master branch
- Error logs
- Configuration
- Platform and Operating System

**Comment by mghio** [comment]
There is no problem with running on my machine. You may confirm whether the `api_host` parameter value is consistent with the `PortalApplication` service?

![Xnip2022-09-22_23-31-33](https://user-images.githubusercontent.com/43461943/191790522-e889e095-8d9c-4fd9-b82b-c26ba028f67e.jpg)

**Comment by MoonBall** [comment]
> There is no problem with running on my machine. You may confirm whether the `api_host` parameter value is consistent with the `PortalApplication` service?
> 
> ![Xnip2022-09-22_23-31-33](https://user-images.githubusercontent.com/43461943/191790522-e889e095-8d9c-4fd9-b82b-c26ba028f67e.jpg)

may be relevant with the version of apollo, There is no this api in apollo [github markdown file](https://github.com/apolloconfig/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0).

**Comment by nobodyiam** [comment]
This api was introduced by #4468, which is available in the master branch but not yet released.
@mghio I think we'd better add a version notice in the API documentation.

**Comment by mghio** [comment]
> This api was introduced by #4468, which is available in the master branch but not yet released. @mghio I think we'd better add a version notice in the API documentation.

Good idea. BTW, Does the current online documentation framework [docsify](https://docsify.js.org/#/) support version selection? e.g. [Elasticsearch doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/index.html).

![Xnip2022-09-24_17-59-44](https://user-images.githubusercontent.com/43461943/192092344-ac6b1312-ce40-46a3-b39d-9d51f0cf65f3.jpg)

**Comment by nobodyiam** [comment]
@mghio There is a discussion on this #4327. Meanwhile, we could simply add a notice in the documentation first.
