### ISSUE TITLE
support config service and admin service use mysql as registry

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4583]
**Is your feature request related to a problem? Please describe.**
Apollo use eureka as registry now, it need eureka's configuration like url when deployment as cluster mode.

Why?
Sometime config service or admin service will **startup failed** due to the configuration themself, and the eureka's configuration maybe a little hard to config when run on multiple idc(a network connected region).

**Describe the solution you'd like**
register: 
when config service and admin service's instance startup, they register to self's database table, and send heartbeat on runtime.

discovery: 
origin data select from database table, and cache them by jvm memory.

Use metadata(mutiple key values) or a label in local .properties file to support only discover same idc's instance.

**Additional context**
benefit:
Auto scale config service and admin service without config registry's url, because they use same database, their url will save in a same table for service discovery.

cost:
* need to maintain a new database table.
* a clearup policy to clean this database table.
* health check

**Comment by nobodyiam** [comment]
Usually, apollo won't have a lot of instances so it won't bring much burden to the database.
However, we do need to consider the health check and clean-up mechanism to make the registry and discovery process correct.
But I'd say I like this idea as this would make the deployment configuration much simpler.
