### ISSUE TITLE
是否能够支持针对环境的查询权限

### ISSUE THREAD

**Issue by Andrew-Yang999** [apolloconfig/apollo#4586]
**Is your feature request related to a problem? Please describe.**
目前公司是将测试环境的查看以及修复发布权限开放给开发人员，而生产环境的权限都只开放给运维人员，开发人员无权查看，
但是apollo上配置的项的人只有开发人员了解，开发人员了解这个配置可能会影响哪些核心业务，故需要让开发人员知道生产环境的配置是怎么样的。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nobodyiam** [comment]
如果不开启[配置查看权限](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90)，开发人员是可以看到生产环境的配置的。
