### ISSUE TITLE
openapi获取某个Namespace信息接口中包含删除的item

### ISSUE THREAD

**Issue by spalagu** [apolloconfig/apollo#4593]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
接口返回的items中不包含已删除的item
或在item中标识已删除的状态

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
This seems a bug that `com.ctrip.framework.apollo.portal.entity.bo.ItemBO#isDeleted` is not used in filter criteria.
