### ISSUE TITLE
docker部署apollo 2.0.1版本时，增加eureka相关环境变量导致portal管理端404错误

### ISSUE THREAD

**Issue by zhangjundong1992** [apolloconfig/apollo#4602]
**描述bug**

使用分布式docker部署apollo服务端，docker-compose.yml文件中增加了eureka注册相关环境变量，获取真实ip地址
相关如下：
    environment:
      EUREKA_INSTANCE_IP_ADDRESS: "10.50.54.35"
      EUREKA_INSTANCE_HOME_PAGE_URL: "http://10.50.54.35:18080"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
此时，打开portal管理界面，登录后选择项目，无法加载环境信息，错误信息如下：
load env:UAT cluster error:404:"....error: Not Fount, path /apps/xxxx/clusters"

### 额外的细节和日志
- 版本：2.0.1
- 平台和操作系统：linux

**Comment by nobodyiam** [comment]
You may check both the portal and admin-service logs.

**Comment by benbenben20** [comment]
admin-server no error 
[AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
