### ISSUE TITLE
test: normailize all integration test's class name

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4606]
**Is your feature request related to a problem? Please describe.**
Integration test and unit test are different, for more distingush of them, we can change the integration test's class name.

An integration test extends the class `AbstractIntegrationTest`.

For example,

```
public class AdminServiceTest extends AbstractIntegrationTest {
```

AdminServiceTest is an integration test, we can change its name to AdminServiceIntegrationTest.

**Describe the solution you'd like**
1. normailize all integration test's class name with suffix IntegrationTest.
2. add some class name verify in AbstractIntegrationTest's constructor
```java
  public AbstractIntegrationTest() {
    String className = this.getClass().getName();
    // do some verify
    if (!className.endsWith("IntegrationTest")) {
      
    }
  }
```

**Comment by nobodyiam** [comment]
Sounds a good idea :-)
