### ISSUE TITLE
Required String parameter 'operator' is not present

### ISSUE THREAD

**Issue by JerryZheng0503** [apolloconfig/apollo#4607]
使用apollo开放平台API接口时，出现如下错误：

请求：
  curl --request PUT \
  --url https://【apollo-address】/openapi/v1/envs/DEV1/releases/1/rollback \
  --header 'Authorization: be022fa6776853d7415f2ef5125b922b4824bc54' \
  --header 'Content-Type: application/json;charset=UTF-8' \
  --header 'operator: apollo'

返回：
{
	"exception": "org.springframework.web.bind.MissingServletRequestParameterException",
	"message": "Required String parameter 'operator' is not present",
	"status": 500,
	"timestamp": "2022-10-17T17:56:39.489"
}

ps：这个接口之前的查看、创建key接口都可以成功；
参考文档：https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3215-%e5%9b%9e%e6%bb%9a%e5%b7%b2%e5%8f%91%e5%b8%83%e9%85%8d%e7%bd%ae%e6%8e%a5%e5%8f%a3

**Comment by nobodyiam** [comment]
`operator` is in the `Request Params`, e.g. `http://{portal_address}/openapi/v1/envs/{env}/releases/{releaseId}/rollback?operator=apollo`.

**Comment by JerryZheng0503** [comment]
{
	"exception": "com.ctrip.framework.apollo.common.exception.BadRequestException",
	"message": "release not found",
	"status": 400,
	"timestamp": "2022-10-18T11:22:38.85"
}
ok, i try by your url, but 400 error, i think my {realeaseId} is error;
master, how to find my {releaseId} ? thank you

**Comment by mghio** [comment]
> 



> { "exception": "com.ctrip.framework.apollo.common.exception.BadRequestException", "message": "release not found", "status": 400, "timestamp": "2022-10-18T11:22:38.85" } ok, i try by your url, but 400 error, i think my {realeaseId} is error; master, how to find my {releaseId} ? thank you

DB: ApolloConfigDB, table:Release.
