### ISSUE TITLE
apollo-configservice.conf配置文件有什么作用啊？我没看到有地方读这个配置文件

### ISSUE THREAD

**Issue by yungyu16** [apolloconfig/apollo#4609]
如题

**Comment by mghio** [comment]
see [assembly-descriptor.xml](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/assembly/assembly-descriptor.xml#L46-L53).

**Comment by yungyu16** [comment]
> see [assembly-descriptor.xml](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/assembly/assembly-descriptor.xml#L46-L53).

@mghio 打包的时候是打到zip文件里去了，但是我看遍了启动脚本、全局搜索了文件名，没有地方读取这个文件啊，这个文件有什么作用呢？
