### ISSUE TITLE
apollo.xsd is not unrecognized

### ISSUE THREAD

**Issue by pingu8007** [apolloconfig/apollo#4611]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
<http://www.ctrip.com/schema/apollo.xsd> can't be resolved by general xml processor.

**To Reproduce**
1. Open xml with any xml-aware editor and add <http://www.ctrip.com/schema/apollo.xsd> to `xsi:schemaLocation`. The editor has knowledge of neither spring framework nor java.
2. `apollo.xsd` is failed to be resolved.

**Expected behavior**
apollo.xsd is resolved without error

**Comment by nobodyiam** [comment]
see https://github.com/apolloconfig/apollo-java/blob/main/apollo-client/src/main/resources/META-INF/spring.schemas
