### ISSUE TITLE
仅查看私有namespace不生效 为何还可查看公共？

### ISSUE THREAD

**Issue by ronaldo-bo** [apolloconfig/apollo#4620]
**描述bug**
看了很多issues 都有提到，configView.memberOnly.envs这个值来设置仅查私有namespace查看权限，不过一直测试失败

问题：创建用户后，分配指定项目管理员权限，设置configView.memberOnly.envs，还是可以查看公共namespace，理解这个参数设置后 只能查看私有namespace 才对，还请帮忙看下

**复现**
通过如下步骤可以复现：

1.用户是项目管理员
2.环境列表 dev,qa
3.configView.memberOnly.envs 同样也设置 dev,qa
![image](https://user-images.githubusercontent.com/71818803/199183116-3437fd4d-a654-465d-80d6-b5234bf214d3.png)

4.用户权限一样
![image](https://user-images.githubusercontent.com/71818803/199179906-c4e39878-4af3-42dd-aa5e-36704b7c43fd.png)

**期望**
期望：仅能查看私有 不能查看公共，且对私有也不能修改、发布

### 额外的细节和日志
- 版本：1.19
- 平台和操作系统：k8s

**Comment by nobodyiam** [comment]
这是符合预期的 - 可以看下[文档说明](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_319-configviewmemberonlyenvs)。

**Comment by ronaldo-bo** [comment]
感谢答复，那请问现在可以实现项目中关闭公共namespace对所有用户可见嘛

**Comment by nobodyiam** [comment]
公共 namespace 在应用中可以覆盖，所以设计上是需要可见的，不过我猜你是想某些敏感配置对普通用户不可见吧？可以看看这个讨论 #3187
