### ISSUE TITLE
Apollo的热更新，目前测试发现XML中使用${} 无法实现热更新

### ISSUE THREAD

**Issue by sq-young2** [apolloconfig/apollo#4627]
您好
      Apollo的热更新，目前测试发现XML中使用${} 无法实现热更新，请问有没有好些的解决方案。
      感谢回复哦！

**Comment by mghio** [comment]
see [XML-based configuration](https://www.apolloconfig.com/#/en/usage/java-sdk-user-guide?id=_3211-xml-based-configuration).
