### ISSUE TITLE
fix document markdown Lightweight Markup Languages code blocks back quote

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4629]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
In document, some markdown's code blocks use 4 back quote *````*, some use 3 back quote *```*

For example: 
* https://github.com/apolloconfig/apollo/blob/5bec3e4bfd7e268fe7f991f1e181bd756bf55f8d/docs/en/deployment/quick-start.md?plain=1#L27
* https://github.com/apolloconfig/apollo/blob/5bec3e4bfd7e268fe7f991f1e181bd756bf55f8d/docs/en/misc/apollo-benchmark.md?plain=1#L9
* https://github.com/apolloconfig/apollo/blob/5bec3e4bfd7e268fe7f991f1e181bd756bf55f8d/docs/en/deployment/deployment-architecture.md?plain=1#L904

Those syntax error will cause some error when tool parse markdown document.

**Expected behavior**
Normalize all 4 back quote *````* to 3 back quote *```*

**Screenshots**
When open 
https://github.com/apolloconfig/apollo/blob/5bec3e4bfd7e268fe7f991f1e181bd756bf55f8d/docs/en/deployment/quick-start.md?plain=1#L27 
with vscode
![image](https://user-images.githubusercontent.com/15523186/200152384-d9eec80c-df61-4591-a5b5-b5166b69ac42.png)
this color should be blue instead of green, 4 back quote *````* broken the syntax.

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by the-lazy-learner** [comment]
Could I attempt this?
