### ISSUE TITLE
2.0.1版本怎么把注册中心替换成zookeeper，有相关文档吗？

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4633]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by mghio** [comment]
see [zookeeper-discovery](https://www.apolloconfig.com/#/en/deployment/distributed-deployment-guide?id=_2233-zookeeper-discovery)

**Comment by leidachui** [comment]
zookeeper只支持3.5以上版本吗，3.4版本支持吗

**Comment by mghio** [comment]
> zookeeper只支持3.5以上版本吗，3.4版本支持吗

Currently not supported. Now Curator in Apollo is version 5.x. After 5.0, ZooKeeper 3.4.x is no longer supported. If you want to use ZooKeeper 3.4.x, you need to replace the dependencies. More see [Curator 5.0 Breaking Changes](https://curator.apache.org/breaking-changes.html).

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/43461943/200852951-b66535a5-5d13-4dca-9f6b-bac23512f07f.png">

**Comment by leidachui** [comment]
ok，thx~
