### ISSUE TITLE
服务调用走https而不是http，支持吗？

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4636]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

因为公司内部网络的原因，portal访问configservice必须走 https，
请问apollo现在支持了吗

**Comment by nobodyiam** [comment]
It's not officially tested but I suppose it should work.

**Comment by oooohhoo** [comment]
self-signed certifcate not working, which gives error: unable to find valid certification path to requested target

**Comment by nobodyiam** [comment]
I believe some JVM configs are needed to trust a self-signed certificate.

**Comment by leidachui** [comment]
嗯嗯，安装证书之后，可以直接发https请求了，直接把 configservice 和 adminservice的地址配置成 https的即可。
在admin-service注册的地方，增加启动参数  -Deureka.instance.homePageUrl=<希望注册上去的域名>
