### ISSUE TITLE
页面请求后端时间较长就会重定向到 index.html页面

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4638]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

你好，我们公司的portal-server必须部署在 海外aws上，但需要在国内办公网访问；
现在发现，访问速度非常慢（网络问题），导致 点击按钮 很多时候都会被跳转到 index.html 这个默认页面。

我推测是有一个超时时间，超时的话，就会重定向到默认页面，
请问这个超时时间可以怎么配置呢？ 我想改长一点。
本人后台开发一枚，不太会看前端代码， 
是否能告知下源码中具体的代码位置，我修改下，感谢~~

**Comment by nobodyiam** [comment]
I'm not aware of such logic... Is it possible to duplicate the behavior in the [demo site](http://81.68.181.139/)?

**Comment by leidachui** [comment]
很遗憾，公司的网络策略限制了，我没法访问 [demo site]；

但我自己在本地用同样的版本部署apollo，没有这个问题； 因为确实本地响应速度很快；
但只要是访问 部署在 国外的apollo，这个问题就 必现。

**Comment by leidachui** [comment]
> I'm not aware of such logic... Is it possible to duplicate the behavior in the [demo site](http://81.68.181.139/)?

抓包发现有很多请求被 canceled
![image](https://user-images.githubusercontent.com/33803494/201823531-415b618a-db6b-48c9-beea-7c9d0b3b4667.png)

还发现，有接口访问一个完全不清楚的ip：
![image](https://user-images.githubusercontent.com/33803494/201823602-6d73952f-52ef-4cc7-a5be-c0a17ff82054.png)

这个ip是哪里来的呢

**Comment by leidachui** [comment]
知道原因了，这个是被运营商劫持了，参考文章：
https://juejin.cn/post/7050368018907398174

改成 https 就可以了
