### ISSUE TITLE
阿波罗接口分页获取配置项接口请求失败

### ISSUE THREAD

**Issue by xiaolangit** [apolloconfig/apollo#4641]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我的apollo是最新的版本2.0.1。现在想调用openapi接口如下

[3.2.16 分页获取配置项接口]
URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items
Method ： GET
Version ： >= 2.1.0
Request Params ：

**复现**

接口全地址如下:
http://apollohostname/openapi/v1/envs/DEV/apps/projectid/clusters/default/namespaces/application/items

请求接口报错如下
{u'status': 400, u'timestamp': u'2022-11-14T14:45:33.113', u'exception': u'org.springframework.web.HttpRequestMethodNotSupportedException', u'message': u"Request method 'GET' not supported"}

**期望**

我不明白这个接口文档version >= 2.1.0

是2.0.1写成了2.1.0？

还是说未来2.1.0的版本会支持分页获取配置项接口。

还是说我的调用有问题？如果不是，现在我想获取配置接口有什么方法？

**Comment by Anilople** [comment]
> version >= 2.1.0

2.1.0 doesn't release yet. It mean you can use it after 2.1.0 release.

**Comment by xiaolangit** [comment]
@Anilople thanks a lot
