### ISSUE TITLE
apollo-configservice 启动异常

### ISSUE THREAD

**Issue by zhanghao0325** [apolloconfig/apollo#4642]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

启动不了

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

![image](https://user-images.githubusercontent.com/49109146/201615354-f2c134a8-6c92-4a3c-864b-d6efb9efaae6.png)

### 额外的细节和日志

- 版本：1.8.2
- 错误日志
[apollo-configservice.log](https://github.com/apolloconfig/apollo/files/10001298/apollo-configservice.log)

- 配置：
- ip：
![image](https://user-images.githubusercontent.com/49109146/201617186-1f452742-8621-4fc4-aa91-006eacbfa0a1.png)
- application-github.properties
![image](https://user-images.githubusercontent.com/49109146/201617474-46f6776e-cb4f-4878-a915-a0d42eca2639.png)
- app.properties
![image](https://user-images.githubusercontent.com/49109146/201617569-44a5ac77-e0be-46c7-aa7f-faf31869d0fa.png)
- 数据库
![image](https://user-images.githubusercontent.com/49109146/201618039-0b6529c4-6ffc-4e08-a6fa-68bcb4d7eaed.png)
- 平台和操作系统 centos 7

**Comment by Anilople** [comment]
Try 
```bash
curl http://localhost:8080
```
maybe there is another server running with port 8080.
