### ISSUE TITLE
Table 'apolloportaldb.server_config' doesn't exist

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4643]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

这个问题在下面的issues也说了，但没有给解决方案，
https://github.com/apolloconfig/apollo/issues/2465

看到 [nobodyiam](https://github.com/nobodyiam) 说
这个策略是在[application.properties](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/resources/application.properties)里面配置的

但我application只配置了下面内容：
![image](https://user-images.githubusercontent.com/33803494/201654835-43527d6f-eed7-4727-b041-9b97e3f55184.png)

请问到底是 哪个策略导致的呢？ 能否详细说明下？

**Comment by nobodyiam** [comment]
是下面的配置策略，用 apollo release 的包应该是没问题的，你是自己打得包或者改过啥配置？

https://github.com/apolloconfig/apollo/blob/e04028dfe9ca3e5792be89b96a6fbd2ee80355b7/apollo-common/src/main/resources/application.properties#L22-L23

**Comment by leidachui** [comment]
我是自己打的包，但我从来不知道，也没有碰过，没有改过 这样的策略，
之前一直这样打包都没问题，就昨天下午有问题，而且在有些环境下运行有问题，有些环境下则没有问题。

好的，那我先试下。

**Comment by leidachui** [comment]
加了这个配置后，服务可以正常起来了

**Comment by leidachui** [comment]
问题已解决
