### ISSUE TITLE
开放平台一个三方应用只能管理一个AppId吗，可以支持一个三方应用管理多个AppId吗

### ISSUE THREAD

**Issue by weihubeats** [apolloconfig/apollo#4649]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/42484192/202400730-a495c3d1-b171-4e7a-821f-196fb936846f.png">
目前看是只能填一个，支持逗号分割之类的吗

**Comment by mghio** [comment]
Currently only one can be assigned at a time, and multiple assignments require multiple submit. 

The actual storage structure of third-party application and assign in Apollo is shown in the figure below. The roles of different App are different.
![Xnip2022-11-18_22-38-22](https://user-images.githubusercontent.com/43461943/202729798-c9551893-5092-4d6c-81c6-f582a39e24b4.jpg)

**Comment by nobodyiam** [comment]
You may use the same token with different appids.

**Comment by weihubeats** [comment]
Okay, thank you very much.

**Comment by cmjzzx** [comment]
> You may use the same token with different appids.

Nice, thank you
