### ISSUE TITLE
apollo client

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4650]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

业务准备接入apollo-client，发现抱错：
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument

原因：
业务用到了cassandra-driver-core，而cassandra-driver-core最高版本也只依赖19.0版本的 guava；
但apollo-client中用到了com.google.common.base.Preconditions.checkArgument，最低是在 guava 20.0版本加入的；

真是伤脑筋啊！

**Comment by mghio** [comment]
You can try to exclude Guava version 19.0 in cassandra-driver-core.

**Comment by leidachui** [comment]
问题解决了，我把cassandra需要的Guava 升级到 20版本即可

**Comment by Anilople** [comment]
mark
* https://github.com/apolloconfig/apollo/issues/4457
* https://github.com/apolloconfig/apollo/discussions/4369
