### ISSUE TITLE
文本无法删除尾部的空行

### ISSUE THREAD

**Issue by wanggang19** [apolloconfig/apollo#4654]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/20056551/202979127-b191eabc-f83f-4326-ab94-84ea9d8d28d0.png">
我没办法把下面的这些空行删掉，如果复制配置到文本，中间带有大量空行(key、value、comment均为空)，在配置中删除空行后，配置尾部依然会有大量空行(key、value、comment均为空的配置)，这个就没法删除了。

**复现**

通过如下步骤可以复现：
1. 拷贝中间存在大量空格的配置到"文本"中
<img width="957" alt="image" src="https://user-images.githubusercontent.com/20056551/202979933-42c4b71d-aac8-4edf-ae4f-959a6aefdf93.png">
2.删除中间配置，尾部会出现大量空行，这些空行之后无法删除

**期望**
<img width="873" alt="image" src="https://user-images.githubusercontent.com/20056551/202980092-48f3374c-8d98-48fd-ae47-9325e1dc3c90.png">
看了下代码(com.ctrip.framework.apollo.portal.component.txtresolver.PropertyResolver#deleteCommentAndBlankItem)，是否还有第三种情况：oldItem为空，newItem不存在，这种也应该删除？
**截图**
如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
This looks like an issue, would you please help to fix it?

**Comment by wg1993** [comment]
> This looks like an issue, would you please help to fix it?
OK
