### ISSUE TITLE
 ApolloPortal still access http with nginx https reverse proxy

### ISSUE THREAD

**Issue by Alceatraz** [apolloconfig/apollo#4655]
- [X] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [X] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

ApolloPortal 使用 Nginx 为其提供https反向代理仍然访问http. 

- 登录页面正常；
- 点击登录后，`http://apollo.xyz:443/signin?` 的请求失败400
- 跳转到`http://apollo.xyz:443/signin?#/error` 页面显示nginx错误页

**复现**

通过如下步骤可以复现：

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx
```

```text
server {
    listen 80 default_server;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl http2;

    server_name apollo.xyz;

    ssl_certificate cert/server.crt;
    ssl_certificate_key cert/server.key;

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;

    location / {
        proxy_pass http://123.123.123.123:8070;
        proxy_set_header Host $http_host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto "http";
        add_header Content-Security-Policy "upgrade-insecure-requests; connect-src *";
    }
}

```

**期望**

页面发出的所有请求均为https，同样的nginx配置用于 gitlab jenkins nexus grafana 可正常工作

**截图**

![Dingtalk_20221122191804](https://user-images.githubusercontent.com/8266702/203301185-af5a7734-d760-41bb-b5b8-cb7970c71c1f.jpg)

### 额外的细节和日志

- 版本：1.8.2 不确定是否在新版修复
- 平台和操作系统 docker 部署

**Comment by nobodyiam** [comment]
There are some discussions you may refer: #3796 #1778

**Comment by Alceatraz** [comment]
> There are some discussions you may refer: #3796 #1778

`proxy_redirect ~^http://([^:]+)(:\d+)?(.*)$ https://$1$2$3;`

的方法确实可用，但是这个解决方法有点非常规了，相当于nginx替前端做了https升级，是否考虑加入自动识别baseURL的功能？

**Comment by nobodyiam** [comment]
There is another related issue #4081, would you please help to verify whether it works?

**Comment by Alceatraz** [comment]
目前看起来像是前端自动解析过程中baseUrl只解析了端口号，而没有解析schema，因为访问的地址是 `https://xxx:443`。

> There is another related issue #4081, would you please help to verify whether it works?

> 登录的时候跳转没有带上https而是http，例如
> ```
> https://login.partner.microsoftonline.cn/{tenant}/oauth2/v2.0/authorize?response_type=code&client_id={client_id}&scope=openid&state=qAVu-cULMtHpc9aZCZGE-tvQs_6uuxMop_84wK8SUHA%3D&redirect_uri=http://xxx.com/login/oauth2/code/azure&nonce=6sFinXXWxR2WxOPDnI8pPpBI7J0UDOQnf6tk-yxVj-g
> ```

在我的环境没有使用OICD，抱歉无法验证。其中 `redirect_uri=http://xxx.com` 指向的是http80地址，推测与我遇到的这个现象有关。

**Comment by nobodyiam** [comment]
This [documentation](https://github.com/apolloconfig/apollo/pull/4104/files) update adds a `server.forward-headers-strategy` config and a sample Nginx config which I suppose should also work for non-oidc scenarios, would you please have a try?
