### ISSUE TITLE
文档上的2.1.0版本指的是spring boot的版本吗

### ISSUE THREAD

**Issue by HeiDuck** [apolloconfig/apollo#4670]
你好,
  我看到文档里的介绍有些功能的限制是要求2.1.0以上版本的, 请问这个2.1.0版本指的是spring boot吗
文档链接: https://www.apolloconfig.com/#/zh/design/apollo-design

![image](https://user-images.githubusercontent.com/20020803/205245061-6fea1881-a3af-4ada-808f-56b333dcf9b6.png)

**Comment by Anilople** [comment]
Need some help to improve the document, one can start from https://www.apolloconfig.com/#/zh/contributing

Welcome~
