### ISSUE TITLE
Apollo Helm 2.0.1版本的 Portal 是否一樣支持一個環境多個metaserver ?

### ISSUE THREAD

**Issue by tsiayutai** [apolloconfig/apollo#4673]
您好 想请问一下 Apollo Helm 2.0.1版本的 Portal 在value.yaml配置metaserver的时候，是否能在同个环境例如 : PRO 配置多个 metaserver位置?
在虚拟机版本环境下设置过没问题，但自己在Helm 的版本在同个环境配置超过一个 metaserver的时，看portal的系统配置 metaserver位置有增加，但是config server和admin server位置还是只有一个，请问是原本就不支持还是我配置可能有问题呢?

**Comment by nobodyiam** [comment]
The [idea](https://github.com/apolloconfig/apollo/issues/3054) behind helm chart installation is to use Kubernetes service for service load balancing and high availability, so there is no need to configure multiple meta/config/admin servers.

**Comment by tsiayutai** [comment]
了解~ 但因为我们的PRO生产环境是有多個机房，所以才會想說能不能再metaserver 同個環境配置多個位置。

**Comment by tsiayutai** [comment]
所以helm版本确实是不行这样配置的是吗?

**Comment by nobodyiam** [comment]
For apollo-portal, you could configure multiple meta servers but only the first available one will be used.
For apollo-client, you could configure the meta server in the same idc.

**Comment by tsiayutai** [comment]
了解～感谢大神
这边想在借问一个问题，能设定多个portal吗， 还是 portal 只能配置一个呢？

**Comment by nobodyiam** [comment]
多个 portal 是指多台 portal server？这个是可以的

**Comment by tsiayutai** [comment]
如果我一个loadbalance 的 vip 回源到 3台 portal server，有需要做會話保持吗？

**Comment by nobodyiam** [comment]
1.9.0 以后的版本会默认开启数据库 session 保持，不需要自己做会话保持了 - https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-session-store

**Comment by tsiayutai** [comment]
了解~非常感謝您!

**Comment by Shelby-Jiao** [comment]
同样请教一下在配置portal数据库阶段就已经可以支持同env可以配置逗号隔开的多个metaserver了吗，代码中似乎实现了但是文档中没有明确说明

**Comment by nobodyiam** [comment]
可以的，在 [配置apollo-portal的meta service信息](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_221124-%e9%85%8d%e7%bd%aeapollo-portal%e7%9a%84meta-service%e4%bf%a1%e6%81%af) 中有说明。

![image](https://user-images.githubusercontent.com/837658/212443653-1749b883-50a0-4343-a295-0e54013ac195.png)
