### ISSUE TITLE
config-service.cache.enabled设置为true启动服务后找不到已发布的配置

### ISSUE THREAD

**Issue by leidachui** [apolloconfig/apollo#4679]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

ApolloConfigDb中ServerConfig表，config-service.cache.enabled字段设置为true，表示走缓存；
然后再启动configservice服务，会报错 
{"timestamp":"2022-12-12T15:44:53.682+0800","status":404,"error":"Not Found","path":"/configs/cloud_pushservice/default/application"}

实际配置是发布了的，当将config-service.cache.enabled字段改成false后再重启服务，
就可以拉取到正确的配置了
{"appId":"cloud_pushservice","cluster":"default","namespaceName":"application","configurations":{"test22":"2222"},"releaseKey":"20221212153942-369f5c3dc2078ee5"}

我的理解是 config-service.cache.enabled设置为true，会走缓存；看代码只是初始化的时候，去从DB拉取然后缓存，并且有一个过期时间。

1. 为什么我再服务启动的时候，却没有拉取到配置呢？ -- 这个字段有热加载机制，发现日志显示加载为 false后，仍然读不到配置
2. 那如果想走缓存，应该在什么时候设置config-service.cache.enabled呢？

**Comment by nobodyiam** [comment]
> 1. 为什么我再服务启动的时候，却没有拉取到配置呢？

可以看下 apollo-configservice 是否有啥错误日志。

> 2. 那如果想走缓存，应该在什么时候设置config-service.cache.enabled呢？

根据 `com.ctrip.framework.apollo.configservice.ConfigServiceAutoConfiguration#configService`, `config-service.cache.enabled` 配置修改后是需要 apollo-configservice 重启的。
