### ISSUE TITLE
Apollo 不支持${}配置引用

### ISSUE THREAD

**Issue by too-difficult-to-name** [apolloconfig/apollo#4683]
为什么不支持类似${}的配置引用方式呢，想知道答案

**Comment by nobodyiam** [comment]
${} is supported in the Spring environment.

**Comment by too-difficult-to-name** [comment]
> ${} 在 Spring 环境中受支持。

i means:

**Comment by too-difficult-to-name** [comment]
> ${} 在 Spring 环境中受到支持。

i have a java project that use apollo to manage configuration environment, It should be parsed It should be parsed correctly which configs on apollo:
source.root:/var/www/pushplatform/pluginmodel
plugin.timePlugin.messageResourceName = camel
plugin.timePlugin.jarPath = ${source.root}/timePlugin
plugin.timePlugin.version = 0.0.1
plugin.timePlugin.fileSuffix = current

plugin.transportPlugin.messageResourceName = camel
plugin.transportPlugin.jarPath =  ${source.root}/timePlugin
plugin.transportPlugin.version = 0.0.1
plugin.transportPlugin.fileSuffix = current
#...more plugins
i get " ${source.root}/timePlugin" not "/var/www/pushplatform/timePlugin" when i use `final Config config = ConfigService.getConfig()` and get `pluginmodelplugin.timePlugin.jarPath`

**Comment by nobodyiam** [comment]
The `${}` placeholder is a feature of Spring instead of Apollo. So you could enable this feature by [integrating it with Spring](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_32-spring%e6%95%b4%e5%90%88%e6%96%b9%e5%bc%8f).
