### ISSUE TITLE
Apollo V2.0.0, V2.0.1 Unauthorized access vulnerability

### ISSUE THREAD

**Issue by ljk5** [apolloconfig/apollo#4684]
Apollo V2.0.0, V2.0.1 Unauthorized access vulnerability exists in the configuration center. This vulnerability is caused by the failure to perform proper permission verification on some interfaces in the administrator tool of the configuration center. As a result, common users with low permission can access these interfaces to obtain sensitive information about the system and other users.
![image](https://user-images.githubusercontent.com/110451039/208673237-c26374f9-4525-4a59-af44-7e0589c3a2bf.png)
The vulnerability stems from
Apoll-portal \src\main\java\com\ctrip\framework\apollo\portal\controller\UserInfoController.java searchUsersByKeyword method Therefore, any user can access the interface to obtain all users' data information.

**Comment by nobodyiam** [comment]
This is a feature that is used in namespace permission management(see the below screenshot).
![image](https://user-images.githubusercontent.com/837658/208790591-17f0485f-f7b6-4e7d-943b-bafab1627ae8.png)

BTW, I don't think the user data information(userId/name/email) is sensitive.

**Comment by ljk5** [comment]
![image](https://user-images.githubusercontent.com/110451039/208804931-7392f810-ef80-4d94-a3b3-73c05557e48d.png)
Users with low rights do not have clear interfaces to view the form on the web interface. As a result, they violate their rights and leak other users' personal information, which cannot be viewed by users with zero rights in common situations
