### ISSUE TITLE
Spring Boot Actuator 配置 在启动过程中出现本地配置文件优先级大于Apollo配置文件

### ISSUE THREAD

**Issue by shiliang-star** [apolloconfig/apollo#4687]
**描述bug**

SpringBoot应用在启动过程中,在判断Actuator配置是否开启时,优先读取的是本地配置文件配置的值

我是按照集成Springboot的方式去配置的,在bootstrap.properties中配置的:
app.id= xxxxx
apollo.meta= http://xxxxxxxx
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application
apollo.bootstrap.eagerLoad.enabled=true

**复现**

通过如下步骤可以复现：

1. Apollo配置中心配置:
management.endpoints.web.exposure.include = httptrace,health
management.endpoints.web.base-path = /actuator
management.endpoint.health.show-details = always
management.health.diskSpace.enabled = true

2.本地配置文件application.yml配置:
 management.endpoints.web.exposure.include = httptrace,health
management.endpoints.web.base-path = /actuator
management.endpoint.health.show-details = always
management.health.diskSpace.enabled = false

3.启动springboot应用 

**期望**

正常应该以Apollo配置中心的配置为准,开启diskSpace的健康检查,实际上却是以本地配置文件为准,未开启diskSpace的配置检查,也就是未注入diskSpace检查的Bean到容器中

**截图**
以下是系统启动过程中,判断Spring Actutor是否开启的源码进行debug,此时发生的时机是扫描包目录下的Component Bean时:

org.springframework.boot.actuate.autoconfigure.OnEndpointElementCondition:
![image](https://user-images.githubusercontent.com/60741254/209597832-fc82aecd-5381-42b1-be0f-6e6f17a17747.png)
Environment对象的值: 
![image](https://user-images.githubusercontent.com/60741254/209597816-4e9c72bb-b09c-438b-9dd8-df15c6d26a89.png)
不符合Apollo的设计思路:
![image](https://user-images.githubusercontent.com/60741254/209597846-0fb7ca19-e60f-4b27-b71f-4a22e4e2b117.png)

### 额外的细节和日志

- 版本：
Apollo Client: 1.9.1    
Spring Boot: 2.3.12.RELEASE

- 平台和操作系统 :Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-55-generic x86_64)

**Comment by nobodyiam** [comment]
There is a related fix(https://github.com/apolloconfig/apollo-java/pull/3), would you please help to try the 2.1.0-SNAPSHOT version to see if it fixes your issue? You could add the following in your pom.xml and update the apollo client version to 2.1.0-SNAPSHOT.

```xml
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

```

**Comment by shiliang-star** [comment]
Yeah,很棒的解决了这个Issue,请问什么时候release 2.1.0正式版本?

**Comment by shiliang-star** [comment]
再请教一下,如果client升级到2.1.0版本,服务端也要升级到2.1.0版本吗?

**Comment by nobodyiam** [comment]
It's not required unless a new server feature is used, like https://github.com/apolloconfig/apollo/pull/4468, https://github.com/apolloconfig/apollo/pull/4549/
