### ISSUE TITLE
OIDC模糊搜索bug

### ISSUE THREAD

**Issue by Jxiu** [apolloconfig/apollo#4689]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
oidc搜索用户时候jpa报错，无法进行用户搜索

原因是因为hibernate 5.5.7final版本中存在一个like语法的bug，具体如下
https://stackoverflow.com/questions/72774965/parameter-value-did-not-match-expected-type-java-lang-string-n-a
我本人已升级版本修复完成。
**复现**

通过如下步骤可以复现：
启动一个oidc或者spring auth的服务器，添加一个新应用添加管理人员

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**
<img width="981" alt="image" src="https://user-images.githubusercontent.com/22760327/209772136-b1a9406a-37e1-47d3-bddd-35ff1ab62685.png">

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
What version of apollo are you using? The hibernate version used in apollo 2.0.1 is 5.6.9.Final.

**Comment by Jxiu** [comment]
ok，thanks. i will close this issue!
