### ISSUE TITLE
接入OIDC是否依旧需要修改start.sh

### ISSUE THREAD

**Issue by Shelby-Jiao** [apolloconfig/apollo#4690]
- [X] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [X] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [X] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

refer to https://github.com/apolloconfig/apollo/issues/4561, helm chart部署服务时里面配置项可以修改config.profile并挂载application-oidc.yml，官方文档中是否还一定需要修改start.sh？可否更新helm chart部署方式OIDC的整合示例？

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

portal支持OIDC认证

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
This is a good proposal and we welcome the community to contribute to the guide based on their own experience.
