### ISSUE TITLE
不能配置https,配置后老是跳到http

### ISSUE THREAD

**Issue by lifeblood** [apolloconfig/apollo#4691]
请问haproxy怎么配置https
环境上是只允许443访问。

**Comment by nobodyiam** [comment]
There is a [sample](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_17-portal%e6%8c%82%e8%bd%bd%e5%88%b0nginxslb%e5%90%8e%e5%a6%82%e4%bd%95%e9%85%8d%e7%bd%aehttps%ef%bc%9f) for nginx, you may follow the idea to see how it could be done for haproxy.
