### ISSUE TITLE
Apache-2.0 开源协议头内容缩进问题

### ISSUE THREAD

**Issue by llnancy** [apolloconfig/apollo#4695]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

标准 Apache-2.0 开源协议模版中间位置的 http://www.apache.org/licenses/LICENSE-2.0 前面是有缩进的。

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40930677/210728631-74ddeec5-12ec-478d-bb2f-43954a362352.png">

github action 中的 skywalking-eyes 最新版已经[修正该问题](https://github.com/apache/skywalking-eyes/commit/897e2e4ffd6172b082ee231fd5a5b42b1eb08b43)

> 本项目的 license.yml 中指定了 apache/skywalking-eyes 的 commitId 为 501a28d2fb4a9b962661987e50cf0219631b32ff

**复现**

通过如下步骤可以复现：

1. 
2. 
4. 
5. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Is it necessary to update all the file headers?
