### ISSUE TITLE
格式解析报错了，捕获异常并发送第三方通知

### ISSUE THREAD

**Issue by TuXiaoDD** [apolloconfig/apollo#4699]
情景是：
yaml或yml格式配置错了；@value加载apollo中map结构格式错了；数据类型不对，比如代码中是个Integer，但apollo配置了个字符串；
遇到这些个报错，我想发送飞书消息通知下。apollo都把异常catch住了，处理方式只能是继承实现比较多的接口去处理，比如我是这样监听yaml格式配置错误这个问题的，要实现和修改四个类，太不友好了。能不能考虑优化下？提供个自定义的接口啥的
![image](https://user-images.githubusercontent.com/40532962/211476855-8239ec19-6f24-4fd6-a3a2-14b1cfb525cd.png)
![image](https://user-images.githubusercontent.com/40532962/211477052-1a96fc94-c133-4196-9422-33038e4096f6.png)

**Comment by nobodyiam** [comment]
Is it possible to extend the tracer to do the job? see https://github.com/apolloconfig/apollo/releases/tag/v0.4.0

![image](https://user-images.githubusercontent.com/837658/211696640-0f08b7e8-8b31-480d-ad63-7b173547e4fb.png)

**Comment by TuXiaoDD** [comment]
问题：不想导cat-client包，想通过自定义实现达到需求。自定义的MessageProducerManager和MessageProducer都使用不上
trace中初始化producerManager只能读到DefaultMessageProducerManager，自定义的使用不上，因为loadFirst只会取第一个，没有设置优先级，不知道怎么保证loadFirst读取到的是自定义的那个而不是DefaultMessageProducerManager。
![image](https://user-images.githubusercontent.com/40532962/212839606-9962f6ee-0ad2-4ed7-9817-39fc4bd1c2cf.png)
![image](https://user-images.githubusercontent.com/40532962/212839869-5fbbe9b5-76cb-4e28-9965-2f2b2fe6a3f9.png)
![image](https://user-images.githubusercontent.com/40532962/212840960-fcae0494-6621-49b1-92d6-99828c21eaa5.png)

**Comment by nobodyiam** [comment]
This is a legacy issue but I think we could fix it now by adding the `Ordered` interface to `MessageProducerManager` and using `ServiceBootstrap.loadPrimary` method to locate the customized `MessageProducerManager`.
As apollo-client requires java 8 now so we could add a default `getOrder` implementation to `MessageProducerManager` interface which won't break backward compatibility.

**Comment by TuXiaoDD** [comment]
👍🏻
