### ISSUE TITLE
apollo密匙不生效问题

### ISSUE THREAD

**Issue by rjzhus** [apolloconfig/apollo#4702]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
apollo所在服务器时间与客户端所在服务器时间不一致时，apollo指定环境添加密匙开启，客户端按照添加的密匙配置以后不生效，会出现两种情况：
1.服务端开启密匙，客户端配置正确密匙，仍然拉取配置失败。
2.服务端开启密匙，客户端配置错误密匙，仍然可以拉取配置。

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. apollo服务器把当前服务器时间调增加12小时，启动apollo服务，完成配置，开启密匙
2. 另一台服务器客户端配置密匙出现拉取失败或者配置错误密匙仍然拉取成功

**期望**
配置并且开启密匙，客户端密匙未配置或者配置错误，应该拉取不到配置信息。

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.2.0
- 错误日志：
- 配置：
- 平台和操作系统：Linux

**Comment by nisiyong** [comment]
Could you provider the apollo server-side version and client-side version?

**Comment by rjzhus** [comment]
apollo 1.2.0
linux red hat 7.9

**Comment by rjzhus** [comment]
apollo server：1.2.0

**Comment by rjzhus** [comment]
apollo server 1.2.0

**Comment by rjzhus** [comment]
apollo server-side version 1.2.0 , client-side version 1.2.0/2.0.1

**Comment by rjzhus** [comment]
accesskey.secret会根据当前时间加密吗，目前三个环境dev uat sit，三个环境分别部署在不同的服务器上，三台机器除了时间其他均保持一致，其中dev 与 sit环境服务器时间与客户端都是保持一致的，没有出现密匙不生效的情况，只有uat所在服务器时间与客户端不一致，出现密匙不生效的情况

**Comment by nisiyong** [comment]
> apollo server-side version 1.2.0 , client-side version 1.2.0/2.0.1

The AccessKey feature was released in version 1.6.0, are you sure your server-side version is 1.2.0? https://github.com/apolloconfig/apollo/releases/tag/v1.6.0
