### ISSUE TITLE
打包后的应用是否会读取自己的app.properties？

### ISSUE THREAD

**Issue by mxian** [apolloconfig/apollo#4703]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我有一个应用A，和另一个应用B，各有自己的app.properties，都有方法会调用到Apollo。我把B打包，A在pom里依赖B。

可为什么A应用在调用B应用方法的时候，B应用加载的app.properties是A的呢？为什么B不读自己的app.properties文件？

是我哪里做错了吗，有什么办法吗？

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by mxian** [comment]
AB单独跑，都正常；
A依赖B，B就会读到A的appid。。。

**Comment by nisiyong** [comment]
That's not good practice, one JVM process could only associate with one Apollo app.
