### ISSUE TITLE
apollo本地IDE使用assembly启动 configservice和adminservice，报错InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by AyraStark077** [apolloconfig/apollo#4706]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**通过IDEA在本地，参考开发手册，使用assembly启动configservice和adminservice，启动报错。搜索后发现spring boot社区曾经提过这个问题，参考：https://github.com/spring-projects/spring-boot/issues/31804 **

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 启动类com.ctrip.framework.apollo.assembly.ApolloApplication，VM Options：-Dapollo_profile=github
-Dspring.datasource.url=jdbc:mysql://xxx/ApolloConfigDB?characterEncoding=utf8
-Dspring.datasource.username=xxx
-Dspring.datasource.password=xxx
-Dlogging.file.name=/xxx/log/apollo/apollo-assembly.log
Program arguments：--configservice --adminservice
2. 直接启动

**期望**

正常启动

**截图**

![image](https://user-images.githubusercontent.com/44752248/213097520-bcd348b7-8624-4cfc-9cd4-e19fd0a241da.png)

### 额外的细节和日志

- 版本：springboot版本：2.6.8
Java 11.0.9.1
Mysql：5.7.2

- 错误日志
- org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmxMBeanExporter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/jmx/JmxEndpointAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jmx.export.MBeanExportException: Failed to register MBean for endpoint 'beans'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=Beans,context=73eb8672
- 配置：
- 平台和操作系统：MAC，本地IDE

**Comment by AyraStark077** [comment]
springboot issue：https://github.com/spring-projects/spring-boot/issues/31718

**Comment by nobodyiam** [comment]
I can't reproduce this issue but It looks like an issue with JMX, is there any other config you didn't mention in the issue?

**Comment by shuohao** [comment]
> * [x]  我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
> * [x]  我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
> * [x]  我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)
> 
> **通过IDEA在本地，参考开发手册，使用assembly启动configservice和adminservice，启动报错。搜索后发现spring boot社区曾经提过这个问题，参考：[spring-projects/spring-boot#31804](https://github.com/spring-projects/spring-boot/issues/31804) **
> 
> 简洁明了地描述一下bug
> 
> **复现**
> 
> 通过如下步骤可以复现：
> 
> 1. 启动类com.ctrip.framework.apollo.assembly.ApolloApplication，VM Options：-Dapollo_profile=github
>    -Dspring.datasource.url=jdbc:mysql://xxx/ApolloConfigDB?characterEncoding=utf8
>    -Dspring.datasource.username=xxx
>    -Dspring.datasource.password=xxx
>    -Dlogging.file.name=/xxx/log/apollo/apollo-assembly.log
>    Program arguments：--configservice --adminservice
> 2. 直接启动
> 
> **期望**
> 
> 正常启动
> 
> **截图**
> 
> ![image](https://user-images.githubusercontent.com/44752248/213097520-bcd348b7-8624-4cfc-9cd4-e19fd0a241da.png)
> 
> ### 额外的细节和日志
> * 版本：springboot版本：2.6.8
>   Java 11.0.9.1
>   Mysql：5.7.2
> * 错误日志
> * org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmxMBeanExporter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/jmx/JmxEndpointAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jmx.export.MBeanExportException: Failed to register MBean for endpoint 'beans'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=Beans,context=73eb8672
> * 配置：
> * 平台和操作系统：MAC，本地IDE

老哥后来解决了吗 我也遇到了
