### ISSUE TITLE
doc中oidc配置

### ISSUE THREAD

**Issue by Shelby-Jiao** [apolloconfig/apollo#4707]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
refer to: https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function?id=%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f%e4%b8%89%ef%bc%9a-%e6%8e%a5%e5%85%a5oidc

spring.security.oauth2.client.registration.registration-name.client-secret -> SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAME_VDISK_CLIENT_SECRET, 其中的registration key在环境变量中并没有正确体现，直接到了后面的REGISTRATION_NAME，同时多了VDISK这个key，是否是文档错误？

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
I think `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAME_VDISK_CLIENT_SECRET` could be any environment variable key that contains the secret? cc @vdisk-group

**Comment by Shelby-Jiao** [comment]
Do we need `VDISK` and `REGISTRATION` (not `REGISTRATION_NAME`) as well?
For instance if my config.yaml looks like as below
spring:
    security:
        oauth2:
            client:
                registration:
                    okta:
should it be `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET` or `SPRING_SECURITY_OAUTH2_CLIENT_OKTA_VDISK_CLIENT_SECRET`?

**Comment by vdisk-group** [comment]
> Do we need `VDISK` and `REGISTRATION` (not `REGISTRATION_NAME`) as well? For instance if my config.yaml looks like as below spring: security: oauth2: client: registration: okta: should it be `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET` or `SPRING_SECURITY_OAUTH2_CLIENT_OKTA_VDISK_CLIENT_SECRET`?

it should be `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_SECRET `

**Comment by vdisk-group** [comment]
> I think `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAME_VDISK_CLIENT_SECRET` could be any environment variable key that contains the secret? cc @vdisk-group

yes, the variable contains the secret such as `spring.datasource.password`、`spring.redis.password` can also be treated like this.
how about we add jasypt to centralized protect the variable contains the secret?
