### ISSUE TITLE
oidc登陆用户显示错误

### ISSUE THREAD

**Issue by Shelby-Jiao** [apolloconfig/apollo#4714]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

- context：使用okta作为oidc提供方，k8s+helm chart 部署

1. oidc登录成功，但登录用户显示为default（ID）格式，且已经设置过`user-display-name-claim-name`，数据库中新增用户见截图
2. okta中需要设置login/logout redirect url， 当正常登录时无问题，登出时apollo逻辑为重定向到ingress地址再跳转`/signin#logout`，但此种方式在配置oidc服务方redirect url时会导致无法退出到登录页面（oidc登出时url必须与实际跳转的首个地址一致，但登入登出都为ingress地址，会进入死循环）

**期望**

oidc登陆正确且显示正确，登入与登出可以由用户自行控制url或取消自动跳转

**截图**

数据库新增用户截图：
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/99865457/215302861-730b3701-5944-4dd2-8bc7-ff06a938fd4c.png">
okta与apollo user Info mapping:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/99865457/215302969-7997701a-cf7d-4ea0-864e-2922fe30757f.png">
application-oidc.yml:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/99865457/215303069-454e5608-8569-4913-9900-8b658c850a27.png">

### 额外的细节和日志

- 版本：2.0.0
- 错误日志: portal 正常，无日志
- 平台和操作系统：

**Comment by nobodyiam** [comment]
@vdisk-group Do you happen to have any experience in this topic?

**Comment by Shelby-Jiao** [comment]
@nobodyiam tried email/name/nickName, nothing changed but always the id itself
Thanks in advance!

**Comment by Shelby-Jiao** [comment]
Hi @nobodyiam @vdisk-group , any updates about this?

**Comment by vdisk-group** [comment]
> Hi @nobodyiam @vdisk-group , any updates about this?

please try this package and add the logging level config to the application-github.properties
```
logging.level.com.ctrip.framework.apollo.portal.spi.oidc.OidcAuthenticationSuccessEventListener=trace
```

https://github.com/vdisk-group/apollo/releases/tag/tag-oidc-debug-log

**Comment by Shelby-Jiao** [comment]
Hi @vdisk-group , thanks for the package but unfortunately we are not allowed to uploaded a package directly to a VM due to company's policy, would you provide a hotfix image or Docker file so that i can either use the debug image or build and push it to the docker-hub?
Thanks in advance!

**Comment by nobodyiam** [comment]
@Shelby-Jiao You may use this [docker file](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/docker/Dockerfile).

**Comment by Shelby-Jiao** [comment]
Hi @nobodyiam and @vdisk-group , build a debug image and tried to start portal, log file attached, any clues on it?
Thanks in advance!
[apollo-portal.txt](https://github.com/apolloconfig/apollo/files/10674200/apollo-portal.txt)

**Comment by vdisk-group** [comment]
> Hi @nobodyiam and @vdisk-group , build a debug image and tried to start portal, log file attached, any clues on it? Thanks in advance! [apollo-portal.txt](https://github.com/apolloconfig/apollo/files/10674200/apollo-portal.txt)

please add the session config to the `application-github.properties` and try again.
```
spring.session.store-type=none

```

**Comment by Shelby-Jiao** [comment]
[apollo-portal (2).txt](https://github.com/apolloconfig/apollo/files/10703584/apollo-portal.2.txt)

**Comment by vdisk-group** [comment]
> [apollo-portal (2).txt](https://github.com/apolloconfig/apollo/files/10703584/apollo-portal.2.txt)

please try this package

https://github.com/vdisk-group/apollo/releases/tag/tag-oidc-debug-log-2

**Comment by Shelby-Jiao** [comment]
[apollo-portal (4).txt](https://github.com/apolloconfig/apollo/files/10719297/apollo-portal.4.txt)

**Comment by vdisk-group** [comment]
> [apollo-portal (4).txt](https://github.com/apolloconfig/apollo/files/10719297/apollo-portal.4.txt)

please try this docker image `docker.io/vdisk/apollo-portal-oidc-debug-1:latest`
image digest `sha256:03e854b95fac34412d9bd73bb5346558293229447d08ab1efbf4b12c9c0771d4`

**Comment by Shelby-Jiao** [comment]
[apollo-portal (5).txt](https://github.com/apolloconfig/apollo/files/10779857/apollo-portal.5.txt)

**Comment by Shelby-Jiao** [comment]
seems like oidc provider didn't pass the profile to apollo, but still would you help locate the root cause ? Is it from provider profile mapping/pass side or apollo side?
Thanks!

**Comment by Shelby-Jiao** [comment]
Hi @nobodyiam @vdisk-group haven't heard you for the last few days, any update or anything i can help?

**Comment by vdisk-group** [comment]
it seems that the okta do not provider the email by default, you should add the `email` scope to the config

application-oidc.yml
```
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            scope:
              - openid
              # add this scope to get the okta user's email address
              - email

```
