### ISSUE TITLE
一台机器上同一个APPID部署多实例，配置并发写入本地缓存文件出现错乱问题

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4727]
一台机器上同一个APPID部署多实例，配置并发写入本地缓存文件出现错乱问题，看看是不是使用mv的方式更稳妥点？
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/9474302/217503694-43c5b582-fdcb-4ac7-bb0e-ce995e6dfa0e.png">

**Comment by nobodyiam** [comment]
It's not a common use case to deploy multiple instances with the same appid in one machine.
But I think we are open to a fix to this issue.
