### ISSUE TITLE
使用疑问，多节点部署如何填写 eureka.service.url 

### ISSUE THREAD

**Issue by 0xc9e36** [apolloconfig/apollo#4731]
假如 configservice 部署了 3 个 docker 节点， 对外是 nginx 做负载均衡用域名 xxx 访问。 服务注册的时候 config db 中 eureka.service.url  是填写域名 xxx 吗 ？ 还是要把 3 个 docker 节点的 ip端口填进去，那岂不是每次容器重启就变了

**Comment by nobodyiam** [comment]
> 服务注册的时候 config db 中 eureka.service.url 是填写域名 xxx 吗 ？ 还是要把 3 个 docker 节点的 ip端口填进去

要把 3 个 docker 节点的 ip端口填进去

> 那岂不是每次容器重启就变了

如果容器无法保持 ip 的话是有这个问题，可以参考[使用其它服务注册中心替换内置eureka](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_223-%e4%bd%bf%e7%94%a8%e5%85%b6%e5%ae%83%e6%9c%8d%e5%8a%a1%e6%b3%a8%e5%86%8c%e4%b8%ad%e5%bf%83%e6%9b%bf%e6%8d%a2%e5%86%85%e7%bd%aeeureka)
