### ISSUE TITLE
灰度删除主版本配置

### ISSUE THREAD

**Issue by wanggang19** [apolloconfig/apollo#4732]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/20056551/218417063-1ce5f108-7362-4c70-a9c0-0e53dde6acea.png">
#1218 @nobodyiam 之前宋老板也解答过这个问题，通过修改为默认配置解决。但是有一个场景，比如某个配置已经不在使用，但是又不是非常确定，希望在灰度删除这个配置进行验证，如果没什么问题再推广到所有生产应用。 
不在灰度做主版本配置删除的原因，或者可能出现的坑是什么呢？

**Comment by nobodyiam** [comment]
see #3891

**Comment by wanggang19** [comment]
> see #3891, but I think we may add the feature to the UI too.

ok, thanks
