### ISSUE TITLE
adminservice 和configserver绑定公网ip后无法使用

### ISSUE THREAD

**Issue by amigo267** [apolloconfig/apollo#4733]
![image](https://user-images.githubusercontent.com/38553785/218748702-2afba6f9-fe41-4b1a-a45c-2ca8e02a2df2.png)
![image](https://user-images.githubusercontent.com/38553785/218748948-05cf3dcc-6f21-4655-a208-34208e9973aa.png)
![image](https://user-images.githubusercontent.com/38553785/218749112-ba478b9c-1ecd-44ac-ad08-d2c65a3127ad.png)

**Comment by nobodyiam** [comment]
You may check the system information page for more information.

![image](https://user-images.githubusercontent.com/837658/218902585-2430b10d-6f94-4bb6-94e8-f99373451d30.png)

**Comment by amigo267** [comment]
![image](https://user-images.githubusercontent.com/38553785/218905647-893c4975-4673-4ead-8aff-bd4c0ce6230d.png)
![image](https://user-images.githubusercontent.com/38553785/218905736-c8974bce-c8bd-4ed7-9970-4ea98584be36.png)

**Comment by amigo267** [comment]
@nobodyiam check success

**Comment by amigo267** [comment]
apollo-portal log
![image](https://user-images.githubusercontent.com/38553785/218906454-36fb014b-e2dd-4f1f-8376-24a97d8e0f1c.png)

**Comment by nobodyiam** [comment]
You need to also check the admin service logs.
