### ISSUE TITLE
openapi 如何增加带斜杠的key

### ISSUE THREAD

**Issue by JJohnsonGe** [apolloconfig/apollo#4734]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

如何使用openapi 增加带有斜杠的key（比如：  r.q@/x/y/z), 目前调用api增加会爆400错误。

**Comment by nobodyiam** [comment]
I believe it's fixed in v2.1.0, see #4549
