### ISSUE TITLE
k8s部署2.1.0版本无法关闭共享session

### ISSUE THREAD

**Issue by schooljenry** [apolloconfig/apollo#4735]
我在k8s使用docker方式部署时，总是出现“”更新失败，你的登录信息已过期“，之前有人提过关闭session就可以，但是关闭了也是不行。还是一直提示，就是这个配置信息的问题，而且只针对于mysql ”spring.datasource.url = jdbc:mysql:“.
我在怀疑是我k8s启动docker时的参数设置不对，还是这里是个bug?

**Comment by nobodyiam** [comment]
这个一般是由于 portal 多个登录 session 没有共享所致，一种方式是[开启共享 session](https://www.apolloconfig.com/#/zh/development/portal-how-to-enable-session-store)，v1.9.0 版本开始应该默认开启的，另一种是[配置 session sticky](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241448-%e4%bb%a5ingress%e9%85%8d%e7%bd%aesession-affinity%e5%bd%a2%e5%bc%8f%e6%9a%b4%e9%9c%b2%e6%9c%8d%e5%8a%a1)，让同一个 session 始终访问到同一台 portal 上。
