### ISSUE TITLE
目前namespace缓存到本地机器的配置内容是明文存储，对于应用APPID存储一些数据库或者支付账号比较敏感的数据，缓存到本地文件是明文的话，存在泄露风险，这个是否可以支持本地密文存储呢？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4736]
目前namespace缓存到本地机器的配置内容是明文存储，对于应用APPID存储一些数据库或者支付账号比较敏感的数据，缓存到本地文件是明文的话，存在泄露风险，这个是否可以支持本地密文存储呢？

**Comment by nobodyiam** [comment]
密文存储需要一个密钥，那就又涉及这个密钥的分发了，所以本质问题还不是明文存储，而是敏感配置从配置到分发一系列的过程，之前有个讨论可以看下 #3187
