### ISSUE TITLE
eureka开启了访问认证 apollo.eureka.server.security.enabled=true 同时设置了账号密码启动的时候日志也显示我开启了访问控制但是我把密码写错却也可以注册

### ISSUE THREAD

**Issue by xieshengxuan** [apolloconfig/apollo#4737]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by xieshengxuan** [comment]
apollo.eureka.server.security.username=xxx
apollo.eureka.server.security.password=xxx
以上两个字段我设置了密码 
我eurka地址http://xxxx:xxxxx@apollo-configservice-0.apollo-configservice.apollo.svc.cluster.local:8080/eureka/,http:///xxxx:xxxxx@apollo-configservice-1.apollo-configservice.apollo.svc.cluster.local:8080/eureka/
注册地址的中的账号密码错误的也可以注册
我的版本是2.1.0

**Comment by nobodyiam** [comment]
Did you also set the `apollo.eureka.server.security.enabled=true`?

**Comment by yuechangyuan** [comment]
我也是2.1.0  使用quick start 的docker启动 
ServerConfig表中设置了

    ('eureka.service.url', 'default', 'http://root:123456@localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
    ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
    ('item.key.length.limit', 'default', '128', 'item key 最大长度限制'),
    ('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
		('eureka.server.security.enabled','default','true','true'),
		('eureka.server.security.username','default','root','root'),
		('eureka.server.security.password','default','123456','123456'),
    ('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！');

但是访问127.0.0.1:8080 可以直接访问 不需要认证

**Comment by yuechangyuan** [comment]
我也是2.1.0 使用quick start 的docker启动
ServerConfig表中设置了

INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('eureka.service.url', 'default', 'http://root:123456@localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
    ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
    ('item.key.length.limit', 'default', '128', 'item key 最大长度限制'),
    ('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
		('apollo.eureka.server.security.enabled','default','true','true'),
		('apollo.eureka.server.security.username','default','root','root'),
		('apollo.eureka.server.security.password','default','123456','123456'),
    ('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！');


但是访问127.0.0.1:8080 可以直接访问 不需要认证

**Comment by yuechangyuan** [comment]
我2.1.0版本，使用quick start 的docker启动
配置如下

INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('eureka.service.url', 'default', 'http://root:123456@localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
    ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
    ('item.key.length.limit', 'default', '128', 'item key 最大长度限制'),
    ('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
		('apollo.eureka.server.security.enabled','default','true','true'),
		('apollo.eureka.server.security.username','default','root','root'),
		('apollo.eureka.server.security.password','default','123456','123456'),
    ('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！');


访问127.0.0.1:8080 仍然不需要认证 就可以直接访问

**Comment by yuechangyuan** [comment]
我2.1.0版本，使用quick start 的docker启动
配置如下

INSERT INTO ServerConfig (Key, Cluster, Value, Comment)
VALUES
('eureka.service.url', 'default', 'http://root:123456@localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
('item.key.length.limit', 'default', '128', 'item key 最大长度限制'),
('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
('apollo.eureka.server.security.enabled','default','true','true'),
('apollo.eureka.server.security.username','default','root','root'),
('apollo.eureka.server.security.password','default','123456','123456'),
('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！');

访问127.0.0.1:8080 仍然不需要认证 就可以直接访问

**Comment by nobodyiam** [comment]
1. the eureka security configs need a reboot after modification
2. the quick start [demo.sh](https://github.com/apolloconfig/apollo-quick-start/blob/007fd258a963396079f19d7426b3f74ca62ebce7/demo.sh#L55) currently hardcodes the eureka.service.url, so that the config in the database won't be effective
3. I would suggest you use the distributed version to test this feature
