### ISSUE TITLE
bootstrap.yml文件在哪里

### ISSUE THREAD

**Issue by Disciplining** [apolloconfig/apollo#4739]
[部署&开发遇到的常见问题](https://github.com/apolloconfig/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-admin-server-%E6%88%96%E8%80%85-config-server-%E6%B3%A8%E5%86%8C%E4%BA%86%E5%86%85%E7%BD%91ip%E5%AF%BC%E8%87%B4portal%E6%88%96%E8%80%85client%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86admin-server%E6%88%96config-server)中![图片](https://dl-web.dropbox.com/s/g97gje257fp6439/_00959b3bcd9_Xnip2023-02-17_17-17-10.jpg)
这个`bootstrap.yml`文件在哪里，下载下来源码没有看到，是需要自己创建吗.

**Comment by nobodyiam** [comment]
Please refer the [latest document](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_3-admin-server-%e6%88%96%e8%80%85-config-server-%e6%b3%a8%e5%86%8c%e4%ba%86%e5%86%85%e7%bd%91ip%ef%bc%8c%e5%af%bc%e8%87%b4portal%e6%88%96%e8%80%85client%e8%ae%bf%e9%97%ae%e4%b8%8d%e4%ba%86admin-server%e6%88%96config-server) in apolloconfig.com
