### ISSUE TITLE
docker升级到2.1.0后，有些页面元素没有中文吗？

### ISSUE THREAD

**Issue by mxian** [apolloconfig/apollo#4741]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
我从2.0.1升级到了2.1.0，发现有些页面的元素直接没有中文了，这需要怎么解决呢？
简洁明了地描述一下bug
![image](https://user-images.githubusercontent.com/15435279/220814901-57233502-a7f9-495c-ba4d-ca08ffb419e4.png)

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
语言文件有一天的缓存（Cache-Control: max-age=86400），强刷一下或者等第二天就会更新了。

**Comment by mxian** [comment]
> 语言文件有一天的缓存（Cache-Control: max-age=86400），强刷一下或者等第二天就会更新了。

的确好了，谢谢哦！
