### ISSUE TITLE
升级到2.1.0后，系统参数页面打开404了

### ISSUE THREAD

**Issue by mxian** [apolloconfig/apollo#4742]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug
![image](https://user-images.githubusercontent.com/15435279/220816846-4067eec4-8059-4337-9d96-c2fd1c21f386.png)

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
url 有变化（/server_config_manage.html），从管理员菜单重新进入吧

**Comment by mxian** [comment]
> url 有变化（/server_config_manage.html），从管理员菜单重新进入吧

好了，谢谢哦
