### ISSUE TITLE
请问当前有版本支持客户端https 拉取配置吗

### ISSUE THREAD

**Issue by weMystic** [apolloconfig/apollo#4744]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
客户端应该没有限制 http 还是 https

**Comment by weMystic** [comment]
我指的是客户端向服务端发起拉取配置请求时，可以通过https吗，就是服务端有没有提供ssl能力

**Comment by nobodyiam** [comment]
see #4636
