### ISSUE TITLE
如何关联一个非default环境的公共namespace

### ISSUE THREAD

**Issue by scSZn** [apolloconfig/apollo#4747]
背景如下：
我创建了两个应用，一个应用1，一个应用2。两个应用均只有一个DEV环境，同时在DEV环境下有集群default和集群SHANGHAI，两个应用都有
现在我在应用1的DEV环境下创建一个公共的Namespace，命名为public，此时它会同时出现在default集群和SHANGHAI集群中，并且互相不影响
然后我在应用2创建一个关联Namespace，不管是在default集群还是SHANGHAI集群，都只能关联到应用1的default集群的public命名空间，无法关联到应用1的SHANGHAI集群的public命名空间

**Comment by scSZn** [comment]
想知道如何让它们对应起来。即
应用2->DEV环境->default集群->public关联命名空间   与   应用1->DEV环境->default集群->public公共命名空间对应  
应用2->DEV环境->SHANGHAI集群->public关联命名空间   与   应用1->DEV环境->SHANGHAI集群->public公共命名空间对应

**Comment by nobodyiam** [comment]
可以看下[4.4.2 公共组件配置的获取规则](https://www.apolloconfig.com/#/zh/design/apollo-introduction?id=_442-%e5%85%ac%e5%85%b1%e7%bb%84%e4%bb%b6%e9%85%8d%e7%bd%ae%e7%9a%84%e8%8e%b7%e5%8f%96%e8%a7%84%e5%88%99)
