### ISSUE TITLE
apolloPortal启动后一直报健康检查超时，排除网络原因

### ISSUE THREAD

**Issue by willing4858** [apolloconfig/apollo#4770]
apollo 2.1.0 版本，centos7.x，portal，adminservice、configservice都正常启动，apolloo配置中心可以正常使用，只是portal日志一直报这个错，不知道是什么问题，倒是不影响apollo的使用，排除网络原因，portal，adminservice、configservice都部署在一台服务器上
![image](https://user-images.githubusercontent.com/99638915/222740864-b666c7ea-e79f-46ab-bb9e-50653866849e.png)
但是 curl http://192.168.1.6:8090/health 有返回结果，
![image](https://user-images.githubusercontent.com/99638915/222742295-af7b3753-4d88-4752-85cc-b4c59074eb2e.png)

**Comment by nobodyiam** [comment]
建议看下服务器 cpu/mem 和 gc 情况。

**Comment by willing4858** [comment]
![image](https://user-images.githubusercontent.com/99638915/222872012-c8f1bcf4-f5f4-483f-8574-ac92f42fe538.png)
![image](https://user-images.githubusercontent.com/99638915/222872110-08785c39-7d82-406c-a5b9-a3f76733dd12.png)

**Comment by willing4858** [comment]
![image](https://user-images.githubusercontent.com/99638915/222873361-0847bcbc-e439-45fa-ab1d-0c0a35ffa885.png)

**Comment by willing4858** [comment]
这是portal 的gc的日志

**Comment by willing4858** [comment]
这是portal 的g
[gc.txt](https://github.com/apolloconfig/apollo/files/10887367/gc.txt)
c的日志

**Comment by willing4858** [comment]
[gc.txt](https://github.com/apolloconfig/apollo/files/10887368/gc.txt)
这是portal的gc日志

**Comment by willing4858** [comment]
![image](https://user-images.githubusercontent.com/99638915/222885652-409b6163-7ddd-42e9-a149-972cfe7a771e.png)
我将portal部署在另外一台cpu、mem很充足的机器上，也出现了这个问题，抓了包看了下，感觉没啥问题，有可能是请求的读写时间设置比较短的原因吗

**Comment by nobodyiam** [comment]
read timeout 默认是 10 秒

https://github.com/apolloconfig/apollo/blob/2f311ae79f36f45d39429814c66d248cd7a69959/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/config/PortalConfig.java#L168-L170

**Comment by willing4858** [comment]
暂时没有定位到原因，不过整体不影响apollo功能的使用，只是portal日志一直在报健康检查failed
