### ISSUE TITLE
继承yml格式的 后覆盖属性, 再删除覆盖属性,会报错!

### ISSUE THREAD

**Issue by AugustFire** [apolloconfig/apollo#4777]
Apollo版本: 2.0.1
复现步骤
1.创建公共项目 common.yml公共的配置文件
2.创建私有项目, 关联common.yml
3.使用覆盖功能,覆盖common.yml的一个属性  -> 发布配置
4.删除刚才覆盖的属性 -> 发布配置

结果:
服务读取不到刚才覆盖的属性的 ,项目报错

**Comment by nobodyiam** [comment]
This is the current behavior, see #3815.
To retrieve the common.yml configuration from public namespace, you need to delete the associated namespace.

![image](https://user-images.githubusercontent.com/837658/223289851-0ce66668-8a12-4aab-9e32-8b5b2d416b8e.png)

**Comment by AugustFire** [comment]
thanks
