### ISSUE TITLE
Kubernetes多命名空间下部署 portal下系统信息

### ISSUE THREAD

**Issue by YoLoveLife** [apolloconfig/apollo#4787]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**疑问**
我详细阅读了 #3054 下针对kubernetes集群下部署apollo的相关架构分享，我有一些疑问希望能够得到解答。
我没有使用helm的方式在Kubernetes集群中部署apollo，而选择将原本部署宿主机的方式自行打包Docker镜像进行部署。

发现一些问题，使用 #3054 当中的架构图部署后发现：portal中的系统信息一栏，针对configService和adminService的信息是否已不再适用于该部署场景。因为使用Kubernetes的Service作为服务发现，configService和adminService在portal系统信息一栏的注册应该是依赖于Eureka的，而在该架构下Eureka已经不被需要了，所以多pods的configService和adminService也不会在系统信息一栏进行展现，而是在本身配置中心的使用高可用上是存在多副本可用。

或者说提个建议，针对Kubernetes集群下apollo配置读取，提供两种解决方案：（1）使用Service，对客户端始终是一个IP地址。（2）
可配置使用Headless，客户端侧针对对应的域名进行解析获取，如果出现多A记录的HeadlessService，同时纳为可用，在这种使用情况下， #3054 提到的 *客户端不再有负载均衡逻辑，灵活度有所降低*，这个缺点就可以解决了。

不知道我对于Kubernetes架构下的apollo部署使用是否有误解的地方。目前我已经部署完毕，我将portal单独部署于一个namespace，我们的项目使用namespace作为环境区分，所以每一个namespace下都有独立的config和admin，portal对于meta的获取是使用Service的，portal是可以看到对应环境下的admin，但是看不到对应环境下的config。使用golang读取配置仍旧是失败的状态，portal\config\admin都是正常运行，未出现任何错误日志，我仍旧在排查相关的错误，是否我在apollo的Kubernetes集群下部署存在误解，希望能得到一些帮助。

**Comment by nobodyiam** [comment]
1. helm chart 部署模式[去除了 eureka](https://github.com/apolloconfig/apollo-helm-chart/blob/aaf8dcec4d164a798446208d94949d8f3e564064/apollo-service/values.yaml#L65)，改为使用 kubernetes 原生的 service 作为 config servcie 和 admin service 对外访问的入口
2. helm chart 部署模式保留了 meta service 的角色，返回 config service/admin service 的 kubernetes service 地址，从而对 apollo-client 和 apollo-portal 实现透明

**Comment by YoLoveLife** [comment]
去除eureka是否是通过启动参数实现的。

**Comment by YoLoveLife** [comment]
实际尝试了一下使用helm来进行部署，发现helm可支持自定义化已经完全不需要自行构建镜像来进行部署。
