### ISSUE TITLE
开放平台第三方应用调用问题

### ISSUE THREAD

**Issue by alongzou** [apolloconfig/apollo#4796]
在开放平台中创建了第三方应用,拿到了token,也给token授了权,但是在使用openapi时,比如给某个namespace增加修改item时,需要传一个用户名,那么这个用户也是需要创建的吗?但我的需求是只是让第三方可以使用api来修改配置,不希望他们能登录到apollo,另外我们用户使用的是AD账号登录,请指点,谢谢!

**Comment by nobodyiam** [comment]
The user name is used for the audit and display purpose, so it's better to pass in the real user id or it won't be displayed properly in the apollo ui.

**Comment by klboke** [comment]
@alongzou https://github.com/apolloconfig/apollo/issues/4240
