### ISSUE TITLE
为什么apollo配置中心针对每个环境下的app可以设置5个密钥？

### ISSUE THREAD

**Issue by hekang123456** [apolloconfig/apollo#4797]
**为什么apollo配置中心针对每个环境下的app可以设置5个密钥**
什么场景下会用到5个密钥呢？而不是只设置一个密钥？

**Comment by nobodyiam** [comment]
One use case is the secret rotation scenario.

**Comment by hekang123456** [comment]
@nobodyiam  thank you very much!!
