### ISSUE TITLE
MetaServer访问控制

### ISSUE THREAD

**Issue by EashShow** [apolloconfig/apollo#4798]
**你的特性请求和某个问题有关吗？请描述**

我的Apollo配置中心要支持放在公网，不同的机房都可以访问

**清晰简洁地描述一下你希望的解决方案**

我希望
  "Apollo": {
    "AppId": "UIMS",
    "Env": "DEV",
    "MetaServer": "http://192.168.101.30:8080/"
  }

这里面的MetaServer支持密钥访问，否则安全性会存在问题

**清晰简洁地描述一下这个特性的备选方案**

或者现在是不是已经有了支持特性可以直接使用的？

**其它背景**

无

**Comment by nobodyiam** [comment]
What's the security issue of meta server? 

BTW, you may reference [7.1.3 System access](https://www.apolloconfig.com/#/en/usage/apollo-user-guide?id=_713-system-access) for more information on how to secure apollo-configservice and apollo-adminservice.

**Comment by EashShow** [comment]
比如我的配置中心部署在公网，面向多个机房。或者是在局域网内，但是并不是面向所有服务都开放的。
这样，便有一个安全性的问题，未授权的机房，也可以使用Apollo上的配置，这样就很危险了。
如果在配置文件中增加一个AccessKey之类的，连接Apollo获取配置的时候，Apollo会校验这个AccessKey，如果不是授权的Key，那么就不让接入获取配置信息，这样就很大程序上规避了这个安全性的问题了。

**Comment by Anilople** [comment]
Meta Server cannot return the config, it only use for service discovery.
