### ISSUE TITLE
Role ReleaseNamespace+infra+config+prod doesn't exist! 500 error

### ISSUE THREAD

**Issue by aarono0** [apolloconfig/apollo#4808]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

通过session的方式调用api给用户添加权限，出现500错误信息：
```
{"exception":"java.lang.IllegalStateException","message":"Role Role ReleaseNamespace+infra+config+prod doesn't exist!","status":500,"timestamp":"2023-03-20T18:25:28.662"}'
```
**复现**

通过如下步骤可以复现：

1.使用session的方式调用以下接口进行权限添加，
请求方式：self.session.post(url=modifynamespace, data=username)
url: http://apollo.demo.com/apps/$appname/envs/$env/namespaces/$ns/roles/ReleaseNamespace
2. 返回值：
{"exception":"java.lang.IllegalStateException","message":"Role ReleaseNamespace+infra+config+prod doesn't exist!","status":500,"timestamp":"2023-03-20T18:25:28.662"}
3.通过select方式过滤数据库中确实没有这条记录。

**期望**

如果数据库中没有role所需信息的话,需要怎么做才可以进行role自动创建?

### 额外的细节和日志

- 版本：1.9.1
- 配置：java-1.8、mysql-5.7.39
- 平台和操作系统：centos 7 x86_64

**Comment by aarono0** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
It should be initialized when the app was first created. If not, there is also a controller to initiate it.

https://github.com/apolloconfig/apollo/blob/196c8f9ab7ba3144d28bdc28eb1db5ff3ae3056f/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/PermissionController.java#L76-L80

**Comment by aarono0** [comment]
@nobodyiam 问题已解决，非常感谢！
