### ISSUE TITLE
在Apollo Portal上更新配置之后，Java客户端会使用老值进行更新。

### ISSUE THREAD

**Issue by JocelynFloresz** [apolloconfig/apollo#4814]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

在Apollo Portal上更新配置之后，Java客户端会使用老值进行更新。

**复现**

通过如下步骤可以复现：

1. Apollo Portal上更新配置
2. 
![企业微信截图_16797125993948](https://user-images.githubusercontent.com/52989209/227689439-edb54f0c-56b1-4f11-9f51-983044b8ae55.png)

3. 在Log打印上，使得的是更新前的值
4. 

**期望**

在Portal上更新值后，使用新值

**截图**
![企业微信截图_16797125993948](https://user-images.githubusercontent.com/52989209/227690011-aba0241d-f5d4-418a-89d2-1ceaec9b236a.png)

### 额外的细节和日志

- 版本：
  - ApolloConfig/Admin/Portal 2.1.0
  - Apollo Java依赖：1.5.1
- 错误日志：
- 配置：
- 平台和操作系统：Ubuntu Server 22.04

**Comment by nobodyiam** [comment]
Would you please describe this issue in more detail? e.g. the steps to duplicate this issue
