### ISSUE TITLE
使用官方k8s部署apollo时，是否有集群高可用方案

### ISSUE THREAD

**Issue by TickFairy** [apolloconfig/apollo#4827]
我再使用官方hemchart 部署apollo时，发现只是configService 和 adminService 复制数的变更，如果要部署高可用的集群，应该怎么配置呢

**Comment by nobodyiam** [comment]
config service 和 admin service 是无状态的服务，通过多副本就可以实现高可用了

**Comment by TickFairy** [comment]
谢谢 了解
