### ISSUE TITLE
Apollo客户端密钥不生效

### ISSUE THREAD

**Issue by hasaiki123** [apolloconfig/apollo#4830]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

Apollo版本2.1.0
java客户端版本2.1.0
我在portal中配置了应用的管理密钥，在客户端使用application.properties配置了apollo.access-key.secret
但是客户端启动后，出现 java.io.IOException:Server return HTTP response code:401
无法读取到Apollo的配置

**复现**

通过如下步骤可以复现：

1. Apollo版本2.1.0，java客户端版本2.1.0
2. portal中配置了应用的管理密钥
3. 客户端使用application.properties配置了apollo.access-key.secret
4. 启动客户端

**期望**

按照官网的描述，应该能正确获取到Apollo的配置

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by hasaiki123** [comment]
我看到有人发布过这个issue
https://github.com/apolloconfig/apollo/issues/4702

**Comment by hasaiki123** [comment]
我在虚拟机部署的Apollo2.1.0，客户端在本地。本地和虚拟机存在时差，上面这个issue有提到时差会导致密钥不生效，我想知道这是否是真的？

**Comment by hasaiki123** [comment]
https://blog.csdn.net/qq_38385659/article/details/105292458
提到了使用密钥认证时，会在过滤器验证客户端发来的时间戳和本地时间戳在1分钟之内，
 ```
String timestamp = request.getHeader(Signature.HTTP_HEADER_TIMESTAMP);  
 String authorization = request.getHeader(Signature.HTTP_HEADER_AUTHORIZATION);   
  // 必须在一分钟内有效  
  if (!checkTimestamp(timestamp)) {  
    logger.warn("Invalid timestamp. appId={},timestamp={}", appId, timestamp);  
    response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "RequestTimeTooSkewed");  
    return;  
  }  

//调用方法
  private boolean checkTimestamp(String timestamp) {  
    long requestTimeMillis = 0L;  
    try {  
      requestTimeMillis = Long.parseLong(timestamp);  
    } catch (NumberFormatException e) {  
      // nothing to do  
    }  
  
    long x = System.currentTimeMillis() - requestTimeMillis;  
    return x <= TIMESTAMP_INTERVAL;  
  }  
```

我想知道为什么要添加必须小于1分钟的校验？这存在的意义是什么？

**Comment by nobodyiam** [comment]
This is a way to prevent [Replay attack](https://en.wikipedia.org/wiki/Replay_attack).

**Comment by hasaiki123** [comment]
> This is a way to prevent [Replay attack](https://en.wikipedia.org/wiki/Replay_attack).

okk, I see, thanks a lot.
