### ISSUE TITLE
使用疑问 xml获取<>都被转义成unicode

### ISSUE THREAD

**Issue by Xiepoder** [apolloconfig/apollo#4831]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
不论本机docker部署，还是官网demo都这个问题

http 方式，xml获取<>等都被转义成unicode

 http://[81.68.181.139:8080/configs/APP_RENT/DEV/dbc.xml](http://81.68.181.139:8080/configs/APP_RENT/DEV/dbc.xml)

**Comment by nobodyiam** [comment]
This is the java properties file spec, as it is stored in iso-8859-1 by default. It would be decoded back to <> if you retrieve the config via apollo sdk.
