### ISSUE TITLE
使用k8s部署Apollo时，eureka出现config-service是OUT_OF_SERVICE

### ISSUE THREAD

**Issue by hasaiki123** [apolloconfig/apollo#4836]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

使用k8s部署Apollo时，eureka出现config-service是OUT_OF_SERVICE

**复现**

通过如下步骤可以复现：

1. 在k8s部署了eureka
2. config-service设置了apollo_eureka_service_enabled=false
3. 在ApolloConfigDB.serverconfig.eureka.service.url中填入eureka的地址
4. 依次启动config-service、admin-service
4. 发现config-service在eureka的状态是out_of_service，admin-service在eureka的状态是up

**期望**

config-service在eureka的状态应该也是up

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
You may check the `/health` endpoint and the server logs for more information.

**Comment by hasaiki123** [comment]
是的，/health返回的也是out_of_service，我重新部署过几次，依旧每次eureka显示的是out_of_service

**Comment by hasaiki123** [comment]
通过在启动参数增加-Deureka.client.registerWithEureka=true -Deureka.client.fetch-registry=true 可以解决这个问题 
#4209

**Comment by nobodyiam** [comment]
Did you enable the kubernetes profile? Or would you please append the whole startup log?

**Comment by robin7chen** [comment]
在k8s中搭建apollo集群时，即使在启动参数中添加了-Deureka.client.registerWithEureka=true -Deureka.client.fetch-registry=true，依旧有部分config server是out of service

**Comment by kiraqjx** [comment]
```yaml
env:
  - name: JAVA_OPTS
    value: '-Deureka.client.registerWithEureka=true -Deureka.client.fetch-registry=true'
```
