### ISSUE TITLE
请问是否计划在 apollo-client SDK 中提供一个修改指定单 key 的接口呢？目前看只能修改整个文件。

### ISSUE THREAD

**Issue by cafeUncle** [apolloconfig/apollo#4837]
**你的特性请求和某个问题有关吗？请描述**

我们在大量使用 apollo-admin 页面进行配置修改，但部分需求期望由 api 触发配置更新、发布、回滚（即不期望使用开放平台第三方应用的方式 https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3210-%e6%96%b0%e5%a2%9e%e9%85%8d%e7%bd%ae%e6%8e%a5%e5%8f%a3）。

**清晰简洁地描述一下你希望的解决方案**
目前看 SDK 中只有 setConfigFile，没有单 key 的 setConfig。直接 set file 需要业务担心有并发覆盖问题，还需要业务在代码中实现队列或锁。

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

**Comment by nobodyiam** [comment]
OpenAPI 也提供了 SDK 的方式了：[2.4.2 Java应用通过apollo-openapi调用Apollo Open API](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_242-java%e5%ba%94%e7%94%a8%e9%80%9a%e8%bf%87apollo-openapi%e8%b0%83%e7%94%a8apollo-open-api)
