### ISSUE TITLE
请问apollo 2.1版本使用了哪些组件及版本

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4842]
请问apollo 2.1版本使用了哪些组件及版本，主要包括如下：
（1）spring boot和spring cloud版本。
（2）eureka版本。
（3）其他的组件及版本。
（4）主要的jar包版本。

**Comment by nobodyiam** [comment]
apollo is a maven project, so I believe you could retrieve these information from the `pom.xml`

**Comment by zihan524** [comment]
> apollo is a maven project, so I believe you could retrieve these information from the `pom.xml`

感谢大佬
