### ISSUE TITLE
无法创建超级管理员token

### ISSUE THREAD

**Issue by amigo267** [apolloconfig/apollo#4847]
业务场景：

几百个APPID 需要同时新增一个itme，并发布

目前已有的方案：

1、 手动一个一个点击
2、通过修改数据库（但是不知道ReleaseKey 的生成规则）

建议：

1、提供创建一个超级管理员token

**Comment by nobodyiam** [comment]
目前 openapi 还没有超级管理员的权限，主要是基于权限控制考虑，模型上应该是可以支持的。
你的问题有一个办法是通过 portal 的 http 接口进行操作，比如用超级管理员登录后获取 session id，然后通过程序调用修改和发布配置的接口。

**Comment by amigo267** [comment]
好的，我来试试
