### ISSUE TITLE
Apollo配置读取和配置同步机制

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4849]
各位大佬，小弟不懂代码，请教下关于apollo机制，看看是否正确。

1、配置读取顺序 
（1）客户端应用启动时，会从服务端读取配置，放到本地缓存（本地缓存目录也会放一份），客户端应用优先读取本地缓存配置，平时也都是读取本地缓存配置，这也大大节省了客户端应用频繁读取服务端造成额外的开销。
 （2）服务端故障情况下的表现 
1）客户端应用不重启时，都会从本地缓存读取配置，不影响客户端应用的使用。
 2）客户端应用重启时，会从本地缓存目录读取配置到本地缓存，不影响客户端应用的使用。 
3）删除客户端本地缓存目录，重启客户端应用，客户端应用无法读取到配置。
2、配置同步机制 
（1）客户端应用启动时，会从服务端同步配置，写到本地缓存和本地缓存目录。
 （2）配置推送--服务端配置发布时，会实时同步配置至客户端应用本地缓存和本地缓存目录。 
（3）配置拉取--客户端应用定时（默认5分钟）向服务端拉取数据，服务端如果没有更新，会返回304给客户端。 
（4）客户端与服务端长连接默认超时时间为60s，超时前服务端会向客户端发送信号以保证长连接不断开。

**Comment by zihan524** [comment]
@nobodyiam 烦请大神指教。

**Comment by nobodyiam** [comment]
看了下基本符合吧，具体可以再参考下[源码解析](https://www.iocoder.cn/categories/Apollo/)

**Comment by zihan524** [comment]
> 看了下基本符合吧，具体可以再参考下[源码解析](https://www.iocoder.cn/categories/Apollo/)

谢谢，我再研究下。
