### ISSUE TITLE
配置key的前面加一个空格，不会报冲突，但是查看的时候看不出来有空格，看起来就有相同多个配置项。

### ISSUE THREAD

**Issue by dailongling** [apolloconfig/apollo#4852]
**描述bug**

配置key的前面加一个空格，不会报冲突，但是查看的时候看不出来有空格，看起来就有相同多个配置项。

**复现**

通过如下步骤可以复现：

1. 例如已经有一条配置:abc = “123”
2. 这个时候再手动插入一条配置: abc = "345"（这个abc前面有一个或多个空格）
3. 插入第二条配置的时候不会报冲突错误
4. 查看配置的时候就能看到两条一样key为abc的配置 
key | Value
abc | "123"
abc | "345"

**期望**

插入“ abc”的时候，报与“abc” key冲突。

**Comment by nobodyiam** [comment]
Can you reproduce this issue in the [demo site](http://81.68.181.139/)? It seems I can't reproduce it...

**Comment by dailongling** [comment]
I am still using version 1.7, but the latest version seems to be fine. Thank you.
