### ISSUE TITLE
apollo-dbdata Service Unable to start

### ISSUE THREAD

**Issue by 1518648489** [apolloconfig/apollo#4855]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我使用官方的docker-compose部署在我的linux服务器，当我运行我的docker compose up命令之后 创建了三个容器，但是apollo-dbdata 这个容器是挂掉的 无法查看容器日志 请问这是怎么回事？是我操作错误 或者？

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
There should be logs in the stdout.
