### ISSUE TITLE
K8s多环境部署，potal获取其他集群的adminserivce地址是内部地址

### ISSUE THREAD

**Issue by hasaiki123** [apolloconfig/apollo#4857]
当前我有三个k8s集群，每一个对应一个apollo环境（部署了config+admin），portal是部署在这其中一个集群中，当我配置meta.server后，返回的admin-server是其他集群内部的ip地址，portal就访问失败。
1.我知道客户端如果连config-service可以跳过metaserver，请问portal可以跳过metaserver吗？
2.请问我这种架构下，最合理的配置方式是什么？
3.那看起来，在k8s部署模式下，config自带的eureka、metaserver是不是可以考虑取消掉，让client、portal直接使用k8s的service的服务发现能力。

**Comment by nobodyiam** [comment]
可以参考[2.4.1 基于Kubernetes原生服务发现](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241-%e5%9f%ba%e4%ba%8ekubernetes%e5%8e%9f%e7%94%9f%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0)
