### ISSUE TITLE
apollo-portal-2.1.0 前端操作进行关联公共Namespace后没有反应

### ISSUE THREAD

**Issue by Layfolk-zcy** [apolloconfig/apollo#4862]
![image](https://user-images.githubusercontent.com/59356890/236596554-3bbc46b6-0088-4b3a-a1d3-0386761b820d.png)

![image](https://user-images.githubusercontent.com/59356890/236596520-a851b9d5-eb8c-4032-92b1-188c16e9fc4f.png)

**Comment by nobodyiam** [comment]
Can you reproduce this issue in the [demo site](http://81.68.181.139/)?

**Comment by Layfolk-zcy** [comment]
> Can you reproduce this issue in the [demo site](http://81.68.181.139/)?

初次使用可能不太懂,按照官网的操作手册中没有成功
1、在对应集群中创建公共关联namespace时选择Namespace后返回
2、对应的公共namespace没有显示为关联(不知道是不是我理解有问题)

**Comment by nobodyiam** [comment]
看这个截图似乎没啥问题啊？

![image](https://github.com/apolloconfig/apollo/assets/837658/f3a3d898-b740-4dba-8c82-9ea8d44facf5)
