### ISSUE TITLE
apollo.bootstrap.enabled = false 写在哪才能禁用apollo？

### ISSUE THREAD

**Issue by jiandam55** [apolloconfig/apollo#4863]
我项目是二次开发，前人可能用的是apollo老版本，
没有yml
只找到一个apollo-env.properties，里面只有四句，apollo.bootstrap.enabled = false加到里面也不起作用：
dev.meta=http://192.168.8.1:8080
fat.meta=http://192.168.8.1:7070
uat.meta=http://192.168.8.1:6060
pro.meta=http://192.168.8.1:5050

**Comment by nobodyiam** [comment]
apollo 有多种客户端的用法，可以参考 [三、客户端用法](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=%e4%b8%89%e3%80%81%e5%ae%a2%e6%88%b7%e7%ab%af%e7%94%a8%e6%b3%95)
