### ISSUE TITLE
openAPI调用修改item值，如果key名称有特殊字符存在，会导致更新失败

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4867]
用户程序通过openAPI调用更新item接口，如
public void updateItem(String appId, String env, String clusterName, String namespaceName, OpenItemDTO itemDTO) {
    itemService.updateItem(appId, env, clusterName, namespaceName, itemDTO);
  }
其中，底层触发的http请求路径为："envs/%s/apps/%s/clusters/%s/namespaces/%s/items/%s"
如果key的名称是 Kong://hostrest/aaaa，那最终访问到的URL地址为   /openapi/v1/envs/TEST/apps/brpc/clusters/default/namespaces/brpc.kong_server_color/items/Kong://hostrest/aaaa，那调用接口就会解析失败。

**Comment by nobodyiam** [comment]
Would you please try [2.1.0](https://github.com/apolloconfig/apollo/releases/tag/v2.1.0), there are several fixes on the special key support in openapi.
