### ISSUE TITLE
发现基本类型检查功能存在缺陷，使用不方便

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#4868]
在properties格式中的namespace新增配置项后(配置项存在多种数据类型)，如图
<img width="1195" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/90b64018-b32d-4cee-8abc-d1a86870a867">
当通过文本模式修改后，发现所有的key的类型都变为了String类型，
<img width="1188" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/13b4e7ef-9a89-44af-a7e9-e7460981dd13">
这样导致在后边的编辑中，又要重新指定数据类型，极为繁琐。
<img width="1185" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/5c8d9637-bd19-44ba-9d7b-de8746024e12">

还有一点，目前该功能只在前端对值进行校验，后端没有对值的具体格式进行校验，存在校验风险。

**Comment by nobodyiam** [comment]
> 当通过文本模式修改后，发现所有的key的类型都变为了String类型，

This is a known issue. Do you have any suggestions on how to fix it?

**Comment by hezhaoye** [comment]
是否可以在提交更改的时候判断值是否有变化，如果没发生过变化的，就不要变更该key的类型？

**Comment by nobodyiam** [comment]
这倒是一个可行的方式，你有兴趣提交一个 PR 吗？
