### ISSUE TITLE
apollo-portal访问无效

### ISSUE THREAD

**Issue by liush2** [apolloconfig/apollo#4880]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 下载了apollo-2.1.0 源码，本地（mac)修改配置，三个模块都可以运行，本地浏览器可以访问 http://127.0.0.1:8070 打开管理后台
2.  修改数据库地址，以及服务端口，上传到服务器，三个模块都可以运行，访问 http://127.0.0.1:18080  http://127.0.0.1:18090 可以，访问http://127.0.0.1:18070 没有任务返回（服务器端口在最前面加了1）
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**
<img width="1666" alt="image" src="https://github.com/apolloconfig/apollo/assets/59461366/73a2be5a-d679-41fd-ad1e-0365b0144409">
<img width="1679" alt="image" src="https://github.com/apolloconfig/apollo/assets/59461366/2f60df11-d63f-4e30-9ad0-ea51bc3d65d0">
<img width="1676" alt="image" src="https://github.com/apolloconfig/apollo/assets/59461366/97f6e709-1195-49c4-a789-34eb30276bb5">

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
You may check the http reponse headers first?

**Comment by liush2** [comment]
<img width="1198" alt="image" src="https://github.com/apolloconfig/apollo/assets/59461366/92f237b6-d8be-4fc0-ada4-05059e63915d">   哭晕在厕所
