### ISSUE TITLE
配置发布后应用被重启

### ISSUE THREAD

**Issue by Piean** [apolloconfig/apollo#4881]
**描述bug**

修改配置发布后，应用中配置刷新成功，随后应用开始关闭重启

**复现**

通过如下步骤可以复现：

1.Spring Boot + Apollo 配置
2.成功注册到Apollo并读取到配置
3.在Apollo上修改配置并发布
4.AutoUpdateConfigChangeListener提示变量更新成功，随后应用开始关闭重启

**期望**

应用中配置变量刷新成功，但是应用不会被关闭重启

**截图**

![image](https://github.com/apolloconfig/apollo/assets/11806405/b5d343a0-8cd2-475d-9c68-0edbac4fb1c6)

### 额外的细节和日志

- 版本：Apollo-client 1.7.0
- 错误日志
- 配置：
app.id=xxxxx
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=false
apollo.meta=xxxxx
变量上使用的@Value(${xxxx})
- 平台和操作系统 Mac

**Comment by nobodyiam** [comment]
You may check if you use spring boot dev tools or use other refresh mechanisms like #4467.
