### ISSUE TITLE
apollo数据源支持从mysql变更为postgresql吗？

### ISSUE THREAD

**Issue by snailair** [apolloconfig/apollo#4882]

**Comment by snailair** [comment]
找到相同的主题了

**Comment by nobodyiam** [comment]
see #4751

**Comment by snailair** [comment]
> see #4751

请问Shoothzj开发的初始化pg的sql脚本支持apollo和pgsql的所有版本吗，还是某些指定版本？

**Comment by nobodyiam** [comment]
还在开发中，是基于最新版本开发的 cc @Shoothzj

**Comment by Shoothzj** [comment]
@snailair Yes, It's now based on master branch. I think the sql script is ok. Still need some works on code.

**Comment by snailair** [comment]
> 还在开发中，是基于最新版本开发的 cc @Shoothzj

好的，辛苦开发者的辛勤付出

> @snailair Yes, It's now based on master branch. I think the sql script is ok. Still need some works on code.

好的，辛苦开发者的辛勤付出

**Comment by MyGit-Z** [comment]
> 还在开发中，是基于最新版本开发的 cc @shoothzj



> see #4751

您好，我是一个新手。点进去您这个4751 不知道那个才是我需要的。 请您点拨一下，我是apollo 2.2.0,需要pg数据库的初始化sql
