### ISSUE TITLE
表结构字段增加唯一性约束

### ISSUE THREAD

**Issue by stringang** [apolloconfig/apollo#4883]
**清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦**

> 公司内部多套本地环境（dev/daily/uat/fat）采用的同一个 portal 进行管理，线上环境（prod-tx, prod-ali）均采用独立的 portal。
>
> 当我们接口去同步生产环境的应用信息到本地环境时，导致 portadb, configdb  库中这 4 张表中 `App`, `AppNamespace`, `Cluster`, `Namespace` 会存在重复的数据。只能手动操作重复数据进行 `isDeleted=1` 操作。
> 

**清晰简洁地描述一下你希望的解决方案**

> 增加唯一性约束

**Comment by nobodyiam** [comment]
Unique constraint index is available since [v2.0.0](https://github.com/apolloconfig/apollo/releases/tag/v2.0.0) release.

**Comment by stringang** [comment]
好的

@nobodyiam
