### ISSUE TITLE
“ConfigDB配置管理”环境列表显示报错，2.1.0版本“prod”环境标

### ISSUE THREAD

**Issue by wwwsky86** [apolloconfig/apollo#4884]
用的apollo 2.1.0 版本，遇到类似问题：
自定义了3个环境，“qa,pre,prod”
管理员工具-系统参数-ConfigDB配置管理，切换环境，“qa、pre” 显示正常
切到prod环境，报错:
message: "No available admin server. Maybe because of meta server down or all admin server down. Meta server address: [http://apollo.meta",status](http://apollo.meta%22%2Cstatus/): 500

三个环境的配置如下：

cat /opt/apollo/apollo-portal/config/apollo-env.properties |grep -vi "^#"
qa.meta=[http://10.10.209.67:8080,http://10.10.209.68:8080,http://10.10.209.69:8080](http://10.10.209.67:8080%2Chttp//10.10.209.68:8080,http://10.10.209.69:8080)
pre.meta=http://10.10.209.64:8080/
prod.meta=http://172.20.19.83:8080/

如果把 prod换成 pro 或 proda （修改：portal DB配置，apollo-env.properties），均为正常。ENV的关键字“PROD” 就报错
![WX20230523-173226](https://github.com/apolloconfig/apollo/assets/10069198/d8b9d3d2-7831-488c-b209-343f9d5e05f9)
![WX20230523-173317](https://github.com/apolloconfig/apollo/assets/10069198/8ed49e9b-86f3-4c0c-8648-8ea719d9aa45)

**Comment by nobodyiam** [comment]
Looks like there is some issue in the meta server config, you may check the System Information page.

![image](https://github.com/apolloconfig/apollo/assets/837658/746e2e61-c26e-4059-8af8-49b2a6e39149)

**Comment by wwwsky86** [comment]
![WX20230525-3333](https://github.com/apolloconfig/apollo/assets/10069198/528aaacb-6354-4202-aea1-e3ab4b267c9b)
![WX20230525-0111111](https://github.com/apolloconfig/apollo/assets/10069198/6827c83c-3c96-45d8-8a6a-ef9b0e26e509)

系统信息里，显示的数据是正常的。
只是管理员工具-系统参数-ConfigDB配置管理， 切到prod环境就报错

**Comment by nobodyiam** [comment]
prod 有一个特殊处理逻辑，看上去是之前的一次重构导致这段逻辑在某些场景没跑到，所以报错了。
可以通过配置环境名为 pro 绕过，具体修复在 #4887

**Comment by wwwsky86** [comment]
tks，下一个版本预计什么时候迭代

**Comment by maweibin** [comment]
@nobodyiam 
> prod 有一个特殊处理逻辑，看上去是之前的一次重构导致这段逻辑在某些场景没跑到，所以报错了。 可以通过配置环境名为 pro 绕过，具体修复在 [#4887](https://github.com/apolloconfig/apollo/pull/4887)

请问
1、 原来是prod，后面升级2.0版本，强制改为pro，页面的环境列表展示也强制为pro，这对以前的prod创建的数据会不会有什么影响
2、现在是不是没法在页面展示prod了，因为以前是prod，所以想要保持一致，避免用户有疑问

**Comment by nobodyiam** [comment]
> [@nobodyiam](https://github.com/nobodyiam)
> 
> > prod 有一个特殊处理逻辑，看上去是之前的一次重构导致这段逻辑在某些场景没跑到，所以报错了。 可以通过配置环境名为 pro 绕过，具体修复在 [#4887](https://github.com/apolloconfig/apollo/pull/4887)
> 
> 请问 1、 原来是prod，后面升级2.0版本，强制改为pro，页面的环境列表展示也强制为pro，这对以前的prod创建的数据会不会有什么影响 2、现在是不是没法在页面展示prod了，因为以前是prod，所以想要保持一致，避免用户有疑问

1. 环境名称只在接口访问寻址的时候用到，在数据中不会保存的，所以不会有影响
2. 只能展示 PRO
