### ISSUE TITLE
namespace配置项文本模式编辑保存时，能否加个与后端版本的比较

### ISSUE THREAD

**Issue by luyiArye** [apolloconfig/apollo#4885]
namespace配置项文本模式编辑保存是，如果页面未刷新，修改了配置项后保存，会出现把这期间其他人添加的配置项删除的情况。

**清晰简洁地描述一下你希望的解决方案**
前端缓存当前文本的版本，在保存时与服务端的版本最比较，如果版本小于服务端的版本则提示不允许保存，必须前端刷新页面后重新编辑配置保存，确保保存是不会出现与其他人修改的配置冲突。

**Comment by nobodyiam** [comment]
It's a good proposal, meanwhile, you may also enable the [namespace.lock.switch](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_322-namespacelockswitch-%e4%b8%80%e6%ac%a1%e5%8f%91%e5%b8%83%e5%8f%aa%e8%83%bd%e6%9c%89%e4%b8%80%e4%b8%aa%e4%ba%ba%e4%bf%ae%e6%94%b9%e5%bc%80%e5%85%b3%ef%bc%8c%e7%94%a8%e4%ba%8e%e5%8f%91%e5%b8%83%e5%ae%a1%e6%a0%b8) to achieve the similar effect.
