### ISSUE TITLE
关于应用的用户授权

### ISSUE THREAD

**Issue by xiangshen123** [apolloconfig/apollo#4892]
我在使用apollo2.1.0,其中有些建议看看能不能采纳，现在的授权方式是需要单独某个应用进行授权，这样繁琐的工作太多，能不能把权限归纳到一个组，比如研发组，将部分人加入研发组，将权限形成一个组，将应用也是形成一个组，然后把权限绑定到这个组，这样工作流程会大大简化。

**Comment by nobodyiam** [comment]
This is a good suggestion, see #2178
