### ISSUE TITLE
关于eureka.service.url  地址问题。

### ISSUE THREAD

**Issue by herozb** [apolloconfig/apollo#4893]
![image](https://github.com/apolloconfig/apollo/assets/10287576/29fce3bf-1e55-40d2-9f36-aa08e3502bb2)

我按照分布式部署文档搭建了admin、config并且成功启动，按照文档中的要求，需要在eureka.service.url的地址后边添加/eureka/的后缀，但是添加后缀之后，这个eureka是无法访问的。

![image](https://github.com/apolloconfig/apollo/assets/10287576/ae55f936-3446-4fea-8710-bc06c0a4b4c7)

不加/eureka/可以正常访问

![image](https://github.com/apolloconfig/apollo/assets/10287576/bd113259-9308-4190-b1eb-0f3abaf4fa16)

我就是想了解一下，这个eureka.service.url配置到底是否需要加后缀，还有就是那些应用或者client会调用这个key呢？带后缀的是否会出现调用失败的问题？

**Comment by herozb** [comment]
![image](https://github.com/apolloconfig/apollo/assets/10287576/aae63ef7-ebb9-4fa3-9fd3-3032fd088bff)

Meta Server只是一个逻辑角色，在部署时和Config Service是在一个JVM进程中的，所以IP、端口和Config Service一致。
目前Eureka在部署时和Config Service是在一个JVM进程中的。

上边两句话是部署文档中的，那么我是否可以使用上图的meta server地址 作为eureka.service.url这个的value呢？

我的版本是2.1

**Comment by nobodyiam** [comment]
8080 打开正常就 OK，/eureka 我记得 get 操作是 404 的

**Comment by herozb** [comment]
> 8080 打开正常就可以了，/eureka 我记得得到操作是 404 的

是的 get操作是404  我主要是想了解一下，程序中哪里会调用这个key（eureka.service.url ），如果调用了，带/eureka会有404，不会导致程序异常么？

**Comment by nobodyiam** [comment]
eureka client 会使用，它会再拼接路径的

**Comment by herozb** [comment]
> 



> eureka client 会使用，它会再拼接路径的

好的，感谢您的答复~
