### ISSUE TITLE
帅哥美女们打扰了，请问官方文档Java客户端使用指南——测试模式一节方便追加下junit5的版本吗

### ISSUE THREAD

**Issue by CennyMo** [apolloconfig/apollo#4894]
**你的特性请求和某个问题有关吗？请描述**
如标题，当前的测试模式指导是基于junit4的，升级到junit5的话，EmbeddedApollo初始化时不会执行@before和@After方法，除非将@before和@After改成@beforeEach和@AfterEach

**清晰简洁地描述一下你希望的解决方案**
出个junit5的EmbeddedApollo，或者文档说明该测试指导仅junit4有效

**清晰简洁地描述一下这个特性的备选方案**
对于使用junit5的用户：
test文件夹下新建一个Mock类如下
`public class EmbeddedApolloAdapter extends EmbeddedApollo implements AfterEachCallback, BeforeEachCallback {

    @Override
    public void afterEach(ExtensionContext extensionContext) throws Exception {
        super.after();
    }

    @Override
    public void beforeEach(ExtensionContext extensionContext) throws Exception {
        try {
            super.before();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }
}`

在SpringIntegrationTest内，将指导内的
`  @ClassRule
  public static EmbeddedApollo embeddedApollo = new EmbeddedApollo();`

修改为

`  @RegisterExtension
    public static EmbeddedApolloAdapter embeddedApolloAdapter = new EmbeddedApolloAdapter();`

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
I believe this pr should work for you: https://github.com/apolloconfig/apollo-java/pull/25

**Comment by CennyMo** [comment]
thanks！
