### ISSUE TITLE
apollo中文乱码

### ISSUE THREAD

**Issue by feiflown** [apolloconfig/apollo#4899]
apollo出现中文乱码
item表value会出现中文乱码；key则不会，但会在页面多展示一条乱码数据，且无法发布
如果直接修改item表的value字段为中文，则也无法进行发布
apollo版本号2.1.0
![img_20230608101140](https://github.com/apolloconfig/apollo/assets/107021435/e8d9e090-70a4-464f-952f-3a8a2db41cc5)
![img_20230608101154](https://github.com/apolloconfig/apollo/assets/107021435/87f20c2a-4e15-4de8-aabd-4c84e7901fcd)

**Comment by feiflown** [comment]
降版本2.0.1无该问题，但portal启动报错序列化IO异常，目前portal单独使用2.1.0的

**Comment by nobodyiam** [comment]
两个方面的问题可以看下
1. startup.sh 中 encoding 相关的配置
2. 数据库连接串上的 encoding 相关的配置

**Comment by feiflown** [comment]
都是utf-8格式的
