### ISSUE TITLE
为用户给单个namespace添加权限不生效

### ISSUE THREAD

**Issue by aarono0** [apolloconfig/apollo#4900]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

1.在apollo portal管理后台给单个用户添加某个应用单namespace的权限后，依然显示需要申请权限；
2.添加all environment权限后，显示有权限，但是如果去掉all environment授权，给单环境授权后依然没权限；

**期望**

不知道有没有相应的解决办法，比如改个参数之类的；

**截图**

![image](https://github.com/apolloconfig/apollo/assets/11747841/87f3cd89-cda9-492f-b2f9-934b26088b74)
![image](https://github.com/apolloconfig/apollo/assets/11747841/b347d88c-903f-48fa-87de-4ed79a7f7d44)
![image](https://github.com/apolloconfig/apollo/assets/11747841/cabc4537-f5a6-4149-abba-c1448b5e85eb)

### 额外的细节和日志

- 版本：1.9.1
- 平台和操作系统: centos7 x86_64

**Comment by aarono0** [comment]
application-github.properties:
```
# DataSource
spring.datasource.url = jdbc:mysql://x.x.x.x:3306/ApolloConfigDB?characterEncoding=utf8
spring.datasource.username = apollo
spring.datasource.password = xxxxxxxxxx
```

**Comment by nobodyiam** [comment]
看看服务端是否有啥报错日志？看起来可能是单环境的 role/permission 信息丢了，导致赋权没生效
可以看下[1.4.2 权限相关E-R Diagram](https://www.apolloconfig.com/#/zh/design/apollo-design?id=_142-%e6%9d%83%e9%99%90%e7%9b%b8%e5%85%b3e-r-diagram)以及[DefaultRolePermissionService](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java)
