### ISSUE TITLE
Apollo 2.1.0 版本使用configservice自带的eureka，实现了eureka server注册验证，为安全考虑，如何实现eureka 的管理界面的http basic 认证呢？

### ISSUE THREAD

**Issue by Jacky-cn** [apolloconfig/apollo#4901]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
apollo configservice 版本 2.1.0  使用的是官方的docker 版本。
首先：在configservice的数据库表（ServerConfig）中增加了：
apollo.eureka.server.security.enabled=true
apollo.eureka.server.security.username=test
apollo.eureka.server.security.password=test123
配置后，更新eureka service url，增加此账号密码后，configservice服务重启后正常注册。此时访问eureka地址如  http://xxxx:8080/  可以直接登录访问信息，无安全验证。

其次，我这边再次增加了eureka的基础验证配置到configservice数据库表ServerConfig中：
spring.security.basic.enable=true
spring.security.user.name=testr
spring.security.user.password=test123
此时，将configservice重启后，访问eureka地址如  http://xxxx:8080/ ，仍是直接登录了，没有安全验证。而且此时未修改eureka service url地址， configservice可以正常注册。

在 apollo.eureka.server.security.enabled=false   和spring.security.basic.enable=true，下，eureka仍不能http basic基础验证。

简洁明了地描述一下bug
1.apollo.eureka.server.security.enabled=true  和spring.security.basic.enable=true  ，此二项配置目前同时不能启用。请问：是否可以同时启用？如何分别启用？为什么？
2.如何才能实现eureka的管理界面的 http basic用户密码验证？
**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

实现eureka的http 页面basic用户密码验证的同时，还支持 eureka server 登录验证，保障应用注册和eureka http安全。

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
[3.2.9 apollo.eureka.server.security.enabled - 配置是否开启eureka server的登录认证](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_329-apolloeurekaserversecurityenabled-%e9%85%8d%e7%bd%ae%e6%98%af%e5%90%a6%e5%bc%80%e5%90%afeureka-server%e7%9a%84%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81)

这个配置控制 eureka 的注册需要认证（在 eureka.service.url 需要配置用户名和密码），访问 http://xxxx:8080/  是不受影响的

**Comment by Jacky-cn** [comment]
eureka的注册认证这个使用对应的参数和账号密码，（在 eureka.service.url 需要配置用户名和密码），这个是没有问题的。
目前就想看能否实现 eureka的注册认证的同时  直接访问 http://xxxx:8080/ 需要登录认证（用户密码的http basic） 怎么实现？也是需要必须去修改eureka的源码及配置文件后重新打jar包么？这个有官方的文档说明最好

**Comment by Jacky-cn** [comment]
目前在apollo官方文档，没有看到如何实现 eureka 的web见面，如何实现 http basic 基本用户认证的方法或参数说明。这个请补充下或给出官方的建议或解决方案

**Comment by Jacky-cn** [comment]
目前来看主要还是 configservice的接口或eureka的 访问其url   http://xxxx:8080/  的  http basic 基础认证如何实现或者能否实现？以及原因，所需的配置等。这个基础认证，主要是为了安全考虑，防止泄露 所注册的服务信息。对于configservice的这个http basic基础认证能否及如何实现，还请 整理及答复下。谢谢

**Comment by ethushiroha** [comment]
想知道为什么需要公开给所有客户端，而不是只有通过 basic 认证才能访问 http://xxx:8080/ 或 eureka 接口。

**Comment by YHuuuui** [comment]
我也遇到和你一样的问题，你是如何解决的？方便加个微信吗？我的微信号：moonshinelin，真心请教，问题已经困扰了我很久，望指导！

**Comment by zxy1994** [comment]
> 我也遇到和你一样的问题，你是如何解决的？加个微信吗？方便我的微信号：moonshinelin，真心请教，问题已经困扰了我很久，望指导！

可以采用 外置eureka来解决

1. 自己写一个带http basic认证的eureka服务
2. 关闭config-service里面内置的eureka
3. 配置eureka地址为自己的eureka服务地址，这个地址里面是带账号密码的，http://账号:密码@ip:端口/eureka
4. 修改数据库中的eureka.service.url 为 http://账号:密码@ip:端口/eureka

**Comment by ethushiroha** [comment]
> > 我也遇到和你一样的问题，你是如何解决的？加个微信吗？方便我的微信号：moonshinelin，真心请教，问题已经困扰了我很久，望指导！
> 
> 可以采用 外置eureka来解决
> 
> 1. 自己写一个带http basic认证的eureka服务
> 2. 关闭config-service里面内置的eureka
> 3. 配置eureka地址为自己的eureka服务地址，这个地址里面是带账号密码的，[http://账号:密码@ip:端口/eureka](http://%E8%B4%A6%E5%8F%B7:%E5%AF%86%E7%A0%81@ip:%E7%AB%AF%E5%8F%A3/eureka)
> 4. 修改数据库中的eureka.service.url 为 [http://账号:密码@ip:端口/eureka](http://%E8%B4%A6%E5%8F%B7:%E5%AF%86%E7%A0%81@ip:%E7%AB%AF%E5%8F%A3/eureka)

这就去 test 一下，谢谢师傅

**Comment by zxy1994** [comment]
> 

使用外置eureka时，配置有个参考链接，如下：
https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_8-%e5%b0%86config-service%e5%92%8cadmin-service%e6%b3%a8%e5%86%8c%e5%88%b0%e5%8d%95%e7%8b%ac%e7%9a%84eureka-server%e4%b8%8a

- 不过这个url必须配置为  http://账号:密码@ip:端口/eureka；

**Comment by jujunchen** [comment]
确实，看文档我以为也开启了eureka界面的登录验证，结果运维配好后，还是能直接访问
