### ISSUE TITLE
fix the 404 of document

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4903]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

Occur 404 when access:
* https://www.apolloconfig.com/#/zh/governance
* https://www.apolloconfig.com/#/zh/contributing
* https://www.apolloconfig.com/#/en/governance
* https://www.apolloconfig.com/#/en/contributing

**Expected behavior**
Show:
* https://github.com/apolloconfig/apollo/blob/master/GOVERNANCE.md for governance
* https://github.com/apolloconfig/apollo/blob/master/CONTRIBUTING.md for contributing

**Screenshots**

![image](https://github.com/apolloconfig/apollo/assets/15523186/c4c868ad-f9ce-4ba0-8a4f-477051c509f5)

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this

**Comment by nobodyiam** [comment]
It works well in my side.

I suspect the issue arises from network problems encountered when accessing the original files:
1. https://raw.githubusercontent.com/apolloconfig/apollo/master/GOVERNANCE.md
2. https://raw.githubusercontent.com/apolloconfig/apollo/master/CONTRIBUTING.md
