### ISSUE TITLE
apollo portal 2.0.1 版本出现 500 错误

### ISSUE THREAD

**Issue by tsiayutai** [apolloconfig/apollo#4904]
您好

最近升级 apollo 的版本从 1.3 -> 2.0.1 , 但升级后在 portal 点选 PRO 环境列表会一直出现 500 错误, 查看 portal  日志出现
duplicate key com.ctrip.framwork.apollo.portal.entity.bo.UserInfo, 有可能是数据库的哪个 key 有重复吗？

另外 1.3 版和 2.0.1 版的 portal 我们都有做二次开发, 有可能是二次开发造成的问题吗？

**Comment by nobodyiam** [comment]
2.0.0 版本增加了 Username 的唯一索引，可以看下是否相关

ALTER TABLE `Users`
    ADD UNIQUE INDEX `UK_Username` (`Username`);

**Comment by tsiayutai** [comment]
了解～
那请问Users 這個表紀錄的是本地帳號嗎?  因为我们是用 ldap 帐号做验证, 有可能是 users 表里面的用户名称和 ldap 那边用户帐号重复会造成的？

**Comment by nobodyiam** [comment]
ldap 应该直接连接 ldap 服务了，不会使用到 Users 表，建议看下 Users 表的数据，以及 ldap 的[配置](https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function?id=%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f%e4%ba%8c%ef%bc%9a-%e6%8e%a5%e5%85%a5ldap)是否正确

**Comment by tsiayutai** [comment]
另外请问一下, 我们从 1.3 升级到 2.0.1 , 再执行 sql delta   apolloportaldb-v190-v200-after.sql 一直遇到 UK 问题, permission 和 role 表里面有重复的资料, 请问这两张表的重复的数据能删除吗？   还是能将 UK 拿掉后再导入 sql 语法？

**Comment by nobodyiam** [comment]
可以参考 #3866 中的 Scripts to check whether there is any duplicate data。
如果有重复的数据可以删除的，不过最好先做备份。

**Comment by tsiayutai** [comment]
了解  我們現在用另一種方式同步数据, 感谢哈。
