### ISSUE TITLE
通过修改源码制作镜像，基于k8s部署Apollo 2.1.0 版本，实现自带的eureka开启登录认证，但是接入apollo_meta时提示401错误

### ISSUE THREAD

**Issue by YHuuuui** [apolloconfig/apollo#4905]
修改源码如下图
![1687056060047](https://github.com/apolloconfig/apollo/assets/23163282/bc716b39-ffda-4717-be43-e6e975f3c058)
开启EUREKA登录认证
apollo.eureka.server.security.enabled=true
apollo.eureka.server.security.username=XXX
apollo.eureka.server.security.password=XXX

**Comment by nobodyiam** [comment]
eureka 登录认证已经[支持](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_329-apolloeurekaserversecurityenabled-%e9%85%8d%e7%bd%ae%e6%98%af%e5%90%a6%e5%bc%80%e5%90%afeureka-server%e7%9a%84%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81)了，按图中的修改，那么所有 path 都需要认证了

**Comment by YHuuuui** [comment]
官方2.1.0镜像，开启eureka登录认证配置，访问eureka服务时没有登录认证，我看其他人也遇到这个问题，所以我就改了源码，发现接入apollo_meta报错401，也就是因为所有请求都被拦截了，想问下如何改源码实现eureka登录认证，官方有没说明文档？

**Comment by YHuuuui** [comment]
> 
官方2.1.0镜像，开启eureka登录认证配置，访问eureka服务时没有登录认证，我看其他人也遇到这个问题，所以我就改了源码，发现接入apollo_meta报错401，也就是因为所有请求都被拦截了，想问下如何改源码实现eureka登录认证，官方有没说明文档？

**Comment by zhangjinhuan** [comment]
我在github上，下载了最新的2.1.0的jar，
在数据库配置了如下信息：
apollo.eureka.server.security.enabled=true
apollo.eureka.server.security.username=xxx
apollo.eureka.server.security.password=yyy
eureka.service.url=http://xxx:yyy@localhost:8080/eureka/
为什么访问eureka：http://localhost:8080，仍然不需要认证呢？
还需要其他的配置吗？

**Comment by nobodyiam** [comment]
http://localhost:8080 是 meta server，这个是不需要认证的，只有 eureka 相关操作（例如注册服务）需要认证，例如 http://localhost:8080/eureka/apps

**Comment by zhangjinhuan** [comment]
如果想对http://localhost:8080&nbsp;进行登录认证，目前apollo的版本支持吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apolloconfig/apollo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月8日(星期二) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apolloconfig/apollo] 通过修改源码制作镜像，基于k8s部署Apollo 2.1.0 版本，实现自带的eureka开启登录认证，但是接入apollo_meta时提示401错误 (Issue #4905)





 
http://localhost:8080 是 meta server，这个是不需要认证的，只有 eureka 相关操作（例如注册服务）需要认证，例如 http://localhost:8080/eureka/apps

**Comment by nobodyiam** [comment]
目前不支持的，不过为什么需要对 http://localhost:8080 加登录认证？这些 server 的信息本来就是给客户端能获取到的
