### ISSUE TITLE
多个eureka疑问

### ISSUE THREAD

**Issue by feiflown** [apolloconfig/apollo#4910]
前提：我有两个环境连接同一个configdb，eureka.service.url也配了两个
apollo版本：1.5和2.0.1
需求：需要指定eureka.url，如：A环境指向A eureka，B环境指向B eureka；但不能保证A apollo-configservice和A apollo-adminservice都注册在A eureka上；会出现A apollo-configservice和A apollo-adminservice注册在B eureka上的情况，请问我该如何实现?

**Comment by nobodyiam** [comment]
每个环境需要连接独立的 configdb
