### ISSUE TITLE
版本为2.1.0，在Windows中进行分布式部署，第一次无法使用sh启动服务

### ISSUE THREAD

**Issue by UnfetteredArtMan** [apolloconfig/apollo#4911]
![5c05cfb97464d59d1ad67965606f904](https://github.com/apolloconfig/apollo/assets/63155008/d3e40c19-46dd-42a6-9a40-88f192bbe880)
查看日志`[0.005s][error][logging] Error opening log file '/opt/logs/100003171/gc.log': No such file or directory
[0.005s][error][logging] Initialization of output 'file=/opt/logs/100003171/gc.log' using options '(null)' failed.
Invalid -Xlog option '-Xlog:gc*:/opt/logs/100003171/gc.log:time,level,tags', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`
然后我使用java -jar apollo-adminservice.jar的方式启动服务后关闭服务，再使用sh命名时就启动成功了
![5a325ba2faa9c0fc25d28d9010ca2c4](https://github.com/apolloconfig/apollo/assets/63155008/18ff99a4-7d6c-4891-bcf7-3b06c3b6f30d)
经过测试，3个服务都是这样，现在还没进行重启系统，不确定bug是否会复现

**Comment by UnfetteredArtMan** [comment]
重启后再次使用sh启动服务，启动成功
![image](https://github.com/apolloconfig/apollo/assets/63155008/99ffcfe7-6a39-4954-bb33-c092d5071216)

**Comment by nobodyiam** [comment]
/opt/logs/ 目录需要存在且可写
