### ISSUE TITLE
web管理界面是否可以根据namespace搜索在哪个项目下

### ISSUE THREAD

**Issue by sk821461726** [apolloconfig/apollo#4914]
![image](https://github.com/apolloconfig/apollo/assets/22365956/51a55d77-fba0-4a0c-a1ce-701850b37cf3)
当项目很多、namespace很多的时候，代码中引入了大量namespace，很多是交错引用的，导致在web页面找namespace属于哪个项目很不方便

**Comment by nobodyiam** [comment]
公共 namespace 支持搜索的

![image](https://github.com/apolloconfig/apollo/assets/837658/c06aaa20-adf7-4303-8474-23db62cfedf5)
