### ISSUE TITLE
Namespace的32个字符的限制

### ISSUE THREAD

**Issue by KanonWY** [apolloconfig/apollo#4918]
我发现namespace的名字有32个字符的显示，有什么设置或者方法可以解除这个限制吗？

**Comment by nobodyiam** [comment]
The [schema](https://github.com/apolloconfig/apollo/blob/master/scripts/sql/apolloportaldb.sql#L64) has the 32 lengh limit.

**Comment by KanonWY** [comment]
I noticed that the front-end  has limitations when creating it. If I modify the sql table and use the api to create it, will there be a test on the back-end? If I want to remove this limitation, is there any better way?

**Comment by nobodyiam** [comment]
I believe the check logic is mainly in the frontend.

**Comment by BlueSodaWater** [comment]
I think change the config in apollo-portal\src\main\resources\static\scripts may help you.
![Snipaste_2023-07-03_10-56-22](https://github.com/apolloconfig/apollo/assets/35420162/555dbe62-cc0d-45b0-b382-967fb5beb4d7)

**Comment by KanonWY** [comment]
Thanks for help, I have solved this problem!

**Comment by KanonWY** [comment]
The official documentation is very complete, and those who are not familiar with java can also modify the source code packaging very well.
