### ISSUE TITLE
apollo两个独立集群合并怎么操作（都有数据）

### ISSUE THREAD

**Issue by feeljia** [apolloconfig/apollo#4926]
目前有个诉求是将apollo两个完全独立，即拥有portal、adminservice、configservice的集群做合并，具体如下

集群1部署包含组件portal、adminservice、configservice，依赖的DB都是独立的，且环境包括dev、fat
集群2部署包含组件portal、adminservice、configservice，依赖的DB都是独立的，且包括环境prod、uat、lpt

现需要将集群1合并到集群2里面，即把对应集群1的数据全部迁移至集群2，且不会对集群2造成脏数据等问题，同时两个集群都有相同的appid，辛苦帮忙回复

**Comment by nobodyiam** [comment]
1. portal 的元数据如果一致的话，那么直接在集群 2 的 portal 上增加 dev 和 fat 环境即可
2. portal 的元数据如果不一致，可以考虑通过配置导入/导出的方式来做，或者先把元数据对齐（比如只在集群 1 中有的 app/namespace）

**Comment by feeljia** [comment]
portal 的元数据不一致，当前我们使用的版本是1.2.0，貌似没有配置导出导入的功能，要是通过SQL导出导入数据的话有办法合并吗，比如从集群1中select出数据，然后inster到集群2中，要是可以的话，都需要倒哪些表及数据啊，会对集群2产生影响吗inster的时候

**Comment by nobodyiam** [comment]
手动导入导出需要理解实体之间的关系，可以参考 [1.4 E-R Diagram](https://www.apolloconfig.com/#/zh/design/apollo-design?id=_14-e-r-diagram)
