### ISSUE TITLE
建议docker官方镜像中提供更丰富的对日志的定制选项

### ISSUE THREAD

**Issue by lindong4067** [apolloconfig/apollo#4927]
我们正在使用apollo官方2.1.0镜像，有个需求需要对日志保留天数，日志大小，日志打印格式等进行定制和管理，但是我发现在apollo官方镜像上做日志管理不是太容易：

当前Docker镜像中，可否考虑将默认的logback.xml文件配置到JVM的-D配置中，这样有特殊需求的用户可以使用docker config等方式定制logback.xml文件，实现对日志的个性化管理。

如果大家有好的建议也可以告诉我，谢谢！

**Comment by nobodyiam** [comment]
日志保留天数、日志大小是在 application.yaml 中配置的，可以通过 ENV 来覆盖，具体可以看下 spring 配置的命名规范。
日志打印格式不确定是否能通过 spring 配置修改，可以研究一下，或者看下是否能在 apollo 运行目录下挂载自定义的 logback.xml。

https://github.com/apolloconfig/apollo/blob/d6bf360b7450c664601435ff4c97cd69c4611a40/apollo-common/src/main/resources/application.yaml#L49-L53

**Comment by lindong4067** [comment]
研究了一下，日志保留天数、日志大小、日志打印格式是可以在application.properties里进行配置的。我们选择通过ENV的方式添加配置到compose文件，可以满足对日志定制的需求。配置如下：

- LOGGING_PATTERN_FILE="xxx"
- LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE=10MB
- LOGGING_LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP=1GB
- LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY=3

感谢 @nobodyiam 指点！
