### ISSUE TITLE
这块的锁是为了线程安全，但是我理解spring容器初始化的时候是单线程顺序执行的，没有理解这块锁的意义

### ISSUE THREAD

**Issue by pengbiaobeyond** [apolloconfig/apollo#4930]
![image](https://github.com/apolloconfig/apollo/assets/46187883/595e3c28-8cfb-41ae-97bc-8960f2f12f7b)

麻烦请教下这块的synchronized关键字是防止哪块用了多线线程？谢谢

**Comment by nobodyiam** [comment]
我理解主要是方法本身确保多线程安全，不依赖外部是否是并行或串行。

**Comment by pengbiaobeyond** [comment]
好的，多谢

**Comment by pengbiaobeyond** [comment]
![image](https://github.com/apolloconfig/apollo/assets/46187883/9167b381-476c-4933-96d6-77df5a8a4cfb)
我看是在多spring实例的情况下加的这个锁，不知道这块有没有啥考虑

**Comment by pengbiaobeyond** [comment]
还有就是，一直加咱们的社区群，却一直没能加入，我的qq号2952109043，麻烦方便的时候帮忙看下，谢谢
