### ISSUE TITLE
2.1.0 版本是否已支持公共namespace为yml格式?

### ISSUE THREAD

**Issue by storm1long** [apolloconfig/apollo#4931]
- [Y] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [Y] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [Y] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
https://github.com/apolloconfig/apollo/discussions/3815 
你好,关于"Apollo 公共 namespace 支持 xml、json、yaml 等格式"的讨论,我想知道的是,目前2.1.0版本是否是只支持第2阶段(整个文件内容粒度)?如果我也希望在UI 和文档中给予明确的提示,还有就是关于第3点,是否还有计划去实现?
**截图**
<img width="919" alt="image" src="https://github.com/apolloconfig/apollo/assets/134041078/aeaf16f1-39bd-45d1-951d-bddddef7dd80">

### 额外的细节和日志

- 版本：2.1.0

**Comment by nobodyiam** [comment]
第 3 点暂时还没有计划，不过是个合理的场景
