### ISSUE TITLE
使用 2.0.1 apollo namespace 建立失败 

### ISSUE THREAD

**Issue by tsiayutai** [apolloconfig/apollo#4934]
大佬想请问一下，我在 apollo 2.0.1 APP裡面建立了一個公有 namespace 叫runConfig，但我在另一個 APP 建立namepsace 叫runconfig
会失败，这两个不同大小寫但是建立的時候報錯說同名称，但我在 1.3版没遇到这问题，請問 namespace 同名會建立失敗是新版才有的功能吗？

**Comment by nobodyiam** [comment]
This logic was introduced in #1894, which was released in [1.3.0](https://github.com/apolloconfig/apollo/releases/tag/v1.3.0).

**Comment by tsiayutai** [comment]
了解, 謝谢大神。
