### ISSUE TITLE
支持自定义 prometheus 指标上报

### ISSUE THREAD

**Issue by 0xc9e36** [apolloconfig/apollo#4935]
现在通过 http://localhost:8090/prometheus 可以获取一些指标，但是希望能自定义一些 metrics，这个有开放接口吗

**Comment by JaredTan95** [comment]
自定义指标是需要在代码中埋点的，欢迎贡献

**Comment by stancycowen** [comment]
> 现在通过 http://localhost:8090/prometheus 可以获取一些指标，但是希望能自定义一些 metrics，这个有开放接口吗

你好，请问你Promethes试过了吗？我看了，吐的数据怎么是json，不是Prometheus的格式
