### ISSUE TITLE
resource/application-profile.yml和apollo配置的优先级问题

### ISSUE THREAD

**Issue by timorDevp** [apolloconfig/apollo#4936]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

根据springboot官网的解释：https://docs.spring.io/spring-boot/docs/2.3.10.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config，jar包内的application-profile.yml的优先级是高于jar包外的application.properties的，那apollo配置加载优先级也低于jar包内的配置吧？

参考issue（https://github.com/apolloconfig/apollo/issues/4687），升级了apollo版本，但是apollo优先级应该还是低于resource/application-profile.yml 

**期望**
apollo配置如何覆盖jar包内的application-profile.yml 相同key配置呢？

### 额外的细节和日志

- 版本：springboot2.5.*  apollo2.1.0
- 配置：
- 平台和操作系统 linux

**Comment by timorDevp** [comment]
apollo的配置可以比config目录下的配置更高吗？（目的是config保存一份配置应急）
期待得到回复，谢谢！

**Comment by nobodyiam** [comment]
apollo 配置设计上优先级是比本地配置文件高的，如果确实有问题的话，可以上传一个样例？
