### ISSUE TITLE
修改配置的时候，报错重新登陆

### ISSUE THREAD

**Issue by long1318737396** [apolloconfig/apollo#4937]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
修改配置的时候，报错重新登陆
简洁明了地描述一下bug
修改配置的时候，报错重新登陆，apollo是在k8s下部署的 
![image](https://github.com/apolloconfig/apollo/assets/116941376/f08fb6cf-e450-40f4-833c-e5a269d75751)

**复现**
![image](https://github.com/apolloconfig/apollo/assets/116941376/0fbb19fd-2ec3-4dca-a0fe-564f757d4bd7)
看连接config和admin都是正常的，我看修改的时候是个put请求，我在apollo pod中抓包看apollo是收到包的，所以这个错误信息是apollo返回的
通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
https://github.com/apolloconfig/apollo/issues/4735#issuecomment-1432243350

**Comment by long1318737396** [comment]
你好，我都是单实例部署的，在k8s中，admin  config  portal都是单pod，portal是以nodeport暴露 即使开启ingress 会话保持也无意义因为请求始终是落在单pod上，关于开启sesson共享看是1.9默认开启的 我的是2.0.0  其他环境都没问题，在另外一个环境无论我怎么部署 都是必现

**Comment by nobodyiam** [comment]
看下 Network 中报错的具体信息，看上去似乎是 connection reset？
