### ISSUE TITLE
config service(version 2.0.0-RC1 or above) return 404 when use double slash "//" in http path

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4947]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

### Describe the bug

apollo client read config fail when there is a slash in the suffix of apollo.meta, for example

```
apollo.meta=http://ip:port/
```

but it work well when `/` doesn't occur in the suffix. i.e 
```
apollo.meta=http://ip:port
```

### Reproduce

run

```bash
curl http://localhost:8080//services/config
```

to access config service, version 2.0.0-RC1

get

```json
{"timestamp":"2023-08-01T21:49:31.123+0800","status":404,"error":"Not Found","path":"//services/config"}
```

watch out that `//` after port 8080

![image](https://github.com/apolloconfig/apollo/assets/15523186/9f8c42ca-856c-47e7-b0ef-d2087b414cbf)

### Expected behavior

get json like

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```
![image](https://github.com/apolloconfig/apollo/assets/15523186/5f63267a-4ff1-48fa-bd2e-181e09114eae)

### Additional Details & Logs

- Platform and Operating System
```bash
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

- Version 2.0.0-RC1 or above

| config service's version | double slash "//" work or not |
| ------------------------ | ----------------------------- |
| 1.8.2                    | work well                     |
| 1.9.2                    | work well                     |
| 2.0.0-RC1                | 404                           |
| 2.0.1                    | 404                           |

more detail from version 1.8.2 to 2.0.1

#### 1.8.2

curl http://localhost:8080/services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

curl http://localhost:8080//services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

#### 1.9.2

curl http://localhost:8080/services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

curl http://localhost:8080//services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

#### 2.0.0-RC1

curl http://localhost:8080/services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

curl http://localhost:8080//services/config

```json
{"timestamp":"2023-08-01T21:54:25.152+0800","status":404,"error":"Not Found","path":"//services/config"}
```

#### 2.0.1

curl http://localhost:8080/services/config

```json
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"localhost:apollo-configservice:8080","homepageUrl":"http://172.29.234.239:8080/"}]
```

curl http://localhost:8080//services/config

```json
{"timestamp":"2023-08-01T21:49:31.123+0800","status":404,"error":"Not Found","path":"//services/config"}
```

#### apollo-client

https://github.com/apolloconfig/apollo-java/blob/265fe49ddf0a4becad40ecf5bcd6bd1c86d9826b/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/ConfigServiceLocator.java#L248C26-L248C35

```java
    return domainName + "/services/config?" + MAP_JOINER.join(queryParams);
```

when domainName(apollo.meta) is `http://ip:port/` will get double slash `//` in `http://ip:port//services/config?...`

#### config-service

The path mapping in

https://github.com/apolloconfig/apollo/blob/99b76dccb0d5700202807d8d75a058006896eee9/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java#L48

Guess that when Spring MVC or Spring WebFlux update in https://github.com/apolloconfig/apollo/pull/4295 cause it?

I.e '//' cannot access again.

----

solution:
* apollo-client: delete the suffix '/' of apollo.meta on then runtime?
* config service: keep the compability? For example add a servlet filter when meet '//' then convert it to '/'

**Comment by Anilople** [comment]
According to https://stackoverflow.com/questions/70606716/getting-404-error-when-url-contains-double-slash-after-spring-boot-2-5-to-2-6-mi

Just add a property in config service's .properties file

```java
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
```
Everything is great again!

---

Reference:
* https://docs.spring.io/spring-boot/docs/2.7.14/reference/html/web.html#web.servlet.spring-mvc.content-negotiation
* https://github.com/spring-projects/spring-boot/blob/191ac10009cdf1f0663221dad16993493ca50205/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcProperties.java#L103

**Comment by nobodyiam** [comment]
The release notes for Spring Boot 2.6 include a section titled [PathPattern Based Path Matching Strategy for Spring MVC](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc). This particular change seems to have escaped my attention when issue #4295 was raised. To maintain the original logic, should we set the following configuration as the default?
```
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
```
