### ISSUE TITLE
json字符串内含有特殊字符#导致字符串被截断

### ISSUE THREAD

**Issue by fsy66** [apolloconfig/apollo#4953]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 配置value为json字符串
2. json中某项包含#
3. 读取到的配置会截断
4. 如图所示，color字段读到为空，怀疑被当作了注释符

**期望**

是否已有解决方法

**截图**

![image](https://github.com/apolloconfig/apollo/assets/49889922/f8b487e0-15f2-4df3-a575-4162a847a31e)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
I tried to duplicate the issue in [apollo-demo](http://81.68.181.139/config.html?#/appid=100004458) site, it seems working well.

![image](https://github.com/apolloconfig/apollo/assets/837658/93211773-531c-441d-b750-0128acc74e0a)

![image](https://github.com/apolloconfig/apollo/assets/837658/f5526c31-bc5b-4ac3-b52c-ddea763fb07c)
