### ISSUE TITLE
portal support config key explorer

### ISSUE THREAD

**Issue by Anilople** [apolloconfig/apollo#4955]
**Is your feature request related to a problem? Please describe.**
Sometimes we need know that how many config keys used, and which one appId, cluster, namespace they in.

**Describe the solution you'd like**
An explorer in admin page.

![image](https://github.com/apolloconfig/apollo/assets/15523186/53f851ad-4a05-4e86-9d66-e6fbb955e53f)

Config key explorer.

And show the key like a file system.

![image](https://github.com/apolloconfig/apollo/assets/15523186/6259cc89-aba7-4789-8ec8-001e1633d122)

**Additional context**
Config are also an important asset, so we need to analysis how many items, and which keys are used.

**Comment by nobodyiam** [comment]
I'm thinking that we could provide this feature, but wouldn't it be even better to illustrate it with a real-life scenario?

**Comment by Anilople** [comment]
> I'm thinking that we could provide this feature, but wouldn't it be even better to illustrate it with a real-life scenario?

### 1. Management Responsibilities 
In management, company maybe assign different config key prefix's responsibilities to different department or role.

With this explorer, we can know that how many keys use in a role quickly

### 2. Reverse check specification according to config key

For example, if a company forbid use a component, explorer can help them detect this component's config quickly, and found that which app use this component.

**Comment by nobodyiam** [comment]
Awesome, I'd say those are pretty solid examples.
