### ISSUE TITLE
Apollo K8S 部署后获取的监控参数含义

### ISSUE THREAD

**Issue by Jerrywgl** [apolloconfig/apollo#4956]
1 . 期望可以维护一个监控指标的含义列表
2. 根据这个指标含义画一个grafana的大盘

**Comment by nobodyiam** [comment]
That sounds like a wonderful idea! I think we could start from the usages of [Tracer](https://github.com/apolloconfig/apollo-java/blob/main/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/Tracer.java).logEvent method.
