### ISSUE TITLE
@ApolloConfig注解注入对象为null，导致程序启动不起来

### ISSUE THREAD

**Issue by wangenji2015** [apolloconfig/apollo#4957]
Springboot版本2.4.2
Apollo-client版本 2.1.0版本

@EnableApolloConfig添加到启动类上了

**Comment by wangenji2015** [comment]
`@Component
@Data
@Slf4j
public class MySqlDataSourceConfig {

    @Autowired
    private DataSource dataSource;

    @ApolloConfig("MYSQL")
    private Config mysqlConfig;`

**Comment by wangenji2015** [comment]
```
@Component
@Data
@Slf4j
@EnableApolloConfig
public class MySqlDataSourceConfig {

    @Autowired
    private DataSource dataSource;

    @ApolloConfig("MYSQL")
    private Config mysqlConfig;
```

**Comment by nobodyiam** [comment]
You may check the logs for more information.

**Comment by wangenji2015** [comment]
> You may check the logs for more information.

就是启动直接报这个config对象为null啊
