### ISSUE TITLE
请问最新的apollo可以适配达梦数据库吗

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4959]
如题，请问最新的apollo可以适配达梦数据库吗，有哪位兄弟做过适配吗？

**Comment by Shoothzj** [comment]
@zihan524 I think it can works theoretically, feel free to open issues if it doesn't work

**Comment by Anilople** [comment]
More and more database recommands by user, maybe we can try to use a middle abstract like shardingsphere?

**Comment by nobodyiam** [comment]
Apollo is taking advantage of [spring data jpa](https://spring.io/projects/spring-data-jpa/), which is a neat abstracted data layer already! Is there any specific features that shardingsphere might be able to offer us?

**Comment by Anilople** [comment]
> Apollo is taking advantage of [spring data jpa](https://spring.io/projects/spring-data-jpa/), which is a neat abstracted data layer already! Is there any specific features that shardingsphere might be able to offer us?

The reletion maybe from 

```mermaid
graph
apollo --> |1.1|jpa
jpa --> |1.2|mysql
jpa --> |1.3|another-sql
jpa --> |1.4|postgresql
```

to

```mermaid
graph
apollo --> |2.1|jpa
jpa --> |2.2|shardingsphere
shardingsphere --> |2.3|mysql
shardingsphere --> |2.4|another-sql
shardingsphere --> |2.5|postgresql
```

If the cost is edge, for example, the cost of using jpa to access mysql is cost1.2

It seem that the cost is at least equal? i.e 

cost1.1 + cost1.2 + cost1.3 + cost 1.4 <= cost2.1 + cost2.2 + cost2.3 + cost2.4 + cost2.5

I'm not sure about that.

If cost1.1 + cost1.2 + cost1.3 + cost 1.4 is larger than cost2.1 + cost2.2 + cost2.3 + cost2.4 + cost2.5

Shardingsphere maybe decrese the cost of using a new database.

**Comment by nobodyiam** [comment]
@Anilople Based on my understanding, the major benefit of Shardingsphere is to support large-scale datasets by database/table sharding and read/write splitting, which is a great feature but might not be related to the problem discussed in this issue.

**Comment by uid13** [comment]
可以适配的，用 2.1.0 改版，测试后没问题，有需要找我，有偿。
