### ISSUE TITLE
cluster 客户端和服务端大小写不一致可能导致获取不到最新配置

### ISSUE THREAD

**Issue by 0xc9e36** [apolloconfig/apollo#4966]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

client 调用 /notifications/v2  长轮询接口，client 中传过去的 cluster 大小写和服务端配置不一致。
如果有新配置发布，configService 会通知等待的 client ，但是在通知前 client 刚好超时返回了就收不到配置变更事件，在下一次长轮询到来时，服务端会去 releaseMessageCache 中取服务端最新发布记录，但是  ConcurrentMap 对 key 是区分大小写的，仍然获取不到最新配置，又会阻塞到超时返回，此后除非再有新配置发布，不然客户端一直是旧的配置

我用的是 agollo 客户端，现在长轮询的间隔是 2s， 如果在这之间发布新配置了，还是有挺大概率出现这个问题的

**复现**

通过如下步骤可以复现：

1. Apollo 服务端建立 A 集群
2. 客户端配置读取的集群为 a
3. 客户端调用  /notifications/v2 超时返回
4. 服务端发布新配置

**期望**

期望能正确收到配置热更新

**Comment by nobodyiam** [comment]
Would you please duplicate this issue in the [apollo-demo](http://81.68.181.139/) site?
