### ISSUE TITLE
如果不小心删除或修改了一个配置，但是还未发布，能不能增加撤销待发布的值得功能

### ISSUE THREAD

**Issue by BQDMDMN** [apolloconfig/apollo#4970]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 改了一个配置项的值，现在不想改，还未发布
2. 删除了一个配置项的值，现在不想删了，还未发布
3. 新增了一个配置项，现在不想加了，还没发布

**期望**

针对这种配置增删改但还未发布的值，能不能加个撤销的功能

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
![image](https://github.com/apolloconfig/apollo/assets/837658/57f64ca1-e0a3-4187-9bfc-a95ac9e3df16)
