### ISSUE TITLE
关于eureka.server.peer-node-read-timeout-ms的查看和调整

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4977]
我有两台config在同一个数据中心，另外两台config在另外一个数据中心，4台config组成一个集群，两个数据中心之间可能偶发性的网络延迟有一点大，网络是专线连接的，config偶发性的报错，请问如何查看和修改eureka.server.peer-node-read-timeout-ms参数。

2023-09-21 14:10:14.021 ERROR 14142 --- [TaskBatchingWorker-target_x.x.x.x-13] c.n.e.cluster.ReplicationTaskProcessor   : It seems to be a socket read timeout exception, it will retry later. if it continues to happen and some eureka node occupied all the cpu time, you should set property 'eureka.server.peer-node-read-timeout-ms' to a bigger value

**Comment by zihan524** [comment]
感谢，我是直接下载的github上apollo 2.1编译过程序部署的，我看apollo-adminservice-2.1.0.jar包里的BOOT-INF/classes目录下有个application-custom-defined-discovery.properties文件，可以直接修改这个上传吗？

**Comment by nobodyiam** [comment]
不用修改包里的配置文件，直接在部署目录下的 config/application-github.properties 加就可以。
另外，如果是两个机房的话，可以考虑[单独组成集群](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_10-%e5%a4%9a%e6%9c%ba%e6%88%bf%e5%a6%82%e4%bd%95%e5%ae%9e%e7%8e%b0a%e6%9c%ba%e6%88%bf%e7%9a%84%e5%ae%a2%e6%88%b7%e7%ab%af%e5%b0%b1%e8%bf%91%e8%af%bb%e5%8f%96a%e6%9c%ba%e6%88%bf%e7%9a%84config-service%ef%bc%8cb%e6%9c%ba%e6%88%bf%e7%9a%84%e5%ae%a2%e6%88%b7%e7%ab%af%e5%b0%b1%e8%bf%91%e8%af%bb%e5%8f%96b%e6%9c%ba%e6%88%bf%e7%9a%84config-service%ef%bc%9f)。

**Comment by zihan524** [comment]
@nobodyiam 感谢，目前我的架构是这样的。
环境信息：
A机房，部署2台portal，2台admin+config，2台数据库
B机房，部署1台portal，2台admin+config，1台数据库
一共10台主机。

数据库容灾：
a机房主从同步，a机房和b机房也是主从同步，整体数据库同步架构是一主两从

应用配置：
a机房2台porta、b机房1台portal使用同一个slb，提供统一的portal服务
a机房2台admin+config、b机房2台admin+config，组成一个集群（eureka.service.url设置了4个地址）
所有的portal、admin+config都连接a机房的同一套数据库。
portal访问meta也是使用的slb

请问这种架构可以吗？目前就是报eureka.server.peer-node-read-timeout-ms超时的错误，可以通过调整来解决吗？
另外eureka.server.peer-node-read-timeout-ms是在admin和config的配置文件都修改呢吧？

**Comment by nobodyiam** [comment]
eureka.server.peer-node-read-timeout-ms 看配置名称在 config service 的配置文件中修改就可以

**Comment by zihan524** [comment]
@nobodyiam 我的admin和config日志都会偶尔有这个报错，我在admin和config的配置文件都增加了eureka.server.peer-node-read-timeout-ms=10000，改成10秒了，在网上查的这个参数默认是200ms，改造后重启，貌似目前没有这个告警了，另外我们机房是专线连接，所以就多中心对等应用多活部署了，这样架构更简单点。
