### ISSUE TITLE
关于在apollo服务端如何知晓客户端配置是否下发成功？

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4978]
目前在apollo服务端下发配置后，可能由于某些原因如网络等异常，导致配置虽然提交了，但客户端未成功更新，虽然客户端也会定期从apollo服务端拉取配置，但apollo服务端能否直观的看到与客户端应用配置是否一致？

**Comment by nobodyiam** [comment]
see the audit logic

https://github.com/apolloconfig/apollo/blob/1deb136c2c40eeb581c43863ee786b8bd0c754f1/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/ConfigController.java#L211-L222
