### ISSUE TITLE
哪个maven仓库有master分支的apollo-core 2.2.0-snapshot 版本

### ISSUE THREAD

**Issue by jackie-coming** [apolloconfig/apollo#4982]
哪个maven仓库有master分支的apollo-core 2.2.0-snapshot 版本
![image](https://github.com/apolloconfig/apollo/assets/64013698/fa74ef28-9df6-4a5f-a5ec-53b794edac51)

**Comment by jackie-coming** [comment]
from where can i get the pom apollo 2.2.0-snapshot

**Comment by nobodyiam** [comment]
You may reference this

https://github.com/apolloconfig/apollo/blob/5e49df687c64cf6f64f0210ba3ebc13084468757/pom.xml#L615-L628

**Comment by jackie-coming** [comment]
thanks
