### ISSUE TITLE
是否可以提供批量新增配置的API接口

### ISSUE THREAD

**Issue by UESTCmushilin** [apolloconfig/apollo#4987]
目前 apollo 官方只提供了**新增单个配置的接口**，详见《Apollo 开放平台接入指南》：[3.2 API接口列表](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_32-api%e6%8e%a5%e5%8f%a3%e5%88%97%e8%a1%a8) —— 3.2.10 新增配置项。

该 API 接口只有新增单个配置项的功能，具体描述如下所示：

> URL ： http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items
Method ： POST
Request Params ：无

### **特性诉求**：
项目上需要通过 apollo 配置中心的 API 接口批量添加 apollo 的配置，在此批量添加的过程中，若某一配置添加失败了，则进行回滚操作。而目前官方已有的新增配置的接口，无法满足批量新增配置时的失败回滚，因此，对项目的实施不太友好，希望官方能考虑此诉求，提供 **批量新增** 配置的 API 接口。

**Comment by nobodyiam** [comment]
see #2866
