### ISSUE TITLE
k8s pod对接非k8s环境apollo疑问

### ISSUE THREAD

**Issue by zihan524** [apolloconfig/apollo#4988]
目前我的apollo部署在虚拟机非k8s环境，那么我的部署在k8s下的应用pod能对接apollo吗？如果能对接apollo，那么在apollo界面实例列表里的貌似只有ip字段，是不是经常会变？

**Comment by nobodyiam** [comment]
> 我的部署在k8s下的应用pod能对接apollo吗

只要网络通就可以

> 在apollo界面实例列表里的貌似只有ip字段，是不是经常会变

这个取决于 pod 的生命周期

**Comment by zihan524** [comment]
> > 我的部署在k8s下的应用pod能对接apollo吗
> 
> 只要网络通就可以
> 
> > 在apollo界面实例列表里的貌似只有ip字段，是不是经常会变
> 
> 这个取决于 pod 的生命周期

如果一个宿主机里的多个pod同时访问apollo，pod出去的话如果是宿主机ip的话，那apollo实例里面岂不是可以看到很多相同的ip？那怎么来做灰度呢？

**Comment by nobodyiam** [comment]
You may check the client side logic:

https://github.com/apolloconfig/apollo-java/blob/5344bc4f07288842bb850145bcf80a084bd94114/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigRepository.java#L308-L311

![image](https://github.com/apolloconfig/apollo/assets/837658/d435f0de-4111-42ee-99e4-10f8026ef86a)

**Comment by zihan524** [comment]
> You may check the client side logic:
> 
> https://github.com/apolloconfig/apollo-java/blob/5344bc4f07288842bb850145bcf80a084bd94114/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigRepository.java#L308-L311
> 
> ![image](https://user-images.githubusercontent.com/837658/273480931-d435f0de-4111-42ee-99e4-10f8026ef86a.png)

thanks
