### ISSUE TITLE
Apollo 客户端有对应1.6运行环境的jar包吗？ 银行有些系统架构老

### ISSUE THREAD

**Issue by nixub** [apolloconfig/apollo#4989]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by Shoothzj** [comment]
https://github.com/apolloconfig/apollo/issues/483 This may helps you

**Comment by nixub** [comment]
社区响应太快了，我试试，谢谢

**Comment by nixub** [comment]
是不是要先找到那个补丁的代码版本，我找到了半天也没找到，尴尬了
