### ISSUE TITLE
基于注解的使用方式导致context 上下初始化失败

### ISSUE THREAD

**Issue by nixub** [apolloconfig/apollo#4991]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
我在这个应用比较老，spring的版本也不支持@configration 来是Apollo客户端实例化，所以，我按着文档提示的通过xml的方式来 加载
实例。但是他直接就报错了，是spring的版本太低了才导致不能正常注册bean吗？我一个spring4.0.2的也出现了同样的问题，不能通过xml 来注册Apollo实例

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 
![dac09fff6c07c7a4ee3d9d31887b74d](https://github.com/apolloconfig/apollo/assets/76879565/a1a84f19-6f6d-4e18-87d6-3766dea0900d)

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Consider starting with the [official demo](https://github.com/apolloconfig/apollo-demo-java/tree/main/spring-demo) to grasp its functionality before integrating it into your project.

**Comment by nixub** [comment]
我是按着 文档去整合的。 但报这个 错classnotfound ：  beandefinitionRegistryPostProcessor; 我的spring bean.jar确实没有这个类，spring -version:2.5.6. 是低版本就没法 通过 <apollo :config> 加载这个bean了吗

**Comment by nixub** [comment]
这些老工程，总是遇到奇奇怪怪的问题，xml 除了那种方式，还有其它比较原始的方式 加载bean 吗

**Comment by nobodyiam** [comment]
The minimum Spring version supported by Apollo is 3.1.1. For older projects, you might want to use the [Apollo API](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_31-api%e4%bd%bf%e7%94%a8%e6%96%b9%e5%bc%8f) directly.

**Comment by nixub** [comment]
我已经升级了本地工程的spring相关依赖，和我之前整合成功的工程一致。其中有个小插曲。就是这个老工程没有slf4j 依赖，Apollo 依赖使用了，不容易被发现确实的是这个slf4j。我现在工程都正常了。唯独是java 1.6的，行里也取消了这些旧应用的计划。我打补丁失败了。不然可以试试。

**Comment by nixub** [comment]
我之前spring4.0.2 直接使用xml方式失败的原因是，我没有新建一个单独的xml文件来放置文档上的<apollo:config/>内容，导致出了问题。引以为戒。
