### ISSUE TITLE
apollo的灰度规则是否支持k8s中的服务？

### ISSUE THREAD

**Issue by geministarshine** [apolloconfig/apollo#4992]
当我们在k8s中进行灰度发布时，希望配置也能同步进行灰度发布，但是目前apollo中配置的灰度发布规则只支持根据ip进行配置，而k8s中服务的ip是变化的，基本无法应用，请问有针对这方面的改进计划吗？

**Comment by nobodyiam** [comment]
As dosu suggests, apollo supports the label feature:
* [client side config](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_1247-apollolabel)
* [grayscale rule config](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_54-%e9%85%8d%e7%bd%ae%e7%81%b0%e5%ba%a6%e8%a7%84%e5%88%99)
