### ISSUE TITLE
uat和fat两个环境的config & admin 都错乱了

### ISSUE THREAD

**Issue by shaukei** [apolloconfig/apollo#4993]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**uat和fat环境不能区分开**

简洁明了地描述一下bug
![image](https://github.com/apolloconfig/apollo/assets/1581783/cbcb8d02-5d49-413e-aedb-214e267491f1)

**复现**

通过如下步骤可以复现：

1. 如图
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by zihan524** [comment]
这个可能是你配置错误。

**Comment by shaukei** [comment]
解决了，docker方式运行的，运行参数和配置都没有问题，主的potral db配置信息也没有问题。最后检查其他数据库里面的配置，
在fat环境的 db，config库的serverconfig表， eureka.service.url这里，由于是从uat环境复制过来，没有改这里。导致上面的问题。

将这个url改成fat的eureka对应服务地址，重启服务（不确定需不需要重启，稳妥点，就重启了）就正常了。

这个解决方式希望对后面有同样问题的人有帮助！

谢谢上面的朋友热心回复！
