### ISSUE TITLE
在K8s部署中使用Eureka作为服务发现，在configDB 中的数据库serverConfig使用Ingress 域名，为什么在8080 页面存在某些实例无法显示？但是通过ip:8080/health 显示是UP 状态。而使用在serverConfig 表中填lb配置的域名，则不会出现这个问题。

### ISSUE THREAD

**Issue by HadwinLing** [apolloconfig/apollo#4995]
> 

- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
[eureka.service.url](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_321-eurekaserviceurl-eureka%e6%9c%8d%e5%8a%a1url) 需要填写所有 eureka server 的地址从而可以实现数据同步，这个是 eureka 的数据同步机制决定的

![image](https://github.com/apolloconfig/apollo/assets/837658/cca2ede9-0ad3-4209-8edc-3646a528484b)

**Comment by Dr-wgy** [comment]
我这边使用apollo 有个发现 发现 apollo-admin-service 已经挂了 但是[eureka] 上面还是显示服务还存在 感觉 eureka拆除不健康的服务这么慢吗

**Comment by nobodyiam** [comment]
eureka 的默认[剔除时间](https://nobodyiam.com/2016/06/25/dive-into-eureka/#335-eviction)是 90 秒，可以自行调整

**Comment by Dr-wgy** [comment]
> eureka 的默认[剔除时间](https://nobodyiam.com/2016/06/25/dive-into-eureka/#335-eviction)是 90 秒

我在想我这个和自动剔除是不是有关系？ 我这个服务因为 https://github.com/apolloconfig/apollo/issues/3405 oom
但是我一直看了 这个上报 还是一直是up 是不是不应该服务上报的up状态 应该server主动检查

**Comment by nobodyiam** [comment]
上报的状态是由 [AdminServiceHealthIndicator](https://github.com/apolloconfig/apollo/blob/master/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/AdminServiceHealthIndicator.java) 定义的
