### ISSUE TITLE
Multiple environments under multiple clusters

### ISSUE THREAD

**Issue by hhy5861** [apolloconfig/apollo#4996]
Hi,

1. How to support multiple clusters, each cluster supporting multiple environments?
2. If portal is supported, how to add configuration? 
thx！

**Comment by hhy5861** [comment]
@dosu-bot This is not the result I want. My problem is that the environment configuration of each cluster can be managed independently.

**Comment by zihan524** [comment]
> environment

you mean use different portal manage different env ？

**Comment by nobodyiam** [comment]
@hhy5861 Could you please provide a concrete example for better understanding?

**Comment by hhy5861** [comment]
> @hhy5861 Could you please provide a concrete example for better understanding?

First of all, thank you for your reply. My needs are: the domestic computer room is a cluster and has 4 environments (dev, test, beta, prod), and the foreign computer room is a cluster and the environments are (test, prod). How can I Access via portal?

**Comment by nobodyiam** [comment]
I think the [Deployment Architecture](https://www.apolloconfig.com/#/en/deployment/deployment-architecture) guide could be beneficial. You might also consider sketching out your own deployment diagram to test its feasibility.
