### ISSUE TITLE
ApolloAdmin删除重建namespace报错app namespaces already exist.

### ISSUE THREAD

**Issue by apa7** [apolloconfig/apollo#4999]
ApolloAdmin删除重建namespace报错app namespaces already exist.

- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

**复现**
在管理
1.新建一个namespace: demo.properties
2.删除这个namespace
3.重建namespace: demo.properties
报错app namespaces already exist.

原因：
删除是逻辑删除，会标记IsDeleted = 1。而在namespace新建的时候，查询条件没有带IsDeleted = 0

**期望**
1.应该允许重建，查询的时候查询未逻辑删除的。
2.重建后，应该允许再次删除

### 额外的细节和日志

- 版本：1.9.2
- 错误日志
- 配置：如https://github.com/apolloconfig/apollo-quick-start
- 平台和操作系统 docker

![image](https://github.com/apolloconfig/apollo/assets/9262517/e5e87cdf-074b-4d21-8631-0a4d9c47729b)
![image](https://github.com/apolloconfig/apollo/assets/9262517/8564ab0e-ac04-4895-afa8-32bc7d16e496)

**Comment by apa7** [comment]
我们为什么会有这个诉求？
有些同学建namespace时，共有/私有选错了，于是有删除重新建一个同名namespace的需要。
还有在废弃namespace之后，又想恢复而不能

**Comment by zihan524** [comment]
我的2.1没有这个问题呢。

**Comment by apa7** [comment]
> 我的2.1没有这个问题呢。

thx，2.1确实OK。
我们考虑1.9升级2.1。

**Comment by nobodyiam** [comment]
管理员工具可以删除 app namespace

![image](https://github.com/apolloconfig/apollo/assets/837658/cc958322-adc3-4fdc-82fc-a1816351168e)
