### ISSUE TITLE
Text配置修改，含有注释的情况下，撤销修改导致后续存在自动添加重复注释

### ISSUE THREAD

**Issue by quanbetter** [apolloconfig/apollo#5000]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
Text配置修改，含有注释的情况下，撤销修改导致后续存在自动添加重复注释

**复现**

通过如下步骤可以复现：

1. 通过文本编辑写配置和注释并发布
```
#注释第一行
key2 = value2
#注释第二行
key3 = value3
```
<img width="1180" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/943a25a0-ef9a-477b-a6e5-d01095bf56e3">

2. 文本编辑移除key3配置，提交但不发布
<img width="1194" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/636c911b-cebb-45d0-833b-a7d45bb13246">

3. 点击撤销按钮
<img width="1206" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/57b162d3-ee29-40fd-afdd-9484cc381427">
<img width="1196" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/778c026f-8ebe-48a7-a8c7-8c618cf21cee">
4. 文本编辑追加配置提交
<img width="1163" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/261ad6ae-d587-411c-b30d-937b3b8cb58d">

6. 再次文本编辑发现有自动添加
<img width="1166" alt="image" src="https://github.com/apolloconfig/apollo/assets/53170750/79e1dd8d-69c6-4e72-b323-f67bd9187a58">

**期望**

简介明了地描述你希望正常情况下应该发生什么
不应该出现文本编辑自动添加一些注释的情况

版本：2.0.1

**Comment by quanbetter** [comment]
> _🤖_
> 
> 您好，感谢您的反馈。
> 
> 根据我在Apollo仓库中找到的相关问题，这个问题可能与Apollo当前的设计有关。在Apollo中，如果配置未发布，是无法撤销的。Apollo的“回滚”功能允许您恢复到之前发布的版本，但这只适用于已经发布的更改。对于未发布的更改，由于它们不是发布版本的一部分，所以无法回滚。
> 
> 另外，关于文本编辑模式下注释重复出现的问题，我找到了一个类似的问题[#4276](https://github.com/apolloconfig/apollo/issues/4276)，这个问题已经在[#4279](https://github.com/apolloconfig/apollo/pull/4279)的pull request中被修复了。这个修复是通过检查item.isDeleted来判断项目是否被删除。
> 
> 但是，我注意到您使用的Apollo版本是2.0.1，而这个修复是在2.1.0版本中才有的。因此，我建议您升级到最新的Apollo版本，看看这个问题是否还存在。
> 
> 如果问题仍然存在，那么可能需要更深入地研究这个问题。如果可能的话，您能提供更多关于这个问题的信息吗？例如，这个问题是否在所有环境中都会出现，还是只在特定的环境中出现？这将有助于我们更好地理解和解决这个问题。
> 
> 再次感谢您的反馈，期待您的回复。
> 
> ## Sources
> * [如果不小心删除或修改了一个配置，但是还未发布，能不能增加撤销待发布的值得功能](https://github.com/apolloconfig/apollo/issues/4970)
> * [文本模式注释掉一些变量之后，不进行发布，重新点击文本模式进行修改，会重复出现注释掉的数据](https://github.com/apolloconfig/apollo/issues/4276)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
官网提供的例子http://81.68.181.139/ 是2.1.0吗，如果是，那2.1.0版本还是存在我上面说的场景

**Comment by youngzil** [comment]
问下，这个问题什么时候会修复吗？有修复的方案吗

**Comment by youngzil** [comment]
**### Add a question about revoke configuration**

1. The initial configuration is as follows

![image](https://github.com/user-attachments/assets/19a20f0e-dcd2-4510-a375-05e0321b4900)

2. The second step only deletes the fourth line, and the comment on the third line is still retained.
3. But when I revoke the configuration, I find that the comment on the third line is also deleted.

![image](https://github.com/user-attachments/assets/a991bf47-66b0-40c5-be32-0675efd1ef27)

4. The reasons why this happens are as follows：
L218：oldKeyMapItem contains a comment or a blank line
L241：The comment or blank line in oldKeyMapItem will be deleted.

So  I removed this comment or blank line in #5232 

  https://github.com/apolloconfig/apollo/blob/31e6486791de3ad60f059f34957b343839aa5ebb/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java#L218C1-L219C1
https://github.com/apolloconfig/apollo/blob/31e6486791de3ad60f059f34957b343839aa5ebb/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java#L241
