### ISSUE TITLE
大佬们，apollo支持java客户端修改配置吗

### ISSUE THREAD

**Issue by yahuiqq** [apolloconfig/apollo#5004]
大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗大佬们，apollo支持java客户端修改配置吗

**Comment by zihan524** [comment]
你是说java客户端修改配置同步到apollo服务端？

**Comment by yahuiqq** [comment]
是的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月02日 08:44 |
| 收件人 | apolloconfig/apollo ***@***.***> |
| 抄送人 | yahuiqq ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [apolloconfig/apollo] 大佬们，apollo支持java客户端修改配置吗 (Issue #5004) |

你是说java客户端修改配置同步到apollo服务端？

**Comment by zihan524** [comment]
目前并不支持，可以尝试通过openapi更改。

**Comment by zihan524** [comment]
不过这个客户端更改，同步到服务端，感觉也违背了配置中心的初衷。

**Comment by yahuiqq** [comment]
好的感谢
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月02日 08:48 |
| 收件人 | apolloconfig/apollo ***@***.***> |
| 抄送人 | yahuiqq ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [apolloconfig/apollo] 大佬们，apollo支持java客户端修改配置吗 (Issue #5004) |

不过这个客户端更改，同步到服务端，感觉也违背了配置中心的初衷。

**Comment by qmwu2000** [comment]
不支持，当初我们就是这么设计的。配置中心到客户端是一个全自动的单向配置分发同步过程，中间可以有多级缓存（基于内存或持久化到磁盘等等），应用程序作为消费者只关心配置获取API；而配置的修改则是一个更加复杂的流程，openapi则专门为配置修改而专门设计。配置修改需要经过各种权限和管控，有自动的也有人工的，包括配置审核、安全审核、灰度发布、全量发布，以及其他操作等等。

作为小公司，或者暂时对这些需求不够关注（但以后会有），长期来说，有一个好的操作规范，有利于网站的持续稳定发展。

**Comment by yahuiqq** [comment]
感谢🙏
---- 回复的原邮件 ----
| 发件人 | Frankie ***@***.***> |
| 发送日期 | 2023年11月02日 09:28 |
| 收件人 | apolloconfig/apollo ***@***.***> |
| 抄送人 | yahuiqq ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [apolloconfig/apollo] 大佬们，apollo支持java客户端修改配置吗 (Issue #5004) |

不支持，当初我们就是这么设计的。配置中心到客户端是一个全自动的单向配置分发同步过程，中间可以有多级缓存（基于内存或持久化到磁盘等等），应用程序作为消费者只关心配置获取API；而配置的修改则是一个更加复杂的流程，openapi则专门为配置修改而专门设计。配置修改需要经过各种权限和管控，有自动的也有人工的，包括配置审核、安全审核、灰度发布、全量发布，以及其他操作等等。

作为小公司，或者暂时对这些需求不够关注（但以后会有），长期来说，有一个好的操作规范，有利于网站的持续稳定发展。
