### ISSUE TITLE
环境变量覆盖apollo配置失败

### ISSUE THREAD

**Issue by ZeroSong211** [apolloconfig/apollo#5009]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

多个应用引用同一个apollo配置时，不同应用间的配置差异我们采用了环境变量去覆盖apollo配置。但使用过程中，发现key中带"-"的配置使用此方式覆盖失败。

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**
配置应该被覆盖为true

**截图**

如果可以，附上截图来描述你的问题
![1](https://github.com/apolloconfig/apollo/assets/83919512/6125aae2-4814-4293-9697-666f427fff42)

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统
![2](https://github.com/apolloconfig/apollo/assets/83919512/d4ffe549-1c61-4685-932f-f5125d5307e5)
![3](https://github.com/apolloconfig/apollo/assets/83919512/e631fd5c-b4b4-4e3b-9bc2-3233c73d7277)
![4](https://github.com/apolloconfig/apollo/assets/83919512/636bebc5-2717-4ed6-a413-91c5eb6a093c)

**Comment by ZeroSong211** [comment]
不是同一种情况，还请人工帮忙看一下，感谢~

**Comment by ZeroSong211** [comment]
经过多次测试，不是带"-"的key覆盖失败，而是key-value左右值不相等才会覆盖失败，改成如下图格式后，环境变量是可以进行覆盖的
![image](https://github.com/apolloconfig/apollo/assets/83919512/f567bd60-e5a9-4a41-8fe4-75d979212aa5)

**Comment by nobodyiam** [comment]
@ZeroSong211 这个是 spring 自身的配置规则，简而言之 test.param.enable-test 等同于环境变量 TEST_PARAM_ENABLE_TEST，两个都是 KEY，不是 value。

**Comment by ZeroSong211** [comment]
TEST_PARAM_ENABLE_TEST打错了吧。。应该是TEST_PARAM_ENABLE-TEST
