### ISSUE TITLE
希望可以在namesapce中增加分页功能

### ISSUE THREAD

**Issue by 690679372** [apolloconfig/apollo#5015]
**你的特性请求和某个问题有关吗？请描述**

由于我们的namespace有上千个key和Value。而且每个Value 的值稍微大一点，所以导致namesapce展开的时候浏览器会卡死很长一段时间。这在修改和添加新key的时候造成了很大的麻烦。

**清晰简洁地描述一下你希望的解决方案**

我希望可以在namesapce下面增加分页来解决这个问题。

**Comment by nobodyiam** [comment]
See #1261

**Comment by 690679372** [comment]
Thanks
