### ISSUE TITLE
apollo portal v2.1.0 管理员工具中的 系统参数 项点击后跳转的页面链接错误

### ISSUE THREAD

**Issue by SkyDriveCN** [apolloconfig/apollo#5024]
**描述bug**

apollo portal v2.1.0 管理员工具中的 系统参数 项点击后跳转的页面链接错误
当前点击后跳转的页面路径为server_config.html
实际应该跳转的页面为server_config_manage.html
![image](https://github.com/apolloconfig/apollo/assets/23717846/0b72119c-0daf-4b8d-a6eb-1123bbf07911)

**复现**

通过如下步骤可以复现：

1. 点击apollo portal v2.1.0 管理员工具
2. 选择 系统参数 项

**期望**

进入系统参数 页面
![image](https://github.com/apolloconfig/apollo/assets/23717846/c93e7508-bb99-46a8-8d0b-babbbe55ce0f)

**截图**
![image](https://github.com/apolloconfig/apollo/assets/23717846/055b0b29-0e8a-4b64-aa48-a025fb2578ef)

- 版本：2.1.0

**Comment by nobodyiam** [comment]
It seems that the problem is related to the browser's cache. To resolve this, please perform a forced refresh of the cache and then attempt to access the page again.
