### ISSUE TITLE
在配置了多个集群的情况下，某个namespace初次发布后，想取消发布，想让程序读取配置走default集群的namespace，这种目前貌似没有取消发布的操作？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#5025]
在配置了多个集群的情况下，某个namespace初次发布后，想取消发布，想让程序读取配置走default集群的namespace，这种目前貌似没有取消发布的操作？

**Comment by nobodyiam** [comment]
如果确信这个集群的 namespace 是误发布，可以删除该 namespace

**Comment by hezhaoye** [comment]
> 如果确信这个集群的 namespace 是误发布，可以删除该 namespace

嗯，删除是可以，不过如果后续再想使用这个namespace就没有恢复此namespace的功能了，也是比较麻烦的。可能做一个单独的功能来撤销首次发布的会更好点？

**Comment by nobodyiam** [comment]
> 如果后续再想使用这个namespace就没有恢复此namespace的功能了
