### ISSUE TITLE
请教一下，修改配置实时生效后，线上老代码不兼容新配置导致容易出现生产问题，有没有什么好的实践

### ISSUE THREAD

**Issue by shuai-huaman** [apolloconfig/apollo#5031]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

先修改了apollo某个配置，新的配置在线上实时生效了，但是因为新代码还在部署中，线上老代码不支持新配置，导致出现生产问题
想问一下大家针对这种场景有没有比较好的处理方案

（有人可能会说先部署代码再变更配置就好了，确实是一种方案，但是实际运行过程中往往很多开发没有评估到哪些配置会产生这种兼容问题，所以还是经常出问题，想看看大家有没有更可靠更有保障的方案流程）

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by shuai-huaman** [comment]
@nobodyiam 大佬，之前的帖子已经看过了，但是感觉帮助不大，因为我们当前只用了一个apollo集群，并且一个服务正常也只有一套配置，每次增量变化

如果每次发布版本想要变更配置，还得增加新配置key或者放在新集群，那成本太高了，我们希望的是始终维护同一套配置

因为只有唯一一套配置，所以必然面临新老代码的兼容，当前的处理方式是完全依靠开发人工判断哪些key需要等到新代码上线后再变更，哪些key可以直接变更线上，但是太容易评估遗漏了

**Comment by nobodyiam** [comment]
建议还是新配置不能影响老代码，不然发布过程中的灰度会很复杂，以及如果遇到问题回滚代码也会比较麻烦
