### ISSUE TITLE
Support slf4j MDC via Apollo audit log？

### ISSUE THREAD

**Issue by BlackBear2003** [apolloconfig/apollo#5032]
**Is your feature request related to a problem? Please describe.**

Maybe the original audit log display **outward** function implement by DB and front-end is not very powerful and practicality.

**Describe the solution you'd like**

So my idea is to **support Apollo's slf4j MDC** so that users can implement full audit-tracing **by modifying logback.xml.** Also, users could **switch this feature on and off** by setting properties like "apollo.audit.log.mdc.enabled=true/false"

**Describe alternatives you've considered**

Maybe we could implement an Apollo's MDCAdapter and maintaining it via AOP which audit-log has implemented.

**Additional context**

Please tell me whether this idea is correct and necessary, because I am just a student and have no actual production experience, so my ideas may be biased.🤔

**Comment by nobodyiam** [comment]
Implementing SLF4J MDC for operational auditing is a novel approach. Technically, it seems viable. However, I'm interested in understanding why you believe the current method of storing these logs in a database and presenting them with a user-friendly interface lacks effectiveness and practicality. Could you elaborate on your perspective regarding this?
Additionally, the durability of audit logs is essential, ensuring that they can be retrieved for future auditing needs. Therefore, it's crucial to explore how this can be effectively achieved through the SLF4J MDC framework.

**Comment by BlackBear2003** [comment]
> Could you elaborate on your perspective regarding this?

Well, my idea is actually that I am not sure whether others will think the original method is useful. 

For the limitation of my front-end abilities, I couldn't represent the relationship between audit logs in a tree structure on the interface. So I have **not yet** implemented the method of obtaining the audit log from AdminService and displaying it on the front-end interface for _avoid to making the front-end looks mess_.
So I am temporarily considering that maybe I can print out the tracing process through MDC first?

I found that the information MDC can actually provide is **not much more than** the original collection method after further thinking in the past two days. And what MDC can actually do has no differences from the original database implementation.
Then, is it still quite a good choice to implementing it?😵‍💫

**Comment by nobodyiam** [comment]
@Anilople, what are your thoughts on this topic?

**Comment by Anilople** [comment]
> @Anilople, what are your thoughts on this topic?

@nobodyiam @BlackBear2003 I think there are maybe 2 things about it.

1. How to pass the rpc context cross process, for example, from portal to admin service.
2. An audit log extension for user, let user can capture the audit log by self way.

MDC maybe isn't a best way to implement them, though the logging system use logback MDC.
