### ISSUE TITLE
关于配置变更的一些疑问

### ISSUE THREAD

**Issue by xingzhuipingye** [apolloconfig/apollo#5045]
springboot项目中，在apollo配置中心修改配置后，可以使用两种方式获得更改后的key
1、使用@Value("${configKey}")，每次使用方法获取属性就可以获得新的值
2、@ApolloConfigChangeListener，在回调方法ConfigChangeEvent中可以获取新的值

基于代码的简洁性，我在代码中监听了某个key，在回调中使用了@Value修饰的属性值，而不是用ConfigChange.getNewValue，在apollo中修改值后获取到了老的值，我对此有点困惑

翻看client源码中，看到触发变更AbstractConfig.fireConfigChange(final ConfigChangeEvent changeEvent) 使用线程池来更新，AutoUpdateConfigChangeListener来更新spring中@Value修饰的值，这就解释了我为什么在@ApolloConfigChangeListener回调中使用@Value修饰的属性值获得了配置变化的老值。

我有两点疑问：
1、是否可以将@Value修饰的值变更优先级提高，用户自定义回调方法优先级降低，毕竟我们依赖框架是希望框架给解决一些黑盒问题，遇到问题还要去拆盒子。确实挺崩溃的。
2、如果1设计上上有别的考虑，是否可以在官方文档标注一下这个问题。

感谢大佬们

**Comment by nobodyiam** [comment]
初始的设计考虑是 listener 之间不存在依赖关系，所以是异步执行。在你的场景，两个 listener 之间存在依赖关系（用户 listener 依赖了 AutoUpdateConfigChangeListener，这个场景确实要考虑下是否要支持以及该怎么支持。

**Comment by xingzhuipingye** [comment]
感谢大佬的回复和解答，很期待后续的设计和变化
