### ISSUE TITLE
if the new gray env should return the main env's latest releases

### ISSUE THREAD

**Issue by xxyush** [apolloconfig/apollo#5054]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

I have a PRO env and the gray env of PRO:
1,without adding or changing any items to the gray，using open api (http://apollo.xxx/openapi/v1/envs/PRO/apps/test_app/clusters/XXX/namespaces/application/releases/latest) to get latest releases is empty（no including the items of PRO env part ）2, then I deploy any oen item in gray env, then using the open api to get the latest releases, the result contains the gray part(the new add one) And the pro env part items.
**复现**

通过如下步骤可以复现：

1. Choose a env
2. build the env's gray env
3. using open api to get the latest releases
4. the result content  is empty and no significant content

**期望**

so I wonder if the fist situation should also include/display the PRO env items as the gray release items

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Could you kindly arrange your scenario on the [demo site](http://81.68.181.139/) to enhance clarity and ease of understanding?

**Comment by xxyush** [comment]
> Could you kindly arrange your scenario on the [demo site](http://81.68.181.139/) to enhance clarity and ease of understanding?

hi what is the demo site username and password?

**Comment by nobodyiam** [comment]
Oh, I thought it was well known as it's documented in the readme.md.
Here it is:
* http://81.68.181.139/
* User/Password: apollo/admin
