### ISSUE TITLE
升级到2.2.0之后强制刷新浏览器，清除js缓存才能看到审计入口

### ISSUE THREAD

**Issue by luger1990** [apolloconfig/apollo#5057]
升级到2.2.0之后强制刷新浏览器，清除js缓存才能看到审计入口。 后续打包的时候可以考虑给js加个版本号之类的。

**Comment by nobodyiam** [comment]
js 文件是有版本号的

![image](https://github.com/apolloconfig/apollo/assets/837658/b3aa3e11-177b-49f4-8375-23e0b5cc4f76)


不过菜单列表确实没有，是依靠缓存过期的，默认是 24 小时

![image](https://github.com/apolloconfig/apollo/assets/837658/04588b2b-9e4b-411b-b0cb-aee5909f7d77)

**Comment by luger1990** [comment]
> js 文件是有版本号的
> 
> ![image](https://private-user-images.githubusercontent.com/837658/292349121-b3aa3e11-177b-49f4-8375-23e0b5cc4f76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDIxNzQsIm5iZiI6MTcwMzM0MTg3NCwicGF0aCI6Ii84Mzc2NTgvMjkyMzQ5MTIxLWIzYWEzZTExLTE3N2ItNDlmNC04Mzc1LTIzZTBiNWNjNGY3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNDMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGQ4NDM5NGQxOTU1Yjc3YmExODU5NzQyYzlmMWUyNjRlZjE5NzBmODZlNzdmNTA2YTgyNjU0MjY1NDJmNTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SHRmWxJpL4O2rom8xfVPLtm1Kpf-dquLDAcFnz-NgvQ)
> 
> 不过菜单列表确实没有，是依靠缓存过期的，默认是 24 小时
> 
> ![image](https://private-user-images.githubusercontent.com/837658/292349086-04588b2b-9e4b-411b-b0cb-aee5909f7d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDIxNzQsIm5iZiI6MTcwMzM0MTg3NCwicGF0aCI6Ii84Mzc2NTgvMjkyMzQ5MDg2LTA0NTg4YjJiLTllNGItNDExYi1iMGNiLWFlZTU5MDlmN2Q3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNDMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2U5MjU5ZmNlM2ZlNTYwY2QxYWE4NjAwYjZjOGI1NzRiMmU0ZWJkYjhmMWIxYzZhMjUxNGU3NzcyNjE0MDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AxCr8OpC7vQgnNp5dHDibB3XxFNt6QWALfcPIRn5XWY)

明白了。多谢！
