### ISSUE TITLE
NotificationControllerV2#handleMessage may set outdated result

### ISSUE THREAD

**Issue by PleaseGiveMeTheCoke** [apolloconfig/apollo#5059]
At the end of the NotificationControllerV2#handleMessage method, the result of the deferredResults are set in the following way
```
    for (DeferredResultWrapper result : results) {
      result.setResult(configNotification);
    }
```
Is it possible that the notificationId in **configNotification** is less than the id on the client side, causing this to be an unnecessary result notification?

**Comment by PleaseGiveMeTheCoke** [comment]
> _🤖_
> 
> Hey there, @PleaseGiveMeTheCoke! 👋 I'm [Dosu](https://dosu.dev), a friendly bot here to assist you with bugs, answer your queries, and guide you on your journey to become a contributor while we wait for a human maintainer. Let's dive into this together! 🏊
> 
> Yes, it is possible that the `notificationId` in `configNotification` could be less than the `id` on the client side, resulting in an unnecessary result notification in the `NotificationControllerV2#handleMessage` method. This could occur in the `filterNotifications` method, where the `notificationId` of the client side is compared with the `notificationId` of the server side. If the `notificationId` of the client side is greater, the server side `notification` is ignored. Here is the relevant code snippet:
> 
> ```java
> private Map<String, ApolloConfigNotification> filterNotifications(String appId,
>                                                                     List<ApolloConfigNotification> notifications) {
>     Map<String, ApolloConfigNotification> filteredNotifications = Maps.newHashMap();
>     for (ApolloConfigNotification notification : notifications) {
>       if (Strings.isNullOrEmpty(notification.getNamespaceName())) {
>         continue;
>       }
>       //strip out .properties suffix
>       String originalNamespace = namespaceUtil.filterNamespaceName(notification.getNamespaceName());
>       notification.setNamespaceName(originalNamespace);
>       //fix the character case issue, such as FX.apollo <-> fx.apollo
>       String normalizedNamespace = namespaceUtil.normalizeNamespace(appId, originalNamespace);
> 
>       // in case client side namespace name has character case issue and has difference notification ids
>       // such as FX.apollo = 1 but fx.apollo = 2, we should let FX.apollo have the chance to update its notification id
>       // which means we should record FX.apollo = 1 here and ignore fx.apollo = 2
>       if (filteredNotifications.containsKey(normalizedNamespace) &&
>           filteredNotifications.get(normalizedNamespace).getNotificationId() < notification.getNotificationId()) {
>         continue;
>       }
> 
>       filteredNotifications.put(normalizedNamespace, notification);
>     }
>     return filteredNotifications;
>   }
> ```
> 
> You can find this code in the [NotificationControllerV2.java](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java) file.
> 
> The `notificationId` is generated and updated on the server side through the `ReleaseMessage` entity. This entity is fetched from the `releaseMessageService` which interacts with the database to fetch the latest `ReleaseMessage` for the given watched keys. When a new configuration is published, a new `ReleaseMessage` is created with a new `notificationId`, which triggers the server to send a notification to the client with the updated `notificationId`. You can find more details in the [NotificationController.java](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationController.java) file.
> 
> I hope this answers your question. If you need further clarification, feel free to ask.
> 
> Best regards, [Dosu](https://dosu.dev)
> 
> ## Sources
> * [apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java)
> * [apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationController.java](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationController.java)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

你所说的这个关于NotificationId的比较似乎和我说的场景不一样。
1. 你提到的filterNotifications仅仅是为了过滤掉一些特殊场景，比如FX.apollo = 1 but fx.apollo = 2
2. 即使filterNotifications能过滤掉小于客户端的NotificationId，但filterNotifications发生在设置结果之前。如何保证设置结果的时候，也就是handleMessage方法里设置的NotificationId一定大于client端的？请帮我解决这个疑问 @nobodyiam 
----
This comparison you're talking about regarding NotificationId doesn't seem to be the same scenario I'm talking about.
1. you mentioned filterNotifications just to filter out some special scenarios like fx.apollo = 1 but fx.apollo = 2
2. even though filterNotifications can filter out NotificationId's that are smaller than the client's, the filterNotifications happen before the result is set. How to make sure that the NotificationId set in the handleMessage method must be greater than the client side when setting the result? Please help me with my query @nobodyiam

**Comment by nobodyiam** [comment]
> even though filterNotifications can filter out NotificationId's that are smaller than the client's, the filterNotifications happen before the result is set. How to make sure that the NotificationId set in the handleMessage method must be greater than the client side when setting the result?

I don't think we need to make sure the NotificationId set in the handleMessage method must be greater than the client side. The notification is only an event telling the client that some new configuration released. Even though the id is smaller than the client side, that only means the client already fetched the latest configurations. And we had the notification id check logic in ConfigController.

**Comment by PleaseGiveMeTheCoke** [comment]
> I don't think we need to make sure the NotificationId set in the handleMessage method must be greater than the client side. The notification is only an event telling the client that some new configuration released. Even though the id is smaller than the client side, that only means the client already fetched the latest configurations. And we had the notification id check logic in ConfigController.

Thanks for responding to my query, I have found the checksum logic for the notificationId in the ConfigController as you said, which does ensure that the client gets the latest configuration every time it fetches it.
But I still have a question, would it not be better to add the validation in handleMessage? This can avoid notificationId outdated result setting and reduce the rpc loss for client to do a configuration query.
There may be something I'm not thinking about, such as adding a checksum to the notificationId in the handleMessage would have other negative impacts, and if it does I'd be grateful for an answer!

**Comment by nobodyiam** [comment]
> would it not be better to add the validation in handleMessage

It could be done. However, I suspect the chances that the server-side notification ID is less than the client-side is very rare, so it's not that necessary.
