### ISSUE TITLE
怎么管理项目，为什么我按照分布式教程安装完成后，登陆apollo账号，没有“项目管理”的相关事项

### ISSUE THREAD

**Issue by ZxyNull0** [apolloconfig/apollo#5061]
![image](https://github.com/apolloconfig/apollo/assets/81354529/b53e86b0-5921-4c5f-872c-325e834f8119)

**Comment by nobodyiam** [comment]
Congratulations on successfully installing Apollo. Simply click on the app you've created, and you will be directed to the configuration and app management pages.

**Comment by ZxyNull0** [comment]
![image](https://github.com/apolloconfig/apollo/assets/81354529/8276b235-4087-406f-a47b-09a3a52cc72b)
apollo账号没有创建新项目的权限吗？我只可以新建应用，无法新建项目。

**Comment by nobodyiam** [comment]
老版本叫项目，最近的版本改成应用了
