### ISSUE TITLE
当一个项目存在大概500个namespace的情况下，页面打开到数据显示完成耗时很长，用户体检较差，这个目前有什么好的解决方案吗

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#5065]
当一个项目存在大概500个namespace的情况下，页面打开到数据显示完成耗时很长，用户体检较差，这个目前有什么好的解决方案吗
通过浏览器的F12来看，耗时情况如图：
<img width="1478" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/59378088-1d28-40cb-b5c2-510b745210b3">
其中耗时最长的接口为portal模块中的NamespaceController.java中的接口
<img width="1253" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/ec3618e3-a5aa-4c70-b688-3c097ecd1e1d">

**Comment by nobodyiam** [comment]
#1261

**Comment by 0xc9e36** [comment]
我们内部做了多线程分批调用adminservice，100+ namespace大概只有不到1s就返回前端了
