### ISSUE TITLE
Operation not permitted (cannot access pid file)

### ISSUE THREAD

**Issue by HadwinLing** [apolloconfig/apollo#5066]
**描述bug**
k8s 分为多个环境，其中在beta 环境下部署Apollo，报这个问题，但是在其他环境下部署时正常的。这个什么问题
Operation not permitted (cannot access pid file)
Wed Jan  3 19:50:54 CST 2024 Failed to start apollo-adminservice.jar, return code: 4

**Comment by nobodyiam** [comment]
麻烦提供下复现步骤
