### ISSUE TITLE
有没有考虑支持helm部署

### ISSUE THREAD

**Issue by oomgomgxx** [apolloconfig/apollo#5069]
随着 k8s 普及，无论是调研还是生产，helm 部署方式无疑可以大大降低使用者门槛。
如果可以降低使用者门槛，从另一个角度来看，其实相当于提高了产品本身的竞争力。
但目前在 helm 库中没有发现较新的chats，不知道后续会不会支持。
还有该 https://artifacthub.io/packages/helm/apollo/apollo-portal 库，是不是官方在维护

**Comment by nobodyiam** [comment]
可以看下[文档](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241-%e5%9f%ba%e4%ba%8ekubernetes%e5%8e%9f%e7%94%9f%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0)
