### ISSUE TITLE
不管是 docker compose 还是 helm，都必须手动自行初始化sql吗

### ISSUE THREAD

**Issue by oomgomgxx** [apolloconfig/apollo#5070]
这部分工作不能改由内部完成，即使不用 flyway 应该也不难实现吧。感觉不太方便🤔

**Comment by nobodyiam** [comment]
如果是 quick start，可以参考[文档](https://www.apolloconfig.com/#/zh/deployment/quick-start-docker)，是自动初始化的。
如果是生产部署，一般场景是有 DBA 来审核并执行的，自动初始化的场景不多。

**Comment by oomgomgxx** [comment]
> 如果是 quick start，可以参考[文档](https://www.apolloconfig.com/#/zh/deployment/quick-start-docker)，是自动初始化的。 如果是生产部署，一般场景是有 DBA 来审核并执行的，自动初始化的场景不多。

**Comment by oomgomgxx** [comment]
> 如果是 quick start，可以参考[文档](https://www.apolloconfig.com/#/zh/deployment/quick-start-docker)，是自动初始化的。 如果是生产部署，一般场景是有 DBA 来审核并执行的，自动初始化的场景不多。

但事实上大部份公司都是没有DBA。如果可以提供一个选择方式是不是体验性更好一些，譬如可以选择手动或者执行初始化（不是用flyway）
