### ISSUE TITLE
maven版本是如何定义的

### ISSUE THREAD

**Issue by pengbiaobeyond** [apolloconfig/apollo#5071]
我发现有些依赖是没有定义版本的，是怎样拉取到固定版本的
![image](https://github.com/apolloconfig/apollo/assets/46187883/167e584d-a23e-46ba-8838-9126592f55b6)

**Comment by pengbiaobeyond** [comment]
但是我一直拉到的都是1.29版本的包，仓库中已经有2.2版本的包了

**Comment by nobodyiam** [comment]
org.springframework.boot:spring-boot-dependencies 中定义的

**Comment by pengbiaobeyond** [comment]
谢谢
