### ISSUE TITLE
删除项目后，无法新建同名项目

### ISSUE THREAD

**Issue by annawhiteyellow** [apolloconfig/apollo#5074]
删除项目后，项目数据无法彻底清除，同时无法新建同名项目

**Comment by nobodyiam** [comment]
<img width="1119" alt="image" src="https://github.com/apolloconfig/apollo/assets/837658/63f9aa9a-b067-4c4f-bfd0-debd0313bc3d">

使用管理员工具删除

**Comment by annawhiteyellow** [comment]
谢谢，1.9.2版本存在此问题，升级到2.1.0版本后，可以正常删除和新建同名项目
