### ISSUE TITLE
apollo删除某个私有namespace之后，再创建同名的namespace会提示该名称的namespace已存在

### ISSUE THREAD

**Issue by guofuzheng** [apolloconfig/apollo#5076]
如标题所述，apollo删除某个私有namespace之后，再创建同名的namespace会提示该名称的namespace已存在，这个问题该怎么处理呢？

**Comment by nobodyiam** [comment]
可以用管理员工具中的 删除 AppNamespace 功能

![image](https://github.com/apolloconfig/apollo/assets/837658/fea2e38a-62ce-465b-8f5a-f561f072d614)
