### ISSUE TITLE
Prometheus Metrics接入问题

### ISSUE THREAD

**Issue by stancycowen** [apolloconfig/apollo#5077]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
官方文档里写了，暴露了Prometheus 格式的Metrics，实际怎么是个json？
![image](https://github.com/apolloconfig/apollo/assets/8426317/c0d10255-deae-4c26-8461-1791314261e1)

**复现**
请求 /metrics，是个JSON，Prometheus无法接入
{"names":["application.ready.time","application.started.time","disk.free","disk.total","executor.active","executor.completed","executor.pool.core","executor.pool.max","executor.pool.size","executor.queue.remaining","executor.queued","hikaricp.connections","hikaricp.connections.acquire","hikaricp.connections.active","hikaricp.connections.creation","hikaricp.connections.idle","hikaricp.connections.max","hikaricp.connections.min","hikaricp.connections.pending","hikaricp.connections.timeout","hikaricp.connections.usage","http.server.requests","jdbc.connections.active","jdbc.connections.idle","jdbc.connections.max","jdbc.connections.min","jvm.buffer.count","jvm.buffer.memory.used","jvm.buffer.total.capacity","jvm.classes.loaded","jvm.classes.unloaded","jvm.gc.concurrent.phase.time","jvm.gc.live.data.size","jvm.gc.max.data.size","jvm.gc.memory.allocated","jvm.gc.memory.promoted","jvm.gc.overhead","jvm.gc.pause","jvm.memory.committed","jvm.memory.max","jvm.memory.usage.after.gc","jvm.memory.used","jvm.threads.daemon","jvm.threads.live","jvm.threads.peak","jvm.threads.states","logback.events","process.cpu.usage","process.files.max","process.files.open","process.start.time","process.uptime","spring.data.repository.invocations","system.cpu.count","system.cpu.usage","system.load.average.1m","tomcat.sessions.active.current","tomcat.sessions.active.max","tomcat.sessions.alive.max","tomcat.sessions.created","tomcat.sessions.expired","tomcat.sessions.rejected"]}

请求 /metrics/disk.free
{"name":"disk.free","description":"Usable space for path","baseUnit":"bytes","measurements":[{"statistic":"VALUE","value":3.29164107776E11}],"availableTags":[{"tag":"path","values":["/apollo-portal/."]}]}

**期望**

暴露标准的Prometheus格式
如：
#HELP go_gc_duration_seconds A summary of the GC invocation durations.
#TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.0087e-05
go_gc_duration_seconds{quantile="0.25"} 2.2333e-05
go_gc_duration_seconds{quantile="0.5"} 4.3757e-05
go_gc_duration_seconds{quantile="0.75"} 9.1701e-05
go_gc_duration_seconds{quantile="1"} 0.000750728
go_gc_duration_seconds_sum 14.936457049

**截图**

![image](https://github.com/apolloconfig/apollo/assets/8426317/14de6d1f-4df9-453f-b9d4-5d216c991d0b)

### 额外的细节和日志

- 版本：2.1.0
- 错误日志
- 配置：
- 平台和操作系统   linux k8s

**Comment by nobodyiam** [comment]
文档中写得是`/prometheus`，不是`/metrics`

**Comment by stancycowen** [comment]
> 文档中写得是`/prometheus`，不是`/metrics`

实在抱歉，跟我自己的东西搞混了。
