### ISSUE TITLE
非kv格式的content也支持格式检查

### ISSUE THREAD

**Issue by czd890** [apolloconfig/apollo#5080]
+ 在主版本中是否可以格式检查, 不通过不让点击保存
![1706083358802](https://github.com/apolloconfig/apollo/assets/4011549/a3682210-eaee-43b4-9c71-7370a688f1bb)

+ 在灰度中类似k-v的类型检查(比如说当前namespace是json的, 修改灰度配置项这里的类型可以是固定死的json)
![1706083056816](https://github.com/apolloconfig/apollo/assets/4011549/91cc5efd-99fd-4920-a499-c69f399b70d6)

和k-v格式的namespace中的item差不多.
![1706083276000](https://github.com/apolloconfig/apollo/assets/4011549/6e93094d-0286-4bbf-8959-d386ad60e97f)

**Comment by nobodyiam** [comment]
可以作为一个配置项，有需要的用户可以开启
