### ISSUE TITLE
1.3.0-SNAPSHOT upgrading to the latest version need help?

### ISSUE THREAD

**Issue by majinding** [apolloconfig/apollo#5085]
The company is still using 1.3.0-SNAPSHOT. Could you please tell me if upgrading to the latest version would involve significant data migration? 

Are there any upgrade documents available?

**Comment by nobodyiam** [comment]
Numerous database schema modifications and data migration procedures are required. Please consult the release notes spanning versions 1.3.0 to 2.2.0. For detailed instructions, refer to the "How to Upgrade from xxx to xxx" section.
