### ISSUE TITLE
开启密钥认证后，不生效

### ISSUE THREAD

**Issue by liwei-geng** [apolloconfig/apollo#5091]
三个组件分别运行分三个容器部署的，访问正常，注册正常，但是在管理密钥中开启密钥后，客户端仍然可以不通过密钥认证获取配置。期待解答。

**复现**

通过如下步骤可以复现：

1. 数据修改注册连接
2. docker运行三个服务，启动系统。
3. 开启应用的管理密钥
4. 使用python或者直接get访问url都可以获取配置

**期望**
期望正常开启密钥验证，防止陌生客户端访问

**截图**

### 额外的细节和日志

- 版本：2.2.0
- 错误日志
- 配置：
- 平台和操作系统：阿里云centos7

**Comment by nisiyong** [comment]
Maybe you missed something, you should provide more details.

**Comment by liwei-geng** [comment]
> Maybe you missed something, you should provide more details.

这个在开启认证后不应该打开的，http://120.79.149.94:8090/apps/SampleApp/clusters/default/namespaces，但现在可以打开并获取配置。
下图是我开启的密钥，我使用的是第二种方法访问的，[BruceWW-pyapollo](https://github.com/BruceWW/pyapollo)
![微信截图_20240204151549](https://github.com/apolloconfig/apollo/assets/52914455/75d93521-97c0-4a79-b473-c02b27361c95)
![微信截图_20240204151626](https://github.com/apolloconfig/apollo/assets/52914455/529fda32-c355-4a6c-a56d-9773ee61ceca)

**Comment by liwei-geng** [comment]
抱歉，我对架构的理解出了偏差，以为客户端是要去admin service获取数据，后来看了下架构图，adminservice并不对外开放，仅限内部portal访问，用户都是访问的8080的configservice服务。打扰了。。。
