### ISSUE TITLE
upload properties by openapi  can not upload note

### ISSUE THREAD

**Issue by pengbiaobeyond** [apolloconfig/apollo#5092]
upload properties by openapi  can not upload note
应用openApi上传properties配置文件无法上传注释

**Comment by nobodyiam** [comment]
@pengbiaobeyond 请描述具体的信息，如接口名、参数等，根据 OpenAPI 的[使用文档](https://www.apolloconfig.com/#/zh/portal/apollo-open-api-platform?id=_3210-%e6%96%b0%e5%a2%9e%e9%85%8d%e7%bd%ae%e6%8e%a5%e5%8f%a3)，是可以传入注释的。
