### ISSUE TITLE
use apollo openapi  create properties file, can not create explanatory note

### ISSUE THREAD

**Issue by pengbiaobeyond** [apolloconfig/apollo#5095]
use apollo openapi  create properties file, can not create explanatory note
使用apollo的openapi创建properties配置文件，不能创建注释
![image](https://github.com/apolloconfig/apollo/assets/46187883/f54f1d58-0d23-4d47-ab00-5fcf13dc2333)
zhe这里的备注只存放在库里，并不是文件中的注释信息

**Comment by pengbiaobeyond** [comment]
Hope to receive a manual reply

**Comment by pengbiaobeyond** [comment]
希望老师帮忙确认下，是否是上边的解释，否则机器人回复心里没底

**Comment by BlackBear2003** [comment]
是存在数据库里的，ui上的文本里面也是通过读数据库来渲染的 🤔️

**Comment by pengbiaobeyond** [comment]
ui上的文本里边的注释在数据库中item表中的数据是key、value字段的值是空，comment字段的值是注释；
但是通过openApi，只能创建key、value有值，comment是key和value的备注，不是注释，ui无法渲染

**Comment by pengbiaobeyond** [comment]
如果存在注释的话，注释和key、value在item表里是两条数据

**Comment by pengbiaobeyond** [comment]
但是openApi只能创建一条数据

**Comment by pengbiaobeyond** [comment]
无法渲染注释

**Comment by pengbiaobeyond** [comment]
只有下图的红框的数据才可以渲染成注释，第一条数据是第二条数据的注释

**Comment by pengbiaobeyond** [comment]
<img width="417" alt="1708430375997" src="https://github.com/apolloconfig/apollo/assets/46187883/a5ca55a0-e8cd-4b29-8346-f59dce523c01">

**Comment by pengbiaobeyond** [comment]
但是openApi创建的properties配置是这样的，所以无法渲染
<img width="431" alt="1708430483805" src="https://github.com/apolloconfig/apollo/assets/46187883/c1b412bc-31c0-45b2-a07f-59471259765a">

**Comment by BlackBear2003** [comment]
找了下代码，确实是这样
```javascript
             function parsePropertiesText(namespace) {
                var result = "";
                var itemCnt = 0;
                namespace.items.forEach(function (item) {
                    //deleted key
                    if (item.isDeleted) {
                        return;
                    }
                    if (item.item.key) {
                        //use string \n to display as new line
                        var itemValue = item.item.value.replace(/\n/g, "\\n");

                        result +=
                            item.item.key + " = " + itemValue + "\n";
                    } else {
                        result += item.item.comment + "\n";
                    }
                    itemCnt++;
                });

                namespace.itemCnt = itemCnt;
                return result;
            }

```

**Comment by pengbiaobeyond** [comment]
所以说openApi目前是无法支持给properties配置文件添加注释的对吧

**Comment by BlackBear2003** [comment]
表格里面可以看到，但是文件里面好像是渲染不出来

**Comment by pengbiaobeyond** [comment]
恩恩，就是数据库表里可以看到，只是无法渲染到页面上对吧

**Comment by BlackBear2003** [comment]
可以等明天maintainer大佬来给个准确的回复 😳

**Comment by pengbiaobeyond** [comment]
好的，辛苦您明天帮我问下，谢谢

**Comment by pengbiaobeyond** [comment]
麻烦大佬今天帮忙看下

**Comment by pengbiaobeyond** [comment]
辛苦老师帮忙看下，拜托

**Comment by BlackBear2003** [comment]
我认为你的想法是对的，但我并不是官方人员，没法给你准确的回复 😂

**Comment by nobodyiam** [comment]
properties 文件的注释是在内容里面的，如

```properties
# comment 1
key1 = value1
# comment 2
key2 = value2
```

通过文本模式可以看到，不过请注意这个注释在表格模式是看不到的（设计如此）
![image](https://github.com/apolloconfig/apollo/assets/837658/3f5c5e04-d79f-4871-97b8-d71815e4710e)

**Comment by pengbiaobeyond** [comment]
我明白，但是通过openapi去添加properties配置文件中的内容时，是无法添加注释的

**Comment by pengbiaobeyond** [comment]
您上边的截图其实在数据库item表中是四条数据，但是openApi无法创建注释数据，
![image](https://github.com/apolloconfig/apollo/assets/46187883/dc0c50f2-bb3e-4d0f-86c6-56d193ba3d59)

**Comment by nobodyiam** [comment]
如果是单个配置的话是可以的，下面是我的测试代码和结果

```java
  @Test
  public void testCreate() {
    OpenItemDTO itemDTO = new OpenItemDTO();
    itemDTO.setKey("testKey");
    itemDTO.setValue("testValue");
    itemDTO.setComment("测试注释");
    itemDTO.setDataChangeCreatedBy(operator);

    OpenItemDTO result = client.createItem(appId, env, null, null, itemDTO);

    System.out.println(result);
  }
```

![image](https://github.com/apolloconfig/apollo/assets/837658/79d6597b-a648-4e33-a946-df28b6f4a441)

**Comment by pengbiaobeyond** [comment]
好的，明白了，谢谢
