### ISSUE TITLE
低版本升级最新版本 sql结构更新问题

### ISSUE THREAD

**Issue by muguan1995** [apolloconfig/apollo#5097]
scripts/sql/src 目录下没有2.1之前的升级sql文件了，原来低版本的apollo要如何升级数据库结构版本呢?

**Comment by nobodyiam** [comment]
转移到 https://github.com/apolloconfig/apollo/tree/master/scripts/sql/profiles/mysql-default/delta 了

**Comment by muguan1995** [comment]
> 转移到 https://github.com/apolloconfig/apollo/tree/master/scripts/sql/profiles/mysql-default/delta 了

找到了，感谢。顺便请问一下 v190-v200/apolloportaldb-v190-v200-after.sql  和普通的apolloportaldb-v190-v200.sql 区别是什么两个都要执行就行了吧

**Comment by nobodyiam** [comment]
可以看一下 [2.0.0](https://github.com/apolloconfig/apollo/releases/tag/v2.0.0) 的升级步骤
