### ISSUE TITLE
删除项目后异常

### ISSUE THREAD

**Issue by Eleven-M** [apolloconfig/apollo#5101]
![image](https://github.com/apolloconfig/apollo/assets/12506132/b4669072-9749-4f2a-a378-e256b3979879)
项目删除后，仍可以在控制台看到，而且项目内部异常，无法再重新创建一个AppId一致的项目。

**Comment by BlackBear2003** [comment]
https://github.com/apolloconfig/apollo/issues/5076

**Comment by nobodyiam** [comment]
@Eleven-M 请描述下详细的复现步骤
