### ISSUE TITLE
无法删除旧的配置

### ISSUE THREAD

**Issue by cjdxhjj** [apolloconfig/apollo#5123]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
![image](https://github.com/apolloconfig/apollo/assets/5616997/0a7bbd12-2eec-4da5-9a2f-25ccb29408ac)
![image](https://github.com/apolloconfig/apollo/assets/5616997/872b0de4-be37-4f6d-b72e-1ce6a19a715e)

如图,界面上展示的是1天，然而这个最后时间过去好几个月了，依然展示，无法删除
**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
说明这几个实例还连着。配置获取时间是指第一次拿到这个配置的时间。

**Comment by cjdxhjj** [comment]
我代码里早已去除了其引用

**Comment by cjdxhjj** [comment]
![image](https://github.com/apolloconfig/apollo/assets/5616997/eaa4caa8-ec18-474b-ab5f-e3127bc8d29e)
通过日志发现，client会一直试图加载application 这个namespace

**Comment by nobodyiam** [comment]
可以 debug 或者使用 arthas 看下是哪里引用了 application namespace
