### ISSUE TITLE
在项目namespace数量比较多的情况下(大约1000个)，打开页面加载速度很慢，比较影响用户体验，这个是否有什么优化改进方案？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#5126]
在项目namespace数量比较多的情况下(大约1000个)，打开页面加载速度很慢，比较影响用户体验，这个是否有什么优化改进方案？

**Comment by klboke** [comment]
什么版本的

**Comment by hezhaoye** [comment]
> 什么版本的

[Apollo 2.0.0-RC1 Release](https://github.com/apolloconfig/apollo/releases/tag/v2.0.0-RC1)

**Comment by klboke** [comment]
升级到2.1.0会有明显改善，详情见 https://github.com/apolloconfig/apollo/pull/4473

**Comment by hezhaoye** [comment]
好的，感谢。

**Comment by hezhaoye** [comment]
> 升级到2.1.0会有明显改善，详情见 #4473

升级后，发现了一个新的问题，这段逻辑在namespace很多的情况下，执行速度很长，在大概500个namespace的情况下，耗时大概25秒。看看这里是否可以优化下？
<img width="893" alt="image" src="https://github.com/apolloconfig/apollo/assets/9474302/9098c39b-4050-4668-9b4f-d1d84e667dc2">

**Comment by hezhaoye** [comment]
话说这个是否可以通过分页来实现页面加载速度提升呢

**Comment by klboke** [comment]
最新版本可以清理历史数据，也有助于加快查询
