### ISSUE TITLE
1.8.0,接入一个app.id 使用多个namespace的时候，多个namesapce均开启了accesskey.sercet，这时候接入的配置代码要怎么写呢

### ISSUE THREAD

**Issue by mickyss** [apolloconfig/apollo#5128]
apollo.accesskey.sercet= 这个可以直接支持多个秘钥吗

还是只能用
apollo.accesskey.namespace1= xx
apollo.accesskey.namespace2= xx
自己在读取的时候填写对应的key,

thanks

**Comment by mickyss** [comment]
好的，谢谢您

**Comment by bigbigbo** [comment]
学习到了
