### ISSUE TITLE
麻烦问下，有什么办法能同时读到多个环境同一个配置的值吗？

### ISSUE THREAD

**Issue by adgai** [apolloconfig/apollo#5133]
清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦

我们目前项目中获取配置是使用 configService.get(key)，这样的形式，需要看到key 对应的value 只能到 portal 中看，我想开发一个插件展示各个环境的值，所以想同时获取到多个环境的值。

**Comment by nobodyiam** [comment]
可以接入 [Open API](https://www.apolloconfig.com/#/zh/portal/apollo-open-api-platform)

**Comment by adgai** [comment]
open api 如果获取一个没配的key 会404，在获取生产环境的key的值时不太合适
