### ISSUE TITLE
使用客户端添加string类型的配置项时会报错

### ISSUE THREAD

**Issue by di666-dz** [apolloconfig/apollo#5135]
使用客户端增加string类型的配置项时会报错
![image](https://github.com/apolloconfig/apollo/assets/75009969/1701291d-ecce-4660-9d6b-42f54713063f)

{
    "exception": "org.springframework.orm.jpa.JpaSystemException",
    "message": "could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement",
    "status": 500.0,
    "timestamp": "2024-04-29T18:41:13.881"
}也没有改数据库，不清楚为什么会出现这个问题

**Comment by di666-dz** [comment]
> 使用quick start的客户端增加string类型的配置项时会报错 ![image](https://private-user-images.githubusercontent.com/75009969/326414958-1701291d-ecce-4660-9d6b-42f54713063f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODkzOTYsIm5iZiI6MTcxNDM4OTA5NiwicGF0aCI6Ii83NTAwOTk2OS8zMjY0MTQ5NTgtMTcwMTI5MWQtZWNjZS00NjYwLTlkNmItNDJmNTQ3MTMwNjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjc3NmY4MDA5MmUyMTQ0YTJlYzAyZWYxMDYyZTQ0NTFmYjBiM2JiYjdkNDIyODlkYjQ1ZmMzMzdkMTYyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSoJxtQiyzVLD1Fxkj9tvCZ7GHwJaRWvncLdhao-bd8)
> 
> { "exception": "org.springframework.orm.jpa.JpaSystemException", "message": "could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement", "status": 500.0, "timestamp": "2024-04-29T18:41:13.881" }

**Comment by nobodyiam** [comment]
看下 portal 和 admin service 的日志
