### ISSUE TITLE
k8s部署apollo 接入ldap报错

### ISSUE THREAD

**Issue by zhao-jing-hui** [apolloconfig/apollo#5140]
configmap配置如下
![image](https://github.com/apolloconfig/apollo/assets/71484934/cb7bf0ec-4898-456d-ae4a-68e57965ee55)
k8s deployment挂载配置文件如下图
![image](https://github.com/apolloconfig/apollo/assets/71484934/3b521a2a-0a6c-4cf3-a677-4f5f2e22debd)
启动的时候active变量如下图
![image](https://github.com/apolloconfig/apollo/assets/71484934/b481fca8-24fc-4cc2-b5ee-5f85917dc57c)
下面是报错内容，我已明确检查配置ldap的配置文件已经被挂载进去
![image](https://github.com/apolloconfig/apollo/assets/71484934/fa6e75e8-4b86-40d4-92e1-4fd91ac710e2)

**Comment by nobodyiam** [comment]
可以看下具体的报错信息，截图中的信息不够明确

**Comment by ltx0633** [comment]
> 可以看下具体的报错信息，截图中的信息还不够明确

<img width="1377" alt="image" src="https://github.com/apolloconfig/apollo/assets/47582550/3b79099a-7e31-49df-a093-51e49e5b1f1a">

我遇到了同样的错误，这是细节

**Comment by zhao-jing-hui** [comment]
> > 可以查看具体的报错信息，截图中的信息还不够明确
> 
> <img alt="图像" width="1377" src="https://private-user-images.githubusercontent.com/47582550/340231924-3b79099a-7e31-49df-a093-51e49e5b1f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTMwODksIm5iZiI6MTcxODYxMjc4OSwicGF0aCI6Ii80NzU4MjU1MC8zNDAyMzE5MjQtM2I3OTA5OWEtN2UzMS00OWRmLWEwOTMtNTFlNDllNWIxZjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NWMxNGE4ZDAyMzNiMjllZjdlY2Y0ZmJhYzY0ZDAyZDY2Yjg4ZjY0YmI3MTZmNTdjZDE2NDY1ZjVkODQzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cvis5RfoNJ3ZKBSlW2UW-FGAvbILupNycYmUEdSDcAI">
> 我遇到了同样的错误，这是

这个问题我已经解决了，根据此问题修改对应的代码，重新编译生成jar包替换即可。
