### ISSUE TITLE
删除App后，相似的AppID权限异常，并无法恢复

### ISSUE THREAD

**Issue by xyangcm** [apolloconfig/apollo#5143]
使用mysql数据库时，当与删除appid中包含下划线'_'时，导致相似的app权限异常

在mysql中like查询时，下划线代表任意一个字符

当删除 hello_world 后，访问 helloaworld 时，相关权限提示异常，重新授权无法恢复

发现版本：1.4.1
当前master版本中代码仍在使用like的方式查找并删除

**Comment by xyangcm** [comment]
当我从Apollo管理页面中删除AppID为hello_world 的应用后，因为下换线的原因，helloaworld 这个应用的权限出现了异常，重新给helloaworld出现异常的人员再次授权，仍无法使用

**Comment by nobodyiam** [comment]
> 当我从Apollo管理页面中删除AppID为hello_world 的应用后，因为下换线的原因，helloaworld 这个应用的权限出现了异常，重新给helloaworld出现异常的人员再次授权，仍无法使用

可以尝试手动恢复一下被删除的数据，如 

```sql
select * from Role where RoleName in ('ModifyNamespace+helloaworld+application', 'ReleaseNamespace+helloaworld+application');
select * from Permission where TargetId = 'helloaworld+application';
```
