### ISSUE TITLE
dockerfile基础镜像漏洞

### ISSUE THREAD

**Issue by ltx0633** [apolloconfig/apollo#5144]
**你的特性请求和某个问题有关吗？请描述**

在安全合规时发现镜像存在漏洞，是否适用其他版本的jre？

**清晰简洁地描述一下你希望的解决方案**

更新基础镜像

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

![image](https://github.com/apolloconfig/apollo/assets/47582550/ab408329-22a1-4447-9436-9283d628f1df)

**Comment by nobodyiam** [comment]
[eclipse-temurin:17-jre](https://hub.docker.com/layers/library/eclipse-temurin/17-jre/images/sha256-a950541e4ab5fb86f954d91f13d44f41a5f1624da2b5a631462b4137576b7e23?context=explore) appears to be a strong alternative.

**Comment by ltx0633** [comment]
<img width="1343" alt="截屏2024-05-22 21 35 20" src="https://github.com/apolloconfig/apollo/assets/47582550/9d98d799-a4cb-4e08-9145-04ece1867cc9">

According to the product image of [PR](https://github.com/apolloconfig/apollo-quick-start/pull/115). Whether to consider upgrading components (postgres, log4j), etc.

In addition, I have verified that eclipse-temurin:17-jre images are feasible in a production environment

> [eclipse-temurin:17-jre](https://hub.docker.com/layers/library/eclipse-temurin/17-jre/images/sha256-a950541e4ab5fb86f954d91f13d44f41a5f1624da2b5a631462b4137576b7e23?context=explore) appears to be a strong alternative.

**Comment by nobodyiam** [comment]
> Whether to consider upgrading components (postgres, log4j), etc.
PRs are welcome to upgrade these dependencies.
