### ISSUE TITLE
使用docker安装apollo 镜像里面的demo.sh缺少读取环境变量的逻辑

### ISSUE THREAD

**Issue by huangxinze** [apolloconfig/apollo#5145]
**描述bug**

使用docker安装apollo 镜像里面的demo.sh缺少读取环境变量的逻辑；我从下面这个地址下载的docker-compose.yml文件，然后把设置了mysql的密码，启动quick-start的密码的字段后，一直提示数据库链接失败，经确认 镜像里面的启动脚本 不是最新的，没有读取环境变量的逻辑在里面
https://www.apolloconfig.com/#/zh/deployment/quick-start-docker

**复现**

通过如下步骤可以复现：

1. 下载docker-compose.yml
2.  修改mysql密码
3.  sudo docker-compose up 启动服务
4.  启动失败，提示数据库链接失败

**期望**

修复 下载镜像里面的 demo.sh 启动脚本，支持读取环境变量

**Comment by nobodyiam** [comment]
You may check whether the image in your local cache is the latest or not.

https://hub.docker.com/r/nobodyiam/apollo-quick-start/tags

**Comment by huangxinze** [comment]
> You may check whether the image in your local cache is the latest or not.
> 
> https://hub.docker.com/r/nobodyiam/apollo-quick-start/tags

You are correct, it was solved by downloading the image of version 2.2.0, thanks
