### ISSUE TITLE
yml读取k-v的值错误

### ISSUE THREAD

**Issue by Eleven-M** [apolloconfig/apollo#5146]
配置如下：
![image](https://github.com/apolloconfig/apollo/assets/12506132/b6efe6a7-a467-460d-83a2-77f4303d393f)

请求返回null,调整配置，删除只保留一个下节点，返回的v不是节点，而是一个整体。

![image](https://github.com/apolloconfig/apollo/assets/12506132/de54ac1e-c04b-43ef-803b-db96701a387d)

反复手动新增节点修改过，都不行。

**Comment by Eleven-M** [comment]
@xxxx@ 这种项目变量需要怎么处理，要放到项目里面吗？

**Comment by nobodyiam** [comment]
可以看看客户端读取配置的日志
