### ISSUE TITLE
未添加监听, 也在做空转长轮询

### ISSUE THREAD

**Issue by qq31715879** [apolloconfig/apollo#5158]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
未添加监听, 也在空转长轮询
![image](https://github.com/apolloconfig/apollo/assets/21219283/a4952669-e94f-48c8-a312-49df3be44e58)

![image](https://github.com/apolloconfig/apollo/assets/21219283/816675f7-82e6-45ef-b70b-1d2b7a4e29ce)

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**
添加close方法; 有一部分配置, 只希望远程拉完就结束

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>1.7.0</version>
        </dependency>
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
长轮询是为了更新配置，和是否监听无关

**Comment by qq31715879** [comment]
但是我没有监听, 长轮询拉到了新配置也没用呀;
有些业务不需要更新配置; 有些配置是静态的一次读取完毕之后, 就不在需要更新了的
