### ISSUE TITLE
关于指定注册的IP/URL引发的问题

### ISSUE THREAD

**Issue by liwei-geng** [apolloconfig/apollo#5160]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

在apolloconfig和admin中的startup.sh中分别指定-Deureka.instance.ip-address=xxxxx、-Deureka.instance.homePageUrl=http://xxxxx:8080、-Deureka.instance.preferIpAddress=false参数后，系统信息显示正常，Check正常，但是在系统参数界面无法显示配置参数信息。且应用页打开报错，截图如下。

**复现**

通过如下步骤可以复现：

1. 配置安装好portal，并指定apollo.portal.meta.servers，用的为公网地址。
2. 分别安装config和admin服务，配置数据库，vim两个服务下的startup.sh文件，指定参数-Deureka.instance.ip-address=xxxxx、-Deureka.instance.homePageUrl=http://xxxxx:8080、-Deureka.instance.preferIpAddress=false
3. 分别启动config、admin、portal服务

**期望**

期望正常情况下应该正常加载新的环境的配置参数。

**截图**
按照如上步骤后的正常截图：
![image](https://github.com/apolloconfig/apollo/assets/52914455/7a16ba4b-2cce-4f0e-ba6f-7becb3f78692)

无法读取新环境的配置参数
![image](https://github.com/apolloconfig/apollo/assets/52914455/c7b64942-dbc7-4ac0-940c-545579311039)

点击应用后的报错截图
![image](https://github.com/apolloconfig/apollo/assets/52914455/fdb03157-10e0-42e7-8ef8-c937fab603db)

相应的日志截图
![image](https://github.com/apolloconfig/apollo/assets/52914455/e1c84586-fc37-48da-a705-f47042886255)

- 版本：2.2.0
- 平台和操作系统 centos7.5

**Comment by nobodyiam** [comment]
![image](https://github.com/apolloconfig/apollo/assets/837658/fb08e535-3f64-4e16-8d16-8f8118158384)

admin service 的地址看起来注册错了
