### ISSUE TITLE
apollo portal webhook 使用问题

### ISSUE THREAD

**Issue by tsiayutai** [apolloconfig/apollo#5165]
您好想请问一下 apollo portal 的 webhook功能, 如果我启用后要怎么关闭这个功能？
我测试把这两个 key   webhook.supported.envs, config.release.webhook.service.url   留空后发现不能保存.

**Comment by nobodyiam** [comment]
看起来配置页面上做了非空的限制，可以直接操作数据修改配置

**Comment by tsiayutai** [comment]
好的感謝協助.
