### ISSUE TITLE
metrics接口可以关闭或者增加鉴权吗

### ISSUE THREAD

**Issue by banqinghong** [apolloconfig/apollo#5166]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述**
metrics接口可以关闭或者增加鉴权吗？

- 版本：2.1.0
- 错误日志
- 配置：
- 平台和操作系统：centos7.9

**Comment by nobodyiam** [comment]
https://github.com/apolloconfig/apollo/blob/49bd8ccab93c2484dacabd9d0709bb49efbdfc4b/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java#L84-L86
