### ISSUE TITLE
apollo 2.0.1 版接入 keycloak 认证后, 多关连的 namespace 查询配置更慢

### ISSUE THREAD

**Issue by tsiayutai** [apolloconfig/apollo#5167]
您好想请教个问题, 我们以前使用 apollo 1.3版的时候也是用 kyecloak 做验证, 但最近升级到 apollo 2.0.1 版本之后在多关连的 namespace 查寻变的比以前还慢, 请问 apollo 1.3版和 apollo 2.0.1版使用 keycloak 验证身份的时候逻辑有不一漾吗?

**Comment by nobodyiam** [comment]
验证身份的逻辑应该不会影响到性能，可以用 profiler 工具看下慢在哪里？

**Comment by tsiayutai** [comment]
目前看都是点选应用后展开namespace 时会pending 非常久
我们有同时查看过 keycloak 的debug 日志, 当apollo portal 展开一个包含100个namespace 的应用,  会非常频繁的跟keycloak 验证, 感覺是每展開一個 namespace ,都要去跟 kyecloak 驗證, 不晓得是不是这段导致查询很慢

**Comment by nobodyiam** [comment]
#3629 增加了 username 的展示，看起来和这个 feature 相关

**Comment by tsiayutai** [comment]
了解, 那看起来是 1.9.0版本后添加的功能,感谢协助确认谢谢

**Comment by tsiayutai** [comment]
抱歉再请问一下,这问题目前有办法缓解吗, 或是有什么参数能调整?

**Comment by nobodyiam** [comment]
看 PR 的内容没有预留参数开关，如果不是必须的功能，可以考虑增加一个配置参数

**Comment by nobodyiam** [comment]
@hardng 看上去是 KeyCloakUserService.findByUserIds 比较慢，可以看下如何优化下性能

![Image](https://github.com/user-attachments/assets/ff975ab7-881c-44b0-a02e-1bdb7a2a10ae)
