### ISSUE TITLE
eureka目前没有认证机制，如果线上需要增加认证机制，这个代码层面目前是否有办法可以做到不影响线上服务的运行，通过升级增加上认证机制呢？如果可以，可以说下升级改造流程吗？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#5170]
eureka目前没有认证机制，如果线上需要增加认证机制，这个代码层面目前是否有办法可以做到不影响线上服务的运行，通过升级增加上认证机制呢？如果可以，可以说下升级改造流程吗？

**Comment by nobodyiam** [comment]
是指 eureka 服务注册认证还是 eureka 服务发现认证？
服务注册认证是支持的：[3.2.9 apollo.eureka.server.security.enabled - 配置是否开启eureka server的登录认证](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_329-apolloeurekaserversecurityenabled-%e9%85%8d%e7%bd%ae%e6%98%af%e5%90%a6%e5%bc%80%e5%90%afeureka-server%e7%9a%84%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81)

**Comment by hezhaoye** [comment]
> 服务注册认证是支持的：[3.2.9 apollo.eureka.server.security.enabled - 配置是否开启eureka server的登录认证](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_329-apolloeurekaserversecurityenabled-%e9%85%8d%e7%bd%ae%e6%98%af%e5%90%a6%e5%bc%80%e5%90%afeureka-server%e7%9a%84%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81)

是指这个注册认证。对于已有的运行服务，这个升级的流程看文档没有提到。对于已有的服务开启这个特性，升级流程上有什么要注意的吗？

**Comment by nobodyiam** [comment]
可以搭建一个新的带注册认证的集群，而后把 meta server 的域名指向新的集群

**Comment by hezhaoye** [comment]
> 可以搭建一个新的带注册认证的集群，而后把 meta server 的域名指向新的集群

如果不搭建全新的集群，在已有混合的config Service上有办法可以做到平滑升级到开启认证机制吗

**Comment by nobodyiam** [comment]
建议在测试环境验证下，比如改了配置后一台一台重启
