### ISSUE TITLE
Wiki - Apollo 开放平台，文章开头的 Apollo开放平台接入指南链接已失效

### ISSUE THREAD

**Issue by cmjzzx** [apolloconfig/apollo#5174]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

Wiki - [Apollo 开放平台](https://github.com/apolloconfig/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)，文章开头的 Apollo开放平台接入指南链接已失效，点击返回了 404，链接地址是 https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform

正确的链接地址应该是
https://www.apolloconfig.com/#/zh/portal/apollo-open-api-platform

**Comment by nobodyiam** [comment]
Thanks for the reminder. It's fixed now.
