### ISSUE TITLE
优缺点

### ISSUE THREAD

**Issue by SirCFC** [apolloconfig/apollo#5177]
想咨询下，apollo有没有做过其他产品consul之类的配置中心功能比对，以及优缺点

**Comment by nobodyiam** [comment]
热心网友[@Krast](https://github.com/krast)曾经做了一个[开源配置中心对比矩阵](https://github.com/apolloconfig/apollo/files/983064/default.pdf)，可以参考一下。
> consul 并不属于配置中心产品
