### ISSUE TITLE
配置的多个公共properties，如何配置读取不同的properties下的属性?

### ISSUE THREAD

**Issue by wangyabin1126** [apolloconfig/apollo#5178]
springboot项目，apollo配置中心对应项目中关联了两个公共kafka的配置cariad-kafka.properties和cariad-tob-kafka.properties，两个namespace下配置的是相同的属性；
如何在私有的properties中引用不同的namespace下的属性？
![Uploading 1721186543243.jpg…]()

**Comment by nobodyiam** [comment]
可以用 api 方式读取
