### ISSUE TITLE
我希望对接公司的统一登录系统 SSO， 但是我没有再portal项目中找到   登录时设置 cookie和session的入口，我希望知道： 登陆成功后如何设置cookie，在后续的操作中，能够用户验证通过

### ISSUE THREAD

**Issue by maxiaoyin** [apolloconfig/apollo#5179]
版本信息： apollo 1.9.2

问题：
对接公司的单点登陆系统

目的：
希望知道应该如何设置cookie和session， 在后续的页面操作，可以验证通过

**Comment by maxiaoyin** [comment]
有这方便的经验的同志么，可以指导下

**Comment by nobodyiam** [comment]
[实现方式四： 接入公司的统一登录认证系统](https://www.apolloconfig.com/#/zh/extension/portal-how-to-implement-user-login-function?id=%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f%e5%9b%9b%ef%bc%9a-%e6%8e%a5%e5%85%a5%e5%85%ac%e5%8f%b8%e7%9a%84%e7%bb%9f%e4%b8%80%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81%e7%b3%bb%e7%bb%9f)

**Comment by fanslin** [comment]
> [实现方式四： 接入公司的统一登录认证系统](https://www.apolloconfig.com/#/zh/extension/portal-how-to-implement-user-login-function?id=%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f%e5%9b%9b%ef%bc%9a-%e6%8e%a5%e5%85%a5%e5%85%ac%e5%8f%b8%e7%9a%84%e7%bb%9f%e4%b8%80%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81%e7%b3%bb%e7%bb%9f)

如果接入了公司的统一登录认证系统，比如公司用的是钉钉登录，那么用户登录后的权限要如何跟Apollo打通？

**Comment by fanslin** [comment]
> [实现方式四： 接入公司的统一登录认证系统](https://www.apolloconfig.com/#/zh/extension/portal-how-to-implement-user-login-function?id=%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f%e5%9b%9b%ef%bc%9a-%e6%8e%a5%e5%85%a5%e5%85%ac%e5%8f%b8%e7%9a%84%e7%bb%9f%e4%b8%80%e7%99%bb%e5%bd%95%e8%ae%a4%e8%af%81%e7%b3%bb%e7%bb%9f)

@nobodyiam 如果接入了公司的统一登录认证系统，比如公司用的是钉钉登录，那么用户登录后的权限要如何跟Apollo打通？

**Comment by nobodyiam** [comment]
1. 登录和钉钉打通
2. 权限在 apollo 上管理
