### ISSUE TITLE
新建应用时权限赋予错误

### ISSUE THREAD

**Issue by Lin-1997** [apolloconfig/apollo#5181]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
A用户新建一个应用，将应用负责人、应用管理员都仅设置为B用户。此时也为A用户赋予了默认namespace的编辑、发布权限，不应该给A用户任何权限的。

**To Reproduce**
1.新建一个应用，将应用负责人、应用管理员都仅设置为B用户

**Expected behavior**
A用户没有任何权限

### Additional Details & Logs

https://github.com/apolloconfig/apollo/blob/49bd8ccab93c2484dacabd9d0709bb49efbdfc4b/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRoleInitializationService.java#L83-L89

应该赋权限给用户Sets.newHashSet(app.getOwnerName())，而不是Sets.newHashSet(operator)

- Version 2.2.0
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
I believe this is a bug, would you please help to submit a pull request to fix it?

**Comment by Lin-1997** [comment]
> I believe this is a bug, would you please help to submit a pull request to fix it?

see this https://github.com/Lin-1997/apollo/pull/1
