### ISSUE TITLE
Duplicate entry 错误日志在InstanceConfig和Instance表

### ISSUE THREAD

**Issue by czd890** [apolloconfig/apollo#5183]
在微服务使用场景下ip会被重复使用

### Additional Details & Logs

- Version
  - 2.2.0
- Error logs
  - Duplicate entry '{id}-{app}-{namespace}' for key 'InstanceConfig.IX_UNIQUE_KEY'
  - Duplicate entry '{namespace}-{cluster}-{ip}-' for key 'Instance.IX_UNIQUE_KEY'
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
一台机器上有多个 apollo client？

**Comment by czd890** [comment]
@nobodyiam 不是的, 主机/容器是aws ecs fargate.
没有检查代码, 根据异常的message, 我猜测是由同一个ip被多次重复使用导致的. 一个ip分配给A container, A 在terminate之后又分配给了B container(不同的appId).

**Comment by nobodyiam** [comment]
看了下代码，应该是并发创建所致，对功能层面没影响

**Comment by czd890** [comment]
@nobodyiam 应该会影响在portal instances 列表功能把? 是不是需要fix下?
