### ISSUE TITLE
从 1.6.1 升级到 1.9.2 后  访问portal比较慢，尤其是访问有上百个 namespace的appid 时

### ISSUE THREAD

**Issue by netkey** [apolloconfig/apollo#5184]
因为我们的 apollo 已经几年时间未做过版本升级，为了和官方版本不至于落后太多，近日将apollo进行了版本升级，从 1.6.1 版本升级到 1.9.2 版本，我们使用了 LDAP 认证。升级后发现 portal 页面加载比之前变慢了，这部分原因我理解为需要从 LDAP拉取用户真实姓名有所影响，大部分app加载的时候还能接受。但是在加载有上百个 namespace 的 app 信息时，浏览器在查询 namespace接口时比如/apps/appname/envs/PRO/clusters/default/namespaces 时候 pending 很久，等待 1-2 分钟才能返回结果。请问下原因是否和#5126一样，需要升级到 2.1.0 版本才能解决？

**Comment by gosszhang** [comment]
我也遇到类似问题，我自己把这段代码（文件：apollo-portal\src\main\java\com\ctrip\framework\apollo\portal\service\AdditionalUserInfoEnrichServiceImpl.java）注释掉，自己打包了一个镜像，目前速度明显提升了。这里是否可以加个开关，可以选择是否补全用户姓名。
![image](https://github.com/user-attachments/assets/6feb1a4c-f963-4cbb-8151-cf823454356b)
