### ISSUE TITLE
 使用teams 提供的 webhook 會報錯

### ISSUE THREAD

**Issue by eddie-huhu** [apolloconfig/apollo#5187]
- [X] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [X] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [X] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
![image](https://github.com/user-attachments/assets/2bf92084-7ca6-4460-89da-a7934e256233)

使用teams 提供的webhook 會噴錯

**复现**
通过如下步骤可以复现：

![Snipaste_2024-07-30_13-53-50](https://github.com/user-attachments/assets/0c850ae7-d178-4d0d-be29-2a92ff366dc1)

**期望**

有甚麼方法能處理呢

**截图**

![image](https://github.com/user-attachments/assets/ce785096-8da9-4da8-9777-feea1fbfc54d)

### 额外的细节和日志

- 版本： k8s helm apollo
- 错误日志

**Comment by nobodyiam** [comment]
中间加一个转换，把 apollo 的 [webhook request](https://www.apolloconfig.com/#/zh/extension/portal-how-to-enable-webhook-notification) 转成 teams 需要的格式
