### ISSUE TITLE
2.2版本中环境PROD被转换为PRO，导致consumer使用时匹配环境失败

### ISSUE THREAD

**Issue by Jason-King** [apolloconfig/apollo#5193]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

2.2版本中，环境（ENV）PROD被转换为PRO，导致consumer调用/openapi/v1/apps/{appId}/envclusters接口，拿到返回值后使用prod匹配环境失败

**期望**

应该返回prod，否则升级2.2版本后会出现不兼容的情况
**截图*
![image](https://github.com/user-attachments/assets/b941070b-d778-46cd-bc10-28293dc10d8e)

**Comment by nobodyiam** [comment]
这个改动是 #4887 中带来的，看起来也是为了修复一个 bug
