### ISSUE TITLE
客户端启动阶段能否考虑并行获取配置集

### ISSUE THREAD

**Issue by whitefeather2018** [apolloconfig/apollo#5196]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

ApolloApplicationContextInitializer在启动阶段遍历Apollo

ApolloApplicationContextInitializer在启动阶段遍历Apollo.bootstrap.namespaces列表中的配置集，串行进行配置集获取，想问一下为什么考虑串行而不是并行。目前碰到的问题是在配置集比较多的场景下，如果配置中心服务出问题，客服端会由于启动阶段配置获取失败而导致重试（重试存在时间间隔），又因为是串行的，综合导致了启动时间过长。

**复现**

通过如下步骤可以复现：

1. 将apollo.meta参数配置为错误值，模拟启动阶段连不上服务端
2. 在apollo.bootstrap.namespaces中配置多个配置集
3. 本地没有缓存文件
4. 

**期望**
希望可以并行进行配置集获取。（但是并行获取配置集不确定会不会有其他副作用）

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
有一个 PR 尝试提升配置获取速度可以参考下 - https://github.com/apolloconfig/apollo-java/pull/64
