### ISSUE TITLE
关于k8s容器化部署和portal管理多集群环境的网络问题

### ISSUE THREAD

**Issue by fychaha** [apolloconfig/apollo#5201]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

场景是这样的，我这边是有两套k8s集群，集群1和集群2两套集群各部署了一套apollo服务，但是portal只部署了一套，想通过这一套portal去管理两套集群环境。实际部署下来portal在访问集群2的metaserver后，会出现疑似docker内部网络的ip，portal通过这个ip去访问health接口出现了网络不通的问题。请问有可用的方案实现这种功能吗，不然只能两套集群都部署portal吗

**Comment by nobodyiam** [comment]
* [1.4 网络策略](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_14-%e7%bd%91%e7%bb%9c%e7%ad%96%e7%95%a5)
* [2.4.1.3.4.5 指定Meta Server返回的apollo-adminservice地址](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241345-%e6%8c%87%e5%ae%9ameta-server%e8%bf%94%e5%9b%9e%e7%9a%84apollo-adminservice%e5%9c%b0%e5%9d%80)
