### ISSUE TITLE
Apollo合适可以支持Tongweb容器

### ISSUE THREAD

**Issue by taoyiqun** [apolloconfig/apollo#5203]
**你的特性请求和某个问题有关吗？请描述**

最近遇到XC改造的需求，Apollo对Tongweb的兼容性貌似不是很好。

**清晰简洁地描述一下你希望的解决方案**

兼容Tongweb

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by shoothzj** [comment]
Are you having any problems? What do you expect the community to do? :)

**Comment by shoothzj** [comment]
closed by no additional information
