### ISSUE TITLE
apollo-adminservice服务增加了认证，apollo-portal增加了对应token.但是apollo首页就没登录了，也没办法登出

### ISSUE THREAD

**Issue by yueqingMonkey** [apolloconfig/apollo#5207]
**描述bug**
因为8090、8080端口提供的服务，能直接通过url拿到信息。需要增加认证。然后就根据如下章节：
1.7.1及以上版本可以考虑为apollo-adminservice开启[访问控制](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#6-admin-serviceaccesscontrolenabled---%E9%85%8D%E7%BD%AEapollo-adminservice%E6%98%AF%E5%90%A6%E5%BC%80%E5%90%AF%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6)，从而只有合法的apollo-portal才能访问对应接口，增强安全性。
进行了修改。但是修改完以后，apollo首页就不需要登录了，也不能登出了。

- 版本： 1.9.2

- 配置：
admin-service增加配置如下：
admin-service:
  access:
    tokens: c5fde189123547e49655ae1d6c8b3b56
    control:
      enabled: true

apollo-portal增加配置如下：
admin-service:
  access:
    tokens: '{"dev":"c5fde189123547e49655ae1d6c8b3b56"}'

**Comment by nobodyiam** [comment]
看描述是 portal 的 profile 改错了，可以参考下[文档](https://www.apolloconfig.com/#/zh/extension/portal-how-to-implement-user-login-function)看看哪里改错了

**Comment by yueqingMonkey** [comment]
谢谢，8090的admin-service服务可以了，portal也可以登录了。现在有一个新的问题，8080端口应用提供拉取配置的服务，可以直接通过url拿到配置，这个有什么修复方法吗？

**Comment by nobodyiam** [comment]
[7.1.3 系统访问](https://www.apolloconfig.com/#/zh/portal/apollo-user-guide?id=_713-%e7%b3%bb%e7%bb%9f%e8%ae%bf%e9%97%ae)
