### ISSUE TITLE
客户端启动时拉取不到Apollo配置导致重启

### ISSUE THREAD

**Issue by Arthur-X-Wang** [apolloconfig/apollo#5208]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

在容器部署场景下，当微服务重启、扩容等操作时，Apollo集群不可达，业务容器拉取不到配置，本地也没有任何缓存配置。此时，业务容器会因缺少配置启动不起来。
假设正好某个情境下，业务容器大批量崩溃，Apollo也同时崩溃且一段时间不可恢复，原本业务容器可以通过扩容使服务恢复，此时也完成不了这个操作，异常影响较大。
对于此种方案，我们考虑过本地默认配置，但是由于Apollo配置更新多次后，本地默认配置过于老旧。比如开关类的，这样更加不可控。
对于此种异常情景，Apollo是否有高可用设计?

**复现**

通过如下步骤可以复现：

1. 关闭Apollo配置中心，新启动客户端

**期望**

当配置中心连接不可达时，业务容器的启动不应该受到影响

**截图**

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
see #3506，另外[开源之夏](https://github.com/apolloconfig/apollo/wiki/Open-Source-Promotion-Plan-Summer-2024-Tasks)有一个项目是为Apollo的java、golang客户端缓存支持Kubernetes ConfigMap，导师是 @shoothzj
