### ISSUE TITLE
希望openapi支持撤销修改的功能

### ISSUE THREAD

**Issue by b675987273** [apolloconfig/apollo#5221]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦
我通过openapi进行删除一些配置项时，需要先调用删除接口再调用发布接口。要是调用发布接口时报错，实际上删除接口已经进入修改状态但是没有发布，那么我希望的是我能感知这个修改但没有发布的状态。
![image](https://github.com/user-attachments/assets/07e0d94b-b47d-4447-825f-cbae9832e119)

**清晰简洁地描述一下你希望的解决方案**
openapi支持撤销修改或者感知当前是否处于修改但未发布状态
![image](https://github.com/user-attachments/assets/59554891-7c00-4705-a885-a9978f382c8c)

**清晰简洁地描述一下这个特性的备选方案**
目前没有

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
see #5028
