### ISSUE TITLE
普通应用如何不通过Portal来管理配置？

### ISSUE THREAD

**Issue by a1156698162** [apolloconfig/apollo#5225]
**描述问题**

apollo提供了openai的方式支持第三方应用可以公共http的方式来管理应用配置包括新增配置，发布配置等操作？
但是对于apollo中的普通应用我看到文档用有通过http或者java客户端的方式来获取应用的配置信息，对于普通应用管理配置的方式只能通过官方提供Portal来操作吗？

**期望**

我希望对于普通应用能有用http的方式或者java客户端的方式来管理应用配置，而不是通过Portal界面来管理

**Comment by nobodyiam** [comment]
OpenAPI  提供了常用的管理配置能力

**Comment by a1156698162** [comment]
Apollo提供的OpenApi不仅能管理第三方应用，也能管理普通应用吗。那管理普通应用的token从哪里获取呢
