### ISSUE TITLE
【bug】A用户打开管理端页面长时间不刷新，中间时间B用户进行发布配置，B发布完成后A用户没刷新页面就直接通过文本模式修改配置，由于A用户不会重新加载当前最新配置，导致操作会覆盖当前最新配置，这个问题是否可以增加版本检查来避免此问题？

### ISSUE THREAD

**Issue by hezhaoye** [apolloconfig/apollo#5226]
复现流程
1、A用户打开管理端应用页面后，长时间没关闭页面
2、B用户打开管理端页面后进行配置修改和发布
3、B用户发布完成后，A用户没有刷新页面，直接文本模式编辑properties的namespace配置，然后发布。
4、由于A用户没有刷新页面，导致没有重新拉取最新的配置，导致发布会覆盖当前的最新配置。

注：当前的防止多人并发修改特性也不能避免此问题；因为B用户编辑并发布完成后(锁释放了)，A用户再来操作，也会出现此问题。类似java并发的ABA问题。

针对此问题，看看是否可以增加版本控制检查来判断，如果是旧版本，就提示用户刷新页面？

**Comment by nobodyiam** [comment]
> 针对此问题，看看是否可以增加版本控制检查来判断，如果是旧版本，就提示用户刷新页面？

这个方式是可行的，不过上述例子中 A 用户提交配置后是能看到修改了预期之外的配置，在发布的时候也会有提示的，稍加注意应该是能避免该问题的。

**Comment by hezhaoye** [comment]
> > 针对此问题，看看是否可以增加版本控制检查来判断，如果是旧版本，就提示用户刷新页面？
> 
> 这个方式是可行的，不过上述例子中 A 用户提交配置后是能看到修改了预期之外的配置，在发布的时候也会有提示的，稍加注意应该是能避免该问题的。

如果A用户一直都没有刷新过页面，直接text修改，是感知不到新配置的。部分用户有保留页面没刷新的习惯，这种虽然出现的概率较低，但是生产配置还是有隐患，官方看看是否完善下？

**Comment by hezhaoye** [comment]
如果同一个项目，使用的组员较多的情况下，这个情况出现的频率就会变高，这个官方考虑修复下吗

**Comment by hezhaoye** [comment]
> > 针对此问题，看看是否可以增加版本控制检查来判断，如果是旧版本，就提示用户刷新页面？
> 
> 这个方式是可行的，不过上述例子中 A 用户提交配置后是能看到修改了预期之外的配置，在发布的时候也会有提示的，稍加注意应该是能避免该问题的。

最近有用户通过openapi来自定义实现一个业务平台，也遇到这个问题了，Apollo server接口端如果没有增加版本判断的话，还是不能杜绝此问题的发生的。
