### ISSUE TITLE
两个namespace相同属性，如何在使用时使用特定的命名空间的属性

### ISSUE THREAD

**Issue by sheiy** [apolloconfig/apollo#5230]
<img width="873" alt="Xnip2024-09-14_11-58-36" src="https://github.com/user-attachments/assets/cf939367-262c-4f37-b87d-27011982aa6f">

**Comment by nobodyiam** [comment]
可以用`@ApolloConfig`

**Comment by sheiy** [comment]
还有其他办法不，不然只能自己创建datasource那个bean了？
