### ISSUE TITLE
应用需要加载监听多个appId下的配置，类似与共享配置如何配置？

### ISSUE THREAD

**Issue by fuxiuzhan** [apolloconfig/apollo#5231]
多个应用需要加载同一份配置，这份配置是共享配置，比如common-config，app1，app2，app3都需要加载监听这个配置，应用里如何配置？

**Comment by nobodyiam** [comment]
[二、公共组件接入指南](https://www.apolloconfig.com/#/zh/portal/apollo-user-guide?id=%e4%ba%8c%e3%80%81%e5%85%ac%e5%85%b1%e7%bb%84%e4%bb%b6%e6%8e%a5%e5%85%a5%e6%8c%87%e5%8d%97)
