### ISSUE TITLE
Apollo关联namespace展示问题

### ISSUE THREAD

**Issue by youngzil** [apolloconfig/apollo#5237]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1、appid：demo1创建ns：demo1-test-common-ns，配置如下
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/359f8f06-d849-42e8-bea5-55c1c0b70ae5">

2、appid：demo1，修改ns：demo1-test-common-ns（修改1个，删除1个，新增1个），如下
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/b16a5496-09e9-496a-b239-19be6edde54b">

3、当前在已发布的配置tab页面展示的事没有任何修改的配置（**修改的删除的配置没有**）
**备注：已经修改和删除的配置，但是并没有发布，依然应该展示在已发布配置的tab页面中，直到修改和删除的配置被发布**

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/9ae883e7-85da-4d9b-bb98-5a5a0fb48b9d">

4、
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/7aa4ae3e-6979-4258-aa67-1a73d96179bd">

**期望**

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/ae59ba97-337f-4c41-aa29-6616fb55f489">

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/09ee9cac-9ac4-4013-8f7d-c1519a2fde73">

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by youngzil** [comment]
如果这是个优化项，我可以提交我修改后的代码

**Comment by nobodyiam** [comment]
我觉得你的建议是合理的，可以看下如何实现
