### ISSUE TITLE
创建应用时，建议增加“应用描述” 输入框

### ISSUE THREAD

**Issue by aisuhua** [apolloconfig/apollo#5238]
**你的特性请求和某个问题有关吗？请描述**

因为 appid 和 应用名称两个字段，信息量比较少，还不能完整描述一个应用的基本情况。比如我想填写一个中文名称备注，说明它的背景等。

**清晰简洁地描述一下你希望的解决方案**

创建应用时，增加 “应用描述” 输入框，文本支持至少 100 字以上。

**其它背景**

因为我们公司的应用非常多，大部分是外包公司开发，且项目负责人变动比较频繁，所以需要对应用做一些注释，方便日后识别。

**Comment by nobodyiam** [comment]
一般而言应用本身应该是有一个 CMDB 管理的，在 apollo 这里更多是引用的关系。
当然在 apollo 这里增加应用描述也是可以的，需要考虑下如何展示
