### ISSUE TITLE
Apollo OpenAPI  3.2.5 获取集群下所有Namespace信息接口 新增参数决定是否填充所有的Namespace下面的item信息

### ISSUE THREAD

**Issue by youngzil** [apolloconfig/apollo#5243]
**你的特性请求和某个问题有关吗？请描述**

Apollo OpenAPI [3.2.5 获取集群下所有Namespace信息接口](https://www.apolloconfig.com/#/zh/portal/apollo-open-api-platform?id=_325-%e8%8e%b7%e5%8f%96%e9%9b%86%e7%be%a4%e4%b8%8b%e6%89%80%e6%9c%89namespace%e4%bf%a1%e6%81%af%e6%8e%a5%e5%8f%a3) 获取的返回参数默认是填充所有的 items 的，这个填充是个非常耗费时间和资源的动作，但是实际上很多时候业务是只需要获取cluster下面的所有的Namespace列表的，后续再根据实际情况获取对应的Namespace下面的所有item数据 或者 不获取具体的items数据

代码位置：`com.ctrip.framework.apollo.portal.service.NamespaceService#transformNamespace2BO`
其中主要的逻辑就是在 填充NS中的items数据

![image](https://github.com/user-attachments/assets/ce7d52b9-9daf-40de-9826-b51cf40d36de)

**清晰简洁地描述一下你希望的解决方案**

可以考虑新增个param，比如 boolean fillItems，拉取端来决定是否填充所有的Namespace下面的item信息

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

BTW：如果觉得这个特性合理，我可以实现这个方案

**Comment by nobodyiam** [comment]
我觉得是可以的
