### ISSUE TITLE
ConfigServiceWithCache 新增recordStats功能

### ISSUE THREAD

**Issue by youngzil** [apolloconfig/apollo#5246]
**你的特性请求和某个问题有关吗？请描述**

目前Apollo-ConfigService为了提升性能，会选择开启配置缓存功能ConfigServiceWithCache，但是目前对于缓存的size、命中率、淘汰数量等数据没有很好的监控，无法及时处理一下问题

**清晰简洁地描述一下你希望的解决方案**

希望ConfigServiceWithCache能新增一个监控缓存的功能，此功能可通过增加一个开关的方式手动开启，默认关闭（兼容性）

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

BTW：如果觉得这个特性合理，我可以实现这个方案

**Comment by nobodyiam** [comment]
Sounds a good idea.
