### ISSUE TITLE
能否新增通过appid的维度来跳过对Value长度的校验

### ISSUE THREAD

**Issue by youngzil** [apolloconfig/apollo#5254]
**你的特性请求和某个问题有关吗？请描述**

目前 Apollo 提供了参数 `namespace.value.length.limit.override` 来通过 namespace 维度覆盖Value长度校验值。能否再提供一个 appid 维度提供一个参数，对某些 appid 跳过Value值长度限制的检查，以满足一些特定 appid 的需求，比如 gateway，可能配置了一些比较大的路由配置等

通过Namespace 维度覆盖Value值长度上限值（`namespace.value.length.limit.override`参数） 在公共 NS 且NS变化不大的场景下比较合适，但存在下面两个点
1. 上述参数实际配置的是 namespaceId ，配置起来会比较麻烦，需要先查询到 namespaceId ，如果数量大，就比较麻烦，且配置需要特别谨慎
2. 比如上面提到的网关，当网关增加新的 NS 时，Apollo 维护者就需要更新 `namespace.value.length.limit.override` 的值，这样感觉不太合理 

**清晰简洁地描述一下你希望的解决方案**

能否再提供一个 appid 维度提供一个参数，对某些 appid 跳过Value值长度限制的检查，比如 `item.value.length.limit.white`，以满足一些特定 appid 的需求，比如 gateway等

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
不建议增加跳过长度检查的需求，可以增加 appid 维度的长度上限值配置。
