### ISSUE TITLE
Apollo不同表的的相同业务含义的字段长度不一致

### ISSUE THREAD

**Issue by youngzil** [apolloconfig/apollo#5259]
**你的特性请求和某个问题有关吗？请描述**

在实际使用时，发现日志经常会有少量的数据库字段超长的报错，发现是`Release`表的`NamespaceName`字段是 varchar(500)，但是`InstanceConfig`表的`ConfigNamespaceName`字段是 varchar(32)

1. 比如NamespaceName，在`AppNamespace`表中`Name` 字段是varchar(32)
2. 比如Cluster字段，`Cluster`表中`Name`字段是 varchar(32)，`Commit`表中`ClusterName`字段是 varchar(500)

相同含义的字段在所有表中是否有必要同一，避免一些潜在的问题

**清晰简洁地描述一下你希望的解决方案**

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by youngzil** [comment]
I saw that there was a PR #4725 that made some optimizations for the field length unification, but it did not include the three tables `commit`, `namespace`, and `release`. Why is this?

**Comment by nobodyiam** [comment]
It includes the `commit`, `namespace`, and `release` tables but appears to miss the `NamespaceName` and `ClusterName` fields.

**Comment by youngzil** [comment]
> It includes the `commit`, `namespace`, and `release` tables but appears to miss the `NamespaceName` and `ClusterName` fields.

I think this can be fixed and is safe.
