### ISSUE TITLE
Spring3中使用Apollo 2.1.0 出现无法自动解析yaml的问题

### ISSUE THREAD

**Issue by painAdmin** [apolloconfig/apollo#5281]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

  在springboot 3 中，使用apollo2.1.0 客户端，读取yml格式的namespace文件时，不能使用Config.getProperty(String key, String defaultValue) 获取属性值，因为apolo-client 中引用yaml版本太低，报下面的错误：
|-WARN  [restartedMain] tryTransformToProperties(YamlConfigFile.java:69) - yaml to properties failed, reason: Parse yaml file content failed for namespace: ***.yml [Cause: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found] 

**复现**

通过如下步骤可以复现：

1. 创建yml格式的namespace文件，添加相关属性
2. 创建springboot项目，版本号：3.3.3，spring版本6.1.12，snakeyaml：2.2
3. 服务启动后，在项目中使用Config.getProperty(String key, String defaultValue) 获取属性值, 
4. 结果无法读取到

**期望**

希望后续的版本中修复这个问题

**截图**
![image](https://github.com/user-attachments/assets/64d5355f-68be-4aca-8638-c30349558b06)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
It is fixed in apollo-java 2.2.0, see https://github.com/apolloconfig/apollo-java/pull/35

**Comment by painAdmin** [comment]
> It is fixed in apollo-java 2.2.0, see [apolloconfig/apollo-java#35](https://github.com/apolloconfig/apollo-java/pull/35)

👍
