### ISSUE TITLE
建议加上value的格式验证

### ISSUE THREAD

**Issue by Hellerz** [apolloconfig/apollo#590]
有些业务场景的配置可能是多层次的，需要配置json或xml格式的，数据量也比较大，通常会交给产品或业务去配置，如果能加上json或xml格式的编辑器或者校验，就能很大程度的方便使用和减少出错率。

**Comment by nobodyiam** [comment]
恩，多谢建议，目前我们的配置还没有格式，后面希望能增加简单的格式以及对应的校验的，比如数字，日志，json等。

**Comment by nobodyiam** [comment]
@Hellerz [0.9.1 release](https://github.com/ctripcorp/apollo/releases/tag/v0.9.1)引入了ace编辑器（#828）来展示和校验json或xml格式的namespace，效果如下，如果需要的话，可以升级一下。

![image](https://user-images.githubusercontent.com/837658/34915402-0ef30c26-f961-11e7-947a-c52e7398bf0a.png)

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本对Yml/Yaml格式的namespace在页面上增加了语法检查功能。
